### ISSUE TITLE
Tried to log in using browser

### ISSUE THREAD

**Issue by afeinber** [avocode/avocode#1002]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.0
Source UID: null
```
TypeError: Parameter "url" must be a string, not object
    at Url.parse (url.js:79:11)
    at Object.urlParse [as parse] (url.js:73:5)
    at t._normalizeUri (file:///Users/alexf/Downloads/Avocode%202.app/Contents/Resources/app.asar/dist/avocode.min.js:21:378)
    at t._addItemWithUri (file:///Users/alexf/Downloads/Avocode%202.app/Contents/Resources/app.asar/dist/avocode.min.js:20:29852)
    at t._handleAction (file:///Users/alexf/Downloads/Avocode%202.app/Contents/Resources/app.asar/dist/avocode.min.js:20:27282)
    at Object.ID_2 (file:///Users/alexf/Downloads/Avocode%202.app/Contents/Resources/app.asar/dist/avocode.min.js:20:25041)
    at Dispatcher._invokeCallback (/Users/alexf/Downloads/Avocode 2.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:198:24)
    at Dispatcher.dispatch (/Users/alexf/Downloads/Avocode 2.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:174:14)
    at e.dispatch (file:///Users/alexf/Downloads/Avocode%202.app/Contents/Resources/app.asar/dist/avocode.min.js:21:8327)
    at t.e.dispatch (file:///Users/alexf/Downloads/Avocode%202.app/Contents/Resources/app.asar/dist/avocode.min.js:2:20643)
    at t.addItemWithUri (file:///Users/alexf/Downloads/Avocode%202.app/Contents/Resources/app.asar/dist/avocode.min.js:15:23134)
    at e.openUri (file:///Users/alexf/Downloads/Avocode%202.app/Contents/Resources/app.asar/dist/avocode.min.js:14:17277)
    at file:///Users/alexf/Downloads/Avocode%202.app/Contents/Resources/app.asar/dist/avocode.min.js:1:27666
    at Array.forEach (native)
    at t._openInitialUris (file:///Users/alexf/Downloads/Avocode%202.app/Contents/Resources/app.asar/dist/avocode.min.js:1:27600)
    at Immediate._onImmediate (file:///Users/alexf/Downloads/Avocode%202.app/Contents/Resources/app.asar/dist
```

**Comment by petrbrzek** [comment]
This has been fixed in newer version. Please update your app to 2.8.4.
