### ISSUE TITLE
Opened Macbook with Avocode showing this message https://cl.ly/gptb/

### ISSUE THREAD

**Issue by Vucek** [avocode/avocode#1006]
IMPORTANT: Please try to describe how did it happen.

-----
Source UID: 63690
```
TypeError: this._getConnectionStatusState is not a function
    at t._handleConnectionStatusChange (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:37:15522)
    at emitNone (events.js:91:20)
    at t.emit (events.js:185:7)
    at t.Store.emitChange (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/flux/lib/store.js:26:19)
    at t.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:6:881)
    at Dispatcher._invokeCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:198:24)
    at Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:174:14)
    at Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/flux/lib/dispatcher.js:58:35)
    at t.ActionCreator.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/flux/lib/
```

**Comment by petrbrzek** [comment]
Fixed in 2.9.0.
