### ISSUE TITLE
i can't upload design

### ISSUE THREAD

**Issue by pqhhl** [avocode/avocode#1011]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.4
Source UID: 77420
```
TypeError: Cannot read property 'get' of null
    at Function.e.fromProject (file:///C:/Users/HungHuy/AppData/Local/avocode/app-2.8.4/resources/app.asar/dist/avocode.min.js:14:15313)
    at e.createUploadTargetFromProject (file:///C:/Users/HungHuy/AppData/Local/avocode/app-2.8.4/resources/app.asar/dist/avocode.min.js:14:2823)
    at Constructor._createUploadTarget (file:///C:/Users/HungHuy/AppData/Local/avocode/app-2.8.4/resources/app.asar/dist/avocode.min.js:34:16653)
    at Constructor._handleUploadNewDesign (file:///C:/Users/HungHuy/AppData/Local/avocode/app-2.8.4/resources/app.asar/dist/avocode.min.js:34:16835)
    at Constructor._onDrop (C:\Users\HungHuy\AppData\Local\avocode\app-2.8.4\resources\app.asar\node_modules\react-droparea\index.js:149:20)
    at HTMLDivElement.d (file:///C:/Users/HungHuy/AppData/Local/avocode/app-2.8.4/resources/app.asar/static/raven.min.js:2:3637)
```

**Comment by connor-bean** [comment]
We are tracking this in #1004. We will close this out and follow it there instead.
