### ISSUE TITLE
Problem with uploading a design

### ISSUE THREAD

**Issue by sigaev-pro** [avocode/avocode#1012]
I'm using Avocode about 9 month on Linux Mint, and as I see it is getting worse with every new version.

Here is an error during adding new file to project.

IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.4
Source UID: 45092
```
TypeError: Cannot read property 'get' of null
    at Function.e.fromProject (file:///home/vadim/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:14:15313)
    at e.createUploadTargetFromProject (file:///home/vadim/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:14:2823)
    at Constructor._createUploadTarget (file:///home/vadim/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:34:16653)
    at Constructor._handleUploadNewDesign (file:///home/vadim/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:34:16835)
    at Constructor._handleUploadNewDesign (file:///home/vadim/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:36:2465)
    at Object.invokeGuardedCallback (/home/vadim/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactErrorUtils.js:27:12)
    at executeDispatch (/home/vadim/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/EventPluginUtils.js:79:21)
    at Object.executeDispatchesInOrder (/home/vadim/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/EventPluginUtils.js:99:7)
    at executeDispatchesAndRelease (/home/vadim/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/EventPluginHub.js:43:22)
    at executeDispatchesAndReleaseTopLevel (/home/vadim/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/EventPluginHub.js:54:10)
    at Array.forEach (native)
    at forEachAccumulated (/home/vadim/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/forEachAccumulated.js:23:9)
    at Object.processEventQueue (/home/vadim/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/EventPluginHub.js:259:7)
    at runEventQueueInBatch (/home/vadim/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
    at Object.handleTopLevel [as _hand
```

**Comment by connor-bean** [comment]
Hey, @sigaev-pro -

We definitely apologize for any frustration you're experiencing. We are working hard to make Avocode as user-friendly as possible as well as eliminating bugs. 

Would you be able to send us any screenshots and the problematic design to team@avocode.com?

Once again, we sincerely apologize for this.

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
We are tracking this in #1004. I will close this one out and we can follow it there instead.
