### ISSUE TITLE
avocode error

### ISSUE THREAD

**Issue by PabloSuarez** [avocode/avocode#1020]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.4
Source UID: 69536
```
Error: Could not call remote function 'quit'. Check that the function signature is correct. Underlying error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: avocode.min.js:23:13547.
Error: Could not call remote function 'quit'. Check that the function signature is correct. Underlying error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: avocode.min.js:23:13547.
    at callFunction (/Users/pablosuarez/Downloads/Avocode.app/Contents/Resources/electron.asar/browser/rpc-server.js:222:11)
    at EventEmitter.<anonymous> (/Users/pablosuarez/Downloads/Avocode.app/Contents/Resources/electron.asar/browser/rpc-server.js:303:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at EventEmitter.<anonymous> (/Users/pablosuarez/Downloads/Avocode.app/Contents/Resources/electron.asar/browser/api/web-contents.js:165:13)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at metaToValue (/Users/pablosuarez/Downloads/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:178:13)
    at remoteMemberFunction (/Users/pablosuarez/Downloads/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:112:18)
    at t.quit (file:///Users/pablosuarez/Downloads/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:2:7270)
    at Constructor._handleShortcut (file:///Users/pablosuarez/Downloads/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:7:15191)
    at Constructor._handleShortcuts (/Users/pablosuarez/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/component/shortcuts.js:138:25)
    at _fireCallback (/Users/pablosuarez/Downloads/Avocode.app/Conte
```

**Comment by connor-bean** [comment]
Hey, @PabloSuarez -

Thanks for the report. I am going to close this out as we are tracking it in #960. 

Thanks,
Connor, Avocode Support
