### ISSUE TITLE
Unexpected Error occured

### ISSUE THREAD

**Issue by naduhy2** [avocode/avocode#1021]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.4
Source UID: 75289
```
Error: Could not call remote function 'quit'. Check that the function signature is correct. Underlying error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: avocode.min.js:23:13547.
Error: Could not call remote function 'quit'. Check that the function signature is correct. Underlying error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: avocode.min.js:23:13547.
    at callFunction (/Applications/Avocode.app/Contents/Resources/electron.asar/browser/rpc-server.js:222:11)
    at EventEmitter.<anonymous> (/Applications/Avocode.app/Contents/Resources/electron.asar/browser/rpc-server.js:303:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at EventEmitter.<anonymous> (/Applications/Avocode.app/Contents/Resources/electron.asar/browser/api/web-contents.js:165:13)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at metaToValue (/Applications/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:178:13)
    at remoteMemberFunction (/Applications/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:112:18)
    at t.quit (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:2:7270)
    at a.call.concat.click (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:25:14416)
    at CallbacksRegistry.apply (/Applications/Avocode.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:54:39)
    at EventEmitter.<anonymous> (/Applications/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:243:21)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

**Comment by connor-bean** [comment]
Hey @naduhy2 -

Thanks for the report. We are currently tracking this bug in #960 so I'm going to close this out and we will follow it there.

Thanks,
Connor, Avocode Support
