### ISSUE TITLE
I tried to open image in a new tab, by double click, and nothing happened, except error

### ISSUE THREAD

**Issue by foxspace** [avocode/avocode#1022]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.6.0
Source UID: 159251
```
TypeError: Cannot read property 'then' of undefined
  at e.requestRevisionDownload (/home/sashka/pf/Avocode/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:25741)
  at e.loadRevision (/home/sashka/pf/Avocode/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:26028)
  at t._loadRevisionToView (/home/sashka/pf/Avocode/resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:20334)
  at t._addRevisionView (/home/sashka/pf/Avocode/resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:17701)
  at t._openAvocodeResource (/home/sashka/pf/Avocode/resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:16930)
  at t.opener (/home/sashka/pf/Avocode/resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:15327)
  at /home/sashka/pf/Avocode/resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:1178
  at wrappedOpener (/home/sashka/pf/Avocode/resources/app.asar/src/workspace.js:525:18)
  at Workspace.module.exports.Workspace.openURIInPane (/home/sashka/pf/Avocode/resources/app.asar/src/workspace.js:441:22)
  at Workspace.module.exports.Workspace.open (/home/sashka/pf/Avocode/resources/app.asar/src/workspace.js:371:19)
  at t.openSubdocument (/home/sashka/pf/Avocode/resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:28715)
  at e._onDblClick (/home/sashka/pf/Avocode/resources/app.asar/node_modules/@avocode/select-tool/lib/select-tool.js:1:2671)
  at t.module.exports.Emitter.emit (/home/sashka/pf/Avocode/resources/app.asar/node_modules/emissary/lib/emitter.js:118:15)
  at HTMLCanvasElement.<anonymous> (/home/sashka/pf/Avocode/resources/app.asar/node_modules/@avocode/core/lib/stage.js:1:4351)

```

**Comment by petrbrzek** [comment]
Please update your app to 2.9.1 version.
