### ISSUE TITLE
123

### ISSUE THREAD

**Issue by ath01** [avocode/avocode#1026]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.4
Source UID: 24303
```
RangeError: Maximum call stack size exceeded
    at t._handleChildProgressInfo (file:///C:/Users/spv/AppData/Local/avocode/app-2.8.4/resources/app.asar/dist/avocode.min.js:10:10919)
    at t.<anonymous> (file:///C:/Users/spv/AppData/Local/avocode/app-2.8.4/resources/app.asar/dist/avocode.min.js:10:8002)
    at emitOne (events.js:96:13)
    at t.emit (events.js:188:7)
    at t.emitInfo (file:///C:/Users/spv/AppData/Local/avocode/app-2.8.4/resources/app.asar/dist/avocode.min.js:10:9268)
    at t._handleChildProgressInfo (file:///C:/Users/spv/AppData/Local/avocode/app-2.8.4/resources/app.asar/dist/avocode.min.js:10:10994)
    at t.<anonymous> (file:///C:/Users/spv/AppData/Local/avocode/app-2.8.4/resources/app.asar/dist/avocode.min.js:10:8002)
    at emitOne (events.js:101:20)
    at t.emit (events.js:188:7)
    at t.emitInfo (file:///C:/Users/spv/AppData/Local/avocode/app-2.8.4/resources/app.asar/dist/avocode.min.js:10:9268)
    at t._handleChildProgressInfo (file:///C:/Users/spv/AppData/
```

**Comment by connor-bean** [comment]
We are tracking this in #1027
