### ISSUE TITLE
123

### ISSUE THREAD

**Issue by ath01** [avocode/avocode#1027]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.4
Source UID: 24303
```
RangeError: Maximum call stack size exceeded
    at t.g (events.js:282:13)
    at emitOne (events.js:101:20)
    at t.emit (events.js:188:7)
    at t.abort (file:///C:/Users/spv/AppData/Local/avocode/app-2.8.4/resources/app.asar/dist/avocode.min.js:10:8874)
    at t._handleChildAbort (file:///C:/Users/spv/AppData/Local/avocode/app-2.8.4/resources/app.asar/dist/avocode.min.js:10:10865)
    at t.<anonymous> (file:///C:/Users/spv/AppData/Local/avocode/app-2.8.4/resources/app.asar/dist/avocode.min.js:10:8002)
    at t.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at t.emit (events.js:188:7)
    at t.abort (file:///C:/Users/spv/AppData/Local/avocode/app-2.8.4/resources/app.asar/dist/avocode.min.js:10:8874)
    at t._handleChildAbort (file:///C:/Users/spv/AppData/Local/avocode/app-2.8.4/resources/app.asar/dist/avocode.min.js:10:10865)
    at t.<anonymous> (file:///C:/Users/spv/AppData/Local/avocode/app-2.8.4/resources/app.asar/dist/avocode.min.js:10:8002)
    at t.g (events.js:28
```

**Comment by connor-bean** [comment]
Hey, @ath01 -

Could you please provide us with more information as to what happened when you received this? Screenshots would be greatly appreciated.

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Closing out due to inactivity. Please reopen if you could provide us with more information.

Thanks,
Connor, Avocode Support
