### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by jetcohen** [avocode/avocode#1031]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.4
Source UID: 80281
```
Error: Cannot open a document with no revision or no current revision
    at t.openDesign (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:2:8298)
    at t.openDesignById (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:2:7986)
    at Constructor._handleEntityOpen (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:35:17353)
    at Constructor._handleEntityDoubleClick (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:35:26324)
    at Object.invokeGuardedCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactErrorUtils.js:27:12)
    at executeDispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:79:21)
    at Object.executeDispatchesInOrder (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:102:5)
    at executeDispatchesAndRelease (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:43:22)
    at executeDispatchesAndReleaseTopLevel (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:54:10)
    at Array.forEach (native)
    at forEachAccumulated (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/forEachAccumulated.js:23:9)
    at Object.processEventQueue (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:259:7)
    at runEventQueueInBatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
    at Object.handleTopLevel [as _handleTopLevel] (/Applications/Avocode.app/Contents/Resources/app.asar/node
```

**Comment by connor-bean** [comment]
Hey @jetcohen -

Could you describe what was going on when you received this error? Also - could you send us any screenshots and the problematic design file to team@avocode.com?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey @jetcohen -

Could you describe what was going on when you received this error? Also - could you send us any screenshots and the problematic design file to team@avocode.com?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Closing due to inactivity. Please reopen if you can send us the the design/screenshots and more info to team@avocode.com.

Thanks,
Connor, Avocode Support
