### ISSUE TITLE
dưq

### ISSUE THREAD

**Issue by Huynhvantoan** [avocode/avocode#1035]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.9.1
Source UID: 61408
```
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at invariant (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/node_modules/fbjs/lib/invariant.js:35:15)
    at Object.findComponentRoot (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMount.js:764:478)
    at Object.findReactNodeByID (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMount.js:679:23)
    at Object.getNodeFromInstance (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMount.js:180:32)
    at Object.findDOMNode (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/findDOMNode.js:43:23)
    at Constructor._getElementToBind (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/component/shortcuts.js:100:28)
    at Constructor._unbindShortcuts (/Applications/Avocod
```

**Comment by connor-bean** [comment]
We are tracking this in #1067. Closing out this one
