### ISSUE TITLE
When I'm open Avocode

### ISSUE THREAD

**Issue by YuriyChaban** [avocode/avocode#1036]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.0-beta.6
Source UID: 83499
```
Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (C:\Users\shute\AppData\Local\avocodebeta\app-2.8.0-beta6\resources\electron.asar\browser\objects-registry.js:44:28)
    at EventEmitter.<anonymous> (C:\Users\shute\AppData\Local\avocodebeta\app-2.8.0-beta6\resources\electron.asar\browser\rpc-server.js:317:31)
    at emitMany (events.js:121:13)
    at EventEmitter.emit (events.js:195:7)
    at EventEmitter.<anonymous> (C:\Users\shute\AppData\Local\avocodebeta\app-2.8.0-beta6\resources\electron.asar\browser\api\web-contents.js:139:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at metaToValue (C:\Users\shute\AppData\Local\avocodebeta\app-2.8.0-beta6\resources\electron.asar\renderer\api\remote.js:176:13)
    at remoteMemberFunction (C:\Users\shute\AppData\Local\avocodebeta\app-2.8.0-beta6\resources\electron.asar\renderer\api\remote.js:110:18)
    at t._sendMessage (file://
```

**Comment by connor-bean** [comment]
Hey @YuriyChaban -

Thanks for the report. We are currently tracking this bug in #940. This is an Electron bug and you can see more about it here.

I am going to close out this ticket and we will continue to monitor this in #940.

Thanks,
Connor, Avocode Support
