### ISSUE TITLE
Project unable to open

### ISSUE THREAD

**Issue by kkamikazi** [avocode/avocode#1037]
IMPORTANT: Please try to describe how did it happen.

Hello,

First I want to say that here we really love avocode.
But I am experiencing an error after trying to update a PSD.
I dragged & dropped in a new project & now this project wont open.
Can you tell what's wrong?

Cheers

-----
App v.2.8.4
Source UID: 16534
```
TypeError: Cannot read property 'get' of undefined
    at file:///opt/avocode/resources/app.asar/dist/avocode.min.js:36:24270
    at /opt/avocode/resources/app.asar/node_modules/immutable/dist/immutable.js:4420:31
    at /opt/avocode/resources/app.asar/node_modules/immutable/dist/immutable.js:2701:43
    at List.__iterate (/opt/avocode/resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at OrderedMap.__iterate (/opt/avocode/resources/app.asar/node_modules/immutable/dist/immutable.js:2700:25)
    at OrderedMap.reduce (/opt/avocode/resources/app.asar/node_modules/immutable/dist/immutable.js:4415:12)
    at t._sortDesignsByCategories (file:///opt/avocode/resources/app.asar/dist/avocode.min.js:36:24518)
    at t.getProjectById (file:///opt/avocode/resources/app.asar/dist/avocode.min.js:36:19866)
    at Constructor._handleRouteTransition (file:///opt/avocode/resources/app.asar/dist/avocode.min.js:34:13838)
    at Constructor.componentWillReceiveProps (file:///opt/avocode/resources/app.asar/dist/avocode.min.js:34:12263)
    at ReactCompositeComponentWrapper.updateComponent (/opt/avocode/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:458:14)
    at ReactCompositeComponentWrapper.receiveComponent (/opt/avocode/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:405:10)
    at Object.receiveComponent (/opt/avocode/resources/app.asar/node_modules/react/lib/ReactReconciler.js:87:22)
    at Object.updateChildren (/opt/avocode/resources/app.asar/node_modules/react/lib/ReactChildReconciler.js:84:25)
    at ReactDOMComponent._reconcilerUpdateChildren (/opt/avocode/resources/app.asar/node_modules/react/lib/ReactMultiChild.js:220:35)
    at ReactDOMComponent._updateChildren (/opt/avocode/resources/app.asar/node_modules/react/li
```

**Comment by connor-bean** [comment]
Hey @kkamikazi -

Can you try updating to our most recent version? It looks like you're using 2.8.4 and we just released 2.9.1 a week or so ago.

You can download it [here](https://manager.avocode.com/downloads/).

Please let me know if this problem still persists once you've updated.

Thanks!
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey, @kkamikazi -

Did downloading 2.9.1 solve this?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey, @kkamikazi -

Did downloading 2.9.1 solve this?

Thanks,
Connor, Avocode Support

**Comment by jakubzitny** [comment]
Closing as this was related to old version of Avocode. Please update to `2.10`(available from [manager.avocode.com/downloads](http://manager.avocode.com/downloads/)) and let us know if you have any more problems with it.
