### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by smirnovvu** [avocode/avocode#1047]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.9.1
Source UID: 85216
```
TypeError: Cannot read property 'componentWillReceiveProps' of null
    at ReactCompositeComponentWrapper.updateComponent (/Users/Vitaliy/Downloads/Программы/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:457:15)
    at ReactCompositeComponentWrapper.receiveComponent (/Users/Vitaliy/Downloads/Программы/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:405:10)
    at Object.receiveComponent (/Users/Vitaliy/Downloads/Программы/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:87:22)
    at Object.updateChildren (/Users/Vitaliy/Downloads/Программы/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler.js:84:25)
    at ReactDOMComponent._reconcilerUpdateChildren (/Users/Vitaliy/Downloads/Программы/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react
```

**Comment by connor-bean** [comment]
Hey, @smirnovvu -

Can you explain what you were doing when you received this error?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey, @smirnovvu -

Can you explain what you were doing when you received this error?

Thanks,
Connor, Avocode Support

**Comment by jakubzitny** [comment]
Hi @smirnovvu, thanks for the report. If you have any more info about this we'd be happy to hear it. 

I'll close this issue for now. It is related to bug that's already mentioned in #1058.
