### ISSUE TITLE
Can't rename any designs

### ISSUE THREAD

**Issue by tibbyyo** [avocode/avocode#1048]
IMPORTANT: Please try to describe how did it happen.

I can't rename any designs in Avocode.
-----
App v.2.9.0
Source UID: 71414
```
TypeError: Cannot read property 'API_DESIGN_URL' of undefined
    at t.renameDesign (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:13:13844)
    at e.renameDesign (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:12:21549)
    at Constructor._handleRename (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:35:27456)
    at Constructor._handleShortcuts (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:35:27100)
    at Constructor._handleShortcuts (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/component/shortcuts.js:138:25)
    at _fireCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/node_modules/mousetrap/mousetrap.js:610:17)
    at Mousetrap.self._handleKey (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/node_modules/mousetrap/mousetrap.js:671:
```

**Comment by tibbyyo** [comment]
Upgrade to 2.9.1 fixed the problem.
