### ISSUE TITLE
Empty selection export bug

### ISSUE THREAD

**Issue by linchaolong** [avocode/avocode#1058]
IMPORTANT: Please try to describe how did it happen.

---

App v.2.9.1
Source UID: 63579

```
TypeError: Cannot read property 'reduce' of null
    at u (file:///C:/Users/linchaolong/AppData/Local/avocode/app-2.9.1/resources/app.asar/dist/avocode.min.js:1:9905)
    at Constructor._getExportItemBounds (file:///C:/Users/linchaolong/AppData/Local/avocode/app-2.9.1/resources/app.asar/dist/avocode.min.js:3:14313)
    at file:///C:/Users/linchaolong/AppData/Local/avocode/app-2.9.1/resources/app.asar/dist/avocode.min.js:3:14459
    at C:\Users\linchaolong\AppData\Local\avocode\app-2.9.1\resources\app.asar\node_modules\immutable\dist\immutable.js:3018:46
    at List.__iterate (C:\Users\linchaolong\AppData\Local\avocode\app-2.9.1\resources\app.asar\node_modules\immutable\dist\immutable.js:2208:13)
    at IndexedIterable.mappedSequence.__iterateUncached (C:\Users\linchaolong\AppData\Local\avocode\app-2.9.1\resources\app.asar\node_modules\immutable\dist\immutable.js:3017:23)
    at seqIterate (C:\Users\linchaolong\AppData\Local\avocode\app-2.9.1\resources\app.asar\node_modules\immutable\dist\immutable.js:606:16)
    at IndexedIter
```

**Comment by connor-bean** [comment]
Hey, @linchaolong -

Could you send us the problematic design to team@avocode.com?

What OS are you running?

Thanks,
Connor, Avocode Support

**Comment by jakubzitny** [comment]
Thanks for the report @linchaolong. This is a bug in Avocode, we're working on fixing it for the next release. Any further info would help.

**Comment by connor-bean** [comment]
We just released 2.11 so I'm closing this out. Please let us know if this problem persists.

Thanks for your patience on this.

Connor, Avocode Support

**Comment by jakubzitny** [comment]
Actually, this is planned for `2.11.1`, still under development.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.12, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please comment on it if you’re still experiencing this problem in Version 2.12.

Thanks!
Connor, Avocode Support
