### ISSUE TITLE
i try to export 2 layers into png

### ISSUE THREAD

**Issue by nikbeznosikov** [avocode/avocode#1067]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.9.1
Source UID: 86465
```
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at invariant (/home/user/Programms/Avocode-linux-x64/resources/app.asar/node_modules/react/node_modules/fbjs/lib/invariant.js:35:15)
    at Object.findComponentRoot (/home/user/Programms/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactMount.js:764:478)
    at Object.findReactNodeByID (/home/user/Programms/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactMount.js:679:23)
    at Object.getNodeFromInstance (/home/user/Programms/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactMount.js:180:32)
    at Object.findDOMNode (/home/user/Programms/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/findDOMNode.js:43:23)
    at Constructor._getElementToBind (/home/user/Programms/Avocode-linux-x64/resources/app.asar/node_modules/react-shortcuts/component/shortcuts.js:100:28)
    at Constructor._unbindShortcu
```

**Comment by petrbrzek** [comment]
We've released 2.10.0 version yesterday. The problem should be fixed, so please try it. If there will be any problem related to this let me know and I'll reopen the issue.
