### ISSUE TITLE
Open app -> move app to new location via Finder -> crash

### ISSUE THREAD

**Issue by zamiang** [avocode/avocode#1081]
IMPORTANT: Please try to describe how did it happen.
Tried to describe in the title. Feel like this is a common pattern tho. 
1. Download the zip, 
2. unzip, 
3. open app in zip file
4. **o shit i need to move it to the applications folder**
5. wtf Incessant app errors

---

App v. `2.10.0`
Source UID: 88415

```
Error: ENOENT: no such file or directory, realpath '/Users/zamiang/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar'
    at Error (native)
    at realpathSync (fs.js:1584:18)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:313:24)
    at tryFile (module.js:121:25)
    at tryExtensions (module.js:127:22)
    at Function.Module._findPath (module.js:179:20)
    at Module._resolveFilename (module.js:438:25)
    at Function.Module._resolveFilename (/Users/zamiang/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/zamiang/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/node_modules/combokeys/Combokeys/prototype/handleKeyEvent.js:20:24)
    at HTMLBodyElement.wrapped (/Users/zamiang/Downloads/Avocode-darwin-
```

**Comment by jakubzitny** [comment]
Hey @zamiang, thanks for this report. We should think about how to correctly handle this problem. Otherwise, after moving the app and re-launching it, is everything OK for you?

**Comment by zamiang** [comment]
Yup! everything else is good. Thanks!

**Comment by jakubzitny** [comment]
Similar thing is happening in Atom (https://github.com/atom/atom/issues/10774) and other Electron apps. We're investigating the best solution for this issue.

**Comment by vojtatranta** [comment]
we are not supplying .dmg it forces you to move app to Applications folder.
