### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zekax** [avocode/avocode#1086]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.10.0`
Source UID: null
```
Error: ENOENT: no such file or directory, realpath '/Users/joserodrigues/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar'
    at Error (native)
    at realpathSync (fs.js:1584:18)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:313:24)
    at tryFile (module.js:121:25)
    at tryExtensions (module.js:127:22)
    at Function.Module._findPath (module.js:179:20)
    at Module._resolveFilename (module.js:438:25)
    at Function.Module._resolveFilename (/Users/joserodrigues/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/joserodrigues/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/node_modules/combokeys/Combokeys/prototype/handleKeyEvent.js:20:24)
    at HTMLBodyElement.wrapped (/Users/joserodrigues/D
```

**Comment by petrbrzek** [comment]
@zekax Thanks for the report. Did you moving the app to a different folder or removing something? Any additional information would be appreciated.

**Comment by petrbrzek** [comment]
Ok, it's probably the same case as in #1081 right? @zekax

**Comment by zekax** [comment]
Yes it was!!! My bad!!:(

Thank you for fast response! :)
