### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gradiusalisik** [avocode/avocode#1094]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.10.0`
Source UID: 13001
```
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at invariant (C:\Users\admin\AppData\Local\avocode\app-2.10.0\resources\app.asar\node_modules\react\node_modules\fbjs\lib\invariant.js:35:15)
    at traverseParentPath (C:\Users\admin\AppData\Local\avocode\app-2.10.0\resources\app.asar\node_modules\react\lib\ReactInstanceHandles.js:157:164)
    at Object.traverseAncestors (C:\Users\admin\AppData\Local\avocode\app-2.10.0\resources\app.asar\node_modules\react\lib\ReactInstanceHandles.js:285:5)
    at findDeepestCachedAncestor (C:\Users\admin\AppData\Local\avocode\app-2.10.0\resources\app.asar\node_modules\react\lib\ReactMount.js:234:24)
    at Object.findComponentRoot (C:\Users\admin\AppData\Local\avocode\app-2.10.0\resources\app.asar\node_modules\react\lib\ReactMount.js:708:27)
    at Object.findReactNodeByID (C:\Users\admin\AppData\Local\avocode\app-2.10.0\resources\app.asar\node_modules\react\lib\Rea
```

**Comment by connor-bean** [comment]
Hey, @gradiusalisik -

Could you explain more about what you were doing when you received this error?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey, @gradiusalisik -

Could you explain more about what you were doing when you received this error?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Closing due to inactivity. Please reopen if you can provide more information.

Thanks,
Connor, Avocode Support
