### ISSUE TITLE
avocode error on quit

### ISSUE THREAD

**Issue by PabloSuarez** [avocode/avocode#1100]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.9.1
Source UID: 69536
```
Error: Could not call remote function 'quit'. Check that the function signature is correct. Underlying error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: avocode.min.js:20:3875.
Error: Could not call remote function 'quit'. Check that the function signature is correct. Underlying error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: avocode.min.js:20:3875.
    at callFunction (/Users/pablosuarez/Downloads/Avocode.app/Contents/Resources/electron.asar/browser/rpc-server.js:225:11)
    at EventEmitter.<anonymous> (/Users/pablosuarez/Downloads/Avocode.app/Contents/Resources/electron.asar/browser/rpc-server.js:306:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at EventEmitter.<anonymous> (/Users/pablosuarez/Downloads/Avocode.app/Contents/Resources/electron.asar/browser/api/web-contents.js:165:13)
    at emitTwo (events.js:106:13
```

**Comment by connor-bean** [comment]
Hey @PabloSuarez -

Thanks for the report. We are currently tracking this bug in #960 so I'm going to close this out and we will follow it there.

Thanks, 
Connor, Avocode Support
