### ISSUE TITLE
Error when opening PSD and pressing any button on the keyboard

### ISSUE THREAD

**Issue by neonick** [avocode/avocode#1102]
IMPORTANT: Please try to describe how did it happen.

---

App v. `2.10.1`
Source UID: 89596

```
Error: ENOENT: no such file or directory, realpath '/Users/neo/Desktop/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar'
    at Error (native)
    at realpathSync (fs.js:1584:18)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:325:24)
    at tryFile (module.js:121:25)
    at tryExtensions (module.js:127:22)
    at Function.Module._findPath (module.js:179:20)
    at Module._resolveFilename (module.js:438:25)
    at Function.Module._resolveFilename (/Users/neo/Desktop/Avocode-darwin-x64/Avocode.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/neo/Desktop/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/node_modules/combokeys/Combokeys/prototype/handleKeyEvent.js:20:24)
    at HTMLUnknownElement.wrapped (/Users/neo/Desktop/Avocode-darwin-x64/Avocode.app/Conte
```

**Comment by connor-bean** [comment]
Hey, @neonick -

I believe this is the same bug we're tracking in #1081. When you take a look at 1081, the user outlined the recreation steps (in the very first comment of the thread). Is this the same thing that happened to you?

Thanks,
Connor, Avocode Support

**Comment by neonick** [comment]
nope, it doesn't same thing
My steps:
1) Open psd.
2) Press any button on keyboard (OS 10.11.6)
restart helps me

**Comment by bolekkerous** [comment]
This shouldn't happen anymore in the latest version of the Avocode app.

You can always download the latest version here:
https://manager.avocode.com/downloads/

If you still experience this problem or any other problem, please create a new issue or comment here.
