### ISSUE TITLE
title

### ISSUE THREAD

**Issue by ValikValik** [avocode/avocode#1106]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.10.1`
Source UID: 90985
```
Error: ENOENT: no such file or directory, realpath '/Users/weblem/Desktop/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar'
    at Error (native)
    at realpathSync (fs.js:1584:18)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:325:24)
    at tryFile (module.js:121:25)
    at tryExtensions (module.js:127:22)
    at Function.Module._findPath (module.js:179:20)
    at Module._resolveFilename (module.js:438:25)
    at Function.Module._resolveFilename (/Users/weblem/Desktop/Avocode-darwin-x64/Avocode.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/weblem/Desktop/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/node_modules/combokeys/Combokeys/prototype/handleKeyEvent.js:20:24)
    at HTMLDivElement.wrapped (/Users/weblem/Desktop/Avocode-darwin-x64/Avocode.a
```

**Comment by connor-bean** [comment]
Thanks for reporting this issue. Did you move the application to a different folder while it was open?

**Comment by connor-bean** [comment]
Thanks for reporting this issue. Did you move the application to a different folder while it was open?

**Comment by connor-bean** [comment]
Closing as we are tracking this in #1107
