### ISSUE TITLE
Fix this issue while opening file

### ISSUE THREAD

**Issue by caseydev** [avocode/avocode#1107]
IMPORTANT: Please try to describe how did it happen.

---

App v. `2.10.1`
Source UID: 29387

```
Error: ENOENT: no such file or directory, realpath '/Users/waituk-imac-2/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar'
    at Error (native)
    at realpathSync (fs.js:1584:18)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:325:24)
    at tryFile (module.js:121:25)
    at tryExtensions (module.js:127:22)
    at Function.Module._findPath (module.js:179:20)
    at Module._resolveFilename (module.js:438:25)
    at Function.Module._resolveFilename (/Users/waituk-imac-2/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/waituk-imac-2/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/node_modules/combokeys/Combokeys/prototype/handleKeyEvent.js:20:24)
    at HTMLBodyElement.wrapped (/Users/waituk-imac-2/D
```

**Comment by petrbrzek** [comment]
Thanks for reporting this issue. Did you move the application to a different folder while it was open?

**Comment by caseydev** [comment]
No i have open from same as i import before.

**Comment by vojtatranta** [comment]
If you are on Mac we now ship Avocode in .dmg files which forces you to move Avocode into Applications folder. So this is no longer an issue.
