### ISSUE TITLE
i know not, hand screen send this mensage 

### ISSUE THREAD

**Issue by SantiagoMolinaOrozco** [avocode/avocode#1109]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.10.1`
Source UID: 90457
```
Invariant Violation: Cannot call beginDrag while dragging.
    at Object.invariant [as default] (/opt/avocode/resources/app.asar/node_modules/react-dnd/node_modules/invariant/invariant.js:42:15)
    at DragDropManager.beginDrag (/opt/avocode/resources/app.asar/node_modules/react-dnd/node_modules/dnd-core/lib/actions/dragDrop.js:53:25)
    at Object.beginDrag (/opt/avocode/resources/app.asar/node_modules/react-dnd/node_modules/dnd-core/lib/DragDropManager.js:74:36)
    at HTML5Backend.handleTopDragStart (/opt/avocode/resources/app.asar/node_modules/react-dnd-html5-backend/lib/HTML5Backend.js:313:18)
    at wrapped (/opt/avocode/resources/app.asar/node_modules/raven-js/src/raven.js:286:29)
```

**Comment by connor-bean** [comment]
Hello @SantiagoMolinaOrozco -

Could you give us more information on what you were doing when you received this error?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hello @SantiagoMolinaOrozco -

Could you give us more information on what you were doing when you received this error?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Closing due to inactivity. Please reopen if you can provide more information.

Thanks,
Connor, Avocode Support

**Comment by jakubzitny** [comment]
This is similar problem as we started tracking in #1145.

**Comment by SantiagoMolinaOrozco** [comment]
sorry, I've been busy, I can not remember that was the error u.u
