### ISSUE TITLE
'componentWillUnmount' of null

### ISSUE THREAD

**Issue by gradiusalisik** [avocode/avocode#1118]
IMPORTANT: Please try to describe how did it happen.

---

App v. `2.10.1`
Source UID: 13001

```
TypeError: Cannot read property 'componentWillUnmount' of null
    at ReactCompositeComponentWrapper.unmountComponent (C:\Users\admin\AppData\Local\avocode\app-2.10.1\resources\app.asar\node_modules\react\lib\ReactCompositeComponent.js:242:13)
    at Object.unmountComponent (C:\Users\admin\AppData\Local\avocode\app-2.10.1\resources\app.asar\node_modules\react\lib\ReactReconciler.js:52:22)
    at Object.unmountChildren (C:\Users\admin\AppData\Local\avocode\app-2.10.1\resources\app.asar\node_modules\react\lib\ReactChildReconciler.js:115:25)
    at ReactDOMComponent.unmountChildren (C:\Users\admin\AppData\Local\avocode\app-2.10.1\resources\app.asar\node_modules\react\lib\ReactMultiChild.js:398:28)
    at ReactDOMComponent.unmountComponent (C:\Users\admin\AppData\Local\avocode\app-2.10.1\resources\app.asar\node_modules\react\lib\ReactDOMComponent.js:911:10)
    at Object.unmountComponent (C:\Users\admin\AppData\Local\avocode\app-2.10.1\resources\app.asar\node_modules\react\lib\ReactReconci
```

**Comment by petrbrzek** [comment]
@gradiusalisik I really don't now how to reproduce this one. Would you be willing to describe me how did it happen? Thanks in advance.

**Comment by jakubzitny** [comment]
This might be related to #1058 (based on the stack), which is causing also `Cannot read property 'componentWillReceiveProps' of null` (e.g. #1023), similarly having null component.

Needs more info or investigation though.

**Comment by gradiusalisik** [comment]
>Среда, 21 сентября 2016, 0:28 +03:00 от Petr Brzek <notifications@github.com>:
>
>@gradiusalisik I really don't now how to reproduce this one. Would you be willing to describe me how did it happen? Thanks in advance.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .
I downloaded the layout and it dramatically showed the error

**Comment by gradiusalisik** [comment]
Коллеги и друзья, всем привет.

Прошу заглянуть в блог, где рассказано про мою племяшку (www.storied.mozello.ru)

Спасибо!
