### ISSUE TITLE
Clicking on Leading 1 in Styles panel is crashing

### ISSUE THREAD

**Issue by blorenz** [avocode/avocode#1124]
![image](https://cloud.githubusercontent.com/assets/915873/18753100/5e8b5758-80b2-11e6-918a-ffc04e7b7f6b.png)

IMPORTANT: Please try to describe how did it happen.

---

App v. `2.10.1`
Source UID: 282

```
TypeError: Error processing argument at index 0, conversion failure from 76
    at TypeError (native)
    at Constructor._onClick (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:18110)
    at Object.invokeGuardedCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactErrorUtils.js:27:12)
    at executeDispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:79:21)
    at Object.executeDispatchesInOrder (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:102:5)
    at executeDispatchesAndRelease (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:43:22)
    at executeDispatchesAndReleaseTopLevel (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:54:10)
    at Array.forEach (native)
    at forEachAccumulated (/Applications/Avocode.app/
```

**Comment by bolekkerous** [comment]
Hello!
Thanks for the report!

I've tried to replicate the issue, but I haven't managed to replicate it. Could you please send us the problematic design to team@avocode.com?

Thanks!
Bolek, Avocode Team

**Comment by vojtatranta** [comment]
this should be fixed in newer versions. Please comment if it still happening.
