### ISSUE TITLE
just start macbook after few days 

### ISSUE THREAD

**Issue by vAhyThe** [avocode/avocode#1130]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.10.1`
Source UID: 52477
```
Error: InvalidStateError: The connection has not been established yet
    at SockJS.send (/Users/vAhy_The/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/sockjs-client/lib/main.js:158:11)
    at e.value (file:///Users/vAhy_The/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:5:23588)
    at e.value (file:///Users/vAhy_The/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:5:23092)
    at file:///Users/vAhy_The/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:5:22957
    at /Users/vAhy_The/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3907:58
    at /Users/vAhy_The/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:1379:16
    at ArrayMapNode.iterate.HashCollisionNode.iterate [as iterate] (/Users/vAhy_The/Downloads/A
```

**Comment by jakubzitny** [comment]
Hi @vAhyThe, thanks for this report. This is a bug in Avocode and we're working on a fix. We are already tracking this problem in issue https://github.com/avocode/avocode/issues/1122 so I am going to close this thread. Feel free to let us know if you have any more problems.

**Comment by vojtatranta** [comment]
nažer se https://avocode-media.s3.amazonaws.com/download/avocode-app/2.13.3/Avocode-2.13.3.dmg
