### ISSUE TITLE
An unexpected error has ocurred

### ISSUE THREAD

**Issue by greystate** [avocode/avocode#1132]
With the beta (2.11.0-community-beta.2 - says so in the dump but actually no way to find that in the app...) I tried to open a specific design, but was hit with an error and the app stopped on the "Loading metadata..." message. 

(To me, it looks like what happened for me in #960, just with a different error message - but that's maybe just because it's the same design that fails...)

-----
App v. `2.11.0-community-beta.2`
Source UID: 460
```
TypeError: Cannot read property 'length' of undefined
    at s (file:///Users/chriz/Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:27:2371)
    at Array.reduce (native)
    at e._readLayerFonts (file:///Users/chriz/Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:27:2420)
    at file:///Users/chriz/Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:27:1496
    at Array.map (native)
    at e._processLayers (file:///Users/chriz/Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:27:1255)
    at file:///Users/chriz/Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:27:1401
    at Array.map (native)
    at e._processLayers (file:///Users/chriz/Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:27:1255)
    at new e (file:///Users/chriz/Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:26:31567)
    at file:///Users/chriz/Application
```

**Comment by petrbrzek** [comment]
Fixed in 2.11.0
