### ISSUE TITLE
Error from loading design

### ISSUE THREAD

**Issue by DakEnviy** [avocode/avocode#1144]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.11.0`
Source UID: 92650
```
Error: No such design (ID=4009905)
    at t.openDesignById (file:///home/dakenviy/.apps/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:23:2337)
    at Constructor._handleEntityOpen (file:///home/dakenviy/.apps/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:43:20144)
    at Constructor._handleEntityDoubleClick (file:///home/dakenviy/.apps/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:42:12265)
    at Object.invokeGuardedCallback (/home/dakenviy/.apps/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactErrorUtils.js:27:12)
    at executeDispatch (/home/dakenviy/.apps/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/EventPluginUtils.js:79:21)
    at Object.executeDispatchesInOrder (/home/dakenviy/.apps/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/EventPluginUtils.js:102:5)
    at executeDispatchesAndRelease (/home/dakenviy/.apps/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/EventPluginHub.js:43:22)
    at 
```

**Comment by connor-bean** [comment]
Hey, @DakEnviy -

Could you provide us with more information on what you were doing when you received this error? Additional information would really help us troubleshoot this.

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Closing due to inactivity. Please reopen if you can provide more information on this error.

Thanks,
Connor, Avocode Support
