### ISSUE TITLE
annoying error

### ISSUE THREAD

**Issue by DrazenHizakowski** [avocode/avocode#1146]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.10.1`
Source UID: 41900
```
Error: InvalidStateError: The connection has not been established yet
    at SockJS.send (/opt/avocode/resources/app.asar/node_modules/sockjs-client/lib/main.js:158:11)
    at e.value (file:///opt/avocode/resources/app.asar/dist/avocode.min.js:5:23588)
    at e.value (file:///opt/avocode/resources/app.asar/dist/avocode.min.js:5:23092)
    at file:///opt/avocode/resources/app.asar/dist/avocode.min.js:5:22957
    at /opt/avocode/resources/app.asar/node_modules/immutable/dist/immutable.js:3907:58
    at /opt/avocode/resources/app.asar/node_modules/immutable/dist/immutable.js:1379:16
    at ValueNode.iterate (/opt/avocode/resources/app.asar/node_modules/immutable/dist/immutable.js:1746:12)
    at BitmapIndexedNode.iterate.HashArrayMapNode.iterate [as iterate] (/opt/avocode/resources/app.asar/node_modules/immutable/dist/immutable.js:1739:24)
    at BitmapIndexedNode.iterate.HashArrayMapNode.iterate [as iterate] (/opt/avocode/resources/app.asar/node_modules/immutable/dist/immutable.js:1739:2

it happens doing nothing
```

**Comment by vojtatranta** [comment]
Hi @DrazenHizakowski ,
we know about this issue, and we fixed it in `2.11.0`. So just update your app and this should be fixed!
