### ISSUE TITLE
Getting dialog all time when moving from one tab to another.

### ISSUE THREAD

**Issue by MilapKundalia** [avocode/avocode#1157]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.11.0`
Source UID: 48505
```
TypeError: Cannot read property '_currentElement' of null
    at ReactCompositeComponentWrapper._updateRenderedComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:559:52)
    at ReactCompositeComponentWrapper._performComponentUpdate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:544:10)
    at ReactCompositeComponentWrapper.updateComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:473:12)
    at ReactCompositeComponentWrapper.receiveComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:405:10)
    at Object.receiveComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:87:22)
    at Object.updateChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReco
```

**Comment by petrbrzek** [comment]
This bug has been fixed in 2.11.1. Please just update the app.
