### ISSUE TITLE
report

### ISSUE THREAD

**Issue by Dartlen** [avocode/avocode#1160]
IMPORTANT: Please try to describe how did it happen.
---

App v. `2.11.1`
Avocode UID: 96972

```
Error: EACCES: permission denied, mkdir '/home/dartlen/.avocode/userdata/96972/documents'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at sync (/usr/share/applications/Avocode-linux-x64/resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:55:12)
    at Function.sync (/usr/share/applications/Avocode-linux-x64/resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:61:24)
    at Object.makeTreeSync (/usr/share/applications/Avocode-linux-x64/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:374:23)
    at e.exports.e.ensureDirectory (file:///usr/share/applications/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:21:26169)
    at e._downloadRevisionMetadata (file:///usr/share/applications/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:19:26153)
    at e._downloadDesignRevision (file:///usr/share/applications/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:19:25955)
    at e._downloadRevision (file:///usr/share/applications/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:19:24377)
    at file:///usr/share/applications/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:19:23846
    at e._processRevision (file:///usr/share/applications/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:30:3623)
    at e._processRevision (file:///usr/share/applications/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:30:1645)
    at e.addRevision (file:///usr/share/applications/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:30:2334)
    at e._addRevisionToQueueWithPriority (file:///usr/share/applications/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:19:23244)
    at e._downloadRevisionAsPrioritized (file:///usr/share/applications/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:19:23571)
    at e.downloadRevisionById (file:///usr/share/applications/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:19:19225)
    at e._downloadRevisionById (file:///usr/share/applications/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:17:28115)
    at e._ensureCompleteRevision (file:///usr/share/applications/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:17:24959)
    at e._loadRevision (file:///usr/share/applications/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:17:24326)
    at e.loadRevisionById (file:///usr/share/applications/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:17:22844)
    at Immediate.N.initialize (file:///usr/share/applications/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:23:12670)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by connor-bean** [comment]
Hey, @Dartlen -

Can you explain more what you were doing when you received this error? This looks similar to #960. Were you having a connection error?

If so, here's how it was fixed for this other user:
Got the same connection error running Avocode on Ubuntu 16.04, however found out that it was a permission problem by reading the error message below. Avocode wasn't allowed to create a folder in my system.

Solved the problem by running the app as administrator, hope this helps somebody else.

Could you try this as well and let us know how it goes?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey, @Dartlen -

Can you explain more what you were doing when you received this error? This looks similar to #960. Were you having a connection error?

If so, here's how it was fixed for this other user:
Got the same connection error running Avocode on Ubuntu 16.04, however found out that it was a permission problem by reading the error message below. Avocode wasn't allowed to create a folder in my system.

Solved the problem by running the app as administrator, hope this helps somebody else.

Could you try this as well and let us know how it goes?

Thanks,
Connor, Avocode Support
