### ISSUE TITLE
Issue while drag and drop

### ISSUE THREAD

**Issue by ronyv89** [avocode/avocode#1165]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.11.1`
Avocode UID: 86143
```
Invariant Violation: Cannot call hover while not dragging.
    at Object.invariant [as default] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dnd/node_modules/invariant/invariant.js:42:15)
    at DragDropManager.hover (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dnd/node_modules/dnd-core/lib/actions/dragDrop.js:116:25)
    at Object.hover (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dnd/node_modules/dnd-core/lib/DragDropManager.js:74:36)
    at HTML5Backend.handleTopDrop (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dnd-html5-backend/lib/HTML5Backend.js:540:18)
    at wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:286:29)
```

**Comment by jakubzitny** [comment]
Hi @ronyv89, thanks for letting us know. We already know about this bug and we have a fix ready for next Avocode release.

As we're already tracking this problem in #1145 I am going to close this thread.
