### ISSUE TITLE
Doesn't copying base64

### ISSUE THREAD

**Issue by salexpro** [avocode/avocode#1169]
IMPORTANT: Please try to describe how did it happen.

---

App v. `2.11.1`
Avocode UID: 30893

```
Error: Unknown layer type "textLayer"
    at e.value (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/rendering/dist/rendering.js:1:14454)
    at e.value (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/rendering/dist/rendering.js:1:8334)
    at e.value (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/rendering/dist/rendering.js:1:7954)
    at e.renderLayer (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:27:12809)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:27:12321
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3018:46
    at List.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3017:23)
    at seqIterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:606:16)
    at IndexedIterable.IndexedSeq.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:322:14)
    at IndexedIterable.toArray (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4260:23)
    at new List (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2067:62)
    at reify (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3572:37)
    at List.map (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4403:14)
    at e.renderLayers (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:27:12184)
    at e.copySelectedLayersAsBase64 (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:17:15904)
    at t._handleCopyBase64 (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:24:2428)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:24:688
    at CallbacksRegistry.apply (/Applications/Avocode.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:54:39)
    at EventEmitter.<anonymous> (/Applications/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:282:21)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

**Comment by connor-bean** [comment]
Hello @salexpro -

Thanks for the report. We have added this to our internal tracking system.

Connor, Avocode Support

**Comment by salexpro** [comment]
It was an icon font and avocode doesn't copying that symbol

**Comment by connor-bean** [comment]
Hey @salexpro 

This should be fixed in our next release. Please let us know of any other questions.

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.12, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please comment on it if you’re still experiencing this problem in Version 2.12.

Thanks!
Connor, Avocode Support
