### ISSUE TITLE
Tried to quit without creating project

### ISSUE THREAD

**Issue by joshwand** [avocode/avocode#1170]
Tried to quit without creating project

---

App v. `2.11.1`
Avocode UID: 100196

```
Error: Could not call remote function 'quit'. Check that the function signature is correct. Underlying error: Cannot read property 'getDisplayMatching' of null
Error: Could not call remote function 'quit'. Check that the function signature is correct. Underlying error: Cannot read property 'getDisplayMatching' of null
    at callFunction (/Users/jwand/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/electron.asar/browser/rpc-server.js:226:11)
    at EventEmitter.<anonymous> (/Users/jwand/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/electron.asar/browser/rpc-server.js:307:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Users/jwand/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/electron.asar/browser/api/web-contents.js:219:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/Users/jwand/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:217:13)
    at remoteMemberFunction (/Users/jwand/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:111:18)
    at t.quit (file:///Users/jwand/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:23:17661)
    at Constructor._handleShortcut (file:///Users/jwand/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:23:27122)
    at _this._handleShortcuts (/Users/jwand/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/lib/component/shortcuts.js:150:23)
    at module.exports [as fireCallback] (/Users/jwand/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/node_modules/combokeys/Combokeys/prototype/fireCallback.js:24:7)
    at module.exports [as handleKey] (/Users/jwand/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/node_modules/combokeys/Combokeys/prototype/handleKey.js:61:12)
    at _this._combokeys.handleKey (/Users/jwand/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/lib/component/shortcuts.js:117:11)
    at HTMLBodyElement._this._customGlobalHandler (/Users/jwand/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/lib/component/shortcuts.js:72:26)
    at HTMLBodyElement.wrapped (/Users/jwand/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:286:29)
    at _this._combokeys.handleKey (/Users/jwand/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/lib/component/shortcuts.js:102:19)
    at module.exports (/Users/jwand/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/node_modules/combokeys/Combokeys/prototype/handleKeyEvent.js:35:8)
    at HTMLUnknownElement.wrapped (/Users/jwand/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:286:29)
```

**Comment by bolekkerous** [comment]
Hey, Josh!
Thanks for reporting the problem.

Could you please tell us what OS are you using? And how exactly did the error happen? You just created new account and tried to quit (How? Cmd + Q? Or in the menu?). Or you tried to add a new project and then quit?

Thanks!
Best regards,
Bolek, Avocode Team

**Comment by connor-bean** [comment]
Hey, @joshwand!
Thanks for reporting the problem.

Could you please tell us what OS are you using? And how exactly did the error happen? You just created new account and tried to quit (How? Cmd + Q? Or in the menu?). Or you tried to add a new project and then quit? 

Thanks!
Best regards,
Connor, Avocode Team

**Comment by connor-bean** [comment]
Hey, @joshwand!
Thanks for reporting the problem.

Could you please tell us what OS are you using? And how exactly did the error happen? You just created new account and tried to quit (How? Cmd + Q? Or in the menu?). Or you tried to add a new project and then quit?

Thanks!
Best regards,
Connor, Avocode Team
