### ISSUE TITLE
Avocode crashes when loading metadata

### ISSUE THREAD

**Issue by aivaras-b** [avocode/avocode#1171]
## This error happens after image have been downloaded and when it starts to show "loading metadata" as application just hangs down

App v. `2.11.1`
Avocode UID: 35574

```
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at invariant (C:\Users\User\AppData\Local\avocode\app-2.11.1\resources\app.asar\node_modules\react\node_modules\fbjs\lib\invariant.js:35:15)
    at Object.findDOMNode (C:\Users\User\AppData\Local\avocode\app-2.11.1\resources\app.asar\node_modules\react\lib\findDOMNode.js:45:205)
    at t.a._focusElement (file:///C:/Users/User/AppData/Local/avocode/app-2.11.1/resources/app.asar/dist/avocode.min.js:8:25008)
    at Immediate.<anonymous> (file:///C:/Users/User/AppData/Local/avocode/app-2.11.1/resources/app.asar/dist/avocode.min.js:8:26731)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by aivaras-b** [comment]
And also it now shows that Processing failed.

**Comment by connor-bean** [comment]
Hey, @aivaras-b -

Is this still happening? Is it happening on multiple designs or just one? 

If it's just happening on one design, could you try reuploading it?

Thanks,
Connor, Avocode Support

**Comment by aivaras-b** [comment]
Hey, @connor-bean 

This happens on a multiple designs where map exists. I will send you design file via email. Thank you in advance.

**Comment by connor-bean** [comment]
Hey @aivaras-b 

Thanks for letting me know. I will await your email of the designs to team@avocode.com

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey @aivaras-b 

I have received your email. I will pass this along to my dev team. We will respond here once we have more information.

Thanks,
Connor, Avocode Support

**Comment by vojtatranta** [comment]
This should be fixed.

Please comment here if it happens again.
