### ISSUE TITLE
tried to load PSD and crash

### ISSUE THREAD

**Issue by tonnyDev** [avocode/avocode#1178]
IMPORTANT: Please try to describe how did it happen.

---

App v. `2.11.1`
Avocode UID: 76617

```
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at invariant (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/node_modules/fbjs/lib/invariant.js:35:15)
    at traverseParentPath (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactInstanceHandles.js:157:164)
    at Object.traverseAncestors (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactInstanceHandles.js:285:5)
    at findDeepestCachedAncestor (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMount.js:234:24)
    at Object.findComponentRoot (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMount.js:708:27)
    at Object.findReactNodeByID (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMount.js:679:23)
    at Object.getNode (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMount.js:162:32)
    at Object.dangerouslyProcessChildrenUpdates [as processChildrenUpdates] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMIDOperations.js:83:42)
    at processQueue (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:160:31)
    at ReactDOMComponent.updateChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:334:13)
    at ReactDOMComponent._updateDOMChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:871:12)
    at ReactDOMComponent.updateComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:700:10)
    at ReactDOMComponent.receiveComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:645:10)
    at Object.receiveComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:87:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:562:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:544:10)
    at ReactCompositeComponentWrapper.updateComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:473:12)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:421:12)
    at Object.performUpdateIfNecessary (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:102:22)
    at runBatchedUpdates (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdates.js:129:21)
    at ReactReconcileTransaction.perform (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:136:20)
    at ReactUpdatesFlushTransaction.perform (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:136:20)
    at ReactUpdatesFlushTransaction.perform (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdates.js:86:38)
    at Object.flushBatchedUpdates (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdates.js:147:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:202:25)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:149:16)
    at Object.batchedUpdates (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
    at Object.enqueueUpdate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdates.js:176:22)
    at enqueueUpdate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdateQueue.js:24:16)
    at Object.enqueueSetState (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdateQueue.js:190:5)
    at t.ReactComponent.setState (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactComponent.js:65:16)
    at o._handleLineMouseUp (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:12:12121)
    at wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:286:29)
```

**Comment by connor-bean** [comment]
Hello @tonnyDev -

Could you provide us with more information on this crash? What were you doing when it happened?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hello @tonnyDev -

Could you provide us with more information on this crash? What were you doing when it happened?

Thanks,
Connor, Avocode Support

**Comment by tonnyDev** [comment]
Hi. I only opened the psd file of my project. It tried to load and I got crash

**Comment by connor-bean** [comment]
Hey, @tonnyDev 

We are working on improving the opening of large designs and it should be included in our next release. 

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.12, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please comment on it if you’re still experiencing this problem in Version 2.12.

Thanks!
Connor, Avocode Support
