### ISSUE TITLE
Error on sleep

### ISSUE THREAD

**Issue by irbisadm** [avocode/avocode#1192]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.11.1`
Avocode UID: 49422
```
Error: getaddrinfo ENOENT manager.avocode.com:443
    at Object.exports._errnoException (util.js:1026:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

**Comment by connor-bean** [comment]
Hey, @irbisadm -

Would you be able to provide us with more information on what was going/what you were doing when you received this error?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey, @irbisadm -

Would you be able to provide us with more information on what was going/what you were doing when you received this error?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Closing due to inactivity. Please comment on it if you are able to provide us with more information on what was going on/what you were doing when you received the error.

Thanks,
Connor, Avocode Support
