### ISSUE TITLE
Error when drag from a zip.

### ISSUE THREAD

**Issue by t1gu1** [avocode/avocode#1201]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.11.1`
Avocode UID: 38990
```
Invariant Violation: Cannot call hover while not dragging.
    at Object.invariant [as default] (/home/guillaume/apps/Avocode-linux-x64/resources/app.asar/node_modules/react-dnd/node_modules/invariant/invariant.js:42:15)
    at DragDropManager.hover (/home/guillaume/apps/Avocode-linux-x64/resources/app.asar/node_modules/react-dnd/node_modules/dnd-core/lib/actions/dragDrop.js:116:25)
    at Object.hover (/home/guillaume/apps/Avocode-linux-x64/resources/app.asar/node_modules/react-dnd/node_modules/dnd-core/lib/DragDropManager.js:74:36)
    at HTML5Backend.handleTopDrop (/home/guillaume/apps/Avocode-linux-x64/resources/app.asar/node_modules/react-dnd-html5-backend/lib/HTML5Backend.js:540:18)
    at wrapped (/home/guillaume/apps/Avocode-linux-x64/resources/app.asar/node_modules/raven-js/src/raven.js:286:29)
```

**Comment by vojtatranta** [comment]
What do you mean by "drag from a zip"?

**Comment by connor-bean** [comment]
Hey @t1gu1 -

Could you provide more information for Vojta? He was wondering if you could explain more what you mean when you said "drag from a zip?"

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey @t1gu1 -

Could you provide more information for Vojta? He was wondering if you could explain more what you mean when you said "drag from a zip?"

Thanks,
Connor, Avocode Support
