### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by andrewbateman** [avocode/avocode#1202]
Describe your problem here…

-----

```
Error: Emitter has been disposed
    at Emitter.module.exports.Emitter.on (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:34:15)
    at e.module.exports.e.onDidClose (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode-view.js:1:880)
    at t._loadRevisionToView (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:15932)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:15274
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:15538
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:17758
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/progress.js:1:4040
    at done (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:132:19)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:32:16
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/progress.js:1:3925
    at s._handleRevisionResult (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/revision-download-queue.js:1:3485)
    at next (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:798:43)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:32:16
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/revision-download-queue.js:1:2300
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:1064
```

**Comment by connor-bean** [comment]
Hey @andrewbateman -

Can you tell us more about what was going on when you received this error?

Thanks,
Connor, Avocode Support

**Comment by andrewbateman** [comment]
Hi, I uploaded a new design while the project I was uploading to was synching to my local computer. Side note: every week or so my local cache seems to get lost and I need to re-download all my designs. This error seems to occur while this is happening.

**Comment by jankuca** [comment]
Hi Andrew,
What version of Avocode are you using?

IIRC, this bug should not be happening in the latest version (2.11.1).

**Comment by connor-bean** [comment]
Hi Andrew,
What version of Avocode are you using?

IIRC, this bug should not be happening in the latest version (2.11.1).

**Comment by connor-bean** [comment]
Please comment if you can provide more information.

Thanks,
Connor, Avocode Support

**Comment by andrewbateman** [comment]
Hi sorry for the delay... my version is quite old admittedly, 2.2.0-4d88223. I will upgrade and hopefully this will fix it.

**Comment by vojtatranta** [comment]
@andrewbateman wooow, that's ancient! Go to https://avocode.com/ to download latets version `2.12.0`
