### ISSUE TITLE
Crashed on quit.

### ISSUE THREAD

**Issue by epsimatic** [avocode/avocode#1209]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.11.1`
Avocode UID: 107857
```
Error: Could not call remote function 'quit'. Check that the function signature is correct. Underlying error: Cannot read property 'getDisplayMatching' of null
Error: Could not call remote function 'quit'. Check that the function signature is correct. Underlying error: Cannot read property 'getDisplayMatching' of null
    at callFunction (/private/var/folders/jb/q9g9lnm167g9sb9x66ln9hc80000gn/T/AppTranslocation/44C668CA-BB71-46AC-952D-C4BA8988D87B/d/Avocode.app/Contents/Resources/electron.asar/browser/rpc-server.js:226:11)
    at EventEmitter.<anonymous> (/private/var/folders/jb/q9g9lnm167g9sb9x66ln9hc80000gn/T/AppTranslocation/44C668CA-BB71-46AC-952D-C4BA8988D87B/d/Avocode.app/Contents/Resources/electron.asar/browser/rpc-server.js:307:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/private/var/folders/jb/q9g9lnm167g9sb9x66ln9hc80000gn/T/AppTranslocation/44C668CA-BB71-46AC-952D-C4BA8988D87B/d/Avocode.app/Contents/Resources/electron.asar/browser/api/web-contents.js:219:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/private/var/folders/jb/q9g9lnm167g9sb9x66ln9hc80000gn/T/AppTranslocation/44C668CA-BB71-46AC-952D-C4BA8988D87B/d/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:217:13)
    at remoteMemberFunction (/private/var/folders/jb/q9g9lnm167g9sb9x66ln9hc80000gn/T/AppTranslocation/44C668CA-BB71-46AC-952D-C4BA8988D87B/d/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:111:18)
    at t.quit (file:///private/var/folders/jb/q9g9lnm167g9sb9x66ln9hc80000gn/T/AppTranslocation/44C668CA-BB71-46AC-952D-C4BA8988D87B/d/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:23:17661)
    at Constructor._handleShortcut (file:///private/var/folders/jb/q9g9lnm167g9sb9x66ln9hc80000gn/T/AppTranslocation/44C668CA-BB71-46AC-952D-C4BA8988D87B/d/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:23:27122)
    at _this._handleShortcuts (/private/var/folders/jb/q9g9lnm167g9sb9x66ln9hc80000gn/T/AppTranslocation/44C668CA-BB71-46AC-952D-C4BA8988D87B/d/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/lib/component/shortcuts.js:150:23)
    at module.exports [as fireCallback] (/private/var/folders/jb/q9g9lnm167g9sb9x66ln9hc80000gn/T/AppTranslocation/44C668CA-BB71-46AC-952D-C4BA8988D87B/d/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/node_modules/combokeys/Combokeys/prototype/fireCallback.js:24:7)
    at module.exports [as handleKey] (/private/var/folders/jb/q9g9lnm167g9sb9x66ln9hc80000gn/T/AppTranslocation/44C668CA-BB71-46AC-952D-C4BA8988D87B/d/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/node_modules/combokeys/Combokeys/prototype/handleKey.js:61:12)
    at _this._combokeys.handleKey (/private/var/folders/jb/q9g9lnm167g9sb9x66ln9hc80000gn/T/AppTranslocation/44C668CA-BB71-46AC-952D-C4BA8988D87B/d/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/lib/component/shortcuts.js:117:11)
    at HTMLBodyElement._this._customGlobalHandler (/private/var/folders/jb/q9g9lnm167g9sb9x66ln9hc80000gn/T/AppTranslocation/44C668CA-BB71-46AC-952D-C4BA8988D87B/d/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/lib/component/shortcuts.js:72:26)
    at HTMLBodyElement.wrapped (/private/var/folders/jb/q9g9lnm167g9sb9x66ln9hc80000gn/T/AppTranslocation/44C668CA-BB71-46AC-952D-C4BA8988D87B/d/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:286:29)
    at _this._combokeys.handleKey (/private/var/folders/jb/q9g9lnm167g9sb9x66ln9hc80000gn/T/AppTranslocation/44C668CA-BB71-46AC-952D-C4BA8988D87B/d/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/lib/component/shortcuts.js:102:19)
    at module.exports (/private/var/folders/jb/q9g9lnm167g9sb9x66ln9hc80000gn/T/AppTranslocation/44C668CA-BB71-46AC-952D-C4BA8988D87B/d/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/node_modules/combokeys/Combokeys/prototype/handleKeyEvent.js:35:8)
    at HTMLDivElement.wrapped (/private/var/folders/jb/q9g9lnm167g9sb9x66ln9hc80000gn/T/AppTranslocation/44C668CA-BB71-46AC-952D-C4BA8988D87B/d/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:286:29)
```

**Comment by vojtatranta** [comment]
Hello @epsimatic,
this is a common bug in Electron and it should be fixed in the next release.

Could you please after release of `2.12.0` confirm the fix?

**Comment by epsimatic** [comment]
Sorry I couldn't. My trial would be over before 2.12 will be out

**Comment by connor-bean** [comment]
Hey @epsimatic -

Can you email us at team@avocode.com with the email address you use with Avocode? I will extend your trial so you can test 2.12. 

Please reference this ticket in your email and I'll make sure your trial gets extended.

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.12, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please comment on it if you’re still experiencing this problem in Version 2.12.

Thanks!
Connor, Avocode Support
