### ISSUE TITLE
artboard photoshop

### ISSUE THREAD

**Issue by drinkmaker** [avocode/avocode#1211]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.12.0-community-beta.2`
Avocode UID: 78879
```
Error: Cannot open a document with no revision or no current revision
    at t.openDesignById (file:///home/ak/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:51:26954)
    at Constructor._handleEntityOpen (file:///home/ak/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:53:14978)
    at Constructor._handleEntityDoubleClick (file:///home/ak/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:52:3314)
    at Object.invokeGuardedCallback (/home/ak/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactErrorUtils.js:27:12)
    at executeDispatch (/home/ak/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/EventPluginUtils.js:79:21)
    at Object.executeDispatchesInOrder (/home/ak/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/EventPluginUtils.js:102:5)
    at executeDispatchesAndRelease (/home/ak/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/EventPluginHub.js:43:22)
    at executeDispatchesAndReleaseTopLevel (/home/ak/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/EventPluginHub.js:54:10)
    at Array.forEach (native)
    at forEachAccumulated (/home/ak/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/forEachAccumulated.js:23:9)
    at Object.processEventQueue (/home/ak/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/EventPluginHub.js:259:7)
    at runEventQueueInBatch (/home/ak/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
    at Object.handleTopLevel [as _handleTopLevel] (/home/ak/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactEventEmitterMixin.js:34:5)
    at handleTopLevelWithoutPath (/home/ak/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactEventListener.js:93:24)
    at handleTopLevelImpl (/home/ak/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactEventListener.js:73:3)
    at ReactDefaultBatchingStrategyTransaction.perform (/home/ak/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/Transaction.js:136:20)
    at Object.batchedUpdates (/home/ak/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
    at Object.batchedUpdates (/home/ak/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactUpdates.js:94:20)
    at dispatchEvent (/home/ak/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactEventListener.js:204:20)
    at HTMLDocument.wrapped (/home/ak/Avocode-linux-x64/resources/app.asar/node_modules/raven-js/src/raven.js:274:29)
```

**Comment by vojtatranta** [comment]
Thank you @drinkmaker,
we know about it and we are working on a fix for stable release.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.12, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please comment on it if you’re still experiencing this problem in Version 2.12.

Thanks!
Connor, Avocode Support
