### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by sozonovalexey** [avocode/avocode#1216]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.12.0`
Avocode UID: 4706
```
Error: Cannot open a document with no revision or no current revision
    at t.openDesignById (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:53:9553)
    at Constructor._handleEntityOpen (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:54:28789)
    at Constructor._handleEntityDoubleClick (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:53:18188)
    at Object.invokeGuardedCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactErrorUtils.js:27:12)
    at executeDispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:79:21)
    at Object.executeDispatchesInOrder (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:102:5)
    at executeDispatchesAndRelease (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:43:22)
    at executeDispatchesAndReleaseTopLevel (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:54:10)
    at Array.forEach (native)
    at forEachAccumulated (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/forEachAccumulated.js:23:9)
    at Object.processEventQueue (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:259:7)
    at runEventQueueInBatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
    at Object.handleTopLevel [as _handleTopLevel] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventEmitterMixin.js:34:5)
    at handleTopLevelWithoutPath (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventListener.js:93:24)
    at handleTopLevelImpl (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventListener.js:73:3)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:136:20)
    at Object.batchedUpdates (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
    at Object.batchedUpdates (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdates.js:94:20)
    at dispatchEvent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventListener.js:204:20)
    at HTMLDocument.wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:278:29)
```

**Comment by connor-bean** [comment]
Hey @sozonovalexey -

Thanks for the report. Could you tell us more about what you were doing when this happened?

Thanks,
Connor, Avocode Support

**Comment by sozonovalexey** [comment]
The problem was solved! I deleted a file, create a new project and upload it again. Sorry for panic!

**Comment by vojtatranta** [comment]
@sozonovalexey actually it is a reason to panic for us...

Can you please tell use what were you doing? I think that you were uploading design from Sketch or on the web and you tried to open in the app during the upload / processign, right?

**Comment by sozonovalexey** [comment]
Yes. After the app was updated. I open the project. But the file download stopped in the middle. I wait some time. Then I relaunch the app and I try to open the file and get this error.

**Comment by vojtatranta** [comment]
@sozonovalexey acknowledge.

It will be fixed, thanks!
