### ISSUE TITLE
"An unexpected error has occured" after finishing upload the psd file

### ISSUE THREAD

**Issue by Danny-weebo** [avocode/avocode#1226]
I just tried to upload a psd and when it finished and tried to open the "editor mode" I receive the error.
I'm getting this kinds of errors a lot lately, and it's really annoying, please help me here.

-----
App v.2.3.2-ea60620
Source UID: 104492
```
Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.
    at invariant (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/invariant.js:42:15)
    at o.Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:185:5)
    at o.handleServerAction (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/dispatcher.js:1:980)
    at e._emitItemUploadProgress (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uploader.js:1:10344)
    at ReadStream.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uploader.js:1:8619)
    at emitOne (events.js:77:13)
    at ReadStream.emit (events.js:166:7)
    at ReadStream.source.emit (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/request/node_modules/combined-stream/node_modules/delayed-stream/lib/delayed_stream.js:30:21)
    at ReadStream.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uploader.js:1:9056)
    at emitOne (events.js:82:20)
    at ReadStream.emit (events.js:166:7)
    at ReadStream.source.emit (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/request/node_modules/combined-stream/node_modules/delayed-stream/lib/delayed_stream.js:30:21)
    at ReadStream.Readable.read (_stream_readable.js:356:10)
    at flow (_stream_readable.js:734:26)
    at resume_ (_stream_readable.js:714:3)
    at _stream_readable.js:701:7
    at process._tickCallback (node.js:357:13)
    at EventEmitter.ipc.sendSync (/Applications/Avocode.app/Contents/Resources/atom.asar/renderer/api/lib
```

**Comment by Danny-weebo** [comment]
Now when I try to open the design from the app I get this error,

-----
App v.2.3.2-ea60620
Source UID: 104492
```
Error: channel closed
    at ChildProcess.target.send (child_process.js:396:26)
    at Task.module.exports.Task.send (/Applications/Avocode.app/Contents/Resources/app.asar/src/task.js:125:27)
    at e._send (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:5895)
    at e._addRequest (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:3910)
    at e.downloadFiles (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:1981)
    at e.downloadFiles (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:6381)
    at t.module.exports.t._createImageRequest (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-downloader.js:1:1938)
    at t.module.exports.t.downloadImages (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-downloader.js:1:1150)
    at e._downloadRevisionImages (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:13852)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:12667
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:801
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:5681
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:6126
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/fstream/node_modules/graceful-fs/graceful-fs.js:104:5
    at FSReqWrap.oncomplete (fs.js:77:15)
```

**Comment by vojtatranta** [comment]
Hi @Danny-weebo you are using an ancient version of the App!

Please update or download current build here https://avocode.com/download.html

And then please try again.

**Comment by Danny-weebo** [comment]
Hi, thanks for the quick reply.

Yes it does work now, an Inside update or any notice in the app could be useful.

thanks!

**Comment by vojtatranta** [comment]
@Danny-weebo there is one, but you had a version of the app which had been one and half year old.

**Comment by Danny-weebo** [comment]
I really like the app and so used to it (as it was) so I probably didn't even pay attention to it :)

thanks again.

**Comment by vojtatranta** [comment]
Yes, I understand that, no problem.

Thank you for using it! I hope you'll appreciate all those new features in 9 versions you missed :))
