### ISSUE TITLE
TypeError: Cannot read property 'get' of null at Object.createLayerComposition 

### ISSUE THREAD

**Issue by exdeniz** [avocode/avocode#1231]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.12.1`
Avocode UID: 94565
```
TypeError: Cannot read property 'get' of null
    at Object.createLayerComposition (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/rendering-composer/lib/utils/composition-utils.js:34:43)
    at e._layerComposition (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:6:4172)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:6:4645
    at List.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at List.forEach (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4383:19)
    at e._layersComposition (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:6:4505)
    at e.documentComposition (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:6:5010)
    at t._getUpdatedDocumentComposition (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:45:30737)
    at t._createDocumentComposition (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:45:29601)
    at t._handleAction (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:45:29112)
    at Object.ID_40 (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:45:27457)
    at Dispatcher._invokeCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:198:24)
    at Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:174:14)
    at Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/flux/lib/dispatcher.js:70:28)
    at t.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/flux/lib/action-creator.js:37:24)
    at t.revisionLoad (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:40:988)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:40:9296
    at Immediate.<anonymous> (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:41:19275)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by connor-bean** [comment]
Hey @exdeniz -

Can you tell us more about what you were doing when this happened? Could you also send us this problematic design file to team@avocode.com?

Thanks,
Connor, Avocode Support

**Comment by exdeniz** [comment]
@connor-bean yep. I will send the design in the next three days.

**Comment by bolekkerous** [comment]
Hey, @exdeniz -
are you still experiencing this problem even with the latest version of Avocode?

If so, could you please send us the problematic design file to team@avocode.com?

Thanks,
Bolek, Avocode Team

**Comment by connor-bean** [comment]
Hey, @exdeniz -
are you still experiencing this problem even with the latest version of Avocode?

If so, could you please send us the problematic design file to team@avocode.com?

Thanks,
Connor, Avocode Team
