### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by dmitriy-chernysh** [avocode/avocode#1241]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.12.4`
Avocode UID: 117015
```
Invariant Violation: Cannot call hover while not dragging.
    at Object.invariant [as default] (/home/cdv/Dev/Tools/Avocode-linux-x64/resources/app.asar/node_modules/react-dnd/node_modules/invariant/invariant.js:42:15)
    at DragDropManager.hover (/home/cdv/Dev/Tools/Avocode-linux-x64/resources/app.asar/node_modules/react-dnd/node_modules/dnd-core/lib/actions/dragDrop.js:116:25)
    at Object.hover (/home/cdv/Dev/Tools/Avocode-linux-x64/resources/app.asar/node_modules/react-dnd/node_modules/dnd-core/lib/DragDropManager.js:74:36)
    at HTML5Backend.handleTopDrop (/home/cdv/Dev/Tools/Avocode-linux-x64/resources/app.asar/node_modules/react-dnd-html5-backend/lib/HTML5Backend.js:540:18)
    at wrapped (/home/cdv/Dev/Tools/Avocode-linux-x64/resources/app.asar/node_modules/raven-js/src/raven.js:278:29)
```

**Comment by connor-bean** [comment]
Hello @dmitriy-chernysh -

Can you tell us more what you were doing when this crash happened?

Thanks,
Connor, Avocode Support

**Comment by dmitriy-chernysh** [comment]
Hi!
I had created a new project and tried to move .sketch file to Avocode window (see attachment image). But, I have Ubuntu OS and later I have understood that I can't do it. But it would be great uploading .sketch from Ubuntu :)

![screenshot from 2017-01-17 18-08-06](https://cloud.githubusercontent.com/assets/5750211/22028468/efbb681a-dcdf-11e6-9c10-15d3306ffb6a.png)

**Comment by vojtatranta** [comment]
@dmitriy-chernysh great! Thank you for this report, we will try to reproduce it and fix it.

**Comment by connor-bean** [comment]
Hey @dmitriy-chernysh -

We are tracking this in #1249 so I will close this duplicate
