### ISSUE TITLE
Just tried to upload .psd with 4 artboards ;(

### ISSUE THREAD

**Issue by mozares** [avocode/avocode#1244]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.12.4`
Avocode UID: 96210
```
Error: No such module: atom_common_app
    at Error (native)
    at process.atomBinding (/Applications/Avocode.app/Contents/Resources/electron.asar/common/init.js:10:14)
    at Object.<anonymous> (/Applications/Avocode.app/Contents/Resources/electron.asar/browser/api/app.js:3:26)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.get (/Applications/Avocode.app/Contents/Resources/electron.asar/browser/api/exports/electron.js:11:14)
    at stringify (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/node_modules/json-stringify-safe/stringify.js:5:15)
    at Object._makeRequest (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1495:22)
    at Object._sendProcessedPayload (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1431:56)
    at Object._send (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1388:14)
    at Object._processException (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1285:14)
    at Object._handleStackInfo (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1191:14)
    at Object.captureException (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:345:18)
    at e.captureException (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:30:28213)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:41:4134
```

**Comment by petrbrzek** [comment]
@mozares Thanks for the report. Are you able to replicate the error every time or does it happen randomly?

**Comment by connor-bean** [comment]
GL 2989

**Comment by connor-bean** [comment]
Hey @sera2007 -

Are you able to replicate the error every time or does it happen randomly?

Thanks,
Connor, Avocode Support

**Comment by sera2007** [comment]
It was only once, I just reloaded the app and it works fine right now

**Comment by vojtatranta** [comment]
@sera2007 yes, it's Electron bug we can't do much about, we downgraded Electron to new stable version and we'll wait for fix.
