### ISSUE TITLE
Drang and drop from a zip

### ISSUE THREAD

**Issue by t1gu1** [avocode/avocode#1249]
IMPORTANT: Please try to describe how did it happen.

**## How to reproduce:**

On linux

1. Open a zip (without extract it)
2. drag and drop the files from .zip to avocode.

-----
App v. `2.12.1`
Avocode UID: 38990
```
Invariant Violation: Cannot call hover while not dragging.
    at Object.invariant [as default] (/home/guillaume/apps/Avocode-linux-x64/resources/app.asar/node_modules/react-dnd/node_modules/invariant/invariant.js:42:15)
    at DragDropManager.hover (/home/guillaume/apps/Avocode-linux-x64/resources/app.asar/node_modules/react-dnd/node_modules/dnd-core/lib/actions/dragDrop.js:116:25)
    at Object.hover (/home/guillaume/apps/Avocode-linux-x64/resources/app.asar/node_modules/react-dnd/node_modules/dnd-core/lib/DragDropManager.js:74:36)
    at HTML5Backend.handleTopDrop (/home/guillaume/apps/Avocode-linux-x64/resources/app.asar/node_modules/react-dnd-html5-backend/lib/HTML5Backend.js:540:18)
    at wrapped (/home/guillaume/apps/Avocode-linux-x64/resources/app.asar/node_modules/raven-js/src/raven.js:278:29)
```

**Comment by connor-bean** [comment]
Hey @t1gu1 -

Thanks for the report. We will look more into this

Connor, Avocode Support

**Comment by vojtatranta** [comment]
Not in 2.13.0 yet
