### ISSUE TITLE
Issue when launching Avocode

### ISSUE THREAD

**Issue by AlexandruDoda** [avocode/avocode#1255]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.10.1`
Source UID: 651
```
Error: Could not call remote function 'quit'. Check that the function signature is correct. Underlying error: Cannot read property 'getDisplayMatching' of null
Error: Could not call remote function 'quit'. Check that the function signature is correct. Underlying error: Cannot read property 'getDisplayMatching' of null
    at callFunction (/Applications/Avocode.app/Contents/Resources/electron.asar/browser/rpc-server.js:225:11)
    at EventEmitter.<anonymous> (/Applications/Avocode.app/Contents/Resources/electron.asar/browser/rpc-server.js:306:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Avocode.app/Contents/Resources/electron.asar/browser/api/web-contents.js:218:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/Applications/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:176:13)
    at remoteMemberFunction (/Applications/Avocode.app/Con
```

**Comment by jakubzitny** [comment]
Hi, you have the old version of our app. Please update to the latest, you can download it from [manager.avocode.com/downloads](https://manager.avocode.com/downloads/).

Let us know if you have any more issues with Avocode.
