### ISSUE TITLE
on upload app

### ISSUE THREAD

**Issue by aryeharmon** [avocode/avocode#1256]
upload app
-----
App v.2.4.5
Source UID: 247131
```
TypeError: this._task.removeListener is not a function
    at t._unregisterTaskListeners (/home/aryeh/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:3779)
    at t._restart (/home/aryeh/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:2738)
    at t._send (/home/aryeh/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:6454)
    at t._addRequest (/home/aryeh/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:4400)
    at t.downloadFiles (/home/aryeh/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:2016)
    at e.downloadFiles (/home/aryeh/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:7802)
    at t.module.exports.t.downloadThumbnails (/home/aryeh/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/assets-downloader.js:1:1032)
    at e._downloadThumbnails (/home/aryeh/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:15507)
    at e._updateDesignThumbnail (/home/aryeh/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:19349)
    at /home/aryeh/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:18578
    at /home/aryeh/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:766
    at Request._callback (/home/aryeh/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:4329)
    at Request.self.callback (/home/aryeh/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:198:22)
    at emitTwo (events.js:92:20)
    at Request.emit (events.js:169:7)
    at Request.<anonymous> (/home/aryeh/Avocode
```

**Comment by vojtatranta** [comment]
Hello,
you have an ancient version of the app. Please update it, or download latest version from https://avocode.com/download

Reopen this issue if you still have this problem.
