### ISSUE TITLE
bug finded

### ISSUE THREAD

**Issue by sedatcakir** [avocode/avocode#1264]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.12.4`
Avocode UID: 95125
```
TypeError: Cannot read property 'forEach' of undefined
    at o (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:31:15516)
    at e._getImagesToDownload (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:31:15799)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:31:9881
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:31:11177
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by connor-bean** [comment]
Hello, thanks for the report. We're tracking this in #1263 so I will close this duplicate
