### ISSUE TITLE
Design extract failed

### ISSUE THREAD

**Issue by p-boiko** [avocode/avocode#1266]
This happened during a design extraction on a stage of "Downloading metadata..."
This screen then stalled http://screencloud.net/v/7q4 until procedure was canceled

-----
App v. `2.12.4`
Avocode UID: 78965
```
TypeError: Cannot read property 'forEach' of undefined
    at o (file:///home/.../software/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:31:15516)
    at e._getImagesToDownload (file:///home/.../software/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:31:15799)
    at file:///home/.../software/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:31:9881
    at file:///home/.../software/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:31:11177
    at /home/.../software/Avocode-linux-x64/resources/app.asar/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by connor-bean** [comment]
Hello, thanks for the report. We're tracking this in #1263 so I will close this duplicate
