### ISSUE TITLE
IMPORTANT: Please try to describe how did it happen.

### ISSUE THREAD

**Issue by justlp** [avocode/avocode#1267]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.12.3`
Avocode UID: 97544
```
TypeError: Cannot read property 'forEach' of undefined
    at o (file:///Users/elpe/Desktop/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:31:15516)
    at e._getImagesToDownload (file:///Users/elpe/Desktop/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:31:15799)
    at file:///Users/elpe/Desktop/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:31:9881
    at file:///Users/elpe/Desktop/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:31:11177
    at /Users/elpe/Desktop/Avocode.app/Contents/Resources/app.asar/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by connor-bean** [comment]
Hello, thanks for the report. We're tracking this in #1263 so I will close this duplicate
