### ISSUE TITLE
I can't run avocode

### ISSUE THREAD

**Issue by leonenko** [avocode/avocode#1268]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.12.4`
Avocode UID: 69739
```
TypeError: Cannot read property 'forEach' of undefined
    at o (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:31:15516)
    at e._getImagesToDownload (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:31:15799)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:31:9881
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:31:11177
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by connor-bean** [comment]
Hey, thanks for the report. We're tracking this in #1263 so I will close this duplicate
