### ISSUE TITLE
slice use

### ISSUE THREAD

**Issue by Hkr32** [avocode/avocode#1269]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.12.4`
Avocode UID: 118686
```
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at invariant (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/node_modules/fbjs/lib/invariant.js:35:15)
    at Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:167:160)
    at Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/flux/lib/dispatcher.js:70:28)
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:28:1793)
    at e.setBounds (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:59:10620)
    at _handleAreaSliceCreateBounds (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:59:15903)
    at t._handleMouseMove (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:44:21391)
    at t._handleMouseMove (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:44:18245)
    at t._handleStageChange (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:44:20716)
    at t.<anonymous> (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:44:18245)
    at emitNone (events.js:91:20)
    at t.emit (events.js:185:7)
    at componentDidUpdate (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:44:24356)
    at CallbackQueue.notifyAll (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/CallbackQueue.js:76:22)
    at ReactReconcileTransaction.close (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconcileTransaction.js:80:26)
    at ReactReconcileTransaction.closeAll (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:206:25)
    at ReactReconcileTransaction.perform (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:153:16)
    at ReactUpdatesFlushTransaction.perform (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:140:20)
    at ReactUpdatesFlushTransaction.perform (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:89:32)
    at Object.flushBatchedUpdates (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:172:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:206:25)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:153:16)
    at Object.batchedUpdates (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.enqueueUpdate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:200:22)
    at enqueueUpdate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdateQueue.js:24:16)
    at Object.enqueueSetState (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdateQueue.js:209:5)
    at ReactComponent.setState (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactComponent.js:63:16)
    at _handleUiStoreChange (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:44:24671)
    at emitNone (events.js:91:20)
    at t.emit (events.js:185:7)
    at t.emitChange (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/flux/lib/store.js:47:12)
    at t._handleAction (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:39:7212)
    at Object.ID_11 (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:39:5294)
    at Dispatcher._invokeCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:198:24)
    at Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:174:14)
    at Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/flux/lib/dispatcher.js:70:28)
    at t.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/flux/lib/action-creator.js:37:24)
    at t.addUiItem (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:31:16267)
    at e.openExportModal (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:42:12832)
    at t._handleSaveAsImage (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:34:17883)
    at t._handleSaveAsImage (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:34:16051)
    at click (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:34:19100)
    at CallbacksRegistry.apply (/Applications/Avocode.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:48:25)
    at EventEmitter.<anonymous> (/Applications/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:282:21)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

**Comment by connor-bean** [comment]
Hey @Hkr32 thanks for the report. We will fix this for our next release.

**Comment by vojtatranta** [comment]
This should be fixed.

Leave a comment if it appears again.
