### ISSUE TITLE
I opened the app, and the app crashed

### ISSUE THREAD

**Issue by Chandlerdea** [avocode/avocode#1284]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.12.4`
Avocode UID: 2161
```
Error: Cannot call function 'send' on missing remote object 36
Error: Cannot call function 'send' on missing remote object 36
    at throwRPCError (/Users/chandlerdeangelis/Downloads/Avocode.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Users/chandlerdeangelis/Downloads/Avocode.app/Contents/Resources/electron.asar/browser/rpc-server.js:339:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Users/chandlerdeangelis/Downloads/Avocode.app/Contents/Resources/electron.asar/browser/api/web-contents.js:231:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/Users/chandlerdeangelis/Downloads/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:217:13)
    at remoteMemberFunction (/Users/chandlerdeangelis/Downloads/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:113:18)
    at t._sendStart (file:///Users/chandlerdeangelis/Downloads/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:36:12586)
    at file:///Users/chandlerdeangelis/Downloads/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:36:13287
    at Array.forEach (native)
    at t._handleDownloaderReady (file:///Users/chandlerdeangelis/Downloads/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:36:13260)
    at EventEmitter.<anonymous> (file:///Users/chandlerdeangelis/Downloads/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:36:9805)
    at EventEmitter.g (events.js:286:16)
    at emitTwo (events.js:111:20)
    at EventEmitter.emit (events.js:191:7)
```

**Comment by connor-bean** [comment]
Hello - thanks for the report.

Did this only happen on 2.12.4? Could you try updating to 2.12.5 and let us know if it still happens there?

You can download 2.12.5 here: www.manager.avocode.com/downloads

**Comment by vojtatranta** [comment]
Hello, this is an issue in electron we can't unfortunately do much about it.

But in the `2.12.5` we downgraded electron to hopefully more stable version. Feel free to try it out.
