### ISSUE TITLE
Unexpected crash

### ISSUE THREAD

**Issue by sera2007** [avocode/avocode#1285]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.12.5`
Avocode UID: 19540
```
Error: No such module: atom_common_app
    at Error (native)
    at process.atomBinding (/Users/Serdyuk/Applications/Avocode.app/Contents/Resources/electron.asar/common/init.js:10:14)
    at Object.<anonymous> (/Users/Serdyuk/Applications/Avocode.app/Contents/Resources/electron.asar/browser/api/app.js:3:26)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.get (/Users/Serdyuk/Applications/Avocode.app/Contents/Resources/electron.asar/browser/api/exports/electron.js:11:14)
    at stringify (/Users/Serdyuk/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/node_modules/json-stringify-safe/stringify.js:5:15)
    at Object._makeRequest (/Users/Serdyuk/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1559:22)
    at Object._sendProcessedPayload (/Users/Serdyuk/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1485:56)
    at Object._send (/Users/Serdyuk/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1442:14)
    at Object._processException (/Users/Serdyuk/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1290:14)
    at Object._handleStackInfo (/Users/Serdyuk/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1196:14)
    at Object.captureException (/Users/Serdyuk/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:350:18)
    at e.captureException (file:///Users/Serdyuk/Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:31:1067)
    at file:///Users/Serdyuk/Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:41:9238
```

**Comment by connor-bean** [comment]
Hey @sera2007 thanks for the report. We're tracking this in #1244 so I'm going to close this one and we'll continue tracking it there.

Thanks,
Connor, Avocode Support
