### ISSUE TITLE
i just changed language with Alt+Shift

### ISSUE THREAD

**Issue by nemishkor** [avocode/avocode#1290]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.11.1`
Avocode UID: 66962
```
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at invariant (/home/nemishkor/opt/Avocode-linux-x64/resources/app.asar/node_modules/react/node_modules/fbjs/lib/invariant.js:35:15)
    at Object.findDOMNode (/home/nemishkor/opt/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/findDOMNode.js:45:205)
    at t.a._focusElement (file:///home/nemishkor/opt/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:8:25008)
    at Immediate.<anonymous> (file:///home/nemishkor/opt/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:8:26731)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate (timers.js:533:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by vojtatranta** [comment]
Hello, this should be fixed, please update your application, current version is `2.12.6`, download it here https://avocode.com/download
