### ISSUE TITLE
issue while exporting

### ISSUE THREAD

**Issue by himgupta** [avocode/avocode#1296]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.11.0`
Source UID: 88775
```
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at invariant (/home/himanshugupta/Avocode-linux-x64/resources/app.asar/node_modules/react/node_modules/fbjs/lib/invariant.js:35:15)
    at Object.findComponentRoot (/home/himanshugupta/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactMount.js:764:478)
    at Object.findReactNodeByID (/home/himanshugupta/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactMount.js:679:23)
    at Object.getNode (/home/himanshugupta/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactMount.js:162:32)
    at ReactDOMComponent.getPublicInstance (/home/himanshugupta/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:925:29)
    at Object.removeComponentAsRefFrom (/home/himanshugupta/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactOwner.js:84:59)
    at detachRef (/home/himanshugupta/Avo
```

**Comment by bolekkerous** [comment]
Hello -
you're using old version of app, please update to the latest one. You can always download the latest version here:

https://manager.avocode.com/downloads/

Or you can just check for updates in your app.

Does that help?

**Comment by vojtatranta** [comment]
Please comment when it appears with newer version too.
