### ISSUE TITLE
Something goes wrong

### ISSUE THREAD

**Issue by simonboyko** [avocode/avocode#1301]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.11.1`
Avocode UID: 126257
```
Invariant Violation: Cannot call beginDrag while dragging.
    at Object.invariant [as default] (/home/simon/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/react-dnd/node_modules/invariant/invariant.js:42:15)
    at DragDropManager.beginDrag (/home/simon/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/react-dnd/node_modules/dnd-core/lib/actions/dragDrop.js:53:25)
    at Object.beginDrag (/home/simon/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/react-dnd/node_modules/dnd-core/lib/DragDropManager.js:74:36)
    at HTML5Backend.handleTopDragStart (/home/simon/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/react-dnd-html5-backend/lib/HTML5Backend.js:313:18)
    at wrapped (/home/simon/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/raven-js/src/raven.js:286:29)
```

**Comment by bolekkerous** [comment]
Hey, @simonboyko -
it seems like you're using outdated version of the Avocode app.

Please try to update your app by hitting the "Check for Updates" in menu or by downloading latest version here:

https://avocode.com/download.html

This error shouldn't happen in the newer version as far as I know, so if it happens even there, please let us know here.
