### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by thehalestorm** [avocode/avocode#1305]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.12.6`
Avocode UID: 65941
```
Invariant Violation: Cannot call hover while not dragging.
    at invariant (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dnd/node_modules/invariant/invariant.js:42:15)
    at DragDropManager.hover (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dnd/node_modules/dnd-core/lib/actions/dragDrop.js:107:27)
    at Object.hover (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dnd/node_modules/dnd-core/lib/DragDropManager.js:92:38)
    at HTML5Backend.handleTopDrop (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dnd-html5-backend/lib/HTML5Backend.js:579:20)
    at wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:283:29)
```

**Comment by connor-bean** [comment]
Hey @thehalestorm -

Thanks for the report. We are currently tracking this in #1249 so I will close this as it is a duplicate.
