### ISSUE TITLE
app error while trying to upload from opened zip :)

### ISSUE THREAD

**Issue by kure-** [avocode/avocode#1306]
Its like a no big deal, but i've accidentally tried to upload psd files from opened zip file (total commander) which is basically a unzipped folder in windows temp folder and it threw an app error:

-----
App v. `2.12.6`
Avocode UID: 393
```
Invariant Violation: Cannot call hover while not dragging.
    at invariant (C:\Users\Ondrej\AppData\Local\avocode\app-2.12.6\resources\app.asar\node_modules\react-dnd\node_modules\invariant\invariant.js:42:15)
    at DragDropManager.hover (C:\Users\Ondrej\AppData\Local\avocode\app-2.12.6\resources\app.asar\node_modules\react-dnd\node_modules\dnd-core\lib\actions\dragDrop.js:107:27)
    at Object.hover (C:\Users\Ondrej\AppData\Local\avocode\app-2.12.6\resources\app.asar\node_modules\react-dnd\node_modules\dnd-core\lib\DragDropManager.js:92:38)
    at HTML5Backend.handleTopDrop (C:\Users\Ondrej\AppData\Local\avocode\app-2.12.6\resources\app.asar\node_modules\react-dnd-html5-backend\lib\HTML5Backend.js:579:20)
    at wrapped (C:\Users\Ondrej\AppData\Local\avocode\app-2.12.6\resources\app.asar\node_modules\raven-js\src\raven.js:283:29)
```

**Comment by connor-bean** [comment]
Hey thanks for the report @kure- 

We're tracking this in #1249 so I will close this out.
