### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yoalex5** [avocode/avocode#1348]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.1`
Avocode UID: 76617
```
TypeError: Promise.reject is not a constructor
    at e.exportToSvg (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:55:30052)
    at e.exportLayers (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:55:30357)
    at e._exportLayersToDirectory (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:52:9075)
    at e._exportRuleVariantToDirectory (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:52:7964)
    at wrapper (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/lodash/lodash.js:5232:19)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3018:46
    at List.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3017:23)
    at seqIterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:606:16)
    at IndexedIterable.IndexedSeq.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:322:14)
    at IndexedIterable.toArray (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4260:23)
    at new List (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2067:62)
    at reify (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3572:37)
    at List.map (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4403:14)
    at e._exportRuleGroupToDirectory (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:52:7688)
    at wrapper (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/lodash/lodash.js:5232:19)
    at Array.map (native)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:52:5416
```

**Comment by jakubzitny** [comment]
Hi @yoalex5, thanks for reporting this. We already know about it and we're tracking the progress in #1347. The bug will be fixed in next version of Avocode.
