### ISSUE TITLE
none close

### ISSUE THREAD

**Issue by Webdesme** [avocode/avocode#1352]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.1`
Avocode UID: 31535
```
TypeError: Cannot read property 'id' of undefined
    at p (https://js.intercomcdn.com/frame.562dbe68.js:1:24916)
    at c (https://js.intercomcdn.com/frame.562dbe68.js:5:17660)
    at https://js.intercomcdn.com/frame.562dbe68.js:5:17961
    at Array.map (native)
    at https://js.intercomcdn.com/frame.562dbe68.js:5:17938
    at https://js.intercomcdn.com/frame.562dbe68.js:2:22598
    at https://js.intercomcdn.com/frame.562dbe68.js:2:22034
    at p (https://js.intercomcdn.com/frame.562dbe68.js:2:22803)
    at https://js.intercomcdn.com/frame.562dbe68.js:2:22762
    at Array.map (native)
    at p (https://js.intercomcdn.com/frame.562dbe68.js:2:22737)
    at Array.<anonymous> (https://js.intercomcdn.com/frame.562dbe68.js:18:3808)
    at l (https://js.intercomcdn.com/frame.562dbe68.js:9:14700)
    at https://js.intercomcdn.com/frame.562dbe68.js:18:1776
    at https://js.intercomcdn.com/frame.562dbe68.js:17:26270
    at https://js.intercomcdn.com/frame.562dbe68.js:18:1100
    at https://js.intercomcdn.com/frame.562dbe68.js:17:24742
    at https://js.intercomcdn.com/frame.562dbe68.js:18:743
    at https://js.intercomcdn.com/frame.562dbe68.js:29:14875
    at onUserPresent (https://js.intercomcdn.com/frame.562dbe68.js:5:15382)
    at HTMLDocument.l (https://js.intercomcdn.com/frame.562dbe68.js:18:4761)
    at HTMLDocument.wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:283:29)
```

**Comment by jakubzitny** [comment]
Hi @Webdesme, thanks for the report. Can you please provide us with more details on this error? How did it happen? Did it happen more than once?

We actually know about this issue and we're already tracking it in #1338, we just need more details. I am going to close this thread and let's continue in #1338.
