### ISSUE TITLE
An unexpected error has occurred

### ISSUE THREAD

**Issue by vikynandha** [avocode/avocode#1361]
IMPORTANT: Please try to describe how did it happen.

I had just kept it open for a few hours and was doing something else. Avocode in the dock (Mac) immediately started bouncing. And there was this popup saying "An unexpected error has occurred". The worst part is the popup keeps coming up again no matter whether I click on "Dismiss" or "Send Report". As if it's stuck in some infinite loop.

-----
App v. `2.13.1`
Avocode UID: 97759
```
TypeError: Cannot read property 'id' of undefined
    at p (https://js.intercomcdn.com/frame.6bbb8132.js:1:24680)
    at c (https://js.intercomcdn.com/frame.6bbb8132.js:5:17676)
    at https://js.intercomcdn.com/frame.6bbb8132.js:5:17977
    at Array.map (native)
    at https://js.intercomcdn.com/frame.6bbb8132.js:5:17954
    at https://js.intercomcdn.com/frame.6bbb8132.js:2:22577
    at https://js.intercomcdn.com/frame.6bbb8132.js:2:22013
    at p (https://js.intercomcdn.com/frame.6bbb8132.js:2:22782)
    at https://js.intercomcdn.com/frame.6bbb8132.js:2:22741
    at Array.map (native)
    at p (https://js.intercomcdn.com/frame.6bbb8132.js:2:22716)
    at Array.<anonymous> (https://js.intercomcdn.com/frame.6bbb8132.js:17:31025)
    at l (https://js.intercomcdn.com/frame.6bbb8132.js:9:14939)
    at https://js.intercomcdn.com/frame.6bbb8132.js:17:29055
    at https://js.intercomcdn.com/frame.6bbb8132.js:17:21202
    at https://js.intercomcdn.com/frame.6bbb8132.js:17:28379
    at https://js.intercomcdn.com/frame.6bbb8132.js:17:19674
    at https://js.intercomcdn.com/frame.6bbb8132.js:17:28022
    at https://js.intercomcdn.com/frame.6bbb8132.js:29:12478
    at onUserPresent (https://js.intercomcdn.com/frame.6bbb8132.js:5:15963)
    at HTMLDocument.l (https://js.intercomcdn.com/frame.6bbb8132.js:17:31968)
    at HTMLDocument.wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:283:29)
```

**Comment by connor-bean** [comment]
Hey @vikynandha 

Thanks for the detailed report. We're tracking this in #1331 so I will close this and follow it there.
