### ISSUE TITLE
error on drag & drop psd in project folder

### ISSUE THREAD

**Issue by z4kk** [avocode/avocode#1362]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.12.6`
Avocode UID: 56383
```
Invariant Violation: Cannot call hover while not dragging.
    at invariant (C:\Users\Евгений\AppData\Local\avocode\app-2.12.6\resources\app.asar\node_modules\react-dnd\node_modules\invariant\invariant.js:42:15)
    at DragDropManager.hover (C:\Users\Евгений\AppData\Local\avocode\app-2.12.6\resources\app.asar\node_modules\react-dnd\node_modules\dnd-core\lib\actions\dragDrop.js:107:27)
    at Object.hover (C:\Users\Евгений\AppData\Local\avocode\app-2.12.6\resources\app.asar\node_modules\react-dnd\node_modules\dnd-core\lib\DragDropManager.js:92:38)
    at HTML5Backend.handleTopDrop (C:\Users\Евгений\AppData\Local\avocode\app-2.12.6\resources\app.asar\node_modules\react-dnd-html5-backend\lib\HTML5Backend.js:579:20)
    at wrapped (C:\Users\Евгений\AppData\Local\avocode\app-2.12.6\resources\app.asar\node_modules\raven-js\src\raven.js:283:29)
```

**Comment by connor-bean** [comment]
Hey @z4kk -

Thanks for the report. We are tracking this in #1249 so I will close this as it is a duplicate.
