### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by digital-madam** [avocode/avocode#1379]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.4`
Avocode UID: 73232
```
TypeError: Cannot read property 'id' of undefined
    at p (https://js.intercomcdn.com/frame.56a513af.js:1:29279)
    at c (https://js.intercomcdn.com/frame.56a513af.js:5:18558)
    at https://js.intercomcdn.com/frame.56a513af.js:5:18859
    at Array.map (native)
    at https://js.intercomcdn.com/frame.56a513af.js:5:18836
    at https://js.intercomcdn.com/frame.56a513af.js:2:22777
    at https://js.intercomcdn.com/frame.56a513af.js:2:22213
    at p (https://js.intercomcdn.com/frame.56a513af.js:2:22982)
    at https://js.intercomcdn.com/frame.56a513af.js:2:22941
    at Array.map (native)
    at p (https://js.intercomcdn.com/frame.56a513af.js:2:22916)
    at Array.<anonymous> (https://js.intercomcdn.com/frame.56a513af.js:18:3222)
    at l (https://js.intercomcdn.com/frame.56a513af.js:9:18698)
    at https://js.intercomcdn.com/frame.56a513af.js:18:1200
    at https://js.intercomcdn.com/frame.56a513af.js:17:25244
    at https://js.intercomcdn.com/frame.56a513af.js:18:522
    at https://js.intercomcdn.com/frame.56a513af.js:17:23716
    at https://js.intercomcdn.com/frame.56a513af.js:18:138
    at https://js.intercomcdn.com/frame.56a513af.js:29:14875
    at onUserPresent (https://js.intercomcdn.com/frame.56a513af.js:5:16845)
    at HTMLDocument.l (https://js.intercomcdn.com/frame.56a513af.js:18:4251)
    at HTMLDocument.wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:283:29)
```

**Comment by connor-bean** [comment]
Hello - we are tracking this in #1338 so I will close this duplicate
