### ISSUE TITLE
Export problem

### ISSUE THREAD

**Issue by raquelmsouza** [avocode/avocode#1382]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.5`
Avocode UID: 126175
```
Invariant Violation: Minified React error #44; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=44 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at reactProdInvariant (/opt/Avocode/resources/app.asar/node_modules/react-dom/lib/reactProdInvariant.js:31:15)
    at Object.findDOMNode (/opt/Avocode/resources/app.asar/node_modules/react-dom/lib/findDOMNode.js:53:126)
    at Object._handleMouseMove (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:68:18849)
    at wrapped (/opt/Avocode/resources/app.asar/node_modules/raven-js/src/raven.js:283:29)
```

**Comment by jakubzitny** [comment]
This is actually the same problem as in #1383, so I am going to close this thread.
