### ISSUE TITLE
I've clicked in a slice and just happened

### ISSUE THREAD

**Issue by raquelmsouza** [avocode/avocode#1383]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.5`
Avocode UID: 126175
```
Invariant Violation: Minified React error #44; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=44 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at reactProdInvariant (/opt/Avocode/resources/app.asar/node_modules/react-dom/lib/reactProdInvariant.js:31:15)
    at Object.findDOMNode (/opt/Avocode/resources/app.asar/node_modules/react-dom/lib/findDOMNode.js:53:126)
    at Object._handleMouseMove (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:68:18849)
    at wrapped (/opt/Avocode/resources/app.asar/node_modules/raven-js/src/raven.js:283:29)
```

**Comment by jakubzitny** [comment]
Hi @raquelmsouza, thanks for the report. We can see this problem in our error tracking system and we will try to fix it as soon as possible. Does this happen all the time and you cannot export slices at all or did it happen only few times and you managed to export some slices?

**Comment by jakubzitny** [comment]
This should be fixed in latest version of Avocode. Don't hesitate to open a new issue if you have any more problems 😉
