### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sayx** [avocode/avocode#1396]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.5`
Avocode UID: 119999
```
Error: connect ETIMEDOUT 149.56.18.166:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
```

**Comment by vojtatranta** [comment]
This should be silenced in 2.14.0 please update
