### ISSUE TITLE
Opened a psd file

### ISSUE THREAD

**Issue by hunter-symphony** [avocode/avocode#1398]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.0
Source UID: 50466
```
Error: Cannot open a document with no revision or no current revision
    at t.openDesign (file:///Users/hunterplude/Downloads/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:2:7276)
    at t.openDesignById (file:///Users/hunterplude/Downloads/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:2:6964)
    at Constructor._handleEntityOpen (file:///Users/hunterplude/Downloads/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:35:18177)
    at Constructor._handleEntityDoubleClick (file:///Users/hunterplude/Downloads/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:35:27179)
    at Object.invokeGuardedCallback (/Users/hunterplude/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactErrorUtils.js:27:12)
    at executeDispatch (/Users/hunterplude/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:79:21)
    at Object.executeDispatchesInOrder (/Users/hunterplude/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:102:5)
    at executeDispatchesAndRelease (/Users/hunterplude/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:43:22)
    at executeDispatchesAndReleaseTopLevel (/Users/hunterplude/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:54:10)
    at Array.forEach (native)
    at forEachAccumulated (/Users/hunterplude/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/forEachAccumulated.js:23:9)
    at Object.processEventQueue (/Users/hunterplude/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:259:7)
    at runEventQueueInBatch (/Users/hunterplude/Downloads/Avocode.app/Contents/Reso
```

**Comment by jakubzitny** [comment]
Hi there @hunter-symphony. You're using an old version of Avocode. Please download the latest `2.13.5` from [manager.avocode.com/downloads](https://manager.avocode.com/downloads/) and let us know if you have any other problems.
