### ISSUE TITLE
Empty Avocode after launch on Windows 7.

### ISSUE THREAD

**Issue by martinhalik** [avocode/avocode#140]
after opening Avocode

```
"[5784:0216/152441:ERROR:gpu_info_collector_win.cc(147)] Could not read gaming sc
ore from assessment results.
App load time: 950ms
[4992:0216/152442:INFO:renderer_main.cc(227)] Renderer process started
[5784:0216/152446:INFO:CONSOLE(29)] "SyntaxError: Unexpected token ", source: fi
le:///C:/Users/Doma/Desktop/Avocode/resources/app/static/index.js (29)
[2736:0216/152447:INFO:renderer_main.cc(227)] Renderer process started"
```

**Comment by martinhalik** [comment]
and then in console:
**SyntaxError: Unexpected token**
at Object.parse (native)
  at parseObject (c:\Users\Doma\Desktop\martin\Avocode\resources\app\node_modules\season\lib\cson.js:149:19)
  at parseContentsSync (c:\Users\Doma\Desktop\martin\Avocode\resources\app\node_modules\season\lib\cson.js:155:14)
  at Object.module.exports.readFileSync (c:\Users\Doma\Desktop\martin\Avocode\resources\app\node_modules\season\lib\cson.js:220:14)
  at KeymapManager.module.exports.KeymapManager.readKeymap (c:\Users\Doma\Desktop\martin\Avocode\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:324:21)
  at KeymapManager.module.exports.KeymapManager.loadKeymap (c:\Users\Doma\Desktop\martin\Avocode\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:271:43)
  at KeymapManager.module.exports.KeymapManager.loadKeymap (c:\Users\Doma\Desktop\martin\Avocode\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:265:18)
  at KeymapManager.loadBundledKeymaps (c:\Users\Doma\Desktop\martin\Avocode\resources\app\src\keymap-extensions.js:15:10)
  at Atom.module.exports.Atom.startEditorWindow (c:\Users\Doma\Desktop\martin\Avocode\resources\app\src\atom.js:349:20)
  at Object.<anonymous> (c:\Users\Doma\Desktop\martin\Avocode\resources\app\src\window-bootstrap.js:14:8)
  at Object.<anonymous> (c:\Users\Doma\Desktop\martin\Avocode\resources\app\src\window-bootstrap.js:20:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (C:\Users\Doma\Desktop\martin\Avocode\resources\app\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///C:/Users/Doma/Desktop/martin/Avocode/resources/app/static/index.js:20:25)
  at http://cdn.mxpnl.com/libs/mixpanel-2.2.min.js:21:261

**Comment by martinhalik** [comment]
mac somehow Unziped the file and then it was launched damaged on windows.
