### ISSUE TITLE
Received an "An unexpected error has occurred" while was aways from the app

### ISSUE THREAD

**Issue by lowal** [avocode/avocode#1405]
IMPORTANT: Please try to describe how did it happen.
I was away from the and I logged into web browser using Safari. I then logged into the new faster "Beta" in safari which gave me message the app was optimized for Chrome so login into Chrome. Then I noticed the Desktop app had an error message. 
-----
App v. `2.13.6`
Avocode UID: 2239
```
TypeError: Cannot read property 'id' of undefined
    at p (https://js.intercomcdn.com/frame.5e1234d8.js:1:29439)
    at c (https://js.intercomcdn.com/frame.5e1234d8.js:5:18793)
    at https://js.intercomcdn.com/frame.5e1234d8.js:5:19094
    at Array.map (native)
    at https://js.intercomcdn.com/frame.5e1234d8.js:5:19071
    at https://js.intercomcdn.com/frame.5e1234d8.js:2:23039
    at https://js.intercomcdn.com/frame.5e1234d8.js:2:22475
    at p (https://js.intercomcdn.com/frame.5e1234d8.js:2:23244)
    at https://js.intercomcdn.com/frame.5e1234d8.js:2:23203
    at Array.map (native)
    at p (https://js.intercomcdn.com/frame.5e1234d8.js:2:23178)
    at Array.<anonymous> (https://js.intercomcdn.com/frame.5e1234d8.js:18:6228)
    at l (https://js.intercomcdn.com/frame.5e1234d8.js:9:19252)
    at https://js.intercomcdn.com/frame.5e1234d8.js:18:4206
    at https://js.intercomcdn.com/frame.5e1234d8.js:17:27923
    at https://js.intercomcdn.com/frame.5e1234d8.js:18:3528
    at https://js.intercomcdn.com/frame.5e1234d8.js:17:26395
    at https://js.intercomcdn.com/frame.5e1234d8.js:18:3144
    at https://js.intercomcdn.com/frame.5e1234d8.js:29:14875
    at onUserPresent (https://js.intercomcdn.com/frame.5e1234d8.js:5:17080)
    at HTMLDocument.l (https://js.intercomcdn.com/frame.5e1234d8.js:18:7257)
    at HTMLDocument.wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:283:29)
```

**Comment by connor-bean** [comment]
Thanks for the report. We are aware of this bug.
