### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by hbeygel** [avocode/avocode#1406]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.6`
Avocode UID: 37719
```
Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/request/request.js:778:19)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:185:7)
    at TLSSocket.emitTimeout (_http_client.js:626:10)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket.Socket._onTimeout (net.js:342:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by connor-bean** [comment]
Hello - can you tell us more about what you were doing when this happened?

Has it happened again since you first reported it?
