### ISSUE TITLE
inactive window for certain period of time

### ISSUE THREAD

**Issue by kure-** [avocode/avocode#1411]
IMPORTANT: Please try to describe how did it happen.
Dunno, just had the Windows app on the background left untouched for a while (2 hours?)
-----
App v. `2.13.6`
Avocode UID: 393
```
Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (C:\Users\Ondrej\AppData\Local\avocode\app-2.13.6\resources\app.asar\node_modules\request\request.js:778:19)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:185:7)
    at TLSSocket.emitTimeout (_http_client.js:626:10)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket.Socket._onTimeout (net.js:342:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by n0rule5** [comment]
LOL this just happened to me, too.

**Comment by vojtatranta** [comment]
We had an unexpected outage which may have coused this :(

**Comment by connor-bean** [comment]
@n0rule5 and @kure - Did this error happen again?

**Comment by kure-** [comment]
@connor-bean sorry can't confirm, haven't touched Avocode since then. I'll make sure i'll report back again when it happens

**Comment by n0rule5** [comment]
@connor-bean Same here, I'll leave it open and see if it'll happen again.
