### ISSUE TITLE
Happened when try to close :)

### ISSUE THREAD

**Issue by ShichiroA** [avocode/avocode#1415]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.6`
Avocode UID: 53754
```
Error: Object has been destroyed
Error: Object has been destroyed
    at EventEmitter.<anonymous> (/Applications/Avocode.app/Contents/Resources/electron.asar/browser/rpc-server.js:395:55)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at WebContents.<anonymous> (/Applications/Avocode.app/Contents/Resources/electron.asar/browser/api/web-contents.js:249:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/Applications/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:218:13)
    at Object.descriptor.get [as webContents] (/Applications/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:132:16)
    at t.start (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:48:7395)
    at e.init (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:48:12848)
    at e._restart (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:48:13660)
    at e._handleTaskProcessExit (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:48:16952)
    at EventEmitter.<anonymous> (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:48:9998)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at EventEmitter.emit (events.js:185:7)
    at t.terminate (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:48:8432)
    at e._terminateTaskProcess (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:48:13848)
    at e.dispose (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:48:12967)
    at t.destroy (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:45:13288)
    at e.deactivate (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:44:26100)
    at n (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:40:9292)
    at wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:283:29)
```

**Comment by connor-bean** [comment]
Hey @ShichiroA -

Unfortunately this looks like an electron error to us, which we don't have the ability to troubleshoot?

Does it continue to happen or no?
