### ISSUE TITLE
Cannot call hover while not dragging

### ISSUE THREAD

**Issue by AlexandruDoda** [avocode/avocode#1421]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.6`
Avocode UID: 651
```
Invariant Violation: Cannot call hover while not dragging.
    at Object.invariant [as default] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/invariant/invariant.js:42:15)
    at DragDropManager.hover (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/dnd-core/lib/actions/dragDrop.js:116:25)
    at Object.hover (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/dnd-core/lib/DragDropManager.js:74:36)
    at HTML5Backend.handleTopDrop (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dnd-html5-backend/lib/HTML5Backend.js:540:18)
    at wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:283:29)
```

**Comment by connor-bean** [comment]
Hey @AlexandruDoda -

Thanks for the report. We are tracking this in #1249 so I will close this as it is a duplicate.
