### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by nitrodrill** [avocode/avocode#1422]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.6`
Avocode UID: 142895
```
TypeError: Cannot read property 'get' of null
    at Object.render (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:66:28816)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:799:30)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:822:32)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:746:36)
    at ReactCompositeComponentWrapper._performComponentUpdate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:724:10)
    at ReactCompositeComponentWrapper.updateComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:645:12)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:561:12)
    at Object.performUpdateIfNecessary (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:157:22)
    at runBatchedUpdates (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:150:21)
    at ReactReconcileTransaction.perform (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:140:20)
    at ReactUpdatesFlushTransaction.perform (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:140:20)
    at ReactUpdatesFlushTransaction.perform (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:89:32)
    at Object.flushBatchedUpdates (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:172:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:206:25)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:153:16)
    at Object.batchedUpdates (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.enqueueUpdate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:200:22)
    at enqueueUpdate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdateQueue.js:24:16)
    at Object.enqueueSetState (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdateQueue.js:209:5)
    at Object.ReactComponent.setState (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactComponent.js:63:16)
    at Object._handleProjectManagerStoreChange (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:66:24410)
    at emitNone (events.js:91:20)
    at t.emit (events.js:185:7)
    at t.emitChange (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/flux/lib/store.js:47:12)
    at t.n._handleUserDataStoreChange (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:39:13274)
    at emitNone (events.js:91:20)
    at t.emit (events.js:185:7)
    at t.emitChange (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/flux/lib/store.js:47:12)
    at t._handleAction (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:51:12184)
    at Object.ID_9 (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:51:10585)
    at Dispatcher._invokeCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:198:24)
    at Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:174:14)
    at Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/flux/lib/dispatcher.js:76:28)
    at t.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/flux/lib/action-creator.js:37:24)
    at t.addOrganization (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:43:13818)
    at e.<anonymous> (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:32:10006)
    at tryCatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:116:21)
    at r (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:32:2716)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:32:2816
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by vojtatranta** [comment]
This should have been fixed in `2.14.0`, please update
