### ISSUE TITLE
Err while getting back from sleep mode on Windows

### ISSUE THREAD

**Issue by kure-** [avocode/avocode#1432]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.6`
Avocode UID: 393
```
Error: getaddrinfo ENOTFOUND manager.avocode.com manager.avocode.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

**Comment by connor-bean** [comment]
Hey @kure- 

We are tracking this in #1351 so I will close it here.
