### ISSUE TITLE
ENOTFOUND

### ISSUE THREAD

**Issue by TatianaTF** [avocode/avocode#1472]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.2`
Avocode UID: 150867
```
Error: getaddrinfo ENOTFOUND manager.avocode.com manager.avocode.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

**Comment by jakubzitny** [comment]
Hi @TatianaTF, do you still have similar problems in latest version of Avocode, please?

**Comment by connor-bean** [comment]
Hi @TatianaTF, do you still have similar problems in latest version of Avocode 2.14.6?

**Comment by connor-bean** [comment]
Closing due to inactivity. If you can comment, we will re-open the issue
