### ISSUE TITLE
can not connect

### ISSUE THREAD

**Issue by worldzhy** [avocode/avocode#1486]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.2`
Avocode UID: 37102
```
Error: getaddrinfo ENOTFOUND manager.avocode.com manager.avocode.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

**Comment by petrbrzek** [comment]
@worldzhy Please update to the latest version of Avocode.
