### ISSUE TITLE
Api#updateUploadSlot 400/404

### ISSUE THREAD

**Issue by n0rule5** [avocode/avocode#1495]
IMPORTANT: Please try to describe how did it happen.

Trying to sync using the new plugin for the first time. It never finishes and kinda froze. Tried to add designs to the project again and error occurred. So confused.

-----
App v. `2.14.4`
Avocode UID: 35475
```
Error: Api#updateUploadSlot()() -> error (status: 400)
    at Object.normalizeError (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:16855)
    at Object.normalizeResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:16734)
    at t.normalizeResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1988538)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1985556
    at Request._callback (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1987379)
    at Request.self.callback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/request/request.js:186:22)
    at emitTwo (events.js:111:20)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/request/request.js:1001:12)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by jakubzitny** [comment]
Hi, thanks for reporting this issue. We already know about it and we'll be fixing it for `2.14.5`.

**Comment by jakubzitny** [comment]
#1518 is related as well.

**Comment by jakubzitny** [comment]
Hi @n0rule5, we've just released new version of Avocode, please update and let us know if you still have problems with this 😉
