### ISSUE TITLE
Error on drag & drop files to project

### ISSUE THREAD

**Issue by DmitryLobachov** [avocode/avocode#1505]
I've just tried to drag&drop psd files to my new project.
-----
App v. `2.14.4`
Avocode UID: 159374
```
Invariant Violation: Cannot call hover while not dragging.
    at Object.invariant [as default] (/opt/Avocode/resources/app.asar/node_modules/invariant/invariant.js:42:15)
    at DragDropManager.hover (/opt/Avocode/resources/app.asar/node_modules/dnd-core/lib/actions/dragDrop.js:116:25)
    at Object.hover (/opt/Avocode/resources/app.asar/node_modules/dnd-core/lib/DragDropManager.js:74:36)
    at HTML5Backend.handleTopDrop (/opt/Avocode/resources/app.asar/node_modules/react-dnd-html5-backend/lib/HTML5Backend.js:540:18)
    at wrapped (/opt/Avocode/resources/app.asar/node_modules/raven-js/src/raven.js:314:29)
```

**Comment by vojtatranta** [comment]
This is a known issue, this is due to bug in the window frame when you drag a file overt top edge of app it causes this error.
