### ISSUE TITLE
Troubleshooting->Clear Previews

### ISSUE THREAD

**Issue by drblmb** [avocode/avocode#1507]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.5`
Avocode UID: 120318
```
TypeError: Cannot read property 'delete' of null
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:496682
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:212076
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3018:46
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:1379:16
    at ValueNode.iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:1746:12)
    at BitmapIndexedNode.iterate.HashArrayMapNode.iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:1739:24)
    at HashArrayMapNode.BitmapIndexedNode.iterate.HashArrayMapNode.iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:1739:24)
    at Map.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:1377:32)
    at KeyedIterable.mappedSequence.__iterateUncached (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3017:23)
    at seqIterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:606:16)
    at KeyedIterable.Seq.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:276:14)
    at KeyedIterable.forEach (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4383:19)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:1224:16
    at Map.withMutations (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:1355:7)
    at new Map (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:1221:20)
    at reify (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3572:37)
    at Map.map (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4403:14)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:212028
    at e.update (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:110344)
    at e.updateAll (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:211951)
    at Object.n._handleAction [as ID_24] (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:496652)
    at Dispatcher._invokeCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:198:24)
    at Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:174:14)
    at Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/flux/lib/dispatcher.js:76:28)
    at t.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/flux/lib/action-creator.js:37:24)
    at t.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:287589)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1980377
    at e._runDataTransaction (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1981608)
    at e.clearThumbnails (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1980293)
    at t._handleClearThumbnailsClick (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2136776)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2134499
    at CallbacksRegistry.apply (/Applications/Avocode.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:48:42)
    at EventEmitter.<anonymous> (/Applications/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:283:21)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

**Comment by jakubzitny** [comment]
Hi @drblmb, thanks for reporting this issue. This is a bug, we already know about it and we will try to fix it in upcoming weeks. We're already tracking it in #1466, so I am going to close this thread.
