### ISSUE TITLE
It happens all the time

### ISSUE THREAD

**Issue by buveur** [avocode/avocode#1509]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.5`
Avocode UID: 159528
```
TypeError: Cannot read property 'get' of undefined
    at t._updateBranchSyncStates (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:708940)
    at t._updateRevisionBranchSyncStates (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:708652)
    at t._addDownloadingRevisionById (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:707817)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:707631
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2701:43
    at List.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at OrderedMap.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2700:25)
    at OrderedMap.forEach (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4383:19)
    at t._addDownloadingRevisionStorage (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:707583)
    at t._handleRevisionDownloadStart (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:706387)
    at t._handleRevisionDownloadStart (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:702235)
    at t._handleAction (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:705199)
    at Object.ID_17 (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:702235)
    at Dispatcher._invokeCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:198:24)
    at Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:174:14)
    at Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/flux/lib/dispatcher.js:76:28)
    at t.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/flux/lib/action-creator.js:37:24)
    at t.startRevisionDownload (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:613797)
    at e._downloadRevision (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1972381)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1971865
    at e._processRevision (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2149354)
    at e._processRevision (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2147388)
    at e.addRevision (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2148079)
    at e._addRevisionToQueueWithPriority (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1971263)
    at e._downloadRevisionAsPrioritized (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1971590)
    at e.downloadRevisionById (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1968723)
    at e.downloadRevisionById (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2092606)
    at e._downloadRevisionById (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2215733)
    at e._ensureCompleteRevision (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2212877)
    at e._loadRevision (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2211743)
    at e.loadRevisionById (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2211297)
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1554526)
    at e.<anonymous> (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1572714)
    at r (https://fast.appcues.com/24524.js:1:246598)
    at Generator._invoke (https://fast.appcues.com/24524.js:1:248025)
    at Generator.t.(anonymous function) [as next] (https://fast.appcues.com/24524.js:1:246777)
    at r (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1570252)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1570346
```

**Comment by jakubzitny** [comment]
Hi @buveur, thanks for reporting this problem. It's a bug, we'll try to fix it for the next release.

**Comment by jakubzitny** [comment]
Hi @buveur, we've just released new version of Avocode, please update and let us know if you still have problems with it 😉
