### ISSUE TITLE
asdcfbkasvdfkjclqewc

### ISSUE THREAD

**Issue by Andrew-Dyachenko** [avocode/avocode#1515]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.4`
Avocode UID: 116502
```
Error: Files over size limit are not supported. (500 MB)
    at Object.normalizeError (file:///home/andrew/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:1:16855)
    at Object.normalizeResponse (file:///home/andrew/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:1:16734)
    at t.normalizeResponse (file:///home/andrew/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:1:1988538)
    at file:///home/andrew/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:1:1984599
    at Request._callback (file:///home/andrew/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:1:1987379)
    at Request.self.callback (/home/andrew/Avocode-linux-x64/resources/app.asar/node_modules/request/request.js:186:22)
    at emitTwo (events.js:111:20)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/andrew/Avocode-linux-x64/resources/app.asar/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/andrew/Avocode-linux-x64/resources/app.asar/node_modules/request/request.js:1001:12)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by jakubzitny** [comment]
Hi @Andrew-Dyachenko, thanks for the report. We do not support uploading PSD files over 500MB via drag and drop. Please use our PS plugin or send the file to our support team and they will upload it for you.
