### ISSUE TITLE
Can't upload design. Ubuntu Linux 16.04

### ISSUE THREAD

**Issue by darginyegor** [avocode/avocode#1518]
Got this error immedeatly after selecting a psd file.

-----
App v. `2.14.5`
Avocode UID: 160764
```
Error: Api#createUploadSlot()() -> error (status: 403, error: )
    at Object.normalizeError (file:///home/darginyegor/%D0%9F%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B/avocode-2.14.5-linux/resources/app.asar/dist/avocode.min.js:1:16896)
    at Object.normalizeResponse (file:///home/darginyegor/%D0%9F%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B/avocode-2.14.5-linux/resources/app.asar/dist/avocode.min.js:1:16734)
    at t.normalizeResponse (file:///home/darginyegor/%D0%9F%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B/avocode-2.14.5-linux/resources/app.asar/dist/avocode.min.js:1:1993723)
    at file:///home/darginyegor/%D0%9F%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B/avocode-2.14.5-linux/resources/app.asar/dist/avocode.min.js:1:1989784
    at Request._callback (file:///home/darginyegor/%D0%9F%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B/avocode-2.14.5-linux/resources/app.asar/dist/avocode.min.js:1:1992564)
    at Request.self.callback (/home/darginyegor/Программы/avocode-2.14.5-linux/resources/app.asar/node_modules/request/request.js:186:22)
    at emitTwo (events.js:111:20)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/darginyegor/Программы/avocode-2.14.5-linux/resources/app.asar/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/darginyegor/Программы/avocode-2.14.5-linux/resources/app.asar/node_modules/request/request.js:1001:12)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by jakubzitny** [comment]
Hi @darginyegor, thanks for the report. Do you have any further details on this? Is it happening to all uploads? Did you try uploading via drag&drop? Are you able to upload via web interface or are you behind some sort of proxy?

**Comment by jakubzitny** [comment]
Also, can you try logging out and loggin in? Is it still happening for all uploads afte re-logging?

**Comment by darginyegor** [comment]
@jakubzitny first time i got some popup errors and all i could see is something about "access denied"
it happens to all uploads
gonna try re-logging and upload using web-interface in a moment

**Comment by darginyegor** [comment]
well after relogging i see one of the designs i tried to upload, but cant open it. also now i can upload new files, but have same problem with all:
![2017-07-12 16-17-54](https://user-images.githubusercontent.com/22341230/28113349-0d945f90-671e-11e7-87a8-015fc736a1ed.png)

**Comment by jakubzitny** [comment]
Allright, this looks like a permission problem with the location where we are saving the data. it's in `~/.avocode`, can you try checking (and possibly repair) the permissions there? 

The full path is `/home/darginyegor/.avocode`, this should help:
```
ls -ld /home/darginyegor/.avocode
chmod -R 755 /home/darginyegor/.avocode
```

**Comment by darginyegor** [comment]
@jakubzitny 
```
darginyegor@a2c:~$ ls -ld /home/darginyegor/.avocode
drwxr-xr-x 3 root root 4096 июл 12 11:16 /home/darginyegor/.avocode
```

after running your chmod command with sudo (withuot sudo it told me he cant change permissions)

**Comment by darginyegor** [comment]
and i cant upload designs again

**Comment by jakubzitny** [comment]
Allright, you probably launched Avocode as a superuser, or assigned the `~/.avocode` folder to `root`. Please run:

```
sudo chown -R darginyegor:darginyegor ~/.avocode`
```

and try again.

**Comment by darginyegor** [comment]
@jakubzitny 
figured it out the moment before your last comment hah!
thanks! :+1: 
looks like now everything's fine
best support ever
