### ISSUE TITLE
Please try to describe how did it happen.

### ISSUE THREAD

**Issue by gto999** [avocode/avocode#1532]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.6`
Avocode UID: 164450
```
Error: connect ETIMEDOUT 52.70.75.29:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
```

**Comment by connor-bean** [comment]
Hello @gto999 - thanks for the report. Can you try loading the design in web version at app.avocode.com to see if it works there, please?
