### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nittalee** [avocode/avocode#1540]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.6`
Avocode UID: 165650
```
Error: aborted
    at Uploader._uploadArtboardPath (/Volumes/Avocode/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/uploader/lib/uploader2.js:451:31)
    at /Volumes/Avocode/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3018:46
    at List.__iterate (/Volumes/Avocode/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/Volumes/Avocode/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3017:23)
    at seqIterate (/Volumes/Avocode/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:606:16)
    at IndexedIterable.IndexedSeq.__iterate (/Volumes/Avocode/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:322:14)
    at IndexedIterable.forEach (/Volumes/Avocode/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4383:19)
    at /Volumes/Avocode/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2071:14
    at List.Map.withMutations (/Volumes/Avocode/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:1355:7)
    at new List (/Volumes/Avocode/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2069:20)
    at reify (/Volumes/Avocode/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3572:37)
    at List.map (/Volumes/Avocode/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4403:14)
    at /Volumes/Avocode/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/uploader/lib/uploader2.js:417:36
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by jakubzitny** [comment]
Hi @nittalee, thanks for reporting this. We're already tracking the same problem in #1538, so let's close this and move the conversation there.
