### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pablorcgjn** [avocode/avocode#1541]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.6`
Avocode UID: 36883
```
Error: aborted
    at Uploader._uploadArtboardPath (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/uploader/lib/uploader2.js:451:31)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3018:46
    at List.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3017:23)
    at seqIterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:606:16)
    at IndexedIterable.IndexedSeq.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:322:14)
    at IndexedIterable.forEach (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4383:19)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2071:14
    at List.Map.withMutations (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:1355:7)
    at new List (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2069:20)
    at reify (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3572:37)
    at List.map (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4403:14)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/uploader/lib/uploader2.js:417:36
```

**Comment by jakubzitny** [comment]
Hi @pablorcgjn, thanks for reporting this. We're already tracking the same problem in #1538, so let's close this and move the conversation there.
