### ISSUE TITLE
Bug after terminating Avocode while uploading

### ISSUE THREAD

**Issue by zorandraganov** [avocode/avocode#1546]
IMPORTANT: Please try to describe how did it happen.

I was uploading a design into Avocode. It was at about 75% and I had to terminate the App. From that moment, I am not able to upload more designs.

I'm getting the same error every time.

-----
App v. `2.14.7`
Avocode UID: 63502
```
TypeError: o.replace is not a function
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:599078)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:597707
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3018:46
    at List.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3017:23)
    at seqIterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:606:16)
    at IndexedIterable.IndexedSeq.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:322:14)
    at IndexedIterable.toArray (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4260:23)
    at new List (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2067:62)
    at reify (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3572:37)
    at List.map (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4403:14)
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:597682)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:595019
```

**Comment by jakubzitny** [comment]
Hi @zorandraganov, I think this is the same problem as #1545. We've likely detected incorrect location of your Sketch plugins and the sketch plugin update did not succeed. Please try to update the plugin itself and let me know if it helps. You can download the plugin from [here](https://manager.avocode.com/download/sketch-plugin-new/mac/) and just double click to install it.

We'll improve the installation in next version, so this does not happen again.

**Comment by zorandraganov** [comment]
It worked  👍
