### ISSUE TITLE
error submit sketch to avocode

### ISSUE THREAD

**Issue by idsampaio** [avocode/avocode#1555]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.7`
Avocode UID: 25193
```
TypeError: o.replace is not a function
    at e.value (file:///Users/.../Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:599078)
    at file:///Users/.../Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:597707
    at /Users/.../Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3018:46
    at List.__iterate (/Users/.../Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/Users/.../Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3017:23)
    at seqIterate (/Users/.../Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:606:16)
    at IndexedIterable.IndexedSeq.__iterate (/Users/.../Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:322:14)
    at IndexedIterable.toArray (/Users/.../Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4260:23)
    at new List (/Users/.../Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2067:62)
    at reify (/Users/.../Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3572:37)
    at List.map (/Users/.../Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4403:14)
    at e.value (file:///Users/.../Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:597682)
    at file:///Users/.../Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:595019
```

**Comment by jakubzitny** [comment]
Hi @idsampaio, thanks for reporting this. This is a known issue, similar to #1546 and #1545. We had some problems with updating the latest Avocode plugin in Sketch, which is causing this error.

Can you update the plugin from [here](https://upx.cz/iYd), double click to install it in Sketch and see if it helps, please?

**Comment by idsampaio** [comment]
Thanks, I after commenting here I uninstalled everything including the sketch plugin and I returned to install and already gave.

**Comment by jakubzitny** [comment]
So everything works for you, right? We can close this issue then. Don't hesitate to let us know if you have any other problems with Avocode 😉
