### ISSUE TITLE
Uploading 7 artboards and 59 symbols

### ISSUE THREAD

**Issue by andersLandau** [avocode/avocode#1562]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.7`
Avocode UID: 141424
```
TypeError: Cannot read property 'id' of null
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:325098)
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:322110)
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:336321)
    at emitOne (events.js:96:13)
    at Progress.emit (events.js:188:7)
    at Progress.processingFinish (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/uploader/lib/progress.js:185:12)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/uploader/lib/progress-checker.js:123:28
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1994060
    at Request._callback (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1995715)
    at Request.self.callback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/request/request.js:186:22)
    at emitTwo (events.js:111:20)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/request/request.js:1001:12)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by jakubzitny** [comment]
Hi @andersLandau, thanks for letting us know. Did the whole upload fail? Can you try it again, please? This is probably a bug that is already fixed for the next release, but should not happen during all uploads, so trying one more time might help. Otherewise we'll let you know when the new version is available.

**Comment by jakubzitny** [comment]
Hi again, so we've released new version of Avocode just now. Please update the app and everything should work correctly. Please let us know if you find any problems or have any questions 😉
