### ISSUE TITLE
Out of memory at ImageData creation

### ISSUE THREAD

**Issue by s4shulga** [avocode/avocode#1567]
IMPORTANT: Please try to describe how did it happen.

Hi, I got this error trying to review the sketch file already imported to Avocode in Inspect mode - http://joxi.ru/zANBj0DfBXQM9A

-----
App v. `2.14.8`
Avocode UID: 170315
```
RangeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation
    at e.exports.e.drawImage (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2315614)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2313539
    at List.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at List.forEach (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4383:19)
    at e.exports.e.createSprites (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2313110)
    at e.exports.e.loadDocument (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2312854)
    at t.loadDocument (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2353270)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2227320
    at Immediate.<anonymous> (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2241557)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

![x](https://user-images.githubusercontent.com/3315662/28876155-87c1d7d6-7798-11e7-92f5-5aafa29e6390.jpg)

**Comment by jakubzitny** [comment]
Hi @s4shulga, thanks for letting us know. We already had this problem, but it was always with old 32-bit Windows systems. The problem here is that reneding the image data takes too much memory.

This is the same problem as we already dealt with in #968, #927, #916, #915, and #915. This is probably the first time this happened on macOS. Would you be willing to share the details about your hardware/os? What Mac model do you have and how much memory does it have? Or is this by any chance a hackintosh or macOS running inside a VM?

**Comment by s4shulga** [comment]
Hi @jakubzitny , I use official software only, Sierra 10.12.6 (16G29) 
MacBook Pro (Retina, 15-inch, Mid 2015)
2,2 GHz Intel Core i7
16 Gb 1600 MHz DDR3
So the reason is not in my computer, cause the same issue we have on Windows - http://joxi.ru/4AkE93pTybxNBm

**Comment by jakubzitny** [comment]
Yeah I see, thank you. Then this is about the size (or contents) of the design. We'll look into this more thoroughly, in the meantime I suggest you break the design into smaller pieces and upload it like that.

**Comment by jakubzitny** [comment]
This problem now looks a bit different. Closing with respect to #2173.
