### ISSUE TITLE
ReferenceError: ga is not defined

### ISSUE THREAD

**Issue by BiDbMAK** [avocode/avocode#1568]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.8`
Avocode UID: 157823
```
ReferenceError: ga is not defined
    at Object.pageview (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1470214)
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:181419)
    at e._trackUriChange (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:635307)
    at e.redirectActiveItemToUri (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:631715)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1887267
```

**Comment by jakubzitny** [comment]
Hi @BiDbMAK, thanks for the report. This is a weird error, do you have any more details on how did you get it? You probably have problems starting the app at all, right? How did you download/install Avocode? Is it your first time or did the previous versions work for you?

**Comment by connor-bean** [comment]
Hi @BiDbMAK, thanks for the report. This is a weird error, do you have any more details on how did you get it? You probably have problems starting the app at all, right? How did you download/install Avocode? Is it your first time or did the previous versions work for you?

**Comment by connor-bean** [comment]
Please comment if you can provide more information and we will continue troubleshooting
