### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by alokjethanandani** [avocode/avocode#1591]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.8`
Avocode UID: 166644
```
Error: Command failed: "/Applications/Sketch.app/Contents/Resources/sketchtool/bin/sketchtool" dump --overwriting --use-id-for-name --formats="png" "/Users/alokjethanandani/Dropbox (Fundbox)/Projects (1)/096 Fundbox Pay/Q317 Initiatives/Finalized Designs/LAB-645 "To" Field Autocomplete.sketch" > "/var/folders/tn/695wxzsj6zz4vbs0fv2_zm2w0000gn/T/sketch-avocode-full-dump.1503610841423.json"
2017-08-24 14:40:41.494 sketchtool[57715:17856161] -[ECCommandLineEngine outputError:format:]: unrecognized selector sent to instance 0x7f8b20b02a60
Command threw exception

(ECCommandLineDomain:5)


    at ChildProcess.exithandler (child_process.js:223:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

**Comment by jakubzitny** [comment]
Closing with respect to #1592.
