### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by alokjethanandani** [avocode/avocode#1593]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.8`
Avocode UID: 166644
```
Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1117:19)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by jakubzitny** [comment]
Closing with respect to #1592.
