### ISSUE TITLE
Breaking

### ISSUE THREAD

**Issue by campusboy87** [avocode/avocode#1597]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.8`
Avocode UID: 180157
```
Error: connect ETIMEDOUT 52.70.75.29:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
```

**Comment by jakubzitny** [comment]
Closing with respect to #1677.
