### ISSUE TITLE
when I import files from sketch

### ISSUE THREAD

**Issue by Omaretz** [avocode/avocode#1600]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.8`
Avocode UID: 170010
```
Error: Api#updateUploadSlot()() -> error (status: 400, error: {"project":["Slot target already set"]})
    at Object.normalizeError (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:16897)
    at Object.normalizeResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:16733)
    at t.normalizeResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2003680)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2000698
    at Request._callback (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2002521)
    at Request.self.callback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/request/request.js:186:22)
    at emitTwo (events.js:111:20)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/request/request.js:1001:12)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by jakubzitny** [comment]
Closing with respect to #1601.
