### ISSUE TITLE
Drag and drop from a zip file cause an error

### ISSUE THREAD

**Issue by t1gu1** [avocode/avocode#1602]
OS: 
LINUX (Ubuntu)

HOW IT CAUSE: 
When i open a zip file (**Without unzip it**) and i drag and drop files from zip (**not unzip**) to Avocode.

FILES DRAG AND DROP:
few or one .PSD inside a .ZIP **TO** Avocode

-----
App v. `2.14.8`
Avocode UID: 136162
```
Invariant Violation: Cannot call hover while not dragging.
    at Object.invariant [as default] (/home/guillaume/App/avocode/resources/app.asar/node_modules/invariant/invariant.js:42:15)
    at DragDropManager.hover (/home/guillaume/App/avocode/resources/app.asar/node_modules/dnd-core/lib/actions/dragDrop.js:116:25)
    at Object.hover (/home/guillaume/App/avocode/resources/app.asar/node_modules/dnd-core/lib/DragDropManager.js:74:36)
    at HTML5Backend.handleTopDrop (/home/guillaume/App/avocode/resources/app.asar/node_modules/react-dnd-html5-backend/lib/HTML5Backend.js:540:18)
    at wrapped (/home/guillaume/App/avocode/resources/app.asar/node_modules/raven-js/src/raven.js:314:29)
```

**Comment by vojtatranta** [comment]
It happens only when you don't unzip the app?

**Comment by jakubzitny** [comment]
Hi @t1gu1, thanks for the report. We know about this, we will try to fix it in the future, but right now we have more important things to be fixing. Just unzip the file prior to the upload for now and it should work properly. 😉

**Comment by jakubzitny** [comment]
Closing with respect to #1249. (We have it in our backlog @t1gu1, but we still have other priorities right now :wink:)
