### ISSUE TITLE
Random error

### ISSUE THREAD

**Issue by Cactucs** [avocode/avocode#1604]
IMPORTANT: Please try to describe how did it happen.

I had opened a design in web app, but was working in other tab. But suddenly in the avocode app alert showed up and asked me if I want to report an error.

Using Chrome on Linux

-----
App v. `2.15.0-beta.2-w3471f4b`
Avocode UID: 2563
```
TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
    at e.value (https://cdn.app.avocode.com/dist/v-fb64094/js/avocode-web.min.js:79:511093)
    at n.abortAllRequests (https://cdn.app.avocode.com/dist/v-fb64094/js/avocode-web.min.js:79:671614)
    at _handleOfflineState (https://cdn.app.avocode.com/dist/v-fb64094/js/avocode-web.min.js:79:430837)
```

**Comment by Cactucs** [comment]
Happened once more:

-----
App v. `2.15.0-beta.2-w3471f4b`
Avocode UID: 2563
```
TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
    at e.value (https://cdn.app.avocode.com/dist/v-fb64094/js/avocode-web.min.js:79:511093)
    at n.abortAllRequests (https://cdn.app.avocode.com/dist/v-fb64094/js/avocode-web.min.js:79:671614)
    at _handleOfflineState (https://cdn.app.avocode.com/dist/v-fb64094/js/avocode-web.min.js:79:430837)
```

**Comment by vojtatranta** [comment]
That's an error, we try to fix it as soon as possible.

The code looks ok, there will be something behind it..

**Comment by Cactucs** [comment]
Please fix it. It just happend once more. (And yesterday I haven't reported one). It's quite annoying...

**Comment by jakubzitny** [comment]
Hi @Cactucs, did you see this error in latest versions of Avocode?

**Comment by Cactucs** [comment]
I don't think so.

**Comment by jakubzitny** [comment]
Cool, let's close this then. Please let us know if you have any other problems 😉
