### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xavier78** [avocode/avocode#1620]
* **Version**: 2.15.2

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 39965
---

```
TypeError: t._debounceMouseMoveHandler is not a function
    at t.<anonymous> (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2436619)
    at emitOne (events.js:101:20)
    at t.emit (events.js:191:7)
    at r._handleMouseMove (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3056970)
    at Object.invokeGuardedCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactErrorUtils.js:26:5)
    at executeDispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/EventPluginUtils.js:85:21)
    at Object.executeDispatchesInOrder (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/EventPluginUtils.js:108:5)
    at executeDispatchesAndRelease (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/EventPluginHub.js:43:22)
    at executeDispatchesAndReleaseTopLevel (/Applications/Avocode.app/Contents/
```

**Comment by jakubzitny** [comment]
Closing with respect to #1621.
