### ISSUE TITLE
A mock don't open

### ISSUE THREAD

**Issue by Andrei1982** [avocode/avocode#1627]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.2`
Avocode UID: 60978
```
TypeError: Invalid Version: [object Object]
    at new SemVer (C:\Users\AndreyN\AppData\Local\avocode\app-2.14.2\resources\app.asar\node_modules\semver\semver.js:279:11)
    at compare (C:\Users\AndreyN\AppData\Local\avocode\app-2.14.2\resources\app.asar\node_modules\semver\semver.js:566:10)
    at gte (C:\Users\AndreyN\AppData\Local\avocode\app-2.14.2\resources\app.asar\node_modules\semver\semver.js:615:10)
    at cmp (C:\Users\AndreyN\AppData\Local\avocode\app-2.14.2\resources\app.asar\node_modules\semver\semver.js:640:22)
    at Comparator.test (C:\Users\AndreyN\AppData\Local\avocode\app-2.14.2\resources\app.asar\node_modules\semver\semver.js:704:10)
    at testSet (C:\Users\AndreyN\AppData\Local\avocode\app-2.14.2\resources\app.asar\node_modules\semver\semver.js:1047:17)
    at Range.test (C:\Users\AndreyN\AppData\Local\avocode\app-2.14.2\resources\app.asar\node_modules\semver\semver.js:1039:9)
    at Function.satisfies (C:\Users\AndreyN\AppData\Local\avocode\app-2.14.2\resources\app.asar\node_modules\semver\semver.js:1085:16)
    at file:///C:/Users/AndreyN/AppData/Local/avocode/app-2.14.2/resources/app.asar/dist/avocode.min.js:62:27168
    at file:///C:/Users/AndreyN/AppData/Local/avocode/app-2.14.2/resources/app.asar/dist/avocode.min.js:56:31390
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:416:3)
```

**Comment by jakubzitny** [comment]
This is the same issue as #1626. Closing.
