### ISSUE TITLE
Occurred when I changed my account

### ISSUE THREAD

**Issue by Pavlo-Minkievych** [avocode/avocode#1628]
* **Version**: 2.15.3
* **Sketch plugin version**: 46.2.4

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: null
---

```
Error: The received response does not include an organization list
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1756487
    at Request._callback (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1729794)
    at Request.self.callback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/request/request.js:186:22)
    at emitTwo (events.js:111:20)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/request/request.js:1001:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickC
```

**Comment by jakubzitny** [comment]
Hi, this should be fixed in latest Avocode `2.16.2`. Please update and let us know if you find any other problems :wink:
