### ISSUE TITLE
error

### ISSUE THREAD

**Issue by aleksandr-guryanov** [avocode/avocode#1629]
* **Version**: 2.15.3
* **Sketch plugin version**: 46.2.4

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 12754
---

```
TypeError: t._debounceMouseMoveHandler is not a function
    at t.<anonymous> (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2436648)
    at emitOne (events.js:101:20)
    at t.emit (events.js:191:7)
    at r._handleMouseMove (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3057015)
    at Object.invokeGuardedCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactErrorUtils.js:26:5)
    at executeDispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/EventPluginUtils.js:85:21)
    at Object.executeDispatchesInOrder (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/EventPluginUtils.js:108:5)
    at executeDispatchesAndRelease (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/EventPluginHub.js:43:22)
    at executeDispatchesAndReleaseTopLevel (/Applications/Avocode.app/Contents/
```

**Comment by jakubzitny** [comment]
Hi @aleksandr-guryanov, thank you for reporting this. It's a bug and we're already fixing it for the next release. I am going to close this thread as we're already tracking it in #1621.
