### ISSUE TITLE
ss

### ISSUE THREAD

**Issue by wladan** [avocode/avocode#1630]
* **Version**: 2.15.2

* **Web/Desktop**: Desktop

* **Platform**: win32

* **Avocode UID**: 186830
---

```
TypeError: t._debounceMouseMoveHandler is not a function
    at t.<anonymous> (file:///C:/Users/wladan/AppData/Local/avocode/app-2.15.2/resources/app.asar/dist/avocode.min.js:1:2436619)
    at emitOne (events.js:101:20)
    at t.emit (events.js:191:7)
    at r._handleMouseMove (file:///C:/Users/wladan/AppData/Local/avocode/app-2.15.2/resources/app.asar/dist/avocode.min.js:1:3056970)
    at Object.invokeGuardedCallback (C:\Users\wladan\AppData\Local\avocode\app-2.15.2\resources\app.asar\node_modules\react-dom\lib\ReactErrorUtils.js:26:5)
    at executeDispatch (C:\Users\wladan\AppData\Local\avocode\app-2.15.2\resources\app.asar\node_modules\react-dom\lib\EventPluginUtils.js:85:21)
    at Object.executeDispatchesInOrder (C:\Users\wladan\AppData\Local\avocode\app-2.15.2\resources\app.asar\node_modules\react-dom\lib\EventPluginUtils.js:108:5)
    at executeDispatchesAndRelease (C:\Users\wladan\AppData\Local\avocode\app-2.15.2\resources\app.asar\node_modules\react-dom\lib\EventPluginHub.js:
```

**Comment by jakubzitny** [comment]
Hi @wladan, thank you for reporting this. It's a bug and we're already fixing it for the next release. I am going to close this thread as we're already tracking it in #1621.
