### ISSUE TITLE
error - o.replace is not a function

### ISSUE THREAD

**Issue by jkerdiles** [avocode/avocode#1638]
* **Version**: 2.15.4

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 40512
---

```
TypeError: o.replace is not a function
    at Function.value (file:///Users/jkerdiles/Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:82986)
    at file:///Users/jkerdiles/Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3325899
    at /Users/jkerdiles/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3018:46
    at List.__iterate (/Users/jkerdiles/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/Users/jkerdiles/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3017:23)
    at seqIterate (/Users/jkerdiles/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:606:16)
    at IndexedIterable.IndexedSeq.__iterate (/Users/jkerdiles/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immuta
```

**Comment by jakubzitny** [comment]
Hi @jkerdiles, thanks for reporting this. Do you have any details on how/when and how many times did this happen?

**Comment by apsylone** [comment]
Am answering for @jkerdiles. It occurs each time when exporting an artboard from sketch to Avocode. Maybe a problem with the project files ? 

Do you want us to send you the files ?
 
![capture d ecran 2017-10-09 a 10 38 32](https://user-images.githubusercontent.com/2072877/31330306-1e9274f2-acde-11e7-97e0-7e7251f09fcf.png)

**Comment by jakubzitny** [comment]
Thanks for the info @apsylone. First of all, please update the app to `2.15.5` and also re-install the Sketch plugin from [here](https://avocode-media.s3.amazonaws.com/download/sketch-plugin-new/46.2.4/sketch-plugin-new-mac-46.2.4.sketchplugin.zip) to make sure you have the latest version.

If it's still happening, it might really be in the files and if you'd send them to team@avocode.com it would help us a lot. Also, did you try syncing some really simple file from Sketch to Avocode? Or is it only happening all the time with one(some) specific Sketch file(s)?


Thanks.

**Comment by apsylone** [comment]
@jakubzitny : we've tried reinstalling the plugin. That solves the issue, you can mark it as closed. Thanks.

**Comment by jakubzitny** [comment]
Thanks a lot 🙂

Please let us know if you have any more problems with Avocode.
