### ISSUE TITLE
Cannot read property replace

### ISSUE THREAD

**Issue by MattRoskovec** [avocode/avocode#1652]
* **Version**: 2.15.5-web.1-wfa066e9

* **Web/Desktop**: Web

* **Platform**: macosx 10.13.0
* **Browser**: chrome 61.0.3163.100

* **Avocode UID**: 53649
---

```
TypeError: Cannot read property 'push' of undefined
    at t.value (https://cdn.app.avocode.com/dist/v-67d9eca/js/avocode-web.min.js:79:420294)
    at t.value (https://cdn.app.avocode.com/dist/v-67d9eca/js/avocode-web.min.js:79:414770)
    at t.value (https://cdn.app.avocode.com/dist/v-67d9eca/js/avocode-web.min.js:79:414265)
    at WORKSPACE:ITEM_URI_UPDATE (https://cdn.app.avocode.com/dist/v-67d9eca/js/avocode-web.min.js:79:410786)
    at Object.ID_2 (https://cdn.app.avocode.com/dist/v-67d9eca/js/avocode-web.min.js:48:2208258)
    at e._invokeCallback (https://cdn.app.avocode.com/dist/v-67d9eca/js/avocode-web.min.js:79:427337)
    at e.dispatch (https://cdn.app.avocode.com/dist/v-67d9eca/js/avocode-web.min.js:79:427139)
    at e.value (https://cdn.app.avocode.com/dist/v-67d9eca/js/avocode-web.min.js:48:2208062)
    at t.value (https://cdn.app.avocode.com/dist/v-67d9eca/js/avocode-web.min.js:48:2206480)
    at t.value (https://cdn.app.avocode.com/dist/v-67d9eca/js/avocode-web.min.js:6
```

**Comment by jakubzitny** [comment]
Should not be happening anymore, we'll reopen if it occurs again.

**Comment by jankuca** [comment]
@MattRoskovec Do you remember by any chance when this happened? What were you doing before receiving this error? We are having a very hard time reproducing it.
