### ISSUE TITLE
Cannot call beginDrag while dragging

### ISSUE THREAD

**Issue by cupok** [avocode/avocode#1663]
* **Version**: 2.15.5

* **Web/Desktop**: Desktop

* **Platform**: win32

* **Avocode UID**: 191556
---

```
Invariant Violation: Cannot call beginDrag while dragging.
    at Object.invariant [as default] (C:\Users\cupok\AppData\Local\avocode\app-2.15.5\resources\app.asar\node_modules\invariant\invariant.js:42:15)
    at DragDropManager.beginDrag (C:\Users\cupok\AppData\Local\avocode\app-2.15.5\resources\app.asar\node_modules\dnd-core\lib\actions\dragDrop.js:53:25)
    at Object.beginDrag (C:\Users\cupok\AppData\Local\avocode\app-2.15.5\resources\app.asar\node_modules\dnd-core\lib\DragDropManager.js:74:36)
    at HTML5Backend.handleTopDragStart (C:\Users\cupok\AppData\Local\avocode\app-2.15.5\resources\app.asar\node_modules\react-dnd-html5-backend\lib\HTML5Backend.js:313:18)
    at wrapped (C:\Users\cupok\AppData\Local\avocode\app-2.15.5\resources\app.asar\node_modules\raven-js\src\raven.js:314:29)
```

**Comment by connor-bean** [comment]
hey @cupok -

can you give us more information on what you were doing when this happened?

**Comment by jakubzitny** [comment]
This is related to #1145 and linked issues. It seems that there is still a case where it is happening, we need more info to debug it. I hope it's not something that blocks you from working.

**Comment by cupok** [comment]
I just move a document with a hand tool

**Comment by jakubzitny** [comment]
Thanks @cupok, we'll try to reproduce this and fix it..

**Comment by jakubzitny** [comment]
Hi @cupok, is this still happening to you in latest versions, please?

**Comment by cupok** [comment]
Hey, @jakubzitny, nope. I haven't noticed that for a long time.

**Comment by jakubzitny** [comment]
Thanks for the info, I'll close the issue then. Let us know if you have any other problems 😉
