### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shaka111222** [avocode/avocode#1664]
* **Version**: 2.15.5
* **Sketch plugin version**: 46.2.4

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 116367
---

```
Error: Api#createProject()() -> error (status: 403, error: )
    at t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:143920)
    at t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:143811)
    at new t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:144739)
    at Object._getErrorByStatusCode (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:38773)
    at Object.normalizeError (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:38330)
    at Object.normalizeResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:38161)
    at t.normalizeResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1733401)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1726691
    at Request._callback (file:///Applicatio
```

**Comment by connor-bean** [comment]
We discussed in Intercom. Logging out and back in and making sure the time zone was correct helped solve this.
