### ISSUE TITLE
Software closed while adding a new design with drag&drop feature from zip archive

### ISSUE THREAD

**Issue by Uncleseneca** [avocode/avocode#1667]
* **Version**: 2.16.0

* **Web/Desktop**: Desktop

* **Platform**: win32

* **Avocode UID**: 144195
---

```
Invariant Violation: Cannot call hover while not dragging.
    at Object.invariant [as default] (C:\Users\Vladimir\AppData\Local\avocode\app-2.16.0\resources\app.asar\node_modules\invariant\invariant.js:42:15)
    at DragDropManager.hover (C:\Users\Vladimir\AppData\Local\avocode\app-2.16.0\resources\app.asar\node_modules\dnd-core\lib\actions\dragDrop.js:116:25)
    at Object.hover (C:\Users\Vladimir\AppData\Local\avocode\app-2.16.0\resources\app.asar\node_modules\dnd-core\lib\DragDropManager.js:74:36)
    at HTML5Backend.handleTopDrop (C:\Users\Vladimir\AppData\Local\avocode\app-2.16.0\resources\app.asar\node_modules\react-dnd-html5-backend\lib\HTML5Backend.js:540:18)
    at wrapped (C:\Users\Vladimir\AppData\Local\avocode\app-2.16.0\resources\app.asar\node_modules\raven-js\src\raven.js:314:29)
```

**Comment by jakubzitny** [comment]
This same thing is actually happening on both Windows and Linux, where users are allowed to open ZIP files without unzipping them. I'll close this thread with respect to #1602.
