### ISSUE TITLE
Error trying to add a color

### ISSUE THREAD

**Issue by greystate** [avocode/avocode#1673]
* **Version**: 2.16.0
* **Sketch plugin version**: 47.0.0

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 460
---

Inside a symbol inside another symbol inside a design, I right-clicked a button and chose "Add color to variables" - when I submit the variable dialog an error occurs. Every time.

```
Error: ProjectApi#getProjectById() -> error (status: 404, error: "Not found")
    at t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:145283)
    at t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:145174)
    at new t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:145817)
    at Object._getErrorByStatusCode (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:39208)
    at Object.normalizeError (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:38738)
    at Object.normalizeResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:38569)
    at t.normalizeResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1757497)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1787345
    at Request._callback (f
```

**Comment by jakubzitny** [comment]
Hi @greystate, thanks for reporting the problem. We're already tracking it in #1668 and it will be fixed in next release `2.16.1`.
