### ISSUE TITLE
this sucks

### ISSUE THREAD

**Issue by vdekkernl** [avocode/avocode#1677]
* **Version**: 2.16.0
* **Sketch plugin version**: 47.0.0

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 20437
---

```
Error: ETIMEDOUT
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/request/request.js:813:19
    at wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:314:29)
```

**Comment by jakubzitny** [comment]
Hi @vdekkernl, yeah it does, thanks for reporting it. Do you have any more details on how often is this happening and when exactly, please?

**Comment by vdekkernl** [comment]
Everytime. Can't upload my sketch file. It stucks on 50% 😭😭😭😭

**Comment by jakubzitny** [comment]
I see, is it only one specific file or is it all Sketch files? Does PSD work? Can you try uploading on the web version at app.avocode.com, please?

**Comment by StadnikovP** [comment]
From time to time. Yesterday there were a few times
