### ISSUE TITLE
An unexpected error has occurred

### ISSUE THREAD

**Issue by shaltai** [avocode/avocode#1682]
* **Version**: 2.16.1
* **Sketch plugin version**: 47.1.0

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 141622
---

```
Error: Api#updateUploadSlot()() -> error (status: 400, error: {"__all__":["Parent slot must be uploaded before child slots!"]})
    at t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:152908)
    at new t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:152799)
    at Object._getErrorByStatusCode (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:41518)
    at Object.normalizeError (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:41022)
    at Object.normalizeResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:40853)
    at t.normalizeResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1782248)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1779266
    at Request._callback (file:///Applications/Avocode.app/Contents/Resources/
```
<img width="643" alt="2017-10-20 14 11 37" src="https://user-images.githubusercontent.com/17108398/31818403-a31d1ae0-b5a0-11e7-9b81-c0faf86999c7.png">

**Comment by jakubzitny** [comment]
Hi @shaltai, thanks for reporting this. Do you have any more details on when exactly did this happen? Did it happen more than once, please?

**Comment by shaltai** [comment]
Its permanent. I just try to upload artboards. Sometime Sketch and Avocode relanch helps, sometime only full reboot.

**Comment by leighmckenzie** [comment]
I re-installed Avocode and this issue is still occurring. I haven't been able to upload any artboards for over a week now.

**Comment by jakubzitny** [comment]
Hi @leighmckenzie, @shaltai and others, this should be improved in latest Avocode `2.16.2`. Please update and let us know if it's still happening.
