### ISSUE TITLE
pop up chyba v chromu

### ISSUE THREAD

**Issue by MattRoskovec** [avocode/avocode#1685]
* **Version**: 2.16.1-web

* **Web/Desktop**: Web

* **Platform**: macosx 10.13.0
* **Browser**: chrome 61.0.3163.100

* **Avocode UID**: 53649
---

```
RangeError: Maximum call stack size exceeded
    at t.<anonymous> (https://cdn.app.avocode.com/dist/v-0c05cf0/js/avocode-web.min.js:101:5940)
    at t.n.emit (https://cdn.app.avocode.com/dist/v-0c05cf0/js/avocode-web.min.js:17:94607)
    at a (https://cdn.app.avocode.com/dist/v-0c05cf0/js/avocode-web.min.js:42:673868)
    at t.o.push (https://cdn.app.avocode.com/dist/v-0c05cf0/js/avocode-web.min.js:42:677574)
    at t.o.push (https://cdn.app.avocode.com/dist/v-0c05cf0/js/avocode-web.min.js:42:131682)
    at t.<anonymous> (https://cdn.app.avocode.com/dist/v-0c05cf0/js/avocode-web.min.js:60:389974)
    at r (https://fast.appcues.com/24524.js:1:257900)
    at Generator._invoke (https://fast.appcues.com/24524.js:1:259327)
    at Generator.t.(anonymous function) [as next] (https://fast.appcues.com/24524.js:1:258079)
    at r (https://fast.appcues.com/24524.js:1:257900)
    at Generator._invoke (https://fast.appcues.com/24524.js:1:258966)
    at Generator.t.(anonymous function) [as next] (ht
```

**Comment by jakubzitny** [comment]
Closing with respect to #1671.
