### ISSUE TITLE
Trying to sync artboards from sketch

### ISSUE THREAD

**Issue by edinpuzic** [avocode/avocode#1691]
* **Version**: 2.16.1
* **Sketch plugin version**: 47.1.0

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 49214
---

Hi I'm trying to sync like 5-6 artboards from sketch and I'm getting this error.

```
Error: Could not find upload info for artboard 10D217E4-1EFD-474C-B110-6D09DE6CDDFF
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3383162
    at List.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at List.forEach (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4383:19)
    at t._handleUserDataDesignsRequest (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3383049)
    at emitTwo (events.js:106:13)
    at t.emit (events.js:194:7)
    at t.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1147950)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1510922
    at List.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at List.forEach (/Applications/
```

**Comment by jakubzitny** [comment]
Thanks @edinpuzic. We're tracking this already in #1679 so I'll close this thread. We're fixing it ASAP and the fix should be ready for next Avocode 2.16.2.

For now, please try to sync the file to a separate project or try few more times.
