### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dnikonov** [avocode/avocode#1692]
* **Version**: 2.15.0
* **Sketch plugin version**: 46.2.4

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 24143
---

```
TypeError: t._debounceMouseMoveHandler is not a function
    at t.<anonymous> (file:///Users/ds-nikodim/Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2434098)
    at emitOne (events.js:101:20)
    at t.emit (events.js:191:7)
    at r._handleMouseMove (file:///Users/ds-nikodim/Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3053852)
    at Object.invokeGuardedCallback (/Users/ds-nikodim/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactErrorUtils.js:26:5)
    at executeDispatch (/Users/ds-nikodim/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/EventPluginUtils.js:85:21)
    at Object.executeDispatchesInOrder (/Users/ds-nikodim/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/EventPluginUtils.js:108:5)
    at executeDispatchesAndRelease (/Users/ds-nikodim/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Ev
```

**Comment by connor-bean** [comment]
Hey - Please update to our most recent version and comment on this if you receive the same error again.
