### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by sarates** [avocode/avocode#1693]
* **Version**: 2.16.1

* **Web/Desktop**: Desktop

* **Platform**: linux

* **Avocode UID**: 53626
---

```
Invariant Violation: Cannot call beginDrag while dragging.
    at Object.invariant [as default] (/home/sarates/Desktop/avocode/resources/app.asar/node_modules/invariant/invariant.js:42:15)
    at DragDropManager.beginDrag (/home/sarates/Desktop/avocode/resources/app.asar/node_modules/dnd-core/lib/actions/dragDrop.js:53:25)
    at Object.beginDrag (/home/sarates/Desktop/avocode/resources/app.asar/node_modules/dnd-core/lib/DragDropManager.js:74:36)
    at HTML5Backend.handleTopDragStart (/home/sarates/Desktop/avocode/resources/app.asar/node_modules/react-dnd-html5-backend/lib/HTML5Backend.js:313:18)
    at wrapped (/home/sarates/Desktop/avocode/resources/app.asar/node_modules/raven-js/src/raven.js:314:29)
```

**Comment by connor-bean** [comment]
Hey @sarates 

We've seen this before ( see #1145). Would you be able to tell us more about what you were doing when this happened?

**Comment by jakubzitny** [comment]
Hi, we're actually tracking this in #1663, so I'm going to close this thread.
