### ISSUE TITLE
1

### ISSUE THREAD

**Issue by EgyPetru4o** [avocode/avocode#1694]
* **Version**: 2.16.1
* **Sketch plugin version**: 47.1.0

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 33684
---

```
Error: Api#updateUploadSlot()() -> error (status: 400, error: {"__all__":["Parent slot must be uploaded before child slots!"]})
    at t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:152908)
    at new t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:152799)
    at Object._getErrorByStatusCode (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:41518)
    at Object.normalizeError (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:41022)
    at Object.normalizeResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:40853)
    at t.normalizeResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1782248)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1779266
    at Request._callback (file:///Applications/Avocode.app/Contents/Resources/
```

**Comment by connor-bean** [comment]
Hey @EgyPetru4o -

We are tracking this in #1682 so I will close this as it's a duplicate
