### ISSUE TITLE
Don't have choice, upload on the wrong folder... :/

### ISSUE THREAD

**Issue by error32** [avocode/avocode#1695]
* **Version**: 2.16.1
* **Sketch plugin version**: 47.1.0

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 203722
---

```
Error: Could not find upload info for artboard 62C8A5F6-9190-4404-A4A5-6403F8E8BF15
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3383162
    at List.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at List.forEach (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4383:19)
    at t._handleUserDataDesignsRequest (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3383049)
    at emitTwo (events.js:106:13)
    at t.emit (events.js:194:7)
    at t.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1147950)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1510922
    at List.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at List.forEach (/Applications/
```

**Comment by jakubzitny** [comment]
Hi, thanks for reporting this. We're already this problem in #1679, it should be fixed in 2.16.2 next week.
