### ISSUE TITLE
Sketch -> Avocode sync issue

### ISSUE THREAD

**Issue by leighmckenzie** [avocode/avocode#1700]
* **Version**: 2.16.1
* **Sketch plugin version**: 47.1.0

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 56092
---

```
Error: Api#updateUploadSlot()() -> error (status: 400, error: {"__all__":["Parent slot must be uploaded before child slots!"]})
    at t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:152908)
    at new t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:152799)
    at Object._getErrorByStatusCode (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:41518)
    at Object.normalizeError (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:41022)
    at Object.normalizeResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:40853)
    at t.normalizeResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1782248)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1779266
    at Request._callback (file:///Applications/Avocode.app/Contents/Resources/
```

**Comment by connor-bean** [comment]
Hey @leighmckenzie -

Thanks for the report. We're currently tracking this in the ticket #1682 so I will ask you to provide any additional information possible - does it happen all the time? what you were doing exactly when it happened? does it help to restart Sketch as well as Avocode? that sort of thing

**Comment by leighmckenzie** [comment]
This just started happening about 30 minutes ago. I had successfully synced a number of artboards to my Avocode project and then the last two I tried started popping this issue. 

I tried restarting Sketch, Avocode, and then my whole computer.

**Comment by connor-bean** [comment]
Thanks again, yeah this is similar to #1682. We're actually tracking this exact thing in #1679 so I'll close this thread. We're fixing it ASAP.
