### ISSUE TITLE
Cannot Upload

### ISSUE THREAD

**Issue by KatieSiu** [avocode/avocode#1702]
* **Version**: 2.16.1
* **Sketch plugin version**: 47.1.0

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 83286
---

```
Error: Could not find upload info for artboard 06FFA411-E76B-48FA-AC48-9AEF805D02ED
    at file:///Users/katie.siu/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3383162
    at List.__iterate (/Users/katie.siu/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at List.forEach (/Users/katie.siu/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4383:19)
    at t._handleUserDataDesignsRequest (file:///Users/katie.siu/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3383049)
    at emitTwo (events.js:106:13)
    at t.emit (events.js:194:7)
    at t.value (file:///Users/katie.siu/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1147950)
    at file:///Users/katie.siu/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/
```

**Comment by connor-bean** [comment]
Hi, thanks for reporting this. We're already this problem in #1679, it should be fixed in 2.16.2 next week.
