### ISSUE TITLE
Avocode not working

### ISSUE THREAD

**Issue by Mighty-Lake** [avocode/avocode#1706]
* **Version**: 2.16.1
* **Sketch plugin version**: 47.1.0

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 96304
---

```
Error: Could not find upload info for artboard C5004E62-C409-4622-B32B-31BB28BF3161
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3383162
    at List.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at List.forEach (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4383:19)
    at t._handleUserDataDesignsRequest (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3383049)
    at emitTwo (events.js:106:13)
    at t.emit (events.js:194:7)
    at t.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1147950)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1510922
    at List.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at List.forEach (/Applications/
```

**Comment by bolekkerous** [comment]
Hey - 
thanks for the report. Could you please elaborate how did this exactly happen?

Were you syncing a design from Sketch or were you just trying to open a document? Or something completely different?

Thanks and sorry for the inconvenience.

**Comment by jakubzitny** [comment]
Thanks again, we're actually tracking this exact thing in #1679 so I'll close this thread. We're fixing it ASAP.
