### ISSUE TITLE
Uploading not working in just certain file

### ISSUE THREAD

**Issue by spooner2802** [avocode/avocode#1707]
* **Version**: 2.16.1
* **Sketch plugin version**: 47.1.0

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 13535
---

```
Error: Could not find upload info for artboard E506AE4D-3469-41AF-AE28-A18B287BF44D
    at file:///Users/Spoony/Downloads/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3383162
    at List.__iterate (/Users/Spoony/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at List.forEach (/Users/Spoony/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4383:19)
    at t._handleUserDataDesignsRequest (file:///Users/Spoony/Downloads/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3383049)
    at emitTwo (events.js:106:13)
    at t.emit (events.js:194:7)
    at t.value (file:///Users/Spoony/Downloads/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1147950)
    at file:///Users/Spoony/Downloads/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1510922
    at List.__iterate (/Users/Spoony/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/im
```

**Comment by bolekkerous** [comment]
Hey,
if it happens only with specific file, could you please send us the problematic sketch file to team@avocode.com, so we can investigate properly?

Thanks!

**Comment by jakubzitny** [comment]
Thanks again, we're actually tracking this exact thing in #1679 so I'll close this thread. We're fixing it ASAP.
