### ISSUE TITLE
Upload larges PSD files rapidly

### ISSUE THREAD

**Issue by ArrowBaZ** [avocode/avocode#1708]
* **Version**: 2.16.1-web

* **Web/Desktop**: Web

* **Platform**: windows 10.0
* **Browser**: opera 50.0.2753.0

* **Avocode UID**: 102722
---

Upload larges PSD files rapidly
```
TypeError: undefined is not a function
    at Array.forEach (<anonymous>)
    at t.value (https://cdn.app.avocode.com/dist/v-0c05cf0/js/avocode-web.min.js:79:388605)
    at r (https://cdn.app.avocode.com/dist/v-0c05cf0/js/avocode-web.min.js:79:385082)
    at a (https://cdn.app.avocode.com/dist/v-0c05cf0/js/avocode-web.min.js:79:383455)
    at https://cdn.app.avocode.com/dist/v-0c05cf0/js/avocode-web.min.js:79:388507
    at https://cdn.app.avocode.com/dist/v-0c05cf0/js/avocode-web.min.js:1:15686
    at Be.__iterate (https://cdn.app.avocode.com/dist/v-0c05cf0/js/avocode-web.min.js:1:38409)
    at r.__iterateUncached (https://cdn.app.avocode.com/dist/v-0c05cf0/js/avocode-web.min.js:1:15645)
    at G (https://cdn.app.avocode.com/dist/v-0c05cf0/js/avocode-web.min.js:1:3458)
    at r.I.__iterate (https://cdn.app.avocode.com/dist/v-0c05cf0/js/avocode-web.min.js:1:26146)
    at r.toArray (https://cdn.app.avocode.com/dist/v-0c05cf0/js/avocode-web.min.js:1:49401)
    at Be [as constructor] (http
```

**Comment by bolekkerous** [comment]
Hey, @ArrowBaZ -
could you please elaborate what exactly were you trying to do when this error happened?

Have you uploaded a lot of PSDs at once? 

Thanks and sorry for the inconvenience.
