### ISSUE TITLE
Drag&drop image with telegram to avocode

### ISSUE THREAD

**Issue by savaxakep** [avocode/avocode#1711]
* **Version**: 2.16.1

* **Web/Desktop**: Desktop

* **Platform**: win32

* **Avocode UID**: 200781
---

```
Invariant Violation: Cannot call hover while not dragging.
    at Object.invariant [as default] (C:\Users\vsavr\AppData\Local\avocode\app-2.16.1\resources\app.asar\node_modules\invariant\invariant.js:42:15)
    at DragDropManager.hover (C:\Users\vsavr\AppData\Local\avocode\app-2.16.1\resources\app.asar\node_modules\dnd-core\lib\actions\dragDrop.js:116:25)
    at Object.hover (C:\Users\vsavr\AppData\Local\avocode\app-2.16.1\resources\app.asar\node_modules\dnd-core\lib\DragDropManager.js:74:36)
    at HTML5Backend.handleTopDrop (C:\Users\vsavr\AppData\Local\avocode\app-2.16.1\resources\app.asar\node_modules\react-dnd-html5-backend\lib\HTML5Backend.js:540:18)
    at wrapped (C:\Users\vsavr\AppData\Local\avocode\app-2.16.1\resources\app.asar\node_modules\raven-js\src\raven.js:314:29)
```

**Comment by jakubzitny** [comment]
Hi @savaxakep, thanks for the report. Did this happen by any chance after dragging a design into Avocode from opened ZIP file, or something similar?

We have a similar thread in #1667, so I am going to closet this one.

**Comment by savaxakep** [comment]
Hi @jakubzitny, yes. Okey
