### ISSUE TITLE
Avocode: An unexpected error has occurred

### ISSUE THREAD

**Issue by biswasxrajib** [avocode/avocode#1713]
* **Version**: 2.16.1
* **Sketch plugin version**: 47.1.0

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 111909
---

```
Error: Api#updateUploadSlot()() -> error (status: 400, error: {"__all__":["Parent slot must be uploaded before child slots!"]})
    at t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:152908)
    at new t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:152799)
    at Object._getErrorByStatusCode (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:41518)
    at Object.normalizeError (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:41022)
    at Object.normalizeResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:40853)
    at t.normalizeResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1782248)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1779266
    at Request._callback (file:///Applications/Avocode.app/Contents/Resources/
```

**Comment by connor-bean** [comment]
Thanks for the report. We're currently tracking this in the ticket #1682 so I will ask you to provide any additional information possible - does it happen all the time? what you were doing exactly when it happened? does it help to restart Sketch as well as Avocode? that sort of thing

**Comment by biswasxrajib** [comment]
Yes its repeating now. One of my team member is cleaning other project on the same account. I tried to upload after relaunching still shows the same error.

**Comment by jakubzitny** [comment]
Thanks for the info @biswasxrajib, I'll close this thread with respect to #1682.
