### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by design-ninja** [avocode/avocode#1719]
* **Version**: 2.16.1
* **Sketch plugin version**: 47.1.0

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 125888
---

```
Error: Api#createProject()() -> error (status: 400, error: {"owner":["Only organization member can add new projects!"]})
    at t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:152908)
    at new t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:152799)
    at Object._getErrorByStatusCode (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:41518)
    at Object.normalizeError (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:41022)
    at Object.normalizeResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:40853)
    at t.normalizeResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1782248)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1775538
    at Request._callback (file:///Applications/Avocode.app/Contents/Resources/app.asa
```

**Comment by vojtatranta** [comment]
This error should not pop up. We will fix it in the next release.

**Comment by vojtatranta** [comment]
`2.16.3` released
