### ISSUE TITLE
I have issue in avacode today.

### ISSUE THREAD

**Issue by Kasst1el** [avocode/avocode#1720]
* **Version**: 2.16.0

* **Web/Desktop**: Desktop

* **Platform**: win32

* **Avocode UID**: 165211
---

```
Invariant Violation: Cannot call beginDrag while dragging.
    at Object.invariant [as default] (C:\Users\Артем\AppData\Local\avocode\app-2.16.0\resources\app.asar\node_modules\invariant\invariant.js:42:15)
    at DragDropManager.beginDrag (C:\Users\Артем\AppData\Local\avocode\app-2.16.0\resources\app.asar\node_modules\dnd-core\lib\actions\dragDrop.js:53:25)
    at Object.beginDrag (C:\Users\Артем\AppData\Local\avocode\app-2.16.0\resources\app.asar\node_modules\dnd-core\lib\DragDropManager.js:74:36)
    at HTML5Backend.handleTopDragStart (C:\Users\Артем\AppData\Local\avocode\app-2.16.0\resources\app.asar\node_modules\react-dnd-html5-backend\lib\HTML5Backend.js:313:18)
    at wrapped (C:\Users\Артем\AppData\Local\avocode\app-2.16.0\resources\app.asar\node_modules\raven-js\src\raven.js:314:29)
```

**Comment by jakubzitny** [comment]
Hi @Kasst1el, thanks for the report. When did this happen? Did you by any chance try to upload a design from ZIP archive? Did it happen more than once?

**Comment by jakubzitny** [comment]
We're actually tracking this in #1663, so I am going to close this issue, but please let us know the details so we can reproduce it.
