### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Venegrad** [avocode/avocode#1725]
* **Version**: 2.16.4

* **Web/Desktop**: Desktop

* **Platform**: win32

* **Avocode UID**: 211324
---

```
TypeError: (0 , t._mouseupCancellers[e]) is not a function
    at file:///C:/Users/Venegrad/AppData/Local/avocode/app-2.16.4/resources/app.asar/dist/avocode.min.js:1:2332722
    at wrapped (C:\Users\Venegrad\AppData\Local\avocode\app-2.16.4\resources\app.asar\node_modules\raven-js\src\raven.js:314:29)
```

**Comment by jakubzitny** [comment]
Hi @Venegrad, thanks for submitting this issue. Do you have any details on how did it happen?
