### ISSUE TITLE
Error: connect ETIMEDOUT 52.70.75.29:443

### ISSUE THREAD

**Issue by StadnikovP** [avocode/avocode#1730]
* **Version**: 2.16.4

* **Web/Desktop**: Desktop

* **Platform**: win32

* **Avocode UID**: 48764
---

```
Error: connect ETIMEDOUT 52.70.75.29:443
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
```

**Comment by jakubzitny** [comment]
Hi @StadnikovP, we're already tracking this in #1677. Do you have any details on how is this happening? More than once? When exactly?
