### ISSUE TITLE
error (I'm in China)

### ISSUE THREAD

**Issue by rasult22** [avocode/avocode#1741]
---
* **Version**: 2.16.6
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: null
---
```
Error: Callback was already called.
    at file:///C:/Users/%D0%A1%D0%BA%D1%80%D0%BE%D0%BB%D0%BB/AppData/Local/avocode/app-2.16.6/resources/app.asar/dist/avocode.min.js:1:160405
    at file:///C:/Users/%D0%A1%D0%BA%D1%80%D0%BE%D0%BB%D0%BB/AppData/Local/avocode/app-2.16.6/resources/app.asar/dist/avocode.min.js:1:1904322
    at n (file:///C:/Users/%D0%A1%D0%BA%D1%80%D0%BE%D0%BB%D0%BB/AppData/Local/avocode/app-2.16.6/resources/app.asar/dist/avocode.min.js:1:1904896)
    at file:///C:/Users/%D0%A1%D0%BA%D1%80%D0%BE%D0%BB%D0%BB/AppData/Local/avocode/app-2.16.6/resources/app.asar/dist/avocode.min.js:1:1904728
    at file:///C:/Users/%D0%A1%D0%BA%D1%80%D0%BE%D0%BB%D0%BB/AppData/Local/avocode/app-2.16.6/resources/app.asar/dist/avocode.min.js:1:1893836
    at Request.<anonymous> (file:///C:/Users/%D0%A1%D0%BA%D1%80%D0%BE%D0%BB%D0%BB/AppData/Local/avocode/app-2.16.6/resources/app.asar/dist/avocode.min.js:1:1894305)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:101:20)
  
```

**Comment by jakubzitny** [comment]
Hi @rasult22, thanks for letting us know. What exactly have you been trying to do? Did this happen more than once? Are you able to use Avocode at all?

**Comment by rasult22** [comment]
It's happened when I try to login into desktop app use browser login. I'm already logined by desktop app. It's OK. Thank you for your support. 
--
Отправлено из Mail.Ru для Android понедельник, 20 ноября 2017г., 20:57 +08:00 от Jakub Žitný  notifications@github.com :

**Comment by jakubzitny** [comment]
Thanks @rasult22, let us know if you have any more problems with Avocode 😉
