### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MrValis** [avocode/avocode#1749]
---
* **Version**: 2.17.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 15839
---
```
Error: getaddrinfo EAI_AGAIN preview-production.avcd.cz:443
    at Object.exports._errnoException (util.js:1050:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
```

**Comment by vojtatranta** [comment]
Hello, we know about this connection problems and we will fix them as soon as possible.
