### ISSUE TITLE
Request aborted by the downloader process

### ISSUE THREAD

**Issue by pavelsamonin** [avocode/avocode#1750]
---
* **Version**: 2.16.6
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 215444
---
```
Error: Request aborted by the downloader process.
    at e._handleRequestAbort (file:///home/pavel/%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B8/avocode/resources/app.asar/dist/avocode.min.js:1:2097089)
    at t.<anonymous> (file:///home/pavel/%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B8/avocode/resources/app.asar/dist/avocode.min.js:1:2090460)
    at emitOne (events.js:96:13)
    at t.emit (events.js:191:7)
    at t._handleDownloaderEvent (file:///home/pavel/%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B8/avocode/resources/app.asar/dist/avocode.min.js:1:2113868)
    at EventEmitter.<anonymous> (file:///home/pavel/%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B8/avocode/resources/app.asar/dist/avocode.min.js:1:2110636)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

**Comment by jakubzitny** [comment]
Hi @pavelsamonin, do you have any details on when and how often is this happening, please? We're inspecting the problem and we'll try to fix it asap.

**Comment by pavlosamonin** [comment]
Hi!
Sorry, I haven't details - but this happened everytime I tried

2017-12-01 13:34 GMT+02:00 Jakub Žitný <notifications@github.com>:

**Comment by jakubzitny** [comment]
This problem is related to #1779.
