### ISSUE TITLE
是萨芬

### ISSUE THREAD

**Issue by matinazpp** [avocode/avocode#1754]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.3-3630f5a
Source UID: undefined
```
TypeError: Cannot read property 'statusCode' of undefined
  at Request._callback (C:\Users\Administrator\AppData\Local\avocode\app-2.4.3\resources\app.asar\node_modules\@avocode\core\lib\api.js:1:3336)
  at self.callback (C:\Users\Administrator\AppData\Local\avocode\app-2.4.3\resources\app.asar\node_modules\@avocode\core\node_modules\request\request.js:198:22)
  at emitOne (events.js:77:13)
  at Request.emit (events.js:166:7)
  at Request.onRequestError (C:\Users\Administrator\AppData\Local\avocode\app-2.4.3\resources\app.asar\node_modules\@avocode\core\node_modules\request\request.js:867:8)
  at emitOne (events.js:77:13)
  at ClientRequest.emit (events.js:166:7)
  at TLSSocket.socketErrorListener (_http_client.js:254:9)
  at emitOne (events.js:77:13)
  at TLSSocket.emit (events.js:166:7)
  at net.js:438:14
  at process._tickCallback (node.js:357:13)

```

**Comment by vojtatranta** [comment]
Hello, you have a realy old version of the app.

Please update: https://avocode.com/download
