### ISSUE TITLE
Faild on inspect

### ISSUE THREAD

**Issue by artur152** [avocode/avocode#1757]
---
* **Version**: 2.17.1
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 221744
---
```
Error: Request aborted by the downloader process.
    at e._handleRequestAbort (file:///home/envy/Downloads/avocode-2.17.1-linux/resources/app.asar/dist/avocode.min.js:1:2132598)
    at t.<anonymous> (file:///home/envy/Downloads/avocode-2.17.1-linux/resources/app.asar/dist/avocode.min.js:1:2125969)
    at emitOne (events.js:96:13)
    at t.emit (events.js:191:7)
    at t._handleDownloaderEvent (file:///home/envy/Downloads/avocode-2.17.1-linux/resources/app.asar/dist/avocode.min.js:1:2149377)
    at EventEmitter.<anonymous> (file:///home/envy/Downloads/avocode-2.17.1-linux/resources/app.asar/dist/avocode.min.js:1:2146145)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

**Comment by jakubzitny** [comment]
Hi @artur152, do you have any details on when and how often is this happening, please?

I am going to close this with respect to #1750.
