### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SerZubkov** [avocode/avocode#1763]
---
* **Version**: 2.17.1-web.2
* **Web/Desktop**: Web
* **Platform**: linux -1
* **Browser**: yandex 17.9.1.982
* **Avocode UID**: 223473
---
```
RangeError: Failed to execute 'createImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation
    at e.exports.e.drawHit (https://cdn.app.avocode.com/dist/v-7fe3264/js/avocode-web.min.js:101:1475807)
    at e.exports.e.drawImage (https://cdn.app.avocode.com/dist/v-7fe3264/js/avocode-web.min.js:101:1476821)
    at https://cdn.app.avocode.com/dist/v-7fe3264/js/avocode-web.min.js:101:1474667
    at Be.__iterate (https://cdn.app.avocode.com/dist/v-7fe3264/js/avocode-web.min.js:1:38410)
    at Be.forEach (https://cdn.app.avocode.com/dist/v-7fe3264/js/avocode-web.min.js:1:50947)
    at e.exports.e.createSprites (https://cdn.app.avocode.com/dist/v-7fe3264/js/avocode-web.min.js:101:1474238)
    at https://cdn.app.avocode.com/dist/v-7fe3264/js/avocode-web.min.js:101:1474590
    at Be.__iterate (https://cdn.app.avocode.com/dist/v-7fe3264/js/avocode-web.min.js:1:38410)
    at Be.forEach (https://cdn.app.avocode.com/dist/v-7fe3264/js/avocode-web.min.js:1:50947)
    at e.export
```

**Comment by vojtatranta** [comment]
Hi,
does it happen every time you try to open this design?

Another thing I noticed is that you use some uncommon browser which may have stricter rule about WebGL

**Comment by jakubzitny** [comment]
We already have this in #1567. We're preparing a better check for canvas support in browsers and we'll notify in advance if the support is insufficient.

Closing with respect to #1567.
