### ISSUE TITLE
Failed to sync and download data 

### ISSUE THREAD

**Issue by tallrye** [avocode/avocode#1764]
---
* **Version**: 2.17.1
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 222946
---
```
Error: Request aborted by the downloader process.
    at e._handleRequestAbort (file:///C:/Users/Serhat/AppData/Local/avocode/app-2.17.1/resources/app.asar/dist/avocode.min.js:1:2132598)
    at t.<anonymous> (file:///C:/Users/Serhat/AppData/Local/avocode/app-2.17.1/resources/app.asar/dist/avocode.min.js:1:2125969)
    at emitOne (events.js:96:13)
    at t.emit (events.js:191:7)
    at t._handleDownloaderEvent (file:///C:/Users/Serhat/AppData/Local/avocode/app-2.17.1/resources/app.asar/dist/avocode.min.js:1:2149377)
    at EventEmitter.<anonymous> (file:///C:/Users/Serhat/AppData/Local/avocode/app-2.17.1/resources/app.asar/dist/avocode.min.js:1:2146145)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

**Comment by vojtatranta** [comment]
Hi,
we will track this issue here #1766 this one is it's duplicate
