### ISSUE TITLE
Can't open screen

### ISSUE THREAD

**Issue by irbisadm** [avocode/avocode#1765]
---
* **Version**: 2.17.1
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 49422
---
```
Error: Request aborted by the downloader process.
    at e._handleRequestAbort (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:2132598)
    at t.<anonymous> (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:2125969)
    at emitOne (events.js:96:13)
    at t.emit (events.js:191:7)
    at t._handleDownloaderEvent (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:2149377)
    at EventEmitter.<anonymous> (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:2146145)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

**Comment by jakubzitny** [comment]
Hi @irbisadm, thanks for reporting this. We're already tracking this problem in #1750.
