### ISSUE TITLE
I can't download design

### ISSUE THREAD

**Issue by skokalin** [avocode/avocode#1766]
---
* **Version**: 2.17.1
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 161890
---
```
Error: Request aborted by the downloader process.
    at e._handleRequestAbort (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:2132598)
    at t.<anonymous> (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:2125969)
    at emitOne (events.js:96:13)
    at t.emit (events.js:191:7)
    at t._handleDownloaderEvent (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:2149377)
    at EventEmitter.<anonymous> (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:2146145)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

**Comment by vojtatranta** [comment]
Hi,
thank you for this report.

Does it fail every time you try to open that design?

**Comment by skokalin** [comment]
Hi!
Yes.

2017-12-03 23:16 GMT+03:00 Vojtěch Tranta <notifications@github.com>:

**Comment by jakubzitny** [comment]
Closing with respect to #1750.
