### ISSUE TITLE
Error syncing selected artboards

### ISSUE THREAD

**Issue by paohlaa** [avocode/avocode#1769]
* **Version**: 2.15.5
* **Sketch plugin version**: 47.1.4

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 175224
---

```
Error: Could not find upload info for artboard 02C18A84-D219-4976-B26D-6302837A590D
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3310470
    at List.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at List.forEach (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4383:19)
    at t._handleUserDataDesignsRequest (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3310332)
    at emitTwo (events.js:106:13)
    at t.emit (events.js:194:7)
    at t.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1116452)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1465655
    at List.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at List.forEach (/Applications/
```

**Comment by jakubzitny** [comment]
Hi @paohlaa, thanks for reporting this problem. You have an old version of our app, please update to `2.17.1` and this problem should be fixed.

Let me know if you still see this (or any other) problem.
