### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by adrugov** [avocode/avocode#1773]
---
* **Version**: 2.17.1
* **Sketch plugin version**: 47.1.4
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 94586
---
```
Error: Missing child slot for artboardId=F6611AF5-9ADB-492B-A275-343863744442.
    at t.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1208228)
    at t.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1207868)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3546705
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Closing with respect to #1772.
