### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by Bryant-24** [avocode/avocode#1775]
---
* **Version**: 2.17.1
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 3364
---
```
Error: connect ECONNREFUSED 104.28.5.96:443
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
```

**Comment by jakubzitny** [comment]
Hi @Bryant-24, thanks for reporting this. Do you have any details on the issue? Is it happening often or just this one time? When exactly?

**Comment by jakubzitny** [comment]
Hi @Bryant-24, we've not seen this problem for a while, is it still happening to you, please?

**Comment by connor-bean** [comment]
Hi @Bryant-24, we've not seen this problem for a while, is it still happening to you, please?

**Comment by jakubzitny** [comment]
Closing due to inactivity, please let us know if you still have problems with it.
