### ISSUE TITLE
The request timed out

### ISSUE THREAD

**Issue by koskinpark** [avocode/avocode#1781]
---
* **Version**: 2.17.1
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 22577
---
```
Error: The request timed out
    at file:///Users/koskinpark/Downloads/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2154222
    at wrapped (/Users/koskinpark/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:314:29)
```

**Comment by jakubzitny** [comment]
Hi @koskinpark, we sometimes do not properly handle these network issues. I'll leave this open and please let us know if it happens again or if it's happening a lot to you. We'll be fixing it for one of upcoming releases.
