### ISSUE TITLE
TypeError: Cannot read property 'toJS' of undefined

### ISSUE THREAD

**Issue by alex-d-ivan** [avocode/avocode#1786]
---
* **Version**: 2.17.0
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 12488
---
```
TypeError: Cannot read property 'toJS' of undefined
    at a (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:1379796)
    at Object.s [as convertColor] (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:1379937)
    at file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:112562
    at /opt/Avocode/resources/app.asar/node_modules/immutable/dist/immutable.js:3018:46
    at List.__iterate (/opt/Avocode/resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/opt/Avocode/resources/app.asar/node_modules/immutable/dist/immutable.js:3017:23)
    at seqIterate (/opt/Avocode/resources/app.asar/node_modules/immutable/dist/immutable.js:606:16)
    at IndexedIterable.IndexedSeq.__iterate (/opt/Avocode/resources/app.asar/node_modules/immutable/dist/immutable.js:322:14)
    at IndexedIterable.toArray (/opt/Avocode/resources/app.asar/node_modules/immutable/dist/immutable.js:4260:23)
    at new List 
```

**Comment by jakubzitny** [comment]
Hi @crypticman, thanks for reporting this. We're already tracking this problem in #1760 and it will be fixed in Avocode `2.18.0` in upcoming weeks.
