### ISSUE TITLE
Sketch file failed to post

### ISSUE THREAD

**Issue by indianabenny** [avocode/avocode#1787]
---
* **Version**: 2.17.1
* **Sketch plugin version**: 47.1.4
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 64882
---
```
Error: Command failed: "/Applications/Sketch.app/Contents/Resources/sketchtool/bin/sketchtool" export artboards --overwriting --use-id-for-name --formats="png" --output="/var/folders/xy/g79m5_r56h38l13qx8zrmtx00000gn/T/com.madebysource.avocode/avocode-sync-1513786140274/4E520CAD-656B-4D20-8A1C-2F5AB8071AF4" --item="4E520CAD-656B-4D20-8A1C-2F5AB8071AF4" --scales="1" "/Users/indianabenny/Downloads/lg cse newsroom.sketch"
2017-12-20 11:09:01.214 sketchtool[2936:535479] -[ECCommandLineEngine outputError:format:]: unrecognized selector sent to instance 0x7fbf8341a690
Command threw exception

(ECCommandLineDomain:5)


    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

**Comment by jakubzitny** [comment]
Hi @indianabenny, this seems to be a `sketchtool` related problem. Would you be willing to send us your sketch file to team@avocode.com so we can inspect the problem in detail, please?

**Comment by connor-bean** [comment]
Hi @indianabenny, this seems to be a sketchtool related problem. Would you be willing to send us your sketch file to team@avocode.com so we can inspect the problem in detail, please?

**Comment by jakubzitny** [comment]
Closing due to inactivity. Let us know if you still have this or any other problem with Avocode 😉
