### ISSUE TITLE
???

### ISSUE THREAD

**Issue by Yugofx** [avocode/avocode#1789]
---
* **Version**: 2.17.1
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 150414
---
```
Error: Request aborted by the downloader process.
    at e._handleRequestAbort (file:///private/var/folders/p2/ggj5z169437d4v4xq5f0jg_40000gn/T/AppTranslocation/20D40C7A-94B5-42A7-A60E-DABE85A2F4D5/d/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2132598)
    at t.<anonymous> (file:///private/var/folders/p2/ggj5z169437d4v4xq5f0jg_40000gn/T/AppTranslocation/20D40C7A-94B5-42A7-A60E-DABE85A2F4D5/d/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2125969)
    at emitOne (events.js:96:13)
    at t.emit (events.js:191:7)
    at t._handleDownloaderEvent (file:///private/var/folders/p2/ggj5z169437d4v4xq5f0jg_40000gn/T/AppTranslocation/20D40C7A-94B5-42A7-A60E-DABE85A2F4D5/d/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2149377)
    at EventEmitter.<anonymous> (file:///private/var/folders/p2/ggj5z169437d4v4xq5f0jg_40000gn/T/AppTranslocation/20D40C7A-94B5-42A7-A60E-DABE85A2F4D5/d/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2146145)
   
```

**Comment by jakubzitny** [comment]
Hi @Yugofx, thanks for the report. We're tracking this in #1750 already so I am going to close this issue.

Do you have any details on it though? Is it happening to more than one design? Did you try to open it in our web version at app.avocode.com?
