### ISSUE TITLE
Copy text

### ISSUE THREAD

**Issue by shevlyakovn** [avocode/avocode#1790]
---
* **Version**: 2.17.1
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 13268
---
```
Invariant Violation: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%3Cclass%3E%2C%20data%2C%20encoding%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at reactProdInvariant (C:\Users\user\AppData\Local\avocode\app-2.17.1\resources\app.asar\node_modules\react-dom\lib\reactProdInvariant.js:31:15)
    at traverseAllChildrenImpl (C:\Users\user\AppData\Local\avocode\app-2.17.1\resources\app.asar\node_modules\react-dom\lib\traverseAllChildren.js:144:261)
    at traverseAllChildren (C:\Users\user\AppData\Local\avocode\app-2.17.1\resources\app.asar\node_modules\react-dom\lib\traverseAllChildren.js:172:10)
    at Object.instantiateChildren (C:\Users\user\AppData\Local\avocode\app-2.17.1\resources\app.asar\node_modules\react-dom\lib\ReactChildReconciler.js:74:7)
    at ReactDOMComponent._reconcilerInstantiateChildren (C:\Users\user\A
```

**Comment by jakubzitny** [comment]
Thanks for the report @shevlyakovn. Is this happening when you copy a text layer by double clicking or by pressing the button in top right panel? Can you please send us the public link to the design or the PSD to team@avocode.com?

**Comment by jakubzitny** [comment]
Thanks for the report @shevlyakovn. Is this happening when you copy a text layer by double clicking or by pressing the button in top right panel? Can you please send us the public link to the design or the PSD to team@avocode.com?

Is it still happening in latest versions of Avocode at all?

**Comment by jakubzitny** [comment]
Closing due to inactivity.
