### ISSUE TITLE
On sync selected artboard

### ISSUE THREAD

**Issue by nzmb** [avocode/avocode#1792]
---
* **Version**: 2.17.1
* **Sketch plugin version**: 47.1.4
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 34285
---
```
Error: connect ECONNREFUSED 13.33.21.121:443
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
```

**Comment by jakubzitny** [comment]
Hi @nzmb, thanks for submitting this. We can see some problems with network, we're tracking this already in #1775. How often is this happening, please?
