### ISSUE TITLE
can't open psd file on linux

### ISSUE THREAD

**Issue by deckrow** [avocode/avocode#1793]
---
* **Version**: 2.17.1
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 238976
---
```
Error: Request aborted by the downloader process.
    at e._handleRequestAbort (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:2132598)
    at t.<anonymous> (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:2125969)
    at emitOne (events.js:96:13)
    at t.emit (events.js:191:7)
    at t._handleDownloaderEvent (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:2149377)
    at EventEmitter.<anonymous> (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:2146145)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

**Comment by jakubzitny** [comment]
Hi @deckrow, thanks for the report. We're tracking this in #1750 already so I am going to close this issue.

Do you have any details on it though? Is it happening to more than one design? Did you try to open it in our web version at app.avocode.com?

**Comment by deckrow** [comment]
When i try to open some psd in avocode, they start to load (10-20%) and then i see next error.
Document faild to load.
If psd very small, he's can be opened.
In web version everything ok.
