### ISSUE TITLE
Linux Mint KDE Drag&Drop from Ark Error

### ISSUE THREAD

**Issue by Rikcon** [avocode/avocode#1797]
---
* **Version**: 2.17.1
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 239726
---
```
Invariant Violation: Cannot call hover while not dragging.
    at Object.invariant [as default] (/opt/Avocode/resources/app.asar/node_modules/invariant/invariant.js:42:15)
    at DragDropManager.hover (/opt/Avocode/resources/app.asar/node_modules/dnd-core/lib/actions/dragDrop.js:116:25)
    at Object.hover (/opt/Avocode/resources/app.asar/node_modules/dnd-core/lib/DragDropManager.js:74:36)
    at HTML5Backend.handleTopDrop (/opt/Avocode/resources/app.asar/node_modules/react-dnd-html5-backend/lib/HTML5Backend.js:540:18)
    at wrapped (/opt/Avocode/resources/app.asar/node_modules/raven-js/src/raven.js:314:29)
```

**Comment by jakubzitny** [comment]
Hi @Rikcon, thanks for reporting this bug. Yes, this is definitely a problem with the archive stuff. Please, just unzip/untar the file you're uploading and then drag and drop it. Everything will work correctly.

At some point we might add a support for uploading archives (zip, tar, etc.) and drag and drop from within archive will be possible, but that is not a priority for now.  We're tracking that in #1602, so I am going to close this issue.
