### ISSUE TITLE
kjgbg

### ISSUE THREAD

**Issue by neprosto** [avocode/avocode#1814]
---
* **Version**: 2.17.2-web.4
* **Web/Desktop**: Web
* **Platform**: windows 10.0
* **Browser**: chrome 63.0.3239.132
* **Avocode UID**: 247014
---
```
TypeError: this._api.setUserProfile is not a function
    at e.updateStorage (https://cdn.app.avocode.com/dist/v-ef1837a/js/avocode-web.min.js:66:116489)
    at e.value (https://cdn.app.avocode.com/dist/v-ef1837a/js/avocode-web.min.js:101:1003034)
    at Object._handlePhaseFinish (https://cdn.app.avocode.com/dist/v-ef1837a/js/avocode-web.min.js:54:289519)
    at Object.r._handleRenameTeamRequest [as onRenameTeamRequest] (https://cdn.app.avocode.com/dist/v-ef1837a/js/avocode-web.min.js:54:292128)
    at Object._handleTeamRenameFormSubmit (https://cdn.app.avocode.com/dist/v-ef1837a/js/avocode-web.min.js:65:34277)
    at Object.r (https://cdn.app.avocode.com/dist/v-ef1837a/js/avocode-web.min.js:28:476185)
    at a (https://cdn.app.avocode.com/dist/v-ef1837a/js/avocode-web.min.js:28:474531)
    at Object.s [as executeDispatchesInOrder] (https://cdn.app.avocode.com/dist/v-ef1837a/js/avocode-web.min.js:28:474746)
    at p (https://cdn.app.avocode.com/dist/v-ef1837a/js/avocode-web.min.js:28:2
```

**Comment by vojtatranta** [comment]
This will be fixed any minute.

**Comment by vojtatranta** [comment]
Fix deployed.
