### ISSUE TITLE
Error Sync

### ISSUE THREAD

**Issue by mcarmenmg** [avocode/avocode#1817]
---
* **Version**: 2.17.2
* **Sketch plugin version**: 47.1.5
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 92744
---
```
Error: Command failed: "/Applications/Sketch.app/Contents/Resources/sketchtool/bin/sketchtool" dump --overwriting --use-id-for-name --formats="png" "/Users/mcarmenmartin/Dropbox/On Work/Auto.ad/DS18001 - auto.ad.sketch" > "/var/folders/8x/4m6qf0390xg09vgkpv3jsxd40000gn/T/sketch-avocode-full-dump.1516010786593.json"
Command threw exception

(ECCommandLineDomain:5)


    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

**Comment by bolekkerous** [comment]
Hey, @mcarmenmg  -
could you please send us the problematic Sketch file to team@avocode.com or in the in-app chat, so we can figure out what's the problem on our end?

Thanks and sorry for the inconvenience.

**Comment by jakubzitny** [comment]
Hi @mcarmenmg, we've just release Avocode 2.20.0 with improved Sketch plugin. Many issues should be fixed, try re-syncing Sketch files and please let us know if you're still having problems.
