### ISSUE TITLE
Just like to share my bug

### ISSUE THREAD

**Issue by TiloNN** [avocode/avocode#1819]
Tried to drag and drop two photoshop files into a new project.
Then I was asked to send a report.
Here we go.

---
* **Version**: 2.17.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 24209
---
```
Invariant Violation: Cannot call hover while not dragging.
    at Object.invariant [as default] (C:\Users\TNeumann\AppData\Local\avocode\app-2.17.2\resources\app.asar\node_modules\invariant\invariant.js:42:15)
    at DragDropManager.hover (C:\Users\TNeumann\AppData\Local\avocode\app-2.17.2\resources\app.asar\node_modules\dnd-core\lib\actions\dragDrop.js:116:25)
    at Object.hover (C:\Users\TNeumann\AppData\Local\avocode\app-2.17.2\resources\app.asar\node_modules\dnd-core\lib\DragDropManager.js:74:36)
    at HTML5Backend.handleTopDrop (C:\Users\TNeumann\AppData\Local\avocode\app-2.17.2\resources\app.asar\node_modules\react-dnd-html5-backend\lib\HTML5Backend.js:540:18)
    at wrapped (C:\Users\TNeumann\AppData\Local\avocode\app-2.17.2\resources\app.asar\node_modules\@avocode\stage\node_modules\raven-js\src\raven.js:351:21)
```

**Comment by vojtatranta** [comment]
Yes this is a known minor issue. We know about. We are going to fix it in the future.
