### ISSUE TITLE
can't open psd file on linux(part 2)

### ISSUE THREAD

**Issue by deckrow** [avocode/avocode#1820]
---
* **Version**: 2.17.2
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 238976
---
```
Error: Request aborted by the downloader process.
    at e._handleRequestAbort (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:2171678)
    at t.<anonymous> (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:2165049)
    at emitOne (events.js:96:13)
    at t.emit (events.js:191:7)
    at t._handleDownloaderEvent (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:2179620)
    at EventEmitter.<anonymous> (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:2176388)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

**Comment by jakubzitny** [comment]
Hi, thanks for the report again. How often is this happening, please? I'll close this with respect to  #1750. We're expecting to improve this behaviour by Avocode 3.0 version.

**Comment by deckrow** [comment]
Never mind
I just downloaded the latest version and now everything ok
Thx for the answer)
