### ISSUE TITLE
d

### ISSUE THREAD

**Issue by gulbas** [avocode/avocode#1831]
---
* **Version**: 2.18.0-web.1
* **Web/Desktop**: Web
* **Platform**: windows 10.0
* **Browser**: chrome 63.0.3239.132
* **Avocode UID**: 252492
---
```
TypeError: Cannot read property 'width' of undefined
    at e.value (https://cdn.app.avocode.com/dist/v-83b9b41/js/avocode-web.min.js:101:1333665)
    at t.describeLayers (https://cdn.app.avocode.com/dist/v-83b9b41/js/avocode-web.min.js:101:1372643)
    at e.value (https://cdn.app.avocode.com/dist/v-83b9b41/js/avocode-web.min.js:101:1595872)
    at e.value (https://cdn.app.avocode.com/dist/v-83b9b41/js/avocode-web.min.js:101:1594797)
    at n._handleShortcut (https://cdn.app.avocode.com/dist/v-83b9b41/js/avocode-web.min.js:101:1405284)
    at Object.handler (https://cdn.app.avocode.com/dist/v-83b9b41/js/avocode-web.min.js:101:1396468)
    at r._handleShortcuts (https://cdn.app.avocode.com/dist/v-83b9b41/js/avocode-web.min.js:54:133513)
    at e.exports [as fireCallback] (https://cdn.app.avocode.com/dist/v-83b9b41/js/avocode-web.min.js:54:140481)
    at e.exports [as handleKey] (https://cdn.app.avocode.com/dist/v-83b9b41/js/avocode-web.min.js:54:136942)
    at e.exports.r._combokeys.han
```

**Comment by jakubzitny** [comment]
Hi @gulbas, this bug should be already fixed in the latest version on web. Please let us know if you still get it or if you have any other problems.
