### ISSUE TITLE
Can not load rendering image data 188/188

### ISSUE THREAD

**Issue by Alex555555** [avocode/avocode#1833]
---
* **Version**: 2.18.1-web
* **Web/Desktop**: Web
* **Platform**: windows 6.1
* **Browser**: chrome 63.0.3239.132
* **Avocode UID**: 248945
---
```
RangeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation
    at Object.Rendering.Module.imageStorageAsBitmapRGBA (https://cdn.app.avocode.com/dist/v-6b29512/js/1.avocode-web.min.js:1:95496)
    at Array.Rendering.ASM_CONSTS (https://cdn.app.avocode.com/dist/v-6b29512/js/1.avocode-web.min.js:1:108717)
    at _emscripten_asm_const_ii (https://cdn.app.avocode.com/dist/v-6b29512/js/1.avocode-web.min.js:1:8649)
    at Array.v1 (https://cdn.app.avocode.com/dist/v-6b29512/js/1.avocode-web.min.js:1:8105137)
    at Array.IG (https://cdn.app.avocode.com/dist/v-6b29512/js/1.avocode-web.min.js:1:2386905)
    at Object.EEA [as dynCall_viiii] (https://cdn.app.avocode.com/dist/v-6b29512/js/1.avocode-web.min.js:1:8348301)
    at invoke_viiii (https://cdn.app.avocode.com/dist/v-6b29512/js/1.avocode-web.min.js:1:92960)
    at Array.fX (https://cdn.app.avocode.com/dist/v-6b29512/js/1.avocode-web.min.js:1:4393396)
    at Object.IuA [as dynCall_viiiiii
```

**Comment by Alex555555** [comment]
please help me

**Comment by vojtatranta** [comment]
Hello,
does it happen with every design?

**Comment by jakubzitny** [comment]
Closing with respect to #1567.

This is a problem with designs consuming too much memory in our rendering engine. We suggest splitting them to multiple designs and uploading separately. Or trying our desktop app,
