### ISSUE TITLE
Problem with sketch plugin

### ISSUE THREAD

**Issue by ahwest** [avocode/avocode#1838]
---
* **Version**: 2.18.2
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 145556
---
```
Error: Command failed: "/Applications/Avocode.app/Contents/Resources/AllApplications" -path "/Applications/Avocode.app/Contents/Resources/file.sketch"
Error: couldn't find any applications for path: /Applications/Avocode.app/Contents/Resources/file.sketch

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by jakubzitny** [comment]
Hi @Scofield001, thanks for reporting this. This looks like we have problems detecting your Sketch.app. Where is it located and which version do you have?

What do you get when you open Terminal.app and enter the following command, please?
```sh
/Applications/Avocode.app/Contents/Resources/AllApplications -path /Applications/Avocode.app/Contents/Resources/file.sketch
```

**Comment by jakubzitny** [comment]
Hi @Scofield001, this looks like we have problems detecting your Sketch.app. Where is it located and which version do you have?

What do you get when you open Terminal.app and enter the command above?

**Comment by jakubzitny** [comment]
Closing due to inactivity.
