### ISSUE TITLE
Lubuntu avocode error

### ISSUE THREAD

**Issue by qynonyq** [avocode/avocode#1843]
---
* **Version**: 2.18.2
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 262180
---
```
Invariant Violation: Cannot call hover while not dragging.
    at Object.invariant [as default] (/opt/Avocode/resources/app.asar/node_modules/invariant/invariant.js:42:15)
    at DragDropManager.hover (/opt/Avocode/resources/app.asar/node_modules/dnd-core/lib/actions/dragDrop.js:116:25)
    at Object.hover (/opt/Avocode/resources/app.asar/node_modules/dnd-core/lib/DragDropManager.js:74:36)
    at HTML5Backend.handleTopDrop (/opt/Avocode/resources/app.asar/node_modules/react-dnd-html5-backend/lib/HTML5Backend.js:540:18)
    at wrapped (/opt/Avocode/resources/app.asar/node_modules/@avocode/stage/node_modules/raven-js/src/raven.js:351:21)
```

**Comment by jakubzitny** [comment]
Hi @gideonwyeth, thanks for report. Most of the time, this means that you're uploading a design from an archive (zip, tar, etc.) that is not unpacked. We're tracking the problem in #1249. If this is the case, please unpack the archive manually and then upload the design(s).

This might also be happening in some special cases too, and all of them will be fixed in upcoming Avocode 2.19.0.
