### ISSUE TITLE
ECONNRESET error

### ISSUE THREAD

**Issue by vasilievruslan** [avocode/avocode#1845]
---
* **Version**: 2.18.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 57927
---
```
Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TLSWrap.onread (net.js:581:26)
```

**Comment by jankuca** [comment]
Hello, sorry to hear you encountered this issue and thanks for reporting it.

Were you doing anything unusual or can you provide any specific information which could help up investigate the problem? Was there anything not functioning properly or did this error just pop up without affecting the functioning of the app? Has is only happen once or repeatedly?

Thanks for any additional info.
