### ISSUE TITLE
Failed to execute 'shaderSource' on 'WebGLRenderingContext':

### ISSUE THREAD

**Issue by OlehVasyliev** [avocode/avocode#1846]
---
* **Version**: 2.18.2-web.1
* **Web/Desktop**: Web
* **Platform**: windows 10.0
* **Browser**: chrome 63.0.3239.132
* **Avocode UID**: 265146
---
```
TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.
    at _glShaderSource (https://cdn.app.avocode.com/dist/v-7fbf84e/js/1.avocode-web.min.js:1:62305)
    at Array.FD (https://cdn.app.avocode.com/dist/v-7fbf84e/js/1.avocode-web.min.js:1:2142520)
    at Object.iQA [as dynCall_iiiii] (https://cdn.app.avocode.com/dist/v-7fbf84e/js/1.avocode-web.min.js:1:8343396)
    at invoke_iiiii (https://cdn.app.avocode.com/dist/v-7fbf84e/js/1.avocode-web.min.js:1:92657)
    at Array.SP (https://cdn.app.avocode.com/dist/v-7fbf84e/js/1.avocode-web.min.js:1:4300358)
    at Object.vvA [as dynCall_iiii] (https://cdn.app.avocode.com/dist/v-7fbf84e/js/1.avocode-web.min.js:1:8354932)
    at invoke_iiii (https://cdn.app.avocode.com/dist/v-7fbf84e/js/1.avocode-web.min.js:1:86898)
    at Eg (https://cdn.app.avocode.com/dist/v-7fbf84e/js/1.avocode-web.min.js:1:1633283)
    at Array.ooA (https://cdn.app.avocode.com/dist/v-7fbf84e/js/1.avocode-web.min.j
```

**Comment by vojtatranta** [comment]
We noticed this bug in our tracking system. We will try to fix it in the next release.

**Comment by vojtatranta** [comment]
It seems that WebGL crashed on this occasion. We added a modal to handle this problem in `2.19.2`
