### ISSUE TITLE
Error while exporting assets

### ISSUE THREAD

**Issue by AlbertRAR** [avocode/avocode#1852]
---
* **Version**: 2.19.0
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 13249
---
```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at Object.cropTransparentPixels (/opt/Avocode/resources/app.asar/node_modules/@avocode/stage/dist/utils/canvas.js:1:2691)
    at t.export (/opt/Avocode/resources/app.asar/node_modules/@avocode/stage/dist/artboards/artboard.js:1:8694)
    at e.value (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:3650387)
    at e.exportLayers (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:3687042)
    at e._exportLayersToDirectory (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:3387973)
    at e._exportRuleVariantToDirectory (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:3386744)
    at wrapper (/opt/Avocode/resources/app.asar/node_modules/lodash/lodash.js:5232:19)
    at /opt/Avocode/resources/app.asar/node_modules/immutable/dist/immutable.js:3018:46
    at List.__iterate (/opt/Avocode/resources/app.asar/node_modules/immutable/dist/immutable.js:220
```

**Comment by vojtatranta** [comment]
Does it happen anytime when you try to export a layer?

**Comment by jakubzitny** [comment]
We're actually tracking this problem in #1833 already, let's continue the discussion over there.
