### ISSUE TITLE
App crashes when opening a design

### ISSUE THREAD

**Issue by connor-bean** [avocode/avocode#1857]
---
* **Version**: 2.19.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 21020
---
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new ArrayBuffer (C:\Users\pavel\AppData\Local\avocode\app-2.19.0\resources\app.asar\node_modules\core-js\modules\_typed-buffer.js:247:14)
    at Rendering (C:\Users\pavel\AppData\Local\avocode\app-2.19.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:1:23371)
    at Object.<anonymous> (C:\Users\pavel\AppData\Local\avocode\app-2.19.0\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:8407)
    at C:\Users\pavel\AppData\Local\avocode\app-2.19.0\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:1414
    at Object.next (C:\Users\pavel\AppData\Local\avocode\app-2.19.0\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:1519)
    at a (C:\Users\pavel\AppData\Local\avocode\app-2.19.0\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:286)
    at <anonymous>
```

**Comment by connor-bean** [comment]
From Intercom, but the user doesn't have GH so I opened it for him.

**Comment by vojtatranta** [comment]
that's duplicated with #1860
