### ISSUE TITLE
I can't open my progects' files

### ISSUE THREAD

**Issue by ViktoriaRudenko** [avocode/avocode#1860]
---
* **Version**: 2.19.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 245154
---
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new ArrayBuffer (C:\Users\User\AppData\Local\avocode\app-2.19.0\resources\app.asar\node_modules\core-js\modules\_typed-buffer.js:247:14)
    at Rendering (C:\Users\User\AppData\Local\avocode\app-2.19.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:1:23371)
    at Object.<anonymous> (C:\Users\User\AppData\Local\avocode\app-2.19.0\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:8407)
    at C:\Users\User\AppData\Local\avocode\app-2.19.0\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:1414
    at Object.next (C:\Users\User\AppData\Local\avocode\app-2.19.0\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:1519)
    at a (C:\Users\User\AppData\Local\avocode\app-2.19.0\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:286)
    at <anonymous>
```

**Comment by vojtatranta** [comment]
What's the size of your RAM?

**Comment by connor-bean** [comment]
Hello @ViktoriaRudenko - does updating to 2.19.1 solve this issue? We had another user report this same problem yesterday and they updated their Avocode app to 2.19.1 (which we released last night) and it worked for them.

Please let us know the result once you update to 2.19.1

**Comment by jakubzitny** [comment]
Closing with respect to #1867.
