### ISSUE TITLE
trying to export

### ISSUE THREAD

**Issue by overflood** [avocode/avocode#1861]
---
* **Version**: 2.19.0
* **Sketch plugin version**: 48.2.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 267083
---
```
TypeError: Cannot read property 'getSelectedLayerType' of undefined
    at t.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3404685)
    at t.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3403963)
    at new t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3400179)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:298:16)
    at ReactCompositeComponentWrapper._constructComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:285:19)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:188:21)
    at Object.mountComponent (/Applications/Avocode.app/Contents/Resources/app
```

**Comment by vojtatranta** [comment]
This should be fixed in `2.19.1`
