### ISSUE TITLE
what it!!???

### ISSUE THREAD

**Issue by ghost** [avocode/avocode#1864]
---
* **Version**: 2.19.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 130666
---
```
TypeError: Cannot read property 'getSelectedLayerType' of undefined
    at t.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3404685)
    at t.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3403963)
    at new t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3400179)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:298:16)
    at ReactCompositeComponentWrapper._constructComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:285:19)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:188:21)
    at Object.mountComponent (/Applications/Avocode.app/Contents/Resources/app
```

**Comment by ghost** [comment]
it appeared on the latest version, already two days, because of this is the work. we want quality for which we pay

**Comment by vojtatranta** [comment]
@Kaiot yes, we fully understand that our beloved customers want quality. That's why we released `2.19.0` like 42 hours ago and when we noticed this bug like 23 hours ago we released fix 15 hours ago along with many other bugfixes.

Therefore just update Avocode to `2.19.1` (update is available) and everything should work as expected. 

By the way. This update was available long before this bug happened to you. I am afraid that we are not able to find every single bug and sadly some of them make their way to production. That's we always try to fix the bug as fast as possible. In your case, we were fast enough, but your application did not manage to update. It was not probably restarted.

We are sorry for that, but we are trying so hard so this would not happen....

**Comment by ghost** [comment]
well I understand you guys, sorry if I was rude

**Comment by vojtatranta** [comment]
@Kaiot no you weren't rude. As I mentioned, we absolutely understand your frustration and therefore we did everything we could to fix it.

I'd be upset too!

We'll be glad if you report us any other bugs in the future. That's the only way we can fix them fast as possible 😉
