### ISSUE TITLE
Array buffer allocation failed

### ISSUE THREAD

**Issue by kapitonovmaxim** [avocode/avocode#1867]
---
* **Version**: 2.19.1
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 264197
---
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new ArrayBuffer (C:\Users\Max\AppData\Local\avocode\app-2.19.1\resources\app.asar\node_modules\core-js\modules\_typed-buffer.js:247:14)
    at Rendering (C:\Users\Max\AppData\Local\avocode\app-2.19.1\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:1:23371)
    at Object.<anonymous> (C:\Users\Max\AppData\Local\avocode\app-2.19.1\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:8407)
    at C:\Users\Max\AppData\Local\avocode\app-2.19.1\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:1414
    at Object.next (C:\Users\Max\AppData\Local\avocode\app-2.19.1\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:1519)
    at a (C:\Users\Max\AppData\Local\avocode\app-2.19.1\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:286)
    at <anonymous>
```

**Comment by vojtatranta** [comment]
Hi @trolololooo ,
what's the size of your RAM?

Did you try to open multiple designs at once?

**Comment by kapitonovmaxim** [comment]
No, I worked on one project for just over an hour. And after switching
between the windows in the layout, the entire image was lost
http://prntscr.com/icaw0a. I closed the project and tried to reopen it. And
got an error

size ram 3gb

**Comment by trolololooo** [comment]
size ram 3gb

2018-02-09 16:51 GMT+03:00 Maxim Kapitonov <kapitonovmaxim@gmail.com>:

**Comment by vojtatranta** [comment]
Aha, rendering of the design takes `500MB` that's the problem...
