### ISSUE TITLE
Export SVG from Sketch issue

### ISSUE THREAD

**Issue by Eugene-Musika** [avocode/avocode#1868]
---
* **Version**: 2.19.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 122136
---
```
TypeError: Cannot read property 'getSelectedLayerType' of undefined
    at t.value (file:///Applications/Developing/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3404685)
    at t.value (file:///Applications/Developing/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3403963)
    at new t (file:///Applications/Developing/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3400179)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (/Applications/Developing/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:298:16)
    at ReactCompositeComponentWrapper._constructComponent (/Applications/Developing/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:285:19)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/Developing/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:188:21)
    at Objec
```

**Comment by vojtatranta** [comment]
Hi @Eugene-Musika ,
this bug is already fixed in the `2.19.1` just update your app. This update is available since yesterday.
