### ISSUE TITLE
hmm

### ISSUE THREAD

**Issue by maxgolv** [avocode/avocode#1869]
---
* **Version**: 2.19.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 69185
---
```
TypeError: Cannot read property 'getSelectedLayerType' of undefined
    at t.value (file:///C:/Users/admin/AppData/Local/avocode/app-2.19.0/resources/app.asar/dist/avocode.min.js:1:3404685)
    at t.value (file:///C:/Users/admin/AppData/Local/avocode/app-2.19.0/resources/app.asar/dist/avocode.min.js:1:3403963)
    at new t (file:///C:/Users/admin/AppData/Local/avocode/app-2.19.0/resources/app.asar/dist/avocode.min.js:1:3400179)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (C:\Users\admin\AppData\Local\avocode\app-2.19.0\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:298:16)
    at ReactCompositeComponentWrapper._constructComponent (C:\Users\admin\AppData\Local\avocode\app-2.19.0\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:285:19)
    at ReactCompositeComponentWrapper.mountComponent (C:\Users\admin\AppData\Local\avocode\app-2.19.0\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:188:2
```

**Comment by vojtatranta** [comment]
hello @maxgolv,
this bug has been fixed in `2.19.1` just update your app.
