### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Ardogar** [avocode/avocode#1872]
---
* **Version**: 2.19.2
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 263123
---
```
TypeError: Cannot read property 'deinitializeOrchestrator' of null
    at t.finalize (/opt/Avocode/resources/app.asar/node_modules/@avocode/stage/dist/stage.js:1:11407)
    at e.value (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:3383584)
    at e.value (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:3383141)
    at destroy (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:3740486)
    at Immediate.<anonymous> (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:1219779)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by jakubzitny** [comment]
Hi @Ardogar, sorry to see this, we've already released a new version which fixes this problem. We've found it shortly after release. Please auto-update again, or if you have problems with it, re-install Avocode altogether. If you have any problem with updating you can manually download the latest Linux version from http://avocode.com/download.

Please let us know if you still have this problem.
