### ISSUE TITLE
Some Errors

### ISSUE THREAD

**Issue by MrVladevoit** [avocode/avocode#1874]
---
* **Version**: 2.19.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 15098
---
```
TypeError: Cannot read property 'deinitializeOrchestrator' of null
    at t.finalize (C:\Users\MrVLadevoit\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\@avocode\stage\dist\stage.js:1:11407)
    at e.value (file:///C:/Users/MrVLadevoit/AppData/Local/avocode/app-2.19.2/resources/app.asar/dist/avocode.min.js:1:3383584)
    at e.value (file:///C:/Users/MrVLadevoit/AppData/Local/avocode/app-2.19.2/resources/app.asar/dist/avocode.min.js:1:3383141)
    at destroy (file:///C:/Users/MrVLadevoit/AppData/Local/avocode/app-2.19.2/resources/app.asar/dist/avocode.min.js:1:3740486)
    at Immediate.<anonymous> (file:///C:/Users/MrVLadevoit/AppData/Local/avocode/app-2.19.2/resources/app.asar/dist/avocode.min.js:1:1219779)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by vojtatranta** [comment]
Hello @MrVladevoit ,
we are sorry for that we noticed this issue like minute after we released `2.19.2` so we rolled back but unfortunately it seems that your application managed to install this faulty `2.19.2`.

Here is working one: https://avocode-media.s3.amazonaws.com/download/avocode-app/2.19.2/Avocode%20Setup%202.19.2.exe
