### ISSUE TITLE
Failed to execute 'shaderSource' on 'WebGLRenderingContext'

### ISSUE THREAD

**Issue by SerhiiKo94** [avocode/avocode#1875]
---
* **Version**: 2.19.2-web.1
* **Web/Desktop**: Web
* **Platform**: windows 10.0
* **Browser**: chrome 63.0.3239.132
* **Avocode UID**: 270394
---
```
TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.
    at _glShaderSource (https://cdn.app.avocode.com/dist/v-b84d929/js/1.avocode-web.min.js:1:57312)
    at l2 (https://cdn.app.avocode.com/dist/v-b84d929/js/1.avocode-web.min.js:1:2365625)
    at r9 (https://cdn.app.avocode.com/dist/v-b84d929/js/1.avocode-web.min.js:1:2801530)
    at Array.rn (https://cdn.app.avocode.com/dist/v-b84d929/js/1.avocode-web.min.js:1:964407)
    at c9 (https://cdn.app.avocode.com/dist/v-b84d929/js/1.avocode-web.min.js:1:2812973)
    at fL (https://cdn.app.avocode.com/dist/v-b84d929/js/1.avocode-web.min.js:1:1912915)
    at daA (https://cdn.app.avocode.com/dist/v-b84d929/js/1.avocode-web.min.js:1:3427659)
    at FdA (https://cdn.app.avocode.com/dist/v-b84d929/js/1.avocode-web.min.js:1:7111009)
    at VuA (https://cdn.app.avocode.com/dist/v-b84d929/js/1.avocode-web.min.js:1:3956826)
    at VuA (https://cdn.app.avocode.com/dist/v-b84d929/js/1.avocod
```

**Comment by vojtatranta** [comment]
Hi @SerhiiKo94 ,
did a WebGL crashed modal poped up?

**Comment by jakubzitny** [comment]
Hi @SerhiiKo94 , did a WebGL crashed modal poped up? Have you tried our desktop version?
