### ISSUE TITLE
avacode has crashed

### ISSUE THREAD

**Issue by ViktorSh25** [avocode/avocode#1878]
---
* **Version**: 2.19.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 271620
---
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new ArrayBuffer (C:\Users\Victor\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\core-js\modules\_typed-buffer.js:247:14)
    at Rendering (C:\Users\Victor\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:1:23388)
    at Object.<anonymous> (C:\Users\Victor\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:8640)
    at C:\Users\Victor\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:1414
    at Object.next (C:\Users\Victor\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:1519)
    at s (C:\Users\Victor\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:286)
    at <anonymous>
```

**Comment by vojtatranta** [comment]
Hi @ViktorSh25 ,
it seems you machine has low memory. You can for now disable Monroe egine in app preferences which should resolve this issue for now.
