### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by mrybakov** [avocode/avocode#1880]
---
* **Version**: 2.19.2
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 23647
---
```
TypeError: n.get is not a function
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1251001)
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1250610)
    at t.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1851092)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1851600
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3018:46
    at List.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3017:23)
    at seqIterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:606:16)
    at IndexedIterable.
```

**Comment by mrybakov** [comment]
Need to remove ~/.avocode directory

**Comment by jakubzitny** [comment]
Hi @mrybakov, did everything work after removing the avocode dir?

**Comment by jakubzitny** [comment]
Hi @mrybakov, did everything work after removing the avocode dir?

**Comment by jakubzitny** [comment]
This should be fixed in latest versions of Avocode, please let us know if you see it again 😉
