### ISSUE TITLE
don't load psd file

### ISSUE THREAD

**Issue by vladchepel** [avocode/avocode#1886]
---
* **Version**: 2.19.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 269727
---
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new ArrayBuffer (C:\Users\Vlad\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\core-js\modules\_typed-buffer.js:247:14)
    at Rendering (C:\Users\Vlad\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:1:23388)
    at Object.<anonymous> (C:\Users\Vlad\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:8640)
    at C:\Users\Vlad\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:1414
    at Object.next (C:\Users\Vlad\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:1519)
    at s (C:\Users\Vlad\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:286)
    at <anonymous>
```

**Comment by vojtatranta** [comment]
hi @vladchepel ,
what's the size of your RAM?

**Comment by vladchepel** [comment]
@vojtatranta, 4gb.
I have to restart avocode to make it work

**Comment by vladchepel** [comment]
@vojtatranta I can load only 1 file, when I want to load 2nd file it shows an error.

**Comment by jakubzitny** [comment]
Closing with respect to #1867. We're improving performance in cases that are causing this, I hope will release it soon.
