### ISSUE TITLE
not loading the page

### ISSUE THREAD

**Issue by shiwamavg** [avocode/avocode#1888]
---
* **Version**: 2.19.2-web.2
* **Web/Desktop**: Web
* **Platform**: windows 6.2
* **Browser**: chrome 64.0.3282.167
* **Avocode UID**: 262324
---
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new _ (https://cdn.app.avocode.com/dist/v-3394921/js/avocode-web.min.js:28:471630)
    at Rendering (https://cdn.app.avocode.com/dist/v-3394921/js/1.avocode-web.min.js:1:81498)
    at Object.<anonymous> (https://cdn.app.avocode.com/dist/v-3394921/js/avocode-web.min.js:65:27030)
    at https://cdn.app.avocode.com/dist/v-3394921/js/avocode-web.min.js:65:28124
    at Object.next (https://cdn.app.avocode.com/dist/v-3394921/js/avocode-web.min.js:65:28229)
    at a (https://cdn.app.avocode.com/dist/v-3394921/js/avocode-web.min.js:65:27213)
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @shiwamavg, thanks for the report. We're already tracking this in #1867.

Is this happening to all designs you're trying to open and all the time?
