### ISSUE TITLE
something went wrong

### ISSUE THREAD

**Issue by kuziv-andrii** [avocode/avocode#1890]
---
* **Version**: 2.19.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 27409
---
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new ArrayBuffer (C:\Users\Andriy\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\core-js\modules\_typed-buffer.js:247:14)
    at Rendering (C:\Users\Andriy\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:1:23388)
    at Object.<anonymous> (C:\Users\Andriy\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:8640)
    at C:\Users\Andriy\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:1414
    at Object.next (C:\Users\Andriy\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:1519)
    at s (C:\Users\Andriy\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:286)
    at <anonymous>
```

**Comment by vojtatranta** [comment]
Hi @kuziv-andriy ,
what's you system? Is it 64bit and what's the size of your RAM? 

This is the first design you tried to open or did you have some other designs in other tabs?

**Comment by kuziv-andrii** [comment]
Hi! I am using win 10, 64 bit / 8Gb RAM.

~4-5 tabs was opened.

**Comment by vojtatranta** [comment]
@kuziv-andriy I see...

That's the problem. Avocode allocates 500MB per design in the rendering engine. We would like to share this memory among designs, but we are not there yet...

So now I can just recommend you not to open this number of designs to prevent this error.
