### ISSUE TITLE
page doesn't work

### ISSUE THREAD

**Issue by sikoray** [avocode/avocode#1892]
---
* **Version**: 2.19.2-web.2
* **Web/Desktop**: Web
* **Platform**: linux -1
* **Browser**: chrome 61.0.3163.100
* **Avocode UID**: 271169
---
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new _ (https://cdn.app.avocode.com/dist/v-3394921/js/avocode-web.min.js:28:471630)
    at Rendering (https://cdn.app.avocode.com/dist/v-3394921/js/1.avocode-web.min.js:1:81498)
    at Object.<anonymous> (https://cdn.app.avocode.com/dist/v-3394921/js/avocode-web.min.js:65:27030)
    at https://cdn.app.avocode.com/dist/v-3394921/js/avocode-web.min.js:65:28124
    at Object.next (https://cdn.app.avocode.com/dist/v-3394921/js/avocode-web.min.js:65:28229)
    at a (https://cdn.app.avocode.com/dist/v-3394921/js/avocode-web.min.js:65:27213)
    at <anonymous>
```

**Comment by vojtatranta** [comment]
Seems like you can't open a design, right? However project manager works, right?

**Comment by jakubzitny** [comment]
Closing with respect to #1867.
