### ISSUE TITLE
Error Report Ubuntu 16.04 

### ISSUE THREAD

**Issue by jtiberio-sv** [avocode/avocode#1894]
---
* **Version**: 2.19.2
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: null
---
```
Error: Missing history object for workspace item ID=2e85a9c8-ef53-49d8-b5e3-ba806ffe8485. Available histories: 59a795fd-832a-499f-9234-fd0c42fd88e7
    at t.value (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:1221032)
    at c (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:1219038)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by vojtatranta** [comment]
Hi @jptiberio ,
we know about this issue and it should be fixed in `2.20.0`
