### ISSUE TITLE
An Error, unexplained, and nothing was affected....... but an error nevertheless 

### ISSUE THREAD

**Issue by ultimate-rob** [avocode/avocode#1896]
---
* **Version**: 2.19.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 209407
---
```
TypeError: Cannot read property 'deinitializeOrchestrator' of null
    at t.finalize (C:\Users\rob\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\@avocode\stage\dist\stage.js:1:11407)
    at e.value (file:///C:/Users/rob/AppData/Local/avocode/app-2.19.2/resources/app.asar/dist/avocode.min.js:1:3383584)
    at e.value (file:///C:/Users/rob/AppData/Local/avocode/app-2.19.2/resources/app.asar/dist/avocode.min.js:1:3383141)
    at destroy (file:///C:/Users/rob/AppData/Local/avocode/app-2.19.2/resources/app.asar/dist/avocode.min.js:1:3740486)
    at Immediate.<anonymous> (file:///C:/Users/rob/AppData/Local/avocode/app-2.19.2/resources/app.asar/dist/avocode.min.js:1:1219779)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by jakubzitny** [comment]
Hi @ultimate-rob, this should be fixed in latest Avocode 2.20. Please update and let us know if you have any more problems 😉
