### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ValeriyKobysh** [avocode/avocode#1898]
---
* **Version**: 2.19.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 192151
---
```
TypeError: Cannot read property 'deinitializeOrchestrator' of null
    at t.finalize (C:\Users\valer\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\@avocode\stage\dist\stage.js:1:11407)
    at e.value (file:///C:/Users/valer/AppData/Local/avocode/app-2.19.2/resources/app.asar/dist/avocode.min.js:1:3383584)
    at e.value (file:///C:/Users/valer/AppData/Local/avocode/app-2.19.2/resources/app.asar/dist/avocode.min.js:1:3383141)
    at destroy (file:///C:/Users/valer/AppData/Local/avocode/app-2.19.2/resources/app.asar/dist/avocode.min.js:1:3740486)
    at Immediate.<anonymous> (file:///C:/Users/valer/AppData/Local/avocode/app-2.19.2/resources/app.asar/dist/avocode.min.js:1:1219779)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by vojtatranta** [comment]
This bug happened in a "wrong" release of 2.19.2 please download correct version [from here](https://avocode.com/download).
