### ISSUE TITLE
Error when zooming 

### ISSUE THREAD

**Issue by sebous** [avocode/avocode#1905]
---
* **Version**: 2.19.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 198902
---
```
TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (C:\Users\BS\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\react-dom\lib\ReactReconciler.js:63:28)
    at ReactCompositeComponentWrapper.getHostNode (C:\Users\BS\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:384:28)
    at Object.getHostNode (C:\Users\BS\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\react-dom\lib\ReactReconciler.js:63:29)
    at Object.updateChildren (C:\Users\BS\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\react-dom\lib\ReactChildReconciler.js:113:48)
    at ReactDOMComponent._reconcilerUpdateChildren (C:\Users\BS\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\react-dom\lib\ReactMultiChild.js:213:28)
    at ReactDOMComponent._updateChildren (C:\Users\BS\AppData\Local\avocode\app-2.19.2\resources\app.asar\node_modules\react-dom\lib\ReactMultiChild.js:312:31
```

**Comment by sebous** [comment]
Also when panning with mouse holding spacebar

**Comment by jakubzitny** [comment]
Hi @sebous, thanks for reporting this. We've just released new version 2.20.0, can you please try to see if it's happening there as well? We'll investigate internally in the meantime..

**Comment by vojtatranta** [comment]
`2.21.0` released

**Comment by sebous** [comment]
Hi, all the issues disappeared now, thanks. Keep up the good work 👍
