### ISSUE TITLE
1

### ISSUE THREAD

**Issue by fufylev** [avocode/avocode#1908]
---
* **Version**: 2.20.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 268245
---
```
TypeError: Failed to execute 'attachShader' on 'WebGLRenderingContext': parameter 2 is not of type 'WebGLShader'.
    at _glAttachShader (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/rendering-emscripten/rendering-asm.js:1:625212)
    at sC (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/rendering-emscripten/rendering-asm.js:7:107345)
    at xu (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/rendering-emscripten/rendering-asm.js:8:150960)
    at Array._S (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/rendering-emscripten/rendering-asm.js:5:304901)
    at Eu (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/rendering-emscripten/rendering-asm.js:8:161885)
    at fta (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/rendering-emscripten/rendering-asm.js:6:580446)
    at vo (/Applications/Avocode.app/Contents/Resources/
```

**Comment by jakubzitny** [comment]
Hi @fufylev, thanks for reporting this problem. It seems that our rendering engine has problems with WebGL in some specific cases. We're already tracking a similar problem in #1875, so I am going to close this.

However, could you please give us more hints on when is this happening? Is it when you're opening a design or when exporting something? Does it happen to all designs or only with one specific design?

In the meantime can you please try our web version at https://app.avocode.com to see if it works there? You can use Safari, Chrome or Firefox.

Thanks 😉
