### ISSUE TITLE
Can't copy text 

### ISSUE THREAD

**Issue by leob0ss** [avocode/avocode#1912]
---
* **Version**: 2.20.0
* **Sketch plugin version**: 48.2.8
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 257566
---
```
Invariant Violation: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bdata%2C%20encoding%2C%20%3Cclass%3E%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at reactProdInvariant (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/reactProdInvariant.js:31:15)
    at traverseAllChildrenImpl (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/traverseAllChildren.js:144:261)
    at traverseAllChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/traverseAllChildren.js:172:10)
    at Object.instantiateChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactChildReconciler.js:74:7)
    at ReactDOMComponent._reconcilerInstantiateChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modu
```

**Comment by jakubzitny** [comment]
Hi @leob0ss, thanks for the report. We're already tracking a similar problem in #1790 so I am going to close this thread. However, would you be so kind and provide us with more info? When exactly is this happening? Does it happen to all layers you're trying to copy text from? Or only in a specific layer in a specific file?

Maybe recording a video of the bug would help us.

Thanks a lot 😉
