### ISSUE TITLE
screnarion 4 testing click on tab more times

### ISSUE THREAD

**Issue by vAhyThe** [avocode/avocode#1917]
---
* **Version**: 3.0.0-public-testing.1
* **Web/Desktop**: Web
* **Platform**: macosx 10.13.3
* **Browser**: chrome 64.0.3282.186
* **Avocode UID**: 9431
---
```
TypeError: Cannot read property 'requestAnimationFrame' of null
    at A (https://fast.appcues.com/24524.js:1:26847)
    at r (https://fast.appcues.com/24524.js:1:62295)
    at https://fast.appcues.com/24524.js:1:115122
    at https://fast.appcues.com/24524.js:1:26779
    at r (https://cdn.app.avcd.cz/dist/v-dc6290b/js/avocode-web.min.js:60:18503)
```

**Comment by jakubzitny** [comment]
Thanks, entering into our internal tracking system. Will be fixed for 3.0.
