### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by kaisee** [avocode/avocode#1927]
---
* **Version**: 2.21.0-web.1
* **Web/Desktop**: Web
* **Platform**: linux -1
* **Browser**: chrome 62.0.3202.75
* **Avocode UID**: 249614
---
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new _ (https://cdn.app.avocode.com/dist/v-e8469e3/js/avocode-web.min.js:28:479593)
    at Rendering (https://cdn.app.avocode.com/dist/v-e8469e3/js/2.avocode-web.min.js:1:81605)
    at Object.<anonymous> (https://cdn.app.avocode.com/dist/v-e8469e3/js/avocode-web.min.js:65:27491)
    at https://cdn.app.avocode.com/dist/v-e8469e3/js/avocode-web.min.js:65:28586
    at Object.next (https://cdn.app.avocode.com/dist/v-e8469e3/js/avocode-web.min.js:65:28691)
    at a (https://cdn.app.avocode.com/dist/v-e8469e3/js/avocode-web.min.js:65:27675)
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @kaisee, thanks for the report. We're already tracking this in #1867.

Is this happening to all designs you're trying to open and all the time?
