### ISSUE TITLE
bug with opening sketch

### ISSUE THREAD

**Issue by romaniv1024** [avocode/avocode#1929]
---
* **Version**: 2.20.1
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 130394
---
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new ArrayBuffer (C:\Users\USER\AppData\Local\avocode\app-2.20.1\resources\app.asar\node_modules\core-js\modules\_typed-buffer.js:247:14)
    at Rendering (C:\Users\USER\AppData\Local\avocode\app-2.20.1\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:1:23388)
    at Object.<anonymous> (C:\Users\USER\AppData\Local\avocode\app-2.20.1\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:8670)
    at C:\Users\USER\AppData\Local\avocode\app-2.20.1\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:1414
    at Object.next (C:\Users\USER\AppData\Local\avocode\app-2.20.1\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:1519)
    at s (C:\Users\USER\AppData\Local\avocode\app-2.20.1\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:286)
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @romaniv1024, thanks for the report. We're already tracking this in #1867.

Is this happening to all designs you're trying to open and all the time?
