### ISSUE TITLE
Clicking on Sync

### ISSUE THREAD

**Issue by miguelcalderons** [avocode/avocode#1930]
---
* **Version**: 2.21.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 228262
---
```
TypeError: Failed to execute 'attachShader' on 'WebGLRenderingContext': parameter 2 is not of type 'WebGLShader'.
    at _glAttachShader (C:\Users\migue\AppData\Local\avocode\app-2.21.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:1:625212)
    at sC (C:\Users\migue\AppData\Local\avocode\app-2.21.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:7:107345)
    at qA (C:\Users\migue\AppData\Local\avocode\app-2.21.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:8:600835)
    at d1 (C:\Users\migue\AppData\Local\avocode\app-2.21.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:6:3874)
    at QB (C:\Users\migue\AppData\Local\avocode\app-2.21.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:7:73534)
    at eA (C:\Users\migue\AppData\Local\avocode\app-2.21.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.j
```

**Comment by jakubzitny** [comment]
Hi @miguelcalderons, thanks for reporting this problem. It seems that our rendering engine has problems with WebGL in some specific cases. We're already tracking a similar problem in #1875, so I am going to close this.

However, could you please give us more hints on when is this happening? Is it when you're opening a design or when exporting something? Does it happen to all designs or only with one specific design?

In the meantime can you please try our web version at https://app.avocode.com to see if it works there? You can use Safari, Chrome or Firefox.

Thanks 😉
