### ISSUE TITLE
overall slowdown and unknown crush issues

### ISSUE THREAD

**Issue by wapec** [avocode/avocode#1931]
---
* **Version**: 2.21.0
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 124843
---
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new ArrayBuffer (/home/wapec/programs/avocode-2.21.0-linux/resources/app.asar/node_modules/core-js/modules/_typed-buffer.js:247:14)
    at Rendering (/home/wapec/programs/avocode-2.21.0-linux/resources/app.asar/node_modules/@avocode/rendering-emscripten/rendering-asm.js:1:23388)
    at Object.<anonymous> (/home/wapec/programs/avocode-2.21.0-linux/resources/app.asar/node_modules/@avocode/stage/dist/rendering.js:1:8670)
    at /home/wapec/programs/avocode-2.21.0-linux/resources/app.asar/node_modules/@avocode/stage/dist/rendering.js:1:1414
    at Object.next (/home/wapec/programs/avocode-2.21.0-linux/resources/app.asar/node_modules/@avocode/stage/dist/rendering.js:1:1519)
    at s (/home/wapec/programs/avocode-2.21.0-linux/resources/app.asar/node_modules/@avocode/stage/dist/rendering.js:1:286)
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @wapec, thanks for the report. We're already tracking this in #1867 so I am going to close this.

Is this happening to all designs you're trying to open and all the time?

The thing is that our new rendering consumes a bit more memory for designs. We'll be releasing more optimized rendering in the next Avocode version. However, if you do not have a lot of memory, you'll need to have less designs open at the same time.
