### ISSUE TITLE
ReferenceError: ga is not defined

### ISSUE THREAD

**Issue by oguilleux** [avocode/avocode#1933]
---
* **Version**: 2.21.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 142964
---
```
ReferenceError: ga is not defined
    at Object.pageview (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2049682)
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:322437)
    at e._trackUriChange (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:491861)
    at e.redirectActiveItemToUri (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:486693)
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:841092)
    at Object.r._handleEntityOpen [as onRequestOpen] (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:769521)
    at Object.r._handleDoubleClick [as onDoubleClick] (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1886937)
    at Object.r._handleDoubleClick [as onDoubleClick] (file:///Applications/Avocode.app/Contents/Resou
```

**Comment by jakubzitny** [comment]
Hi @oguilleux, thanks for the report. We've seen a similar problem in #1568. It's a weird error, do you have any more details on how did you get it? You probably have problems starting the app at all, right? How did you download/install Avocode? Is it your first time or did the previous versions work for you? Or did it just happen once and otherwise everything works?

**Comment by jakubzitny** [comment]
Hi @oguilleux, thanks for the report. We've seen a similar problem in #1568. It's a weird error, do you have any more details on how did you get it? You probably have problems starting the app at all, right? How did you download/install Avocode? Is it your first time or did the previous versions work for you? Or did it just happen once and otherwise everything works?

**Comment by jakubzitny** [comment]
Closing due to inactivity, let us know if you still have problems.
