### ISSUE TITLE
Issue while creating annotation

### ISSUE THREAD

**Issue by LAKnoKAL** [avocode/avocode#1940]
---
* **Version**: 2.21.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 37333
---
```
TypeError: Cannot read property 'update' of undefined
    at editOnBeforeInput (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/draft-js/lib/editOnBeforeInput.js:101:11)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/draft-js/lib/DraftEditor.react.js:146:19
    at Object.invokeGuardedCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactErrorUtils.js:26:5)
    at executeDispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/EventPluginUtils.js:85:21)
    at Object.executeDispatchesInOrder (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/EventPluginUtils.js:108:5)
    at executeDispatchesAndRelease (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/EventPluginHub.js:43:22)
    at executeDispatchesAndReleaseTopLevel (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/EventP
```

**Comment by jakubzitny** [comment]
Hi @LAKnoKAL, thanks for the report. Is this happening all the time or only once? Any further details? Did you try annotating other design?

**Comment by LAKnoKAL** [comment]
@jakubzitny Happened only once while typing in new annotation and cannot reproduce it one more time. Feel free to close :)
