### ISSUE TITLE
11

### ISSUE THREAD

**Issue by hhjxiaoyin** [avocode/avocode#1942]
---
* **Version**: 2.21.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 294025
---
```
TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.
    at _glShaderSource (C:\ProgramData\何慧娟\avocode\app-2.21.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:1:661004)
    at SG (C:\ProgramData\何慧娟\avocode\app-2.21.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:7:369240)
    at xu (C:\ProgramData\何慧娟\avocode\app-2.21.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:8:150901)
    at Array._S (C:\ProgramData\何慧娟\avocode\app-2.21.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:5:304901)
    at rj (C:\ProgramData\何慧娟\avocode\app-2.21.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:11:560113)
    at Aj (C:\ProgramData\何慧娟\avocode\app-2.21.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:11:592451)
    at og (C:\ProgramData\何慧娟\avocode
```

**Comment by jakubzitny** [comment]
Hi @hhjxiaoyin, thanks for reporting this problem. It seems that our rendering engine has problems with WebGL in some specific cases. We're already tracking a similar problem in #1875, so I am going to close this.

However, could you please give us more hints on when is this happening? Is it when you're opening a design or when exporting something? Does it happen to all designs or only with one specific design?

In the meantime can you please try our web version at https://app.avocode.com to see if it works there? You can use Safari, Chrome or Firefox.

Thanks 😉
