### ISSUE TITLE
?

### ISSUE THREAD

**Issue by oleg291291** [avocode/avocode#1943]
---
* **Version**: 2.21.0-web.2
* **Web/Desktop**: Web
* **Platform**: windows 6.1
* **Browser**: chrome 65.0.3325.181
* **Avocode UID**: 296170
---
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new _ (https://cdn.app.avocode.com/dist/v-9a463e2/js/avocode-web.min.js:28:479593)
    at Rendering (https://cdn.app.avocode.com/dist/v-9a463e2/js/2.avocode-web.min.js:1:81605)
    at Object.<anonymous> (https://cdn.app.avocode.com/dist/v-9a463e2/js/avocode-web.min.js:65:27491)
    at https://cdn.app.avocode.com/dist/v-9a463e2/js/avocode-web.min.js:65:28586
    at Object.next (https://cdn.app.avocode.com/dist/v-9a463e2/js/avocode-web.min.js:65:28691)
    at a (https://cdn.app.avocode.com/dist/v-9a463e2/js/avocode-web.min.js:65:27675)
```

**Comment by jakubzitny** [comment]
Hi @oleg291291, thanks for the report. We're already tracking this in #1867 so I am going to close this.

Is this happening to all designs you're trying to open and all the time?

The thing is that our new rendering consumes a bit more memory for designs. We'll be releasing more optimized rendering in the next Avocode version. However, if you do not have a lot of memory, you'll need to have less designs open at the same time.
