### ISSUE TITLE
I was trying to change px to rem

### ISSUE THREAD

**Issue by n1kko777** [avocode/avocode#1948]
---
* **Version**: 2.21.0
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 293327
---
```
TypeError: Failed to execute 'attachShader' on 'WebGLRenderingContext': parameter 2 is not of type 'WebGLShader'.
    at _glAttachShader (/home/nikita/apps/Avocode/resources/app.asar/node_modules/@avocode/rendering-emscripten/rendering-asm.js:1:625212)
    at sC (/home/nikita/apps/Avocode/resources/app.asar/node_modules/@avocode/rendering-emscripten/rendering-asm.js:7:107345)
    at xu (/home/nikita/apps/Avocode/resources/app.asar/node_modules/@avocode/rendering-emscripten/rendering-asm.js:8:150960)
    at Array._S (/home/nikita/apps/Avocode/resources/app.asar/node_modules/@avocode/rendering-emscripten/rendering-asm.js:5:304901)
    at rj (/home/nikita/apps/Avocode/resources/app.asar/node_modules/@avocode/rendering-emscripten/rendering-asm.js:11:560113)
    at Aj (/home/nikita/apps/Avocode/resources/app.asar/node_modules/@avocode/rendering-emscripten/rendering-asm.js:11:592451)
    at og (/home/nikita/apps/Avocode/resources/app.asar/node_modules/@avocode/rendering-emscripten/rendering-
```

**Comment by jakubzitny** [comment]
Hi @n1kko777, thanks for reporting this problem. It seems that our rendering engine has problems with WebGL in some specific cases. We're already tracking a similar problem in #1875, so I am going to close this.

However, could you please give us more hints on when is this happening? Is it when you're opening a design or when exporting something? Does it happen to all designs or only with one specific design?

In the meantime can you please try our web version at https://app.avocode.com to see if it works there? You can use Safari, Chrome or Firefox.

Thanks
