### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by emircanpekyurek** [avocode/avocode#1951]
---
* **Version**: 2.21.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 71500
---
```
TypeError: Failed to execute 'attachShader' on 'WebGLRenderingContext': parameter 2 is not of type 'WebGLShader'.
    at _glAttachShader (C:\Users\Emircan\AppData\Local\avocode\app-2.21.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:1:625212)
    at sC (C:\Users\Emircan\AppData\Local\avocode\app-2.21.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:7:107345)
    at xu (C:\Users\Emircan\AppData\Local\avocode\app-2.21.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:8:150960)
    at Array._S (C:\Users\Emircan\AppData\Local\avocode\app-2.21.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:5:304901)
    at Eu (C:\Users\Emircan\AppData\Local\avocode\app-2.21.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:8:161885)
    at fta (C:\Users\Emircan\AppData\Local\avocode\app-2.21.0\resources\app.asar\node_modules\@avocode\rendering-emsc
```

**Comment by jakubzitny** [comment]
Hi @emircanpekyurek, thanks for reporting this problem. It seems that our rendering engine has problems with WebGL in some specific cases. We're already tracking a similar problem in #1875, so I am going to close this.

However, could you please give us more hints on when is this happening? Is it when you're opening a design or when exporting something? Does it happen to all designs or only with one specific design?

In the meantime can you please try our web version at https://app.avocode.com to see if it works there? You can use Safari, Chrome or Firefox.

Thanks 😉

**Comment by emircanpekyurek** [comment]
In application the designs are opening very slowly. Sometimes not open.

2018-03-28 14:39 GMT+03:00 Jakub Žitný <notifications@github.com>:

**Comment by jakubzitny** [comment]
Yeah, can you try our web version? It might be faster for you.

**Comment by emircanpekyurek** [comment]
ok

2018-03-28 14:43 GMT+03:00 Jakub Žitný <notifications@github.com>:
