### ISSUE TITLE
whats happened? 

### ISSUE THREAD

**Issue by onuralpb** [avocode/avocode#1970]
---
* **Version**: 2.22.1
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 5322
---
```
TypeError: Failed to execute 'attachShader' on 'WebGLRenderingContext': parameter 2 is not of type 'WebGLShader'.
    at _glAttachShader (C:\Users\obaklaci.HURRIYET\AppData\Local\avocode\app-2.22.1\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:1:625344)
    at vC (C:\Users\obaklaci.HURRIYET\AppData\Local\avocode\app-2.22.1\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:7:110912)
    at xu (C:\Users\obaklaci.HURRIYET\AppData\Local\avocode\app-2.22.1\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:8:150988)
    at Array.dT (C:\Users\obaklaci.HURRIYET\AppData\Local\avocode\app-2.22.1\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:5:310063)
    at Eu (C:\Users\obaklaci.HURRIYET\AppData\Local\avocode\app-2.22.1\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:8:161913)
    at qta (C:\Users\obaklaci.HURRIYET\AppData\Local\avocode\app-2.
```

**Comment by jakubzitny** [comment]
Hi @onuralpb, thanks for reporting this problem. It seems that our rendering engine has problems with WebGL in some specific cases. We're already tracking a similar problem in #1875, so I am going to close this.

However, could you please give us more hints on when is this happening? Is it when you're opening a design or when exporting something? Does it happen to all designs or only with one specific design?

In the meantime can you please try our web version at https://app.avocode.com to see if it works there? You can use Safari, Chrome or Firefox.

Thanks 😉

**Comment by onuralpb** [comment]
I was trying to open a sketch file. I guess I tried to open two artboards at the same time. The program has restarted itself. I may have tried to open it very quickly, but I've been doing this before and it's not a problem. We want to see the artboards in the sketch files as thumbnails ... before the file opens.

**Comment by jakubzitny** [comment]
So it only happened once?

Also do you have problems seeing thumbnails? Can you send us a screenshot of what are you seeing?
