### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Roman-wst** [avocode/avocode#1975]
---
* **Version**: 2.23.0
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 287056
---
```
TypeError: Cannot read property 'documentRevisionId' of undefined
    at e.setGuideVisibility (file:///home/roman/avocode_corp/resources/app.asar/dist/avocode.min.js:1:2947019)
    at e.toggleGuideVisibility (file:///home/roman/avocode_corp/resources/app.asar/dist/avocode.min.js:1:2947320)
    at Object.r._handleShortcut [as handler] (file:///home/roman/avocode_corp/resources/app.asar/dist/avocode.min.js:1:4027780)
    at _this._handleShortcuts (/home/roman/avocode_corp/resources/app.asar/node_modules/react-shortcuts/lib/component/shortcuts.js:160:23)
    at module.exports [as fireCallback] (/home/roman/avocode_corp/resources/app.asar/node_modules/combokeys/Combokeys/prototype/fireCallback.js:24:7)
    at module.exports [as handleKey] (/home/roman/avocode_corp/resources/app.asar/node_modules/combokeys/Combokeys/prototype/handleKey.js:61:12)
    at module.exports._this._combokeys.handleKey (/home/roman/avocode_corp/resources/app.asar/node_modules/react-shortcuts/lib/component/shortcuts.
```

When I open more than 4 psd layouts, my laptop starts to brake wildly .. (i5, 4X1.6, 8Gb memory, SSD)

**Comment by jakubzitny** [comment]
Hi @Roman-wst, thanks for the report. We know about this problem, we'll resolve this asap.

**Comment by jakubzitny** [comment]
Hi @Roman-wst, this should be fixed in the latest version of Avocode. Please update and let us know if you have any more problems :wink:

**Comment by Roman-wst** [comment]
Hi @jakubzitny, should be fixed: TypeError or 'When I open more than 4 psd layouts, my laptop starts to brake wildly .. '? Thanks.

**Comment by jakubzitny** [comment]
The TypeError.

Regarding the performance, we're using a certain amount of memory for the rendering of each tab (and the design in it). We're also using Electron framework which is based on Chromium and uses some memory itself so with combination of other similar apps (like Chrome / Spotify / Slack and similar ones) you might see the PC slowing down with 8GB of memory. So I suggest using less tabs open at the same time in Avocode.

One more thing, that would actually help us: Can you compare the performance footprint of Avocode when you use our desktop app and when you use https://app.avocode.com in Chrome/Chromium?

We keep improving our rendering performance with each version so it should be getting better and better, but we'll still need some resources for the rendering and stuff..

**Comment by Roman-wst** [comment]
More freezes when in chrome. But after the last update everything is fine. Sorry for such a long silence. I will keep you informed.
If you need to test write, help Goth.

**Comment by Roman-wst** [comment]
In general, I wanted to thank you, for Avocode. Very satisfied!))
