### ISSUE TITLE
problem with rendering

### ISSUE THREAD

**Issue by pilotocheg** [avocode/avocode#1976]
---
* **Version**: 2.22.1
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 302446
---
```
TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.
    at _glShaderSource (C:\Users\User\AppData\Local\avocode\app-2.22.1\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:1:661136)
    at VG (C:\Users\User\AppData\Local\avocode\app-2.22.1\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:7:372808)
    at xu (C:\Users\User\AppData\Local\avocode\app-2.22.1\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:8:150929)
    at dT (C:\Users\User\AppData\Local\avocode\app-2.22.1\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:5:310063)
    at Array.qPa (C:\Users\User\AppData\Local\avocode\app-2.22.1\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:17:170807)
    at rj (C:\Users\User\AppData\Local\avocode\app-2.22.1\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-
```

**Comment by jakubzitny** [comment]
Hi @pilotocheg, thanks for reporting this problem. It seems that our rendering engine has problems with WebGL in some specific cases. We're already tracking a similar problem in #1875, so I am going to close this.

However, could you please give us more hints on when is this happening? Is it when you're opening a design or when exporting something? Does it happen to all designs or only with one specific design?

In the meantime can you please try our web version at https://app.avocode.com to see if it works there? You can use Safari, Chrome or Firefox.

Thanks 😉
