### ISSUE TITLE
Can't get pro client of avocode on PC

### ISSUE THREAD

**Issue by FOXY-FO** [avocode/avocode#1978]
---
* **Version**: 2.23.0
* **Web/Desktop**: Desktop
* **Platform**: win64
* **Avocode UID**: 261005
---
```
TypeError: Cannot read property '$$' of undefined
    at RegisteredPointer.nonConstNoSmartPtrRawPointerToWireType [as toWireType] (C:\Users\Влад\AppData\Local\avocode\app-2.23.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:1:616496)
    at Object.deinitializeOrchestrator (eval at new_ (C:\Users\Влад\AppData\Local\avocode\app-2.23.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:1:1), <anonymous>:7:26)
    at e.deinitializeOrchestrator (C:\Users\Влад\AppData\Local\avocode\app-2.23.0\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:2668)
    at e.finalize (C:\Users\Влад\AppData\Local\avocode\app-2.23.0\resources\app.asar\node_modules\@avocode\stage\dist\stage.js:1:10468)
    at e.value (file:///C:/Users/%D0%92%D0%BB%D0%B0%D0%B4/AppData/Local/avocode/app-2.23.0/resources/app.asar/dist/avocode.min.js:1:3605733)
    at e.value (file:///C:/Users/%D0%92%D0%BB%D0%B0%D0%B4/AppData/Local/avocode/app-2.23.0/resour
```
The thing is on the browser I have pro app, but on PС I don't

**Comment by jakubzitny** [comment]
Hi @FOXY-FO, we've just released a new version of Avocode and this bug should be fixed in it. Please update and let us know if you still have any problems 😉
