### ISSUE TITLE
Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'

### ISSUE THREAD

**Issue by lexantus** [avocode/avocode#1979]
---
* **Version**: 2.22.0
* **Sketch plugin version**: 49.0.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 277149
---
```
TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2359761)
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2384992)
    at _handleOfflineState (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2295778)
```

**Comment by jakubzitny** [comment]
Hi @lexantus, we've already released a new version of Avocode - `2.24.0`. Can you please update and see if it helps? If so, can you please describe the details of the problem? When exactly and how often is it happening?

**Comment by lexantus** [comment]
Ok, I'll give you feedback if get same error in latest version

2018-04-18 14:54 GMT+03:00 Jakub Žitný <notifications@github.com>:

**Comment by jakubzitny** [comment]
This should be fixed, please let us know if it's still happening.
