### ISSUE TITLE
Hitting Ctrl-R in inspect mode raises an error

### ISSUE THREAD

**Issue by trurl-master** [avocode/avocode#1980]
---
* **Version**: 2.23.0
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 15216
---
```
TypeError: Cannot read property 'documentRevisionId' of undefined
    at e.setGuideVisibility (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:2947019)
    at e.toggleGuideVisibility (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:2947320)
    at Object.r._handleShortcut [as handler] (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:4027780)
    at _this._handleShortcuts (/opt/Avocode/resources/app.asar/node_modules/react-shortcuts/lib/component/shortcuts.js:160:23)
    at module.exports [as fireCallback] (/opt/Avocode/resources/app.asar/node_modules/combokeys/Combokeys/prototype/fireCallback.js:24:7)
    at module.exports [as handleKey] (/opt/Avocode/resources/app.asar/node_modules/combokeys/Combokeys/prototype/handleKey.js:61:12)
    at module.exports._this._combokeys.handleKey (/opt/Avocode/resources/app.asar/node_modules/react-shortcuts/lib/component/shortcuts.js:127:11)
    at module.exports (/opt/Avocode/resources/app.asar/node_modules/combo
```

**Comment by petrbrzek** [comment]
@trurl-master thanks for the report. This bug will be fixed in the next version. It should land this week.

**Comment by jakubzitny** [comment]
Hi @trurl-master, this should be fixed in the latest version of Avocode. Please update and let us know if you have any more problems :wink:
