### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cpart** [avocode/avocode#1981]
---
* **Version**: 2.23.0
* **Sketch plugin version**: 49.0.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 136149
---
```
TypeError: Cannot read property 'get' of undefined
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:788200
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4420:31
    at List.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at List.reduce (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4415:12)
    at Function.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:788157)
    at Function.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:787952)
    at Function.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:786822)
    at t.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1741545)
    at t.value (file:///Applications/Avoc
```

**Comment by jakubzitny** [comment]
Hi @cpart, thanks for reporting this issue. We've just release a new version of Avocode and this bug should be fixed there. Please update and let us know if you still have any problems 😉
