### ISSUE TITLE
error  crashed webGl

### ISSUE THREAD

**Issue by dragin96** [avocode/avocode#1985]
---
* **Version**: 2.24.0-web.2
* **Web/Desktop**: Web
* **Platform**: windows 10.0
* **Browser**: chrome 66.0.3359.117
* **Avocode UID**: 13268
---
```
TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.
    at _glShaderSource (https://cdn.app.avocode.com/dist/v-62de2cb/js/2.avocode-web.min.js:1:57419)
    at V0 (https://cdn.app.avocode.com/dist/v-62de2cb/js/2.avocode-web.min.js:1:2391650)
    at DrA (https://cdn.app.avocode.com/dist/v-62de2cb/js/2.avocode-web.min.js:1:3296173)
    at Gs (https://cdn.app.avocode.com/dist/v-62de2cb/js/2.avocode-web.min.js:1:1345819)
    at Xz (https://cdn.app.avocode.com/dist/v-62de2cb/js/2.avocode-web.min.js:1:2076982)
    at brA (https://cdn.app.avocode.com/dist/v-62de2cb/js/2.avocode-web.min.js:1:3280723)
    at Oz (https://cdn.app.avocode.com/dist/v-62de2cb/js/2.avocode-web.min.js:1:2071477)
    at qsA (https://cdn.app.avocode.com/dist/v-62de2cb/js/2.avocode-web.min.js:1:7114299)
    at WbA (https://cdn.app.avocode.com/dist/v-62de2cb/js/2.avocode-web.min.js:1:4558877)
    at qsA (https://cdn.app.avocode.com/dist/v-62de2cb/js/2.avocode-we
```

**Comment by jakubzitny** [comment]
Hi @dragin96, thanks for reporting this problem. It seems that our rendering engine has issues with WebGL in some specific cases. We're already tracking a similar problem in #1875, so I am going to close this.

However, could you please give us more hints on when is this happening? Is it when you're opening a design or when exporting something? Does it happen to all designs or only with one specific design?

In the meantime can you please try our desktop version to see if you have similar problems in it?

Thanks 😉
