### ISSUE TITLE
The preview could not be loaded

### ISSUE THREAD

**Issue by YevhenNechepurenko** [avocode/avocode#1988]
---
* **Version**: 2.24.0
* **Sketch plugin version**: 49.0.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 316149
---
```
Error: The preview could not be loaded.
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1175704)
    at e.<anonymous> (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3756781)
    at tryCatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:116:21)
    at r (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3750646)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3750740
    at <anonymous>
```

**Comment by connor-bean** [comment]
Hey could you tell us more about this? If possible, could you send us a screenshot of what you see in Avocode? And did it happen in both the desktop app and the web app? Or just the desktop app?

**Comment by YevhenNechepurenko** [comment]
Hello!
This happened in the desktop app.
After restarting the desktop app, the problem disappeared. Now everything works without errors.

> 20 апр. 2018 г., в 11:55, Connor <notifications@github.com> написал(а):
> 
> Hey could you tell us more about this? Were you uploading Sketch design using the plugin or directly into Avocode yourself through the drag and drop method?
> 
> If possible, could you send us a screenshot of what you see in Avocode? And did it happen in both the desktop app and the web app? Or just the desktop app?
>
