### ISSUE TITLE
dasdsa

### ISSUE THREAD

**Issue by ghost** [avocode/avocode#1990]
---
* **Version**: 2.21.0
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 316691
---
```
Error: EACCES: permission denied, mkdir '/home/mrhalid/.avocode/userdata'
    at Object.fs.mkdirSync (fs.js:895:18)
    at sync (/home/mrhalid/Загрузки/avocode-2.21.0-linux/resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:55:12)
    at sync (/home/mrhalid/Загрузки/avocode-2.21.0-linux/resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:61:24)
    at Function.sync (/home/mrhalid/Загрузки/avocode-2.21.0-linux/resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:61:24)
    at Object.makeTreeSync (/home/mrhalid/Загрузки/avocode-2.21.0-linux/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:381:23)
    at e.value (file:///home/mrhalid/%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B8/avocode-2.21.0-linux/resources/app.asar/dist/avocode.min.js:1:2509859)
    at e.value (file:///home/mrhalid/%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B8/avocode-2.21.0-linux/resources/app.asar/dist/avocode.min.js:1:2507319)
    at e.<anonymous> (file:
```

**Comment by jakubzitny** [comment]
Hi @mrHaLid-17, thanks for reporting this. Can you try quitting the app, removing `/home/mrhalid/.avocode` folder and try again, please?

We're tracking a similar problem in #1926, so I will close this issue.
