### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by danielwallem** [avocode/avocode#1993]
---
* **Version**: 2.24.0
* **Sketch plugin version**: 49.0.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 272589
---
```
TypeError: Cannot read property 'get' of undefined
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:793610
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4420:31
    at List.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at List.reduce (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4415:12)
    at Function.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:793567)
    at Function.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:793362)
    at Function.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:792232)
    at t.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1751357)
    at t.value (file:///Applications/Avoc
```

**Comment by jakubzitny** [comment]
Hi @danielwallem, thanks for reporting this problem. We're already tracking this bug in #1992 so I will close this thread. However, any further details on when and how often is this happening would help us. Thanks 🙂
