### ISSUE TITLE
The preview could not be loaded.

### ISSUE THREAD

**Issue by Lena9421** [avocode/avocode#1996]
---
* **Version**: 2.24.0-web.2
* **Web/Desktop**: Web
* **Platform**: macosx 10.12.6
* **Browser**: chrome 66.0.3359.117
* **Avocode UID**: 318401
---
```
Error: The preview could not be loaded.
    at e.value (https://cdn.app.avocode.com/dist/v-62de2cb/js/avocode-web.min.js:42:786123)
    at e.<anonymous> (https://cdn.app.avocode.com/dist/v-62de2cb/js/avocode-web.min.js:106:1295086)
    at r (https://fast.appcues.com/24524.js:1:284620)
    at Generator._invoke (https://fast.appcues.com/24524.js:1:286047)
    at Generator.t.(anonymous function) [as next] (https://fast.appcues.com/24524.js:1:284799)
    at r (https://cdn.app.avocode.com/dist/v-62de2cb/js/avocode-web.min.js:106:1288951)
    at https://cdn.app.avocode.com/dist/v-62de2cb/js/avocode-web.min.js:106:1289045
```

**Comment by jakubzitny** [comment]
Closing with respect to #2004 .
