### ISSUE TITLE
The preview could not be loaded.

### ISSUE THREAD

**Issue by gorbatova** [avocode/avocode#1998]
---
* **Version**: 2.24.0-web.2
* **Web/Desktop**: Web
* **Platform**: windows 10.0
* **Browser**: chrome 65.0.3325.181
* **Avocode UID**: 314150
---
```
Error: The preview could not be loaded.
    at e.value (https://cdn.app.avocode.com/dist/v-62de2cb/js/avocode-web.min.js:42:786123)
    at e.<anonymous> (https://cdn.app.avocode.com/dist/v-62de2cb/js/avocode-web.min.js:106:1295086)
    at r (https://fast.appcues.com/24524.js:1:284620)
    at Generator._invoke (https://fast.appcues.com/24524.js:1:286047)
    at Generator.t.(anonymous function) [as next] (https://fast.appcues.com/24524.js:1:284799)
    at r (https://cdn.app.avocode.com/dist/v-62de2cb/js/avocode-web.min.js:106:1288951)
    at https://cdn.app.avocode.com/dist/v-62de2cb/js/avocode-web.min.js:106:1289045
```

**Comment by jakubzitny** [comment]
Hi @gorbatova, we're aware of this issue, we're tracking it in #2004. It is happening with larger files, usually on windows. Can you please try our desktop version to see if it's happening there as well?
