### ISSUE TITLE
Error: The preview could not be loaded.

### ISSUE THREAD

**Issue by Lena9421** [avocode/avocode#2004]
---
* **Version**: 2.24.0-web.2
* **Web/Desktop**: Web
* **Platform**: macosx 10.12.6
* **Browser**: chrome 66.0.3359.117
* **Avocode UID**: 320760
---
```
Error: The preview could not be loaded.
    at e.value (https://cdn.app.avocode.com/dist/v-62de2cb/js/avocode-web.min.js:42:786123)
    at e.<anonymous> (https://cdn.app.avocode.com/dist/v-62de2cb/js/avocode-web.min.js:106:1295086)
    at r (https://fast.appcues.com/24524.js:1:284885)
    at Generator._invoke (https://fast.appcues.com/24524.js:1:286312)
    at Generator.t.(anonymous function) [as next] (https://fast.appcues.com/24524.js:1:285064)
    at r (https://cdn.app.avocode.com/dist/v-62de2cb/js/avocode-web.min.js:106:1288951)
    at https://cdn.app.avocode.com/dist/v-62de2cb/js/avocode-web.min.js:106:1289045
```

**Comment by bolekkerous** [comment]
Hey,
does this happen regularly, or only with a specific design?

**Comment by Lena9421** [comment]
Hey, it happens if PSD is too heavy. What is the maximum for PSD?
--
Sent from Mail.Ru app for Android Friday, 27 April 2018, 06:07PM +03:00 from Bolek  notifications@github.com :

**Comment by jakubzitny** [comment]
Hi @Lena9421, sorry for late reply. Is this still happening to you, or was it just these two times? Yeah, it's happening with larger files, especially on Windows. Have you tried our desktop app to see if it's happening over there? Max size for uploads is currently at 1.5GB.

**Comment by jakubzitny** [comment]
Hi @Lena9421, is this still happening to you, or was it just these two times? Yeah, it's happening with larger files, especially on Windows. Have you tried our desktop app to see if it's happening over there? Max size for uploads is currently at 1.5GB.
