### ISSUE TITLE
Eror when open PSD

### ISSUE THREAD

**Issue by acidcrash2005** [avocode/avocode#2010]
---
* **Version**: 2.25.2-web.1
* **Web/Desktop**: Web
* **Platform**: linux -1
* **Browser**: chrome 64.0.3282.119
* **Avocode UID**: 271035
---
```
Error: OctopusApi#getOctopusLink() -> error (status: 500, error: "Octopus Generator Error. Our developers has been notified")
    at t (https://cdn.app.avocode.com/dist/v-88bd61e/js/avocode-web.min.js:17:214306)
    at new t (https://cdn.app.avocode.com/dist/v-88bd61e/js/avocode-web.min.js:17:214197)
    at Object.getErrorByStatusCode (https://cdn.app.avocode.com/dist/v-88bd61e/js/avocode-web.min.js:17:106338)
    at Object.normalizeError (https://cdn.app.avocode.com/dist/v-88bd61e/js/avocode-web.min.js:17:105722)
    at Object.normalizeResponse (https://cdn.app.avocode.com/dist/v-88bd61e/js/avocode-web.min.js:17:105468)
    at https://cdn.app.avocode.com/dist/v-88bd61e/js/avocode-web.min.js:89:438127
    at https://cdn.app.avocode.com/dist/v-88bd61e/js/avocode-web.min.js:89:400454
    at <anonymous>
```

**Comment by bolekkerous** [comment]
Hey, @acidcrash2005 -
can you reproduce this with a specific design or was it something that happened once randomly and then it didn't again?

If you can reproduce it with a specific design, could you please send us the link to that design or just the design name to team@avocode.com?

Thanks!

**Comment by jakubzitny** [comment]
Hey, @acidcrash2005 -
can you reproduce this with a specific design or was it something that happened once randomly and then it didn't again?

If you can reproduce it with a specific design, could you please send us the link to that design or just the design name to team@avocode.com?

Thanks!

**Comment by jakubzitny** [comment]
Closing due to inactivity. Let us know if you have any more problems with Avocode, please 😉
