### ISSUE TITLE
Load errore

### ISSUE THREAD

**Issue by iea79** [avocode/avocode#2014]
---
* **Version**: 2.25.2
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 35230
---
```
Error: ETIMEDOUT
    at too_late (/opt/Avocode/resources/app.asar/node_modules/browser-request/index.js:186:14)
    at wrapped (/opt/Avocode/resources/app.asar/node_modules/raven-js/src/raven.js:360:21)
```

**Comment by jakubzitny** [comment]
Hi @iea79, thanks for submitting this. We know about this problem already. However, we'd like to hear more details on this error from you, how often is this happening? When exactly?

I'm closing this with respect to #1677, but please do let us know the details.
