### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Mytka** [avocode/avocode#2016]
---
* **Version**: 2.25.2
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: null
---
```
Error: ENOENT: no such file or directory, lstat '/Users/liliamytko/Dropbox/Avocode.app'
    at fs.lstatSync (fs.js:961:11)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at realpathSync (fs.js:1641:21)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:331:24)
    at toRealPath (module.js:130:13)
    at tryFile (module.js:126:22)
    at tryExtensions (module.js:138:22)
    at Function.Module._findPath (module.js:190:20)
    at Module._resolveFilename (module.js:468:25)
    at Function.Module._resolveFilename (/Users/liliamytko/Dropbox/Avocode.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/liliamytko/Dropbox/Avocode.app/Contents/Resources/app.asar/node_modules/combokeys/Combokeys/prototype/handleKeyEvent.js:20:24)
    at HTMLBodyElement.wrapped (/Users/liliamytko/Dropbox/Avocode.app/Contents/Reso
```

**Comment by vojtatranta** [comment]
It seems you did not have Avocode.app in Applications folder. 

Just download it again and put it into te Applications folder. Here's link: https://avocode.com/download
