### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by agalar** [avocode/avocode#2018]
---
* **Version**: 2.26.0
* **Sketch plugin version**: 49.0.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 83673
---
```
Error: Api#_getUploadSlot()() -> error (status: 500, error: "Internal Server Error")
    at t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:129810)
    at new t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:129701)
    at Object.getErrorByStatusCode (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:75265)
    at Object.normalizeError (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:74649)
    at Object.normalizeResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:74395)
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2491589)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2485961
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2489151
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @agalar, thanks for reporting this problem. Is it still happening, or was this just one-time thing? Can you upload to Avocode now?

**Comment by jakubzitny** [comment]
Hi @agalar, thanks for reporting this problem. Is it still happening, or was this just one-time thing? Can you upload to Avocode now?

**Comment by jakubzitny** [comment]
Closing due to inactivity, let us know if it's still happening to you, please. 😉
