### ISSUE TITLE
error

### ISSUE THREAD

**Issue by weblegko** [avocode/avocode#2020]
---
* **Version**: 2.26.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 184596
---
```
TypeError: Cannot read property 'l' of undefined
    at Object.rectToBounds (C:\Users\dima\AppData\Local\avocode\app-2.26.0\resources\app.asar\node_modules\@avocode\stage\dist\utils\rendering.js:1:3087)
    at t.preview (C:\Users\dima\AppData\Local\avocode\app-2.26.0\resources\app.asar\node_modules\@avocode\stage\dist\artboards\artboard.js:1:12044)
    at e.value (file:///C:/Users/dima/AppData/Local/avocode/app-2.26.0/resources/app.asar/dist/avocode.min.js:1:4030358)
    at t.describeLayers (file:///C:/Users/dima/AppData/Local/avocode/app-2.26.0/resources/app.asar/dist/avocode.min.js:1:4074801)
    at e.value (file:///C:/Users/dima/AppData/Local/avocode/app-2.26.0/resources/app.asar/dist/avocode.min.js:1:4245268)
    at e.value (file:///C:/Users/dima/AppData/Local/avocode/app-2.26.0/resources/app.asar/dist/avocode.min.js:1:4243335)
    at t._getSelectionState (file:///C:/Users/dima/AppData/Local/avocode/app-2.26.0/resources/app.asar/dist/avocode.min.js:1:3122535)
    at t.<anonymous> (
```

**Comment by jakubzitny** [comment]
Hi @dimabednyuk, thanks for reporting this problem. We're already tracking it in #2017 so I'll close the issue. Fixed version will be released early next week.

**Comment by jakubzitny** [comment]
In the meantime, please use our web version at [app.avocode.com](https://app.avocode.com).
