### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Stegura** [avocode/avocode#2021]
---
* **Version**: 2.26.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 330484
---
```
TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.
    at _glShaderSource (C:\Users\Admin\AppData\Local\avocode\app-2.26.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:1:676469)
    at aP (C:\Users\Admin\AppData\Local\avocode\app-2.26.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:5:141067)
    at Ju (C:\Users\Admin\AppData\Local\avocode\app-2.26.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:8:173649)
    at Array.RP (C:\Users\Admin\AppData\Local\avocode\app-2.26.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:5:176024)
    at Wt (C:\Users\Admin\AppData\Local\avocode\app-2.26.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:8:102495)
    at Zta (C:\Users\Admin\AppData\Local\avocode\app-2.26.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rende
```

**Comment by jakubzitny** [comment]
Hi @dragin96, thanks for reporting this problem. It seems that our rendering engine has issues with WebGL in some specific cases. We're already tracking a similar problem in #1875, so I am going to close this.

However, could you please give us more hints on when is this happening? Is it when you're opening a design or when exporting something? Does it happen to all designs or only with one specific design?

In the meantime can you please try our web version to see if you have similar problems in it?

Thanks 😉

**Comment by jakubzitny** [comment]
Hi @dragin96, thanks for reporting this problem. It seems that our rendering engine has issues with WebGL in some specific cases. We're already tracking a similar problem in #1875, so I am going to close this.

However, could you please give us more hints on when is this happening? Is it when you're opening a design or when exporting something? Does it happen to all designs or only with one specific design?

In the meantime can you please try our desktop version to see if you have similar problems in it?

Thanks 😉
