### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by reznichenko1303** [avocode/avocode#2022]
---
* **Version**: 2.26.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 311133
---
```
TypeError: Cannot read property 'l' of undefined
    at Object.rectToBounds (C:\Users\Александр\AppData\Local\avocode\app-2.26.0\resources\app.asar\node_modules\@avocode\stage\dist\utils\rendering.js:1:3087)
    at t.preview (C:\Users\Александр\AppData\Local\avocode\app-2.26.0\resources\app.asar\node_modules\@avocode\stage\dist\artboards\artboard.js:1:12044)
    at e.value (file:///C:/Users/%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80/AppData/Local/avocode/app-2.26.0/resources/app.asar/dist/avocode.min.js:1:4030358)
    at t.describeLayers (file:///C:/Users/%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80/AppData/Local/avocode/app-2.26.0/resources/app.asar/dist/avocode.min.js:1:4074801)
    at e.value (file:///C:/Users/%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80/AppData/Local/avocode/app-2.26.0/resources/app.asar/dist/avocode.min.js:1:4245268)
    at e.value (file:///C:/Users/%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80/AppData/Local/avocode/app-2.2
```

**Comment by jakubzitny** [comment]
Hi @nikemerik, thanks for reporting this problem. We're already tracking it in #2017 so I'll close the issue. Fixed version will be released early next week.

**Comment by jakubzitny** [comment]
In the meantime, please use our web version at [app.avocode.com](https://app.avocode.com).
