### ISSUE TITLE
errow in avocode

### ISSUE THREAD

**Issue by pavel-alpinweb** [avocode/avocode#2026]
---
* **Version**: 2.26.1
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 21020
---
```
RangeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation
    at Object.cropTransparentPixels (C:\Users\pavel\AppData\Local\avocode\app-2.26.1\resources\app.asar\node_modules\@avocode\stage\dist\utils\canvas.js:1:2650)
    at t.build (C:\Users\pavel\AppData\Local\avocode\app-2.26.1\resources\app.asar\node_modules\@avocode\stage\dist\utils\export\export-builder.js:1:3922)
    at t.preview (C:\Users\pavel\AppData\Local\avocode\app-2.26.1\resources\app.asar\node_modules\@avocode\stage\dist\artboards\artboard.js:1:11669)
    at e.value (file:///C:/Users/pavel/AppData/Local/avocode/app-2.26.1/resources/app.asar/dist/avocode.min.js:1:4026757)
    at t.describeLayers (file:///C:/Users/pavel/AppData/Local/avocode/app-2.26.1/resources/app.asar/dist/avocode.min.js:1:4071200)
    at e.value (file:///C:/Users/pavel/AppData/Local/avocode/app-2.26.1/resources/app.asar/dist/avocode.min.js:1:4241667)
    at e.value (file:///C:/Users/pavel/AppData/L
```

**Comment by jakubzitny** [comment]
Hi @pavel-alpinweb , thanks for letting us know. We already had this problem, we're tracking it in #1567. The problem here is that rendering image data takes a lot of memory.

Would you be willing to share the details about your hardware and OS version? How much memory do you have? Can you please try our web version at [app.avocode.com](https://app.avocode.com) to see if it's better there?

When dealing with large designs in Avocode and running out or memory, restarting the app could help and having only one open design as well.
