### ISSUE TITLE
some problem

### ISSUE THREAD

**Issue by alTach** [avocode/avocode#2027]
---
* **Version**: 2.24.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 332841
---
```
Error: The preview could not be loaded.
    at e.value (file:///C:/Users/%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%B9/AppData/Local/avocode/app-2.24.0/resources/app.asar/dist/avocode.min.js:1:1175704)
    at e.<anonymous> (file:///C:/Users/%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%B9/AppData/Local/avocode/app-2.24.0/resources/app.asar/dist/avocode.min.js:1:3756781)
    at tryCatch (C:\Users\Евгений\AppData\Local\avocode\app-2.24.0\resources\app.asar\node_modules\regenerator-runtime\runtime.js:64:40)
    at Generator.invoke [as _invoke] (C:\Users\Евгений\AppData\Local\avocode\app-2.24.0\resources\app.asar\node_modules\regenerator-runtime\runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\Евгений\AppData\Local\avocode\app-2.24.0\resources\app.asar\node_modules\regenerator-runtime\runtime.js:116:21)
    at r (file:///C:/Users/%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%B9/AppData/Local/avocode/app-2.24.0/resources/app.asar/dist/avocode.min.js:1:3750646)
    at 
```

**Comment by jakubzitny** [comment]
Hi @Tuqzar, we're aware of this issue, we're tracking it in #2004. It is happening with larger files, usually on windows. Can you please try our web version to see if it's happening there as well? Also, having too many tabs in Avocode might be causing this. How often is this happening to you?
