### ISSUE TITLE
dont't crush your program please(((

### ISSUE THREAD

**Issue by pavel-alpinweb** [avocode/avocode#2028]
---
* **Version**: 2.26.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 21020
---
```
TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.
    at _glShaderSource (C:\Users\pavel\AppData\Local\avocode\app-2.26.2\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:1:676469)
    at aP (C:\Users\pavel\AppData\Local\avocode\app-2.26.2\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:5:141067)
    at x6 (C:\Users\pavel\AppData\Local\avocode\app-2.26.2\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:6:161707)
    at rO (C:\Users\pavel\AppData\Local\avocode\app-2.26.2\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:5:110369)
    at qg (C:\Users\pavel\AppData\Local\avocode\app-2.26.2\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:13:199309)
    at Nj (C:\Users\pavel\AppData\Local\avocode\app-2.26.2\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-a
```

**Comment by jakubzitny** [comment]
Hi @pavel-alpinweb, thanks for reporting this problem. It seems that our rendering engine has issues with WebGL in some specific cases. We're already tracking a similar problem in #1875, so I am going to close this.

However, could you please give us more hints on when is this happening? Is it when you're opening a design or when exporting something? Does it happen to all designs or only with one specific design?

In the meantime can you please try our web version to see if you have similar problems in it?

Thanks 😉
