### ISSUE TITLE
Crash while opening a psd file

### ISSUE THREAD

**Issue by alexkzr** [avocode/avocode#2036]
---
* **Version**: 2.26.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 328426
---
```
Error: Converting base64 string to bytes failed.
    at intArrayFromBase64 (C:\Users\alexa\AppData\Local\avocode\app-2.26.2\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:1:681612)
    at tryParseAsDataURI (C:\Users\alexa\AppData\Local\avocode\app-2.26.2\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:1:681883)
    at Rendering (C:\Users\alexa\AppData\Local\avocode\app-2.26.2\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:24:8294)
    at C:\Users\alexa\AppData\Local\avocode\app-2.26.2\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:1122
    at Promise (<anonymous>)
    at C:\Users\alexa\AppData\Local\avocode\app-2.26.2\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:637
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @askkozyrev, sorry for late response. When exactly is this happening, please? Do you still have problems with it in latest version of Avocode?

**Comment by alexkzr** [comment]
Thanks, this is no longer relevant.

С Уважением,

Александр Козырев

+7977 863 5778

2018-06-11 12:08 GMT+03:00 Jakub Žitný <notifications@github.com>:

**Comment by jakubzitny** [comment]
Thanks, don't hesitate to let us know if you have any more issues with Avocode 😉
