### ISSUE TITLE
error

### ISSUE THREAD

**Issue by KruglovAnatoliy** [avocode/avocode#2037]
---
* **Version**: 2.26.4
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 289922
---
```
Error: Octopus not available
    at e.<anonymous> (file:///C:/ProgramData/%D0%90%D0%BD%D0%B0%D1%82%D0%BE%D0%BB%D0%B8%D0%B9/avocode/app-2.26.4/resources/app.asar/dist/avocode.min.js:1:4238217)
    at tryCatch (C:\ProgramData\Анатолий\avocode\app-2.26.4\resources\app.asar\node_modules\regenerator-runtime\runtime.js:64:40)
    at Generator.invoke [as _invoke] (C:\ProgramData\Анатолий\avocode\app-2.26.4\resources\app.asar\node_modules\regenerator-runtime\runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (C:\ProgramData\Анатолий\avocode\app-2.26.4\resources\app.asar\node_modules\regenerator-runtime\runtime.js:116:21)
    at tryCatch (C:\ProgramData\Анатолий\avocode\app-2.26.4\resources\app.asar\node_modules\regenerator-runtime\runtime.js:64:40)
    at Generator.invoke [as _invoke] (C:\ProgramData\Анатолий\avocode\app-2.26.4\resources\app.asar\node_modules\regenerator-runtime\runtime.js:297:24)
    at Generator.prototype.(anonymous function) [as next] (C:\ProgramDa
```

**Comment by jakubzitny** [comment]
Hi @KruglovAnatoliy, sorry for late response. Do you have any details on this, is it happening repeatedly or just with a specific file? Would you be able to send it to us to team@avocode.com?

**Comment by connor-bean** [comment]
Hi @KruglovAnatoliy, sorry for late response. Do you have any details on this, is it happening repeatedly or just with a specific file? Would you be able to send it to us to team@avocode.com?

**Comment by jakubzitny** [comment]
Closing due to inactivity, let us know if you still have problems with this and we'll re-open.

**Comment by KruglovAnatoliy** [comment]
Thanks. There is no problem anymore.

2018-06-15 13:07 GMT+04:00 Jakub Žitný <notifications@github.com>:
