### ISSUE TITLE
fghjkl

### ISSUE THREAD

**Issue by mentoripro** [avocode/avocode#2039]
---
* **Version**: 2.26.4-web
* **Web/Desktop**: Web
* **Platform**: windows 10.0
* **Browser**: chrome 66.0.3359.181
* **Avocode UID**: 339919
---
```
Error: The preview could not be loaded.
    at e.value (https://cdn.app.avocode.com/dist/v-71c8c15/js/avocode-web.min.js:42:812590)
    at e.<anonymous> (https://cdn.app.avocode.com/dist/v-71c8c15/js/avocode-web.min.js:106:1294853)
    at i (https://cdn.app.avocode.com/dist/v-71c8c15/js/avocode-web.min.js:48:908033)
    at Generator._invoke (https://cdn.app.avocode.com/dist/v-71c8c15/js/avocode-web.min.js:48:909442)
    at Generator.e.(anonymous function) [as next] (https://cdn.app.avocode.com/dist/v-71c8c15/js/avocode-web.min.js:48:908212)
    at r (https://cdn.app.avocode.com/dist/v-71c8c15/js/avocode-web.min.js:106:1288509)
    at https://cdn.app.avocode.com/dist/v-71c8c15/js/avocode-web.min.js:106:1288603
```

**Comment by jakubzitny** [comment]
Hi @Kuzhimov, we're aware of this issue, we're tracking it in #2004. It is happening with larger files, usually on windows. Can you please try our desktop version to see if it's happening there as well? Also, having too many tabs in Avocode might be causing this. How often is this happening to you?
