### ISSUE TITLE
cannot load design.

### ISSUE THREAD

**Issue by LetaiefAymen** [avocode/avocode#2041]
---
* **Version**: 2.26.4
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 54517
---
```
Error: OctopusApi#getOctopusLink() -> error (status: 500, error: "Octopus Generator Error. Our developers has been notified")
    at t (file:///Users/aymen/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:134733)
    at new t (file:///Users/aymen/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:134624)
    at Object.getErrorByStatusCode (file:///Users/aymen/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:57945)
    at Object.normalizeError (file:///Users/aymen/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:57329)
    at Object.normalizeResponse (file:///Users/aymen/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:57075)
    at file:///Users/aymen/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2543952
    at file:///Users/aymen/Downlo
```

**Comment by bolekkerous** [comment]
Hey @LetaiefAymen -
did this happen just with one specific design or can you reproduce it regularly with multiple designs?

**Comment by LetaiefAymen** [comment]
Hey @bolekkerous , It happened with one design, it was happening on web and desktop version, and we had to re-upload the design to make it work again.

**Comment by bolekkerous** [comment]
Oh, I see. And after reuploading the design, it works correctly again?

**Comment by LetaiefAymen** [comment]
Yes , it worked again.
