### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Ibochkarev** [avocode/avocode#2044]
---
* **Version**: 2.26.4
* **Sketch plugin version**: 49.0.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 343277
---
```
Error: The preview could not be loaded.
    at e.<anonymous> (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:4243894)
    at tryCatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:116:21)
    at r (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:4231175)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:4231321
    at Promise (<anonymous>)
    at e.<anonymous> (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:4231119)
    at e (file:///Applications/Avocode.app/Contents/Resources/app.asar/d
```

**Comment by bolekkerous** [comment]
Hey @Ibochkarev -
does this happen regularly or did it happen just once?

If it happens regularly, can you reproduce it with a specific design?

**Comment by jakubzitny** [comment]
Hey @Ibochkarev -
does this happen regularly or did it happen just once?

If it happens regularly, can you reproduce it with a specific design?

**Comment by jakubzitny** [comment]
Closing due to inactivity, please let us know if you still have problems 😉
