### ISSUE TITLE
Document wounldn't load

### ISSUE THREAD

**Issue by nozpheratu** [avocode/avocode#2045]
---
* **Version**: 2.26.4
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 73288
---
```
Error: OctopusApi#getOctopusLink() -> error (status: 401, error: "Not authenticated")
    at t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:134733)
    at t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:134624)
    at new t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:135552)
    at Object.getErrorByStatusCode (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:57892)
    at Object.normalizeError (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:57329)
    at Object.normalizeResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:57075)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2543952
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2503767
    at <anonymous>
```

**Comment by bolekkerous** [comment]
Hey @nozpheratu - could you try logging out and logging in again in your Avocode app?

Does the problem persist even after you do that?

**Comment by jakubzitny** [comment]
Hey @nozpheratu - could you try logging out and logging in again in your Avocode app?

Does the problem persist even after you do that?

**Comment by nozpheratu** [comment]
Sorry for my late response. Yes, logging out and back in resolved the issue.
