### ISSUE TITLE
dispatchEvent

### ISSUE THREAD

**Issue by AnatoliyKhaulin** [avocode/avocode#2047]
---
* **Version**: 2.22.1
* **Sketch plugin version**: 49.0.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 340416
---
```
TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2360016)
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2385247)
    at _handleOfflineState (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2296033)
```

**Comment by connor-bean** [comment]
Hey @Anatoliy88 

Thanks for this report. It looks like you're running an older version of the Avocode app. Can you update to our most recent version and try again? 

If you cannot update directly from the app, you can download our latest version from www.avocode.com/download.

Once you update, please let us know if you see this issue again.
