### ISSUE TITLE
Эта хуйня ебучая не работает!

### ISSUE THREAD

**Issue by jonytrees** [avocode/avocode#2055]
---
* **Version**: 3.0.0-web
* **Web/Desktop**: Web
* **Platform**: windows 6.1
* **Browser**: chrome 58.0.3029.96
* **Avocode UID**: 344112
---
```
Error: The preview could not be loaded.
    at e.value (https://cdn.app.avocode.com/dist/v-4915cf1/js/avocode-web.min.js:42:815176)
    at e.<anonymous> (https://cdn.app.avocode.com/dist/v-4915cf1/js/avocode-web.min.js:106:1298362)
    at i (https://cdn.app.avocode.com/dist/v-4915cf1/js/avocode-web.min.js:48:908032)
    at Generator._invoke (https://cdn.app.avocode.com/dist/v-4915cf1/js/avocode-web.min.js:48:909441)
    at Generator.e.(anonymous function) [as next] (https://cdn.app.avocode.com/dist/v-4915cf1/js/avocode-web.min.js:48:908211)
    at r (https://cdn.app.avocode.com/dist/v-4915cf1/js/avocode-web.min.js:106:1292018)
    at https://cdn.app.avocode.com/dist/v-4915cf1/js/avocode-web.min.js:106:1292112
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Same problem as #2054, on the web.
