### ISSUE TITLE
TypeError when creating slice

### ISSUE THREAD

**Issue by kuanyshevaidos** [avocode/avocode#2058]
---
* **Version**: 3.0.0-web
* **Web/Desktop**: Web
* **Platform**: macosx 10.12.6
* **Browser**: chrome 66.0.3359.181
* **Avocode UID**: 354474
---
```
TypeError: Cannot read property 'toJS' of null
    at t._addDocumentLayerSliceLayer (https://cdn.app.avocode.com/dist/v-4915cf1/js/avocode-web.min.js:106:808566)
    at t._handleAction (https://cdn.app.avocode.com/dist/v-4915cf1/js/avocode-web.min.js:106:806331)
    at Object.ID_88 (https://cdn.app.avocode.com/dist/v-4915cf1/js/avocode-web.min.js:106:803751)
    at e._invokeCallback (https://cdn.app.avocode.com/dist/v-4915cf1/js/avocode-web.min.js:89:227948)
    at e.dispatch (https://cdn.app.avocode.com/dist/v-4915cf1/js/avocode-web.min.js:89:227750)
    at e.value (https://cdn.app.avocode.com/dist/v-4915cf1/js/avocode-web.min.js:70:128512)
    at e.value (https://cdn.app.avocode.com/dist/v-4915cf1/js/avocode-web.min.js:106:792023)
    at e.addDocumentLayerSlice (https://cdn.app.avocode.com/dist/v-4915cf1/js/avocode-web.min.js:106:799291)
    at Object._handleLayerClick (https://cdn.app.avocode.com/dist/v-4915cf1/js/avocode-web.min.js:106:819114)
    at Object._handleStageClick (https
```

**Comment by jakubzitny** [comment]
Hi @kuanyshevaidos, thanks for reporting this. It's a bug, we'll fix is as soon as possible. Is it happening with all slices or just in this one specific case?
