### ISSUE TITLE
Page not loaded

### ISSUE THREAD

**Issue by sarluk88** [avocode/avocode#2060]
---
* **Version**: 3.0.0-web
* **Web/Desktop**: Web
* **Platform**: macosx 10.13.4
* **Browser**: chrome 67.0.3396.87
* **Avocode UID**: null
---
```
Error: The preview could not be loaded.
    at e.value (https://cdn.app.avocode.com/dist/v-4915cf1/js/avocode-web.min.js:42:815176)
    at e.<anonymous> (https://cdn.app.avocode.com/dist/v-4915cf1/js/avocode-web.min.js:106:1298362)
    at i (https://cdn.app.avocode.com/dist/v-4915cf1/js/avocode-web.min.js:48:908032)
    at Generator._invoke (https://cdn.app.avocode.com/dist/v-4915cf1/js/avocode-web.min.js:48:909441)
    at Generator.e.(anonymous function) [as next] (https://cdn.app.avocode.com/dist/v-4915cf1/js/avocode-web.min.js:48:908211)
    at r (https://cdn.app.avocode.com/dist/v-4915cf1/js/avocode-web.min.js:106:1292018)
    at https://cdn.app.avocode.com/dist/v-4915cf1/js/avocode-web.min.js:106:1292112
```

**Comment by vojtatranta** [comment]
Would you send use a link to this design?

**Comment by vojtatranta** [comment]
If the design is too large it happens that preview loading fails. In this case a refresh shoul make it work, because preview is generated in the background.

**Comment by jakubzitny** [comment]
Hi @sarluk88, do you have any details on this problem for us? Can you send us the link? Did it occur more than one time (after you refreshed)? Did you try using our desktop version or a different browser, please?

**Comment by jakubzitny** [comment]
Closing due to inactivity, please let us know if you have more info / more problems 😉
