### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by MikeBloise77** [avocode/avocode#2061]
---
* **Version**: 3.0.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 340103
---
```
Error: OctopusApi#getOctopusLink() -> error (status: 500, error: "Prerender of document failed")
    at t (file:///C:/Users/mbloise/AppData/Local/avocode/app-3.0.0/resources/app.asar/dist/avocode.min.js:1:135637)
    at new t (file:///C:/Users/mbloise/AppData/Local/avocode/app-3.0.0/resources/app.asar/dist/avocode.min.js:1:135528)
    at Object.getErrorByStatusCode (file:///C:/Users/mbloise/AppData/Local/avocode/app-3.0.0/resources/app.asar/dist/avocode.min.js:1:57958)
    at Object.normalizeError (file:///C:/Users/mbloise/AppData/Local/avocode/app-3.0.0/resources/app.asar/dist/avocode.min.js:1:57342)
    at Object.normalizeResponse (file:///C:/Users/mbloise/AppData/Local/avocode/app-3.0.0/resources/app.asar/dist/avocode.min.js:1:57088)
    at file:///C:/Users/mbloise/AppData/Local/avocode/app-3.0.0/resources/app.asar/dist/avocode.min.js:1:2564450
    at file:///C:/Users/mbloise/AppData/Local/avocode/app-3.0.0/resources/app.asar/dist/avocode.min.js:1:2524265
    at <anonymous>
```

**Comment by vojtatranta** [comment]
Would you send us link a to this design? Thanks!

**Comment by jakubzitny** [comment]
Hi @MikeBloise77, would you send us link a to this design? Thanks!

**Comment by jakubzitny** [comment]
Closing due to inactivity, please let us know if you have more info / more problems 😉
