### ISSUE TITLE
VebGL has crashed

### ISSUE THREAD

**Issue by iryna-kyryllova** [avocode/avocode#2062]
---
* **Version**: 3.1.0-web
* **Web/Desktop**: Web
* **Platform**: windows 10.0
* **Browser**: chrome 67.0.3396.87
* **Avocode UID**: 356961
---
```
TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.
    at _glShaderSource (https://cdn.app.avocode.com/dist/v-bd9de8e/js/2.avocode-web.min.js:1:641464)
    at ff (https://cdn.app.avocode.com/dist/v-bd9de8e/js/2.avocode-web.min.js:1:768079)
    at Tm (https://cdn.app.avocode.com/dist/v-bd9de8e/js/2.avocode-web.min.js:1:1908547)
    at Array.Hf (https://cdn.app.avocode.com/dist/v-bd9de8e/js/2.avocode-web.min.js:1:789827)
    at https://cdn.app.avocode.com/dist/v-bd9de8e/js/2.avocode-web.min.js:1:1392353
    at jv (https://cdn.app.avocode.com/dist/v-bd9de8e/js/2.avocode-web.min.js:1:1393671)
    at jX (https://cdn.app.avocode.com/dist/v-bd9de8e/js/2.avocode-web.min.js:1:2236900)
    at HV (https://cdn.app.avocode.com/dist/v-bd9de8e/js/2.avocode-web.min.js:1:4084848)
    at SS (https://cdn.app.avocode.com/dist/v-bd9de8e/js/2.avocode-web.min.js:1:2712143)
    at SS (https://cdn.app.avocode.com/dist/v-bd9de8e/js/2.avocode-web.min
```

**Comment by jakubzitny** [comment]
Hi @keira-yes, thanks for reporting this problem. It seems that our rendering engine has issues with WebGL in some specific cases. We're already tracking a similar problem in #1875, so I am going to close this.

However, could you please give us more hints on when is this happening? Is it when you're opening a design or when exporting something? Does it happen to all designs or only with one specific design?

In the meantime can you please try our [desktop](http://avocode.com/download) version to see if you have similar problems in it?

Thanks 😉

**Comment by iryna-kyryllova** [comment]
Hi! My English is not so good, so sorry for my mistakes :) This always
happenes when I try to open hidden layers (I press on "eye" to show hidden
layer), so it crashed right away. It happens to all designes, not with one.

2018-07-30 13:51 GMT+03:00 Jakub Žitný <notifications@github.com>:

**Comment by jakubzitny** [comment]
Thanks a lot for the answer 😉 

Did you have time to check our desktop app to see if the problems happens there as well?

Also, I have another tip that might help. Go to `App Preferences` in your avatars dropdown,  try disabling Monroe rendering engine and please let us know if it helps.

![screenshot 2018-08-01 at 12 40 37](https://user-images.githubusercontent.com/3315662/43517258-5482c09c-9588-11e8-89b1-d3417f3661e0.png)

**Comment by iryna-kyryllova** [comment]
Hello! So I try to use Avocode at home and it works very good, don't
crashed. So I have this problem only at my work computer. Maybe it's a
problem with internet or our software. Anyway thank you so much for this
magic program! :)

2018-08-01 13:42 GMT+03:00 Jakub Žitný <notifications@github.com>:
