### ISSUE TITLE
Failed to open. 

### ISSUE THREAD

**Issue by 465media** [avocode/avocode#2065]
---
* **Version**: 2.25.2
* **Sketch plugin version**: 49.0.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 12524
---
```
Error: OctopusApi#getOctopusLink() -> error (status: 401, error: "Not authenticated")
    at t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:126680)
    at t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:126571)
    at new t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:127499)
    at Object.getErrorByStatusCode (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:75213)
    at Object.normalizeError (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:74650)
    at Object.normalizeResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:74396)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2502775
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2464906
    at <anonymous>
```

**Comment by petrbrzek** [comment]
Please update to the latest version of the app.
