### ISSUE TITLE
Searching from main screen

### ISSUE THREAD

**Issue by justMoritz** [avocode/avocode#2072]
---
* **Version**: 2.26.4
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 77015
---
```
Error: DesignApi#searchDesigns() -> error (status: 401, error: "Not authenticated")
    at t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:134733)
    at t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:134624)
    at new t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:135552)
    at Object.getErrorByStatusCode (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:57892)
    at Object.normalizeError (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:57329)
    at Object.normalizeResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:57075)
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2506205)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2526624
    at file:///Applications/Avocod
```

**Comment by jakubzitny** [comment]
Hi @justMoritz, thanks for reporting this problem. You have old version of Avocode, please update. Also, this kind of error is usually solved by logging out and in again.

Let us know if you have any more problems 😉
