### ISSUE TITLE
figma frame failed to load

### ISSUE THREAD

**Issue by benkopf20** [avocode/avocode#2073]
I selected a frame filled with text objects.
I exported to Avocode 
Avocode ran in browser, and I added it to an existing project just as a test
Double-clicked on frame and error reported "failed to load"

---
* **Version**: 3.1.1-web
* **Web/Desktop**: Web
* **Platform**: macosx 10.13.5
* **Browser**: chrome 67.0.3396.99
* **Avocode UID**: 52097
---
```
Error: The preview could not be loaded.
    at e.<anonymous> (https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:159:1716009)
    at S (https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:75:421831)
    at Generator._invoke (https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:75:421596)
    at Generator.e.(anonymous function) [as next] (https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:75:422010)
    at r (https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:159:1704847)
    at https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:159:1704986
    at new Promise (<anonymous>)
    at e.<anonymous> (https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:159:1704784)
    at e.<anonymous> (https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:159:1716469)
    at e.<anonymous> (https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:159:1713267)
    at S (https://cdn.app.avocode.com/di
```

**Comment by jakubzitny** [comment]
Hi @benkopf20, thanks for reporting this issue. I can see your synced Figma design and I see a problem with one of the frames (the last sync from Figma). However, all other calls seem to work, how is it on your end thought? Can you open any of frames in Avocode?

We had a connection problem with Figma API so the our requests were failing. Can you retry syncing the frames from Figma once again, please?

**Comment by jakubzitny** [comment]
Hi @benkopf20, thanks for reporting this issue. I can see your synced Figma design and I see a problem with one of the frames (the last sync from Figma). However, all other calls seem to work, how is it on your end thought? Can you open any of frames in Avocode?

We had a connection problem with Figma API so the our requests were failing. Can you retry syncing the frames from Figma once again, please?

**Comment by jakubzitny** [comment]
Closing due to inactivity. Please, let us know if you have more info. We're also preparing some improvements for Figma integration for next version of Avocode, so stay tuned 😉
