### ISSUE TITLE
Figma updates fail to load

### ISSUE THREAD

**Issue by benkopf20** [avocode/avocode#2074]
I just keep updating a specific Figma frame and I can't view the versions in Avocode for some reason "Document Failed to Load" error

---
* **Version**: 3.1.1-web
* **Web/Desktop**: Web
* **Platform**: macosx 10.13.5
* **Browser**: chrome 67.0.3396.99
* **Avocode UID**: 52097
---
```
Error: OctopusApi#getOctopusLink() -> error (status: 404, error: "Design is not processed.")
    at t (https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:32:319677)
    at t (https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:32:320112)
    at new t (https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:32:320442)
    at Object.getErrorByStatusCode (https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:32:119742)
    at Object.normalizeError (https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:32:119152)
    at Object.normalizeResponse (https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:32:118898)
    at https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:133:457276
    at https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:133:417489
```

**Comment by jakubzitny** [comment]
Closing with respect to #2073.
