### ISSUE TITLE
This error appeared every time when a browser tab is activated!

### ISSUE THREAD

**Issue by SmirnovW** [avocode/avocode#2077]
And it happens twice...

---
* **Version**: 3.1.1-web
* **Web/Desktop**: Web
* **Platform**: linux -1
* **Browser**: chrome 64.0.3282.119
* **Avocode UID**: 169219
---
```
TypeError: Cannot read property 'length' of undefined
    at Object.getStringifiedDatalayer (chrome-extension://ffljdddodmkedhkcjhpmdajhjdbkogke/js/dlc_getdl.js:6:21)
    at Object.postTabMessage (chrome-extension://ffljdddodmkedhkcjhpmdajhjdbkogke/js/dlc_getdl.js:22:77)
    at chrome-extension://ffljdddodmkedhkcjhpmdajhjdbkogke/js/dlc_getdl.js:77:20
    at i (https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:88:77828)
```

**Comment by jakubzitny** [comment]
Hi @SmirnovW, this looks like a problem with [DataLayer Checker](https://chrome.google.com/webstore/detail/datalayer-checker/ffljdddodmkedhkcjhpmdajhjdbkogke) plugin in Chrome. Can you try to disable it and check if it's still happening?

**Comment by SmirnovW** [comment]
@jakubzitny Oh thank you, god! You have saved my day! Please close this issue.
