### ISSUE TITLE
Document failed to load

### ISSUE THREAD

**Issue by ghost** [avocode/avocode#2078]
---
* **Version**: 3.1.1
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 355296
---
```
Error: OctopusApi#getOctopusLink() -> error (status: 401, error: "Not authenticated")
    at t (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:173893)
    at t (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:174328)
    at new t (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:174942)
    at Object.getErrorByStatusCode (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:65452)
    at Object.normalizeError (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:64889)
    at Object.normalizeResponse (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:64635)
    at file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:2659433
    at file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:2619448
    at <anonymous>
```

**Comment by connor-bean** [comment]
Hey @amlagoda could you try logging out and logging in again in your Avocode app?

Does the problem persist even after you do that?

**Comment by jakubzitny** [comment]
Hey @amlagoda could you try logging out and logging in again in your Avocode app?

Does the problem persist even after you do that?

**Comment by ghost** [comment]
Hey @connor-bean @jakubzitny ,  I'm not getting this error anymore, thanks
