### ISSUE TITLE
Not opening on iMac

### ISSUE THREAD

**Issue by bharat00k** [avocode/avocode#2079]
---
* **Version**: 3.1.1-web
* **Web/Desktop**: Web
* **Platform**: macosx 10.13.5
* **Browser**: chrome 67.0.3396.99
* **Avocode UID**: 367612
---
```
Error: The preview could not be loaded.
    at e.value (https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:58:893123)
    at e.<anonymous> (https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:159:1204276)
    at S (https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:75:421831)
    at Generator._invoke (https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:75:421596)
    at Generator.e.(anonymous function) [as next] (https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:75:422010)
    at r (https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:159:1198796)
    at https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:159:1198890
```

**Comment by jakubzitny** [comment]
Hi @bharat00k, can you please give us the design that you're trying to open so we can investigate the problem? Also, is this happening only for this one design or also for others?

**Comment by jakubzitny** [comment]
Hi @bharat00k, can you please give us the design that you're trying to open so we can investigate the problem? Also, is this happening only for this one design or also for others?

**Comment by bharat00k** [comment]
@jakubzitny please find attached. @
[On-Boarding.pdf](https://github.com/avocode/avocode/files/2183116/On-Boarding.pdf)

Unable to open .psb file

**Comment by bharat00k** [comment]
@jakubzitny  Unable to give .psb file due to big file.

**Comment by jakubzitny** [comment]
The pdf is not enough. Try uploading .psb to http://upx.cz, please. Or just share me the Avocode public  link.

**Comment by jakubzitny** [comment]
ping @bharat00k

**Comment by jakubzitny** [comment]
These problems might be happening with larger designs when system does not have enough resources. Please download our desktop app and try if it's also happening in there.

For now I'll close this issue with respect to #2004.
