### ISSUE TITLE
Every time I switch to the Avocode tab this happens

### ISSUE THREAD

**Issue by lucas-conde** [avocode/avocode#2080]
---
* **Version**: 3.1.1-web
* **Web/Desktop**: Web
* **Platform**: windows 10.0
* **Browser**: chrome 67.0.3396.99
* **Avocode UID**: 68607
---
```
TypeError: Cannot read property 'length' of undefined
    at Object.getStringifiedDatalayer (chrome-extension://ffljdddodmkedhkcjhpmdajhjdbkogke/js/dlc_getdl.js:6:21)
    at Object.postTabMessage (chrome-extension://ffljdddodmkedhkcjhpmdajhjdbkogke/js/dlc_getdl.js:22:77)
    at chrome-extension://ffljdddodmkedhkcjhpmdajhjdbkogke/js/dlc_getdl.js:77:20
    at i (https://cdn.app.avocode.com/dist/v-96b6ddd/js/avocode-web.min.js:88:77828)
```

**Comment by jakubzitny** [comment]
Hi @lucas-conde, this looks like a problem with [DataLayer Checker](https://chrome.google.com/webstore/detail/datalayer-checker/ffljdddodmkedhkcjhpmdajhjdbkogke) plugin in Chrome. We've already seen it in #2077, so disabling the plugin should help, let us know if it doesn't please.
