### ISSUE TITLE
Error while uploading

### ISSUE THREAD

**Issue by smiley-cz** [avocode/avocode#2084]
---
* **Version**: 3.1.1
* **Sketch plugin version**: 50.0.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 355458
---
```
TypeError: Method Date.prototype.toISOString called on incompatible receiver #<Object>
    at Object.toISOString (<anonymous>)
    at Object.toJSON (<anonymous>)
    at JSON.stringify (<anonymous>)
    at stringify (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/vendor/json-stringify-safe/stringify.js:23:15)
    at Raven._makeRequest (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1924:39)
    at Raven._sendProcessedPayload (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1877:52)
    at Raven._send (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1811:14)
    at Raven._processException (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1568:10)
    at Raven._handleStackInfo (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1442:10)
    at Raven.captureExcep
```

**Comment by jakubzitny** [comment]
Hi @smiley-cz, thanks for reporting this from #2069. We already know about this and we're working on a fix — we hope to have it ready soon.

Do you have any details on it? How often do you see this problem? What kind of design have you been uploading and when exactly did it happen, please?
