### ISSUE TITLE
Long Preview

### ISSUE THREAD

**Issue by carlos-reynosa** [avocode/avocode#2091]
---
* **Version**: 3.3.0-beta
* **Web/Desktop**: Web
* **Platform**: macosx 10.12.6
* **Browser**: chrome 67.0.3396.99
* **Avocode UID**: 193178
---
```
Error: The preview could not be loaded.
    at e.value (https://cdn.app.avocode.com/dist/v-3fe2851/js/avocode-web.min.js:58:902716)
    at e.<anonymous> (https://cdn.app.avocode.com/dist/v-3fe2851/js/avocode-web.min.js:159:1206743)
    at S (https://cdn.app.avocode.com/dist/v-3fe2851/js/avocode-web.min.js:75:421577)
    at Generator._invoke (https://cdn.app.avocode.com/dist/v-3fe2851/js/avocode-web.min.js:75:421342)
    at Generator.e.(anonymous function) [as next] (https://cdn.app.avocode.com/dist/v-3fe2851/js/avocode-web.min.js:75:421756)
    at r (https://cdn.app.avocode.com/dist/v-3fe2851/js/avocode-web.min.js:159:1201276)
    at https://cdn.app.avocode.com/dist/v-3fe2851/js/avocode-web.min.js:159:1201370
```

**Comment by jakubzitny** [comment]
Hi @carlos-reynosa, thanks for reporting this. Can you please give us the design that you're trying to open so we can investigate the problem? Also, is this happening only for this one design or also for others?

Similar problems might be happening with larger designs, try downloading our Desktop app and see if the same is happening there.

**Comment by jakubzitny** [comment]
Hi @carlos-reynosa, thanks for reporting this. Can you please give us the design that you're trying to open so we can investigate the problem? Also, is this happening only for this one design or also for others?

Similar problems might be happening with larger designs, try downloading our Desktop app and see if the same is happening there.

**Comment by jakubzitny** [comment]
Closing due to inactivity, please let us know if you still have problems with Avocode and more info for us 😉
