### ISSUE TITLE
Добрый день

### ISSUE THREAD

**Issue by pashawol** [avocode/avocode#2095]
---
* **Version**: 3.2.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 140453
---
```
RangeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation
    at Object.cropTransparentPixels (C:\Users\User\AppData\Local\avocode\app-3.2.0\resources\app.asar\node_modules\@avocode\stage\dist\utils\canvas.js:1:2650)
    at t.build (C:\Users\User\AppData\Local\avocode\app-3.2.0\resources\app.asar\node_modules\@avocode\stage\dist\utils\export\export-builder.js:1:3922)
    at t.preview (C:\Users\User\AppData\Local\avocode\app-3.2.0\resources\app.asar\node_modules\@avocode\stage\dist\artboards\artboard.js:1:11669)
    at e.value (file:///C:/Users/User/AppData/Local/avocode/app-3.2.0/resources/app.asar/dist/avocode.min.js:1:4170203)
    at t.describeLayers (file:///C:/Users/User/AppData/Local/avocode/app-3.2.0/resources/app.asar/dist/avocode.min.js:1:4225071)
    at e.value (file:///C:/Users/User/AppData/Local/avocode/app-3.2.0/resources/app.asar/dist/avocode.min.js:7:7262804)
    at e.value (file:///C:/Users/User/AppData/Local/avocode/
```

**Comment by jakubzitny** [comment]
Hi @pashawol , thanks for letting us know. We already know about this problem, we're tracking it in #1567. The problem here is that rendering image data takes a lot of memory. Can you please also share us the design you're having problems with? Is it only one design or multiple?

Would you be willing to share the details about your hardware and OS version? How much memory do you have? Can you please try our web version at [app.avocode.com](https://app.avocode.com) to see if it's better there?

When dealing with large designs in Avocode and running out or memory, restarting the app could help and having only one open design as well.
