### ISSUE TITLE
Problems with open xd files at windows10

### ISSUE THREAD

**Issue by MaximRoganov** [avocode/avocode#2100]
---
* **Version**: 3.3.1
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 96546
---
```
Error: ETIMEDOUT
    at too_late (C:\Users\total\AppData\Local\avocode\app-3.3.1\resources\app.asar\node_modules\browser-request\index.js:186:14)
    at wrapped (C:\Users\total\AppData\Local\avocode\app-3.3.1\resources\app.asar\node_modules\@avocode\stage\node_modules\raven-js\src\raven.js:375:21)
```

**Comment by jakubzitny** [comment]
Hi @MaksimRoganov, thanks for reporting this. We had some server issues yesterday at the time you posted this, it is likely related to the outage. Can you please re-try opening the XD designs and let us know if the problems still persist?

Thank you.

**Comment by MaximRoganov** [comment]
Hi @jakubzitny, today i had tried to open xd file. All work correctly

**Comment by jakubzitny** [comment]
Thanks for the info. Don't hesitate to let us know if you have any other problems in the future 😉
