### ISSUE TITLE
Document failed to load.

### ISSUE THREAD

**Issue by vipii** [avocode/avocode#2102]
---
* **Version**: 3.1.1
* **Sketch plugin version**: 50.0.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 262345
---
```
Error: OctopusApi#getOctopusLink() -> error (status: 401, error: "Not authenticated")
    at t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:173893)
    at t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:174328)
    at new t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:174942)
    at Object.getErrorByStatusCode (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:65452)
    at Object.normalizeError (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:64889)
    at Object.normalizeResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:64635)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2659433
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2619448
    at <anonymous>
```

**Comment by vipii** [comment]
Just updated to 3.3.1, file opens correctly now.
