### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Eugene-im** [avocode/avocode#2104]
---
* **Version**: 2.26.4
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 380188
---
```
Error: OctopusApi#getOctopusLink() -> error (status: 401, error: "Not authenticated")
    at t (file:///opt/avocode/resources/app.asar/dist/avocode.min.js:1:134733)
    at t (file:///opt/avocode/resources/app.asar/dist/avocode.min.js:1:134624)
    at new t (file:///opt/avocode/resources/app.asar/dist/avocode.min.js:1:135552)
    at Object.getErrorByStatusCode (file:///opt/avocode/resources/app.asar/dist/avocode.min.js:1:57892)
    at Object.normalizeError (file:///opt/avocode/resources/app.asar/dist/avocode.min.js:1:57329)
    at Object.normalizeResponse (file:///opt/avocode/resources/app.asar/dist/avocode.min.js:1:57075)
    at file:///opt/avocode/resources/app.asar/dist/avocode.min.js:1:2543952
    at file:///opt/avocode/resources/app.asar/dist/avocode.min.js:1:2503767
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @Eugene-im, thanks for reporting this error. First of all, you're using old version of the app, so please update. Which Linux distro are you using? Also, this error is usually connected to corrupted `~/.avocode` directory. So please quit Avocode, remove `~/.avocode` and relaunch. After that it should work correctly. If it doesn't please let us know.
