### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by Quper24** [avocode/avocode#2111]
---
* **Version**: 3.3.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 385422
---
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new ArrayBuffer (C:\Users\LeskinME\AppData\Local\avocode\app-3.3.2\resources\app.asar\node_modules\core-js\modules\_typed-buffer.js:247:14)
    at Rendering (C:\Users\LeskinME\AppData\Local\avocode\app-3.3.2\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:4:15938)
    at C:\Users\LeskinME\AppData\Local\avocode\app-3.3.2\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:1078
    at Promise (<anonymous>)
    at C:\Users\LeskinME\AppData\Local\avocode\app-3.3.2\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:637
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @Quper24, thanks for the report. We're already tracking same problem in #1867 so I am going to close this thread.

Is this happening to all designs you're trying to open and all the time?

Can you please try our web app at [app.avocode.com](https://app.avocode.com) to see if the same problem occurs?

There is also more info in #2110, it seems that not enough memory is usually causing this problem on Windows. How much cpu/ram do you have?
