### ISSUE TITLE
Loading chunk 2 failed

### ISSUE THREAD

**Issue by radhamanis** [avocode/avocode#2113]
---
* **Version**: 3.3.2-web.2
* **Web/Desktop**: Web
* **Platform**: windows 6.1
* **Browser**: chrome 68.0.3440.84
* **Avocode UID**: 165056
---
```
Error: Loading chunk 2 failed.
(timeout: https://cdn.app.avocode.com/dist/v-c93fe29/js/2.avocode-web.min.js)
    at l (https://cdn.app.avocode.com/dist/v-c93fe29/js/avocode-web.min.js:1:919)
    at https://cdn.app.avocode.com/dist/v-c93fe29/js/avocode-web.min.js:1:728
    at i (https://cdn.app.avocode.com/dist/v-c93fe29/js/avocode-web.min.js:88:77828)
```

**Comment by jakubzitny** [comment]
Hi @RADHAMANISRM, thanks for reporting this problem, we'll look into it. Is it happening all the time or just once, please? Did you try using a different browser than Chrome? Or our [desktop app](https://avocode.com/download)? Desktop app should work correctly for sure.

**Comment by jakubzitny** [comment]
Hi @RADHAMANISRM, thanks again for reporting this problem, is it still happening? Did you try using a different browser than Chrome? Or our desktop app? Desktop app should work correctly for sure.

**Comment by jakubzitny** [comment]
Hi @RADHAMANISRM, is this still happening to you please?
