### ISSUE TITLE
Can't open the design to inspect

### ISSUE THREAD

**Issue by skokalin** [avocode/avocode#2115]
I tried to open design at here https://app.avocode.com/revisions/28210623/?design=16974663
Version: RELEASE 3.3.2 - JUL 31, 2018 (Web)

---
* **Version**: 3.3.2-web.2
* **Web/Desktop**: Web
* **Platform**: linux -1
* **Browser**: chrome 67.0.3396.99
* **Avocode UID**: 161890
---
```
Error: OctopusApi#getOctopusLink() -> error (status: 500, error: "Octopus Generator Error. Our developers has been notified")
    at t (https://cdn.app.avocode.com/dist/v-c93fe29/js/avocode-web.min.js:32:276396)
    at new t (https://cdn.app.avocode.com/dist/v-c93fe29/js/avocode-web.min.js:32:276831)
    at Object.getErrorByStatusCode (https://cdn.app.avocode.com/dist/v-c93fe29/js/avocode-web.min.js:32:118573)
    at Object.normalizeError (https://cdn.app.avocode.com/dist/v-c93fe29/js/avocode-web.min.js:32:117957)
    at Object.normalizeResponse (https://cdn.app.avocode.com/dist/v-c93fe29/js/avocode-web.min.js:32:117703)
    at https://cdn.app.avocode.com/dist/v-c93fe29/js/avocode-web.min.js:133:460345
    at https://cdn.app.avocode.com/dist/v-c93fe29/js/avocode-web.min.js:133:417687
```

**Comment by jakubzitny** [comment]
Hi @baron63, thanks for reporting this problem. We had a trouble rendering your design on our backend. If you try to re-upload the design one more time, it should work correctly. We'll also deploy a fix today that will prevent similar problems in the future.
