### ISSUE TITLE
error in comment avacode

### ISSUE THREAD

**Issue by Serega1288** [avocode/avocode#2120]
---
* **Version**: 3.4.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 71902
---
```
TypeError: Cannot read property 'update' of undefined
    at editOnBeforeInput (C:\Users\svtom\AppData\Local\avocode\app-3.4.0\resources\app.asar\node_modules\draft-js\lib\editOnBeforeInput.js:101:11)
    at C:\Users\svtom\AppData\Local\avocode\app-3.4.0\resources\app.asar\node_modules\draft-js\lib\DraftEditor.react.js:146:19
    at Object.invokeGuardedCallback (C:\Users\svtom\AppData\Local\avocode\app-3.4.0\resources\app.asar\node_modules\react-dom\lib\ReactErrorUtils.js:26:5)
    at executeDispatch (C:\Users\svtom\AppData\Local\avocode\app-3.4.0\resources\app.asar\node_modules\react-dom\lib\EventPluginUtils.js:85:21)
    at Object.executeDispatchesInOrder (C:\Users\svtom\AppData\Local\avocode\app-3.4.0\resources\app.asar\node_modules\react-dom\lib\EventPluginUtils.js:108:5)
    at executeDispatchesAndRelease (C:\Users\svtom\AppData\Local\avocode\app-3.4.0\resources\app.asar\node_modules\react-dom\lib\EventPluginHub.js:43:22)
    at executeDispatchesAndReleaseTopLevel (C:\Users\svtom\
```

**Comment by jakubzitny** [comment]
Hi @Serega1288, thanks for reporting this. We can see this error in our internal tracking, it's a bug and we'll try to fix it asap. Can you please specify, when exactly did it happen?

**Comment by jakubzitny** [comment]
Hi @Serega1288, can you please specify, when exactly did the problem happen? Did you see it more than once after that?

**Comment by jakubzitny** [comment]
Closing due to inactivity, please let us know if you can provide more info / if it happens again.
