### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by morcegon** [avocode/avocode#2122]
---
* **Version**: 3.4.0
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 17209
---
```
Error: OctopusApi#getOctopusLink() -> error (status: 401, error: "Not authenticated")
    at t (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:150310)
    at t (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:150745)
    at new t (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:151359)
    at Object.getErrorByStatusCode (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:67683)
    at Object.normalizeError (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:67120)
    at Object.normalizeResponse (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:66866)
    at file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:2827807
    at file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:2784711
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @morcegon, thanks for reporting this. Which Linux distro are you using, please? This error is usually connected to corrupted `~/.avocode` directory. So please quit Avocode, remove `~/.avocode` and relaunch. After that it should work correctly. If it doesn't please let us know.

**Comment by morcegon** [comment]
Hello @jakubzitny, I'm using Ubuntu 18.04.
Once I restarted Avocode, no more erro is showed.
