### ISSUE TITLE
Document failed to load

### ISSUE THREAD

**Issue by chrisgagan** [avocode/avocode#2126]
---
* **Version**: 3.4.1-web
* **Web/Desktop**: Web
* **Platform**: windows 10.0
* **Browser**: chrome 68.0.3440.106
* **Avocode UID**: 383625
---
```
Error: OctopusApi#getOctopusLink() -> error (status: 403, error: "Unpaid users cannot use octopus view")
    at t (https://cdn.app.avocode.com/dist/v-76d7e34/js/avocode-web.min.js:32:278975)
    at t (https://cdn.app.avocode.com/dist/v-76d7e34/js/avocode-web.min.js:32:279410)
    at new t (https://cdn.app.avocode.com/dist/v-76d7e34/js/avocode-web.min.js:32:280024)
    at Object.getErrorByStatusCode (https://cdn.app.avocode.com/dist/v-76d7e34/js/avocode-web.min.js:32:119709)
    at Object.normalizeError (https://cdn.app.avocode.com/dist/v-76d7e34/js/avocode-web.min.js:32:119146)
    at Object.normalizeResponse (https://cdn.app.avocode.com/dist/v-76d7e34/js/avocode-web.min.js:32:118892)
    at https://cdn.app.avocode.com/dist/v-76d7e34/js/avocode-web.min.js:127:460829
    at https://cdn.app.avocode.com/dist/v-76d7e34/js/avocode-web.min.js:127:418171
```

**Comment by jakubzitny** [comment]
Hi @chrisgagan, thanks for reporting this. When exactly did it happen? Our users are limited when accessing designs they do not have a proper access to, especially guest users.

It seems that you're now a regular part of your team so the link (and everything else) should be ok, right?

**Comment by jakubzitny** [comment]
I'll close this issue, let us know if you still have some problems with loading designs 😉
