### ISSUE TITLE
what?

### ISSUE THREAD

**Issue by Gzbox** [avocode/avocode#2129]
---
* **Version**: 3.4.1-web
* **Web/Desktop**: Web
* **Platform**: macosx 10.13.6
* **Browser**: chrome 68.0.3440.106
* **Avocode UID**: 402995
---
```
Error: Octopus not available
    at e.<anonymous> (https://cdn.app.avocode.com/dist/v-76d7e34/js/avocode-web.min.js:153:1684376)
    at S (https://cdn.app.avocode.com/dist/v-76d7e34/js/avocode-web.min.js:75:526111)
    at Generator._invoke (https://cdn.app.avocode.com/dist/v-76d7e34/js/avocode-web.min.js:75:525876)
    at Generator.e.(anonymous function) [as next] (https://cdn.app.avocode.com/dist/v-76d7e34/js/avocode-web.min.js:75:526290)
    at S (https://cdn.app.avocode.com/dist/v-76d7e34/js/avocode-web.min.js:75:526111)
    at Generator._invoke (https://cdn.app.avocode.com/dist/v-76d7e34/js/avocode-web.min.js:75:525515)
    at Generator.e.(anonymous function) [as next] (https://cdn.app.avocode.com/dist/v-76d7e34/js/avocode-web.min.js:75:526290)
    at r (https://cdn.app.avocode.com/dist/v-76d7e34/js/avocode-web.min.js:153:1678955)
    at https://cdn.app.avocode.com/dist/v-76d7e34/js/avocode-web.min.js:153:1679049
```

**Comment by jakubzitny** [comment]
Hi @Gzbox, thanks for reporting this problem. It seems that the app allowed you to open the design before it was processed completely. I just checked and it seems that everything is inspectable and correct, I also tried to reproduce the same behaviour for your design in my account and everything went well.

Can you please try opening the design again to see if it displays properly? We're sorry for the weird behaviour and inconvenience, we'll by trying to prevent any similar problem in the future.

**Comment by jakubzitny** [comment]
Hi @Gzbox, thanks for reporting this problem. It seems that the app allowed you to open the design before it was processed completely. I just checked and it seems that everything is inspectable and correct, I also tried to reproduce the same behaviour for your design in my account and everything went well.

Can you please try opening the design again to see if it displays properly? We're sorry for the weird behaviour and inconvenience, we'll by trying to prevent any similar problem in the future.

**Comment by jakubzitny** [comment]
Closing due to inactivity, the design should be openable properly.
