### ISSUE TITLE
I just still using avocode

### ISSUE THREAD

**Issue by n1kko777** [avocode/avocode#2143]
---
* **Version**: 3.4.1
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 260903
---
```
TypeError: Cannot read property 'abortOrigin' of undefined
    at t._handleChildAbort (file:///C:/Users/37344/AppData/Local/avocode/app-3.4.1/resources/app.asar/dist/avocode.min.js:1:80490)
    at file:///C:/Users/37344/AppData/Local/avocode/app-3.4.1/resources/app.asar/dist/avocode.min.js:1:77655
    at normalize (C:\Users\37344\AppData\Local\avocode\app-3.4.1\resources\app.asar\node_modules\ljson\LJSON.js:64:44)
    at normalize (C:\Users\37344\AppData\Local\avocode\app-3.4.1\resources\app.asar\node_modules\ljson\LJSON.js:81:78)
    at normalize (C:\Users\37344\AppData\Local\avocode\app-3.4.1\resources\app.asar\node_modules\ljson\LJSON.js:81:78)
    at normalize (C:\Users\37344\AppData\Local\avocode\app-3.4.1\resources\app.asar\node_modules\ljson\LJSON.js:81:78)
    at normalize (C:\Users\37344\AppData\Local\avocode\app-3.4.1\resources\app.asar\node_modules\ljson\LJSON.js:73:48)
    at normalize (C:\Users\37344\AppData\Local\avocode\app-3.4.1\resources\app.asar\node_modules\ljson\LJS
```

**Comment by jakubzitny** [comment]
Hi @n1kko777, thanks for reporting this. We're already aware of this bug and we're tracking it in #2140, so I'll close this thread.

We'll be trying to fix it as soon as possible, would you be able to provide more info about this, please? How many times did you see it and when exactly?
