### ISSUE TITLE
emboss an error

### ISSUE THREAD

**Issue by AndreyYanovskiy** [avocode/avocode#2148]
---
* **Version**: 3.5.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 409389
---
```
Error: Remote octopus link missing
    at e.value (file:///C:/Users/Andrey/AppData/Local/avocode/app-3.5.0/resources/app.asar/dist/avocode.min.js:1:3073712)
    at e.<anonymous> (file:///C:/Users/Andrey/AppData/Local/avocode/app-3.5.0/resources/app.asar/dist/avocode.min.js:1:3072719)
    at tryCatch (C:\Users\Andrey\AppData\Local\avocode\app-3.5.0\resources\app.asar\node_modules\regenerator-runtime\runtime.js:64:40)
    at Generator.invoke [as _invoke] (C:\Users\Andrey\AppData\Local\avocode\app-3.5.0\resources\app.asar\node_modules\regenerator-runtime\runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\Andrey\AppData\Local\avocode\app-3.5.0\resources\app.asar\node_modules\regenerator-runtime\runtime.js:116:21)
    at n (file:///C:/Users/Andrey/AppData/Local/avocode/app-3.5.0/resources/app.asar/dist/avocode.min.js:1:3070175)
    at file:///C:/Users/Andrey/AppData/Local/avocode/app-3.5.0/resources/app.asar/dist/avocode.min.js:1:3070314
    at Promise (<
```

**Comment by bolekkerous** [comment]
Hey @AndreyYanovskiy,
thanks for the report and sorry for the inconvenience.

Do you remember what exactly were you doing when this error happened? Or are you able to reproduce this error reliably?

**Comment by jakubzitny** [comment]
Hey @AndreyYanovskiy,
thanks for the report and sorry for the inconvenience.

Do you remember what exactly were you doing when this error happened? Or are you able to reproduce this error reliably?

Also, a link to the design/project where this is happening could help us with troubleshooting.

**Comment by jakubzitny** [comment]
Closing due to inactivity. Please reopen if it's still happening and you have more info for us 😉
