### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TomasHorak** [avocode/avocode#2149]
---
* **Version**: 3.5.0
* **Sketch plugin version**: 51.2.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 17594
---
```
TypeError: Cannot read property 'get' of undefined
    at Object.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/stage/dist/utils/common.js:1:2904)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/stage/dist/utils/common.js:1:1414
    at Object.next (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/stage/dist/utils/common.js:1:1519)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/stage/dist/utils/common.js:1:453
    at Promise (<anonymous>)
    at __awaiter (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/stage/dist/utils/common.js:1:230)
    at Object.getMaskClippedBounds (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/stage/dist/utils/common.js:1:2787)
    at t.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/stage/dist/artboards/artboard.js:1:9836)
    
```

**Comment by bolekkerous** [comment]
Hey @TomasHorak ,
thanks for the report and sorry for the inconvenience.

Do you remember what exactly were you doing when this error happened? Or are you able to reproduce this error reliably?

**Comment by jakubzitny** [comment]
Hey @TomasHorak ,
thanks for the report and sorry for the inconvenience.

Do you remember what exactly were you doing when this error happened? Or are you able to reproduce this error reliably?

**Comment by jakubzitny** [comment]
Closing due to inactivity. Please reopen if it's still happening and you have more info for us 😉
