### ISSUE TITLE
Remote octopus link missing

### ISSUE THREAD

**Issue by htmlburger-git** [avocode/avocode#2153]
---
* **Version**: 3.5.1
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 63502
---
```
Error: Remote octopus link missing
    at e.value (file:///C:/Users/User1/AppData/Local/avocode/app-3.5.1/resources/app.asar/dist/avocode.min.js:1:3074269)
    at e.<anonymous> (file:///C:/Users/User1/AppData/Local/avocode/app-3.5.1/resources/app.asar/dist/avocode.min.js:1:3073276)
    at tryCatch (C:\Users\User1\AppData\Local\avocode\app-3.5.1\resources\app.asar\node_modules\regenerator-runtime\runtime.js:64:40)
    at Generator.invoke [as _invoke] (C:\Users\User1\AppData\Local\avocode\app-3.5.1\resources\app.asar\node_modules\regenerator-runtime\runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\User1\AppData\Local\avocode\app-3.5.1\resources\app.asar\node_modules\regenerator-runtime\runtime.js:116:21)
    at n (file:///C:/Users/User1/AppData/Local/avocode/app-3.5.1/resources/app.asar/dist/avocode.min.js:1:3070732)
    at file:///C:/Users/User1/AppData/Local/avocode/app-3.5.1/resources/app.asar/dist/avocode.min.js:1:3070871
    at Promise (<anonymo
```

**Comment by jakubzitny** [comment]
Hi @htmlburger-git, thanks for reporting this problem. Can you please send us the link the the project or design where this is happening? We'll investigate the problem.

In the meantime you can try reloading or re-uploading the design to see if the problem still occurs.

**Comment by jakubzitny** [comment]
Hi @htmlburger-git, thanks for reporting this problem. Can you please send us the link the the project or design where this is happening? We'll investigate the problem.

In the meantime you can try reloading or re-uploading the design to see if the problem still occurs.

**Comment by jankuca** [comment]
Can you tell us more about the design (file type – photoshop/sketch/etc.) and when did the error pop up? Were you opening a PSD right after import or was this a design you imported some time ago?
