### ISSUE TITLE
Failed to load PSD

### ISSUE THREAD

**Issue by sergiofraiman** [avocode/avocode#2154]
---
* **Version**: 3.5.0
* **Sketch plugin version**: 51.2.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 311944
---
```
Error: Octopus not available
    at e.<anonymous> (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:11919495)
    at tryCatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:116:21)
    at tryCatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:297:24)
    at Generator.prototype.(anonymous function) [as next] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:11
```

**Comment by jakubzitny** [comment]
Hi @sergiofraiman, thanks for reporting this problem. Can you please send us the link the the project or design where this is happening? We'll investigate the problem.

In the meantime you can try reloading or re-uploading the design to see if the problem still occurs.

**Comment by jakubzitny** [comment]
Hi @sergiofraiman, thanks for reporting this problem. Can you please send us the link the the project or design where this is happening? We'll investigate the problem.

In the meantime you can try reloading or re-uploading the design to see if the problem still occurs.
