### ISSUE TITLE
Not loading 

### ISSUE THREAD

**Issue by CubaJas** [avocode/avocode#2158]
---
* **Version**: 3.5.1
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 333611
---
```
Error: Octopus not available
    at e.<anonymous> (file:///C:/Users/necheporenkoyaa/AppData/Local/avocode/app-3.5.1/resources/app.asar/dist/avocode.min.js:1:11923062)
    at tryCatch (C:\Users\necheporenkoyaa\AppData\Local\avocode\app-3.5.1\resources\app.asar\node_modules\regenerator-runtime\runtime.js:64:40)
    at Generator.invoke [as _invoke] (C:\Users\necheporenkoyaa\AppData\Local\avocode\app-3.5.1\resources\app.asar\node_modules\regenerator-runtime\runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\necheporenkoyaa\AppData\Local\avocode\app-3.5.1\resources\app.asar\node_modules\regenerator-runtime\runtime.js:116:21)
    at tryCatch (C:\Users\necheporenkoyaa\AppData\Local\avocode\app-3.5.1\resources\app.asar\node_modules\regenerator-runtime\runtime.js:64:40)
    at Generator.invoke [as _invoke] (C:\Users\necheporenkoyaa\AppData\Local\avocode\app-3.5.1\resources\app.asar\node_modules\regenerator-runtime\runtime.js:297:24)
    at Generator.prototype
```

**Comment by bolekkerous** [comment]
Hey @CubaJas,
do you remember which design were you trying to open when this error popped out? Would you be able to send us a link to the design to team@avocode.com, so we can investigate more?

**Comment by CubaJas** [comment]
@bolekkerous All designs which not opened before. I think this problem with a connection when i connected across VPN to my office(not internet connection - remote workplace). For some reason Avocode is trying to connect to your servers across this VPN connection. On the office side TMG block this connection(but this problem on administrators side).

**Comment by bolekkerous** [comment]
Hey @CubaJas, we've tried to investigate on our end but didn't really have luck with reproducing the issue.

So if I understand it correctly, you are getting this error when you try to open a design that was not opened before and when you are connected via VPN to your office? And that's most likely an issue on the administrator's side?

Have you also tried connecting via some other network, a wi-fi perhaps to see whether it works that way?
