### ISSUE TITLE
 Document failed to load

### ISSUE THREAD

**Issue by d3signer** [avocode/avocode#2165]
---
* **Version**: 3.3.2
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 46617
---
```
Error: CORS request rejected: https://manager.avocode.com/api/v6.0/octopus/2.2/412d08f91505430abaa0a76df6e09448/?prerender_layers=light&renderer_version=0.105.2
    at on_response (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/browser-request/index.js:242:22)
    at XMLHttpRequest.on_state_change (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/browser-request/index.js:225:7)
    at XMLHttpRequest.wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/stage/node_modules/raven-js/src/raven.js:375:21)
```

**Comment by crashmajstr** [comment]
Hello @d3signer  ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

**Comment by jakubzitny** [comment]
Hello @d3signer ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?
