### ISSUE TITLE
Crashed on preview

### ISSUE THREAD

**Issue by BulatSa** [avocode/avocode#2167]
I work on notebook with integrated Graphic Card, Intel i5-2430. I think Avocode, don't see my AMD Graphic Card - HD 6770

---
* **Version**: 3.5.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 428665
---
```
Error: The preview could not be loaded.
    at e.<anonymous> (file:///C:/Users/bn/AppData/Local/avocode/app-3.5.2/resources/app.asar/dist/avocode.min.js:1:11928705)
    at tryCatch (C:\Users\bn\AppData\Local\avocode\app-3.5.2\resources\app.asar\node_modules\regenerator-runtime\runtime.js:64:40)
    at Generator.invoke [as _invoke] (C:\Users\bn\AppData\Local\avocode\app-3.5.2\resources\app.asar\node_modules\regenerator-runtime\runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\bn\AppData\Local\avocode\app-3.5.2\resources\app.asar\node_modules\regenerator-runtime\runtime.js:116:21)
    at n (file:///C:/Users/bn/AppData/Local/avocode/app-3.5.2/resources/app.asar/dist/avocode.min.js:1:11916751)
    at file:///C:/Users/bn/AppData/Local/avocode/app-3.5.2/resources/app.asar/dist/avocode.min.js:1:11916890
    at Promise (<anonymous>)
    at e.<anonymous> (file:///C:/Users/bn/AppData/Local/avocode/app-3.5.2/resources/app.asar/dist/avocode
```

**Comment by crashmajstr** [comment]
Hello @BulatSa  ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design? 

Otherwise, maybe this article may help how to enable your second graphics card for the specific app https://www.digitalcitizen.life/set-which-video-cards-are-used-apps-games-windows-10.
Let me know.
Best,
Josef

**Comment by crashmajstr** [comment]
Hello @BulatSa ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

Otherwise, maybe this article may help how to enable your second graphics card for the specific app https://www.digitalcitizen.life/set-which-video-cards-are-used-apps-games-windows-10.
Let me know.
Best,
Josef

**Comment by BulatSa** [comment]
I just work with my uploaded sketch file, i open one page for view on Avocode. Also Avocode crashed with message about It doesn't rendered with WebGL. My Noteook HP Pavilion dv6-6b53er with 8GB RAM.

**Comment by crashmajstr** [comment]
@BulatSa Can you reproduce it? A screencast would be helpful, but I am afraid that there'll be a problem with Web-GL (technology used for rendering) on your computer. Did you manage to enable the non-integrated Graphics card?

**Comment by crashmajstr** [comment]
@BulatSa  Can you reproduce it? A screencast would be helpful, but I am afraid that there'll be a problem with Web-GL (technology used for rendering) on your computer. Did you manage to enable the non-integrated Graphics card?
