### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by Zintwo** [avocode/avocode#2171]
---
* **Version**: 3.5.3
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 351212
---
```
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at Object._renderTickCanvas (file:///C:/Users/Jinu/AppData/Local/avocode/app-3.5.3/resources/app.asar/dist/avocode.min.js:1:3479116)
    at Object._updateTickCanvas (file:///C:/Users/Jinu/AppData/Local/avocode/app-3.5.3/resources/app.asar/dist/avocode.min.js:1:3478772)
    at Object.componentWillUpdate (file:///C:/Users/Jinu/AppData/Local/avocode/app-3.5.3/resources/app.asar/dist/avocode.min.js:1:3478524)
    at ReactCompositeComponentWrapper._performComponentUpdate (C:\Users\Jinu\AppData\Local\avocode\app-3.5.3\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:714:14)
    at ReactCompositeComponentWrapper.updateComponent (C:\Users\Jinu\AppData\Local\avocode\app-3.5.3\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:645:12)
    at ReactCompositeComponentWrapper.receiveComponent (C:\Users\Jinu\AppData\L
```

**Comment by crashmajstr** [comment]
Hello @Zintwo 
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

**Comment by jakubzitny** [comment]
Closing with respect to #2173.
