### ISSUE TITLE
Sketch file

### ISSUE THREAD

**Issue by bwdgit** [avocode/avocode#2173]
---
* **Version**: 3.5.3
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 75625
---
```
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at Object._renderTickCanvas (file:///C:/Users/BWD/AppData/Local/avocode/app-3.5.3/resources/app.asar/dist/avocode.min.js:1:3479116)
    at Object._updateTickCanvas (file:///C:/Users/BWD/AppData/Local/avocode/app-3.5.3/resources/app.asar/dist/avocode.min.js:1:3478772)
    at Object.componentWillUpdate (file:///C:/Users/BWD/AppData/Local/avocode/app-3.5.3/resources/app.asar/dist/avocode.min.js:1:3478524)
    at ReactCompositeComponentWrapper._performComponentUpdate (C:\Users\BWD\AppData\Local\avocode\app-3.5.3\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:714:14)
    at ReactCompositeComponentWrapper.updateComponent (C:\Users\BWD\AppData\Local\avocode\app-3.5.3\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:645:12)
    at ReactCompositeComponentWrapper.receiveComponent (C:\Users\BWD\AppData\Local\a
```

**Comment by crashmajstr** [comment]
Hello @bwdgit  ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

**Comment by bwdgit** [comment]
Every time when i try to open same sketch file.
This error strts today after update avocode

**Comment by bwdgit** [comment]
Hold with this http://prntscr.com/l4eif8

**Comment by crashmajstr** [comment]
@bwdgit other sketch files are ok? Please, can you send me the sketch file?

**Comment by bwdgit** [comment]
Mmm.. now a try to open new folder and program hold with this http://prntscr.com/l4ek7f

**Comment by crashmajstr** [comment]
Please, can you try the web app at app.avocode.com if you experience the same issues?

**Comment by bwdgit** [comment]
app.avocode.com - no problem!

**Comment by crashmajstr** [comment]
ok, I'll discuss this issue with our dev team and let you know. 
Sorry for the inconvenience.
