### ISSUE TITLE
Error while saving changes of my account

### ISSUE THREAD

**Issue by NecroSith** [avocode/avocode#2174]
---
* **Version**: 3.5.5
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 321906
---
```
TypeError: t.first is not a function
    at t.value (file:///C:/Users/NecroSith/AppData/Local/avocode/app-3.5.5/resources/app.asar/dist/avocode.min.js:1:3214109)
    at t.value (file:///C:/Users/NecroSith/AppData/Local/avocode/app-3.5.5/resources/app.asar/dist/avocode.min.js:1:3214192)
    at t.value (file:///C:/Users/NecroSith/AppData/Local/avocode/app-3.5.5/resources/app.asar/dist/avocode.min.js:1:3214585)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (C:\Users\NecroSith\AppData\Local\avocode\app-3.5.5\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:799:30)
    at ReactCompositeComponentWrapper._renderValidatedComponent (C:\Users\NecroSith\AppData\Local\avocode\app-3.5.5\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:822:32)
    at ReactCompositeComponentWrapper._updateRenderedComponent (C:\Users\NecroSith\AppData\Local\avocode\app-3.5.5\resources\app.asar\node_modules\react-dom\lib\ReactComposi
```

**Comment by crashmajstr** [comment]
Hello @NecroSith  ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

**Comment by NecroSith** [comment]
@crashmajstr sure
I get this error while trying to create new project. When I click on "new project" and then on "create" avocode is starting project creation but then error popup saying "failed to create project" appears. Sometimes it crashes while creating a project or loading the existing one.
As for "when", this has started to happen very recently, maybe three or four days ago. Before this everything worked like a charm. 
I was trying to open a specific design yes but it happens no matter if I try to load a psd, sketch or jpeg. Existing projects open normally but when opening the existing design it's loading pretty slow, slower than before. After it's loaded sometimes there are no layers in the layer pane, just infinite preloader icon (see the [screenshot](https://2.downloader.disk.yandex.ru/disk/813b23d188f4ed911853e69e2c19a37496a969c6ed2a3bd9039893039f97d939/5bbfcbff/9R9d4mqsqRBxBGO__OEFBzAUuW0Pknx7OvA4yX9NfmmmE3rBPpWg5GI0bTP_cHNYxiX0QwwV7lr9UPHN1isFPA%3D%3D?uid=74248107&filename=2018-10-11_21-11-26.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&fsize=101313&hid=835672e6c5bdfd66e1ab325568cbc02d&media_type=image&tknv=v2&etag=43e63c9dbc86e30b01906db438961277))

**Comment by crashmajstr** [comment]
@NecroSith 
thanks for providing me with this info. We can actually see it in our tracking system. I've raised an issue for our developers, hope we'll fix this soon. Sorry for the inconvenience.
