### ISSUE TITLE
error sent by Avocode

### ISSUE THREAD

**Issue by brunorilla** [avocode/avocode#2177]
---
* **Version**: 3.5.3
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 430583
---
```
Error: Could not call remote function 'close'. Check that the function signature is correct. Underlying error: Object has been destroyed
Error: Could not call remote function 'close'. Check that the function signature is correct. Underlying error: Object has been destroyed
    at callFunction (C:\Users\rillab\AppData\Local\avocode\app-3.5.3\resources\electron.asar\browser\rpc-server.js:258:11)
    at EventEmitter.<anonymous> (C:\Users\rillab\AppData\Local\avocode\app-3.5.3\resources\electron.asar\browser\rpc-server.js:360:5)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (C:\Users\rillab\AppData\Local\avocode\app-3.5.3\resources\electron.asar\browser\api\web-contents.js:293:13)
    at WebContents.emit (events.js:182:13)
    at metaToException (C:\Users\rillab\AppData\Local\avocode\app-3.5.3\resources\electron.asar\renderer\api\remote.js:271:17)
    at Object.exception (C:\Users\rillab\AppData\Local\avocode\app-3.5.3\resources\electron.asar\renderer\api\remot
```

**Comment by crashmajstr** [comment]
Hello @brunorilla  ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

**Comment by brunorilla** [comment]
Hi @crashmajstr !
How are you?
I was trying to open the "grids and rulers" option and it crashed. Nothing more. Then the error appeared and the program got closed. Then I opened the program again and it worked properly. It was the first and only opportunity that this error happened. 
Thank you!

**Comment by vojtatranta** [comment]
@brunorilla there are two options in Grids and rulers. You can enable there Grid and Guides. Do you remember which one did you choose?

**Comment by crashmajstr** [comment]
@brunorilla there are two options in Grids and rulers. You can enable there Grid and Guides. Do you remember which one did you choose?
