### ISSUE TITLE
guides

### ISSUE THREAD

**Issue by ruslandjent** [avocode/avocode#2178]
---
* **Version**: 3.5.5
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 433635
---
```
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at Object._renderTickCanvas (file:///C:/Users/djent/AppData/Local/avocode/app-3.5.5/resources/app.asar/dist/avocode.min.js:1:3479115)
    at Object._updateTickCanvas (file:///C:/Users/djent/AppData/Local/avocode/app-3.5.5/resources/app.asar/dist/avocode.min.js:1:3478771)
    at Object.componentWillUpdate (file:///C:/Users/djent/AppData/Local/avocode/app-3.5.5/resources/app.asar/dist/avocode.min.js:1:3478523)
    at ReactCompositeComponentWrapper._performComponentUpdate (C:\Users\djent\AppData\Local\avocode\app-3.5.5\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:714:14)
    at ReactCompositeComponentWrapper.updateComponent (C:\Users\djent\AppData\Local\avocode\app-3.5.5\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:645:12)
    at ReactCompositeComponentWrapper.receiveComponent (C:\Users\djent\App
```

**Comment by crashmajstr** [comment]
Closing with respect to #2173
