### ISSUE TITLE
error

### ISSUE THREAD

**Issue by agalar** [avocode/avocode#2179]
---
* **Version**: 3.5.5
* **Sketch plugin version**: 51.2.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 83673
---
```
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at Object._renderTickCanvas (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3479115)
    at Object._updateTickCanvas (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3478771)
    at Object.componentWillUpdate (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3478523)
    at ReactCompositeComponentWrapper._performComponentUpdate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:714:14)
    at ReactCompositeComponentWrapper.updateComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:645:12)
    at ReactCompositeComponentWrapper.receiveComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dom/lib/
```

**Comment by crashmajstr** [comment]
Closing with respect to #2173
