### ISSUE TITLE
Sorry, it happened again. It is when I go to 'View>Rulers and Guides" and then it appears. With different kind of PSD files.

### ISSUE THREAD

**Issue by brunorilla** [avocode/avocode#2181]
---
* **Version**: 3.5.5
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 430583
---
```
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at Object._renderTickCanvas (file:///C:/Users/rillab/AppData/Local/avocode/app-3.5.5/resources/app.asar/dist/avocode.min.js:1:3479115)
    at Object._updateTickCanvas (file:///C:/Users/rillab/AppData/Local/avocode/app-3.5.5/resources/app.asar/dist/avocode.min.js:1:3478771)
    at Object.componentDidMount (file:///C:/Users/rillab/AppData/Local/avocode/app-3.5.5/resources/app.asar/dist/avocode.min.js:1:3478298)
    at CallbackQueue.notifyAll (C:\Users\rillab\AppData\Local\avocode\app-3.5.5\resources\app.asar\node_modules\react-dom\lib\CallbackQueue.js:76:22)
    at ReactReconcileTransaction.close (C:\Users\rillab\AppData\Local\avocode\app-3.5.5\resources\app.asar\node_modules\react-dom\lib\ReactReconcileTransaction.js:80:26)
    at ReactReconcileTransaction.closeAll (C:\Users\rillab\AppData\Local\avocode\app-3.5.5\resources\app.asar\node_modules\reac
```

**Comment by crashmajstr** [comment]
Closing with respect to #2173
