### ISSUE TITLE
Cannot open file

### ISSUE THREAD

**Issue by d3signer** [avocode/avocode#2182]
---
* **Version**: 3.3.2
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 46617
---
```
Error: OctopusApi#getOctopusLink() -> error (status: 401, error: "Not authenticated")
    at t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:146202)
    at t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:146637)
    at new t (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:147251)
    at Object.getErrorByStatusCode (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:66200)
    at Object.normalizeError (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:65637)
    at Object.normalizeResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:65383)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2799101
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2756005
    at <anonymous>
```

**Comment by d3signer** [comment]
Cant update cant do anything

**Comment by crashmajstr** [comment]
Hi @d3signer , 
thanks for reaching out. Please, can you try to reinstall your app? You can download it from here https://avocode.com/download.
Let me know if are able to install the new version and if everything works ok.
