### ISSUE TITLE
After try turn on designers guides

### ISSUE THREAD

**Issue by bogusweb** [avocode/avocode#2185]
---
* **Version**: 3.5.5
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 282707
---
```
Invariant Violation: Minified React error #136; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=136&args[]=Ruler for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at reactProdInvariant (/opt/Avocode/resources/app.asar/node_modules/react-dom/lib/reactProdInvariant.js:31:15)
    at ReactCompositeComponentWrapper.updateComponent (/opt/Avocode/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:584:219)
    at ReactCompositeComponentWrapper.receiveComponent (/opt/Avocode/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:547:10)
    at Object.receiveComponent (/opt/Avocode/resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:125:22)
    at Object.updateChildren (/opt/Avocode/resources/app.asar/node_modules/react-dom/lib/ReactChildReconciler.js:109:25)
    at ReactDOMComponent._reconcilerUpdateChildren (/opt/Avocode/resources/app.asar/node_modules/re
```

**Comment by crashmajstr** [comment]
Hi @bogusweb  ,
we are sorry about this issue. We have already found a solution and it will be released on Monday.
