### ISSUE TITLE
Report of not downloading of project

### ISSUE THREAD

**Issue by trendspb-developer** [avocode/avocode#2186]
---
* **Version**: 3.5.5
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 223433
---
```
Error: Remote octopus link missing
    at e.value (file:///C:/Users/Webmaster/AppData/Local/avocode/app-3.5.5/resources/app.asar/dist/avocode.min.js:1:3074071)
    at e.<anonymous> (file:///C:/Users/Webmaster/AppData/Local/avocode/app-3.5.5/resources/app.asar/dist/avocode.min.js:1:3073078)
    at tryCatch (C:\Users\Webmaster\AppData\Local\avocode\app-3.5.5\resources\app.asar\node_modules\regenerator-runtime\runtime.js:64:40)
    at Generator.invoke [as _invoke] (C:\Users\Webmaster\AppData\Local\avocode\app-3.5.5\resources\app.asar\node_modules\regenerator-runtime\runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\Webmaster\AppData\Local\avocode\app-3.5.5\resources\app.asar\node_modules\regenerator-runtime\runtime.js:116:21)
    at n (file:///C:/Users/Webmaster/AppData/Local/avocode/app-3.5.5/resources/app.asar/dist/avocode.min.js:1:3070534)
    at file:///C:/Users/Webmaster/AppData/Local/avocode/app-3.5.5/resources/app.asar/dist/avocode.min.js:1:3070
```

**Comment by crashmajstr** [comment]
Hi @trendspb-developer  , thanks for reporting this problem. Can you please send us the link the project or design where this is happening? We'll investigate the problem.

In the meantime, you can try reloading or re-uploading the design to see if the problem still occurs.

**Comment by crashmajstr** [comment]
Hi @trendspb-developer , thanks for reporting this problem. Can you please send us the link the project or design where this is happening? We'll investigate the problem.

In the meantime, you can try reloading or re-uploading the design to see if the problem still occurs.
