### ISSUE TITLE
Application crush

### ISSUE THREAD

**Issue by d3signer** [avocode/avocode#2187]
---
* **Version**: 3.5.5
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 46617
---
```
Error: Remote octopus link missing
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3074071)
    at e.<anonymous> (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3073078)
    at tryCatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:116:21)
    at n (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3070534)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3070673
    at new Promise (<anonymous>)
    at e.<anonymous> (file:///Applications/Avocode.app/Contents/Resources/app.a
```

**Comment by crashmajstr** [comment]
Hi @d3signer  , thanks for reporting this problem. Can you please send us the link the project or design where this is happening? We'll investigate the problem.

In the meantime, you can try reloading or re-uploading the design to see if the problem still occurs.

**Comment by crashmajstr** [comment]
Hi @d3signer , thanks for reporting this problem. Can you please send us the link the project or design where this is happening? We'll investigate the problem.

In the meantime, you can try reloading or re-uploading the design to see if the problem still occurs.
