### ISSUE TITLE
Too long loading metadata

### ISSUE THREAD

**Issue by maksimsukalov** [avocode/avocode#2188]
---
* **Version**: 3.5.5
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 431832
---
```
Error: Octopus not available
    at e.<anonymous> (file:///C:/Users/User/AppData/Local/avocode/app-3.5.5/resources/app.asar/dist/avocode.min.js:1:11922864)
    at tryCatch (C:\Users\User\AppData\Local\avocode\app-3.5.5\resources\app.asar\node_modules\regenerator-runtime\runtime.js:64:40)
    at Generator.invoke [as _invoke] (C:\Users\User\AppData\Local\avocode\app-3.5.5\resources\app.asar\node_modules\regenerator-runtime\runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\User\AppData\Local\avocode\app-3.5.5\resources\app.asar\node_modules\regenerator-runtime\runtime.js:116:21)
    at tryCatch (C:\Users\User\AppData\Local\avocode\app-3.5.5\resources\app.asar\node_modules\regenerator-runtime\runtime.js:64:40)
    at Generator.invoke [as _invoke] (C:\Users\User\AppData\Local\avocode\app-3.5.5\resources\app.asar\node_modules\regenerator-runtime\runtime.js:297:24)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\User\AppData\Local\avoco
```

**Comment by crashmajstr** [comment]
Hi @maksimsukalov , thanks for reporting this problem. Can you please send us the link the project or design where this is happening? We'll investigate the problem.

In the meantime, you can try reloading or re-uploading the design to see if the problem still occurs.

**Comment by crashmajstr** [comment]
Hi @maksimsukalov , thanks for reporting this problem. Can you please send us the link the project or design where this is happening? We'll investigate the problem.

In the meantime, you can try reloading or re-uploading the design to see if the problem still occurs.
