### ISSUE TITLE
Can't open psd files

### ISSUE THREAD

**Issue by Breeze8** [avocode/avocode#2193]
---
* **Version**: 3.5.6-web
* **Web/Desktop**: Web
* **Platform**: windows 10.0
* **Browser**: chrome 69.0.3497.100
* **Avocode UID**: 195760
---
```
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at https://cdn.app.avocode.com/dist/v-b1f0bac/js/avocode-web.min.js:32:197989
    at dt.__iterate (https://cdn.app.avocode.com/dist/v-b1f0bac/js/avocode-web.min.js:1:26039)
    at dt.forEach (https://cdn.app.avocode.com/dist/v-b1f0bac/js/avocode-web.min.js:1:50005)
    at d (https://cdn.app.avocode.com/dist/v-b1f0bac/js/avocode-web.min.js:32:197879)
    at p (https://cdn.app.avocode.com/dist/v-b1f0bac/js/avocode-web.min.js:32:198886)
    at Function.value (https://cdn.app.avocode.com/dist/v-b1f0bac/js/avocode-web.min.js:32:200193)
    at t._getUpdatedInspectorDocumentComposition (https://cdn.app.avocode.com/dist/v-b1f0bac/js/avocode-web.min.js:75:349246)
    at t._createInspectorDocumentComposition (https://cdn.app.avocode.com/dist/v-b1f0bac/js/avocode-web.min.js:75:347869)
    at t._handleAction (https://cdn.app.avocode.com/dist/v-b1f0bac/js/avoco
```

**Comment by crashmajstr** [comment]
Hello @Breeze8  ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

**Comment by crashmajstr** [comment]
Hello @Breeze8 ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?
