### ISSUE TITLE
Version**: 3.5.5

### ISSUE THREAD

**Issue by pashawol** [avocode/avocode#2194]
---
* **Version**: 3.5.5
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 140453
---
```
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at Object._renderTickCanvas (file:///C:/Users/User/AppData/Local/avocode/app-3.5.5/resources/app.asar/dist/avocode.min.js:1:3479359)
    at Object._updateTickCanvas (file:///C:/Users/User/AppData/Local/avocode/app-3.5.5/resources/app.asar/dist/avocode.min.js:1:3478771)
    at Object.componentWillUpdate (file:///C:/Users/User/AppData/Local/avocode/app-3.5.5/resources/app.asar/dist/avocode.min.js:1:3478523)
    at ReactCompositeComponentWrapper._performComponentUpdate (C:\Users\User\AppData\Local\avocode\app-3.5.5\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:714:14)
    at ReactCompositeComponentWrapper.updateComponent (C:\Users\User\AppData\Local\avocode\app-3.5.5\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:645:12)
    at ReactCompositeComponentWrapper.receiveComponent (C:\Users\User\AppData\L
```

**Comment by vojtatranta** [comment]
Hi @pashawol,
this issue is fixed in 3.5.6. just update your Avocode.
