### ISSUE TITLE
inifinite loading metadata

### ISSUE THREAD

**Issue by AlexKiZer** [avocode/avocode#2198]
---
* **Version**: 3.5.6
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 432251
---
```
Error: Remote octopus link missing
    at e.value (file:///C:/Users/Alexey/AppData/Local/avocode/app-3.5.6/resources/app.asar/dist/avocode.min.js:1:3073731)
    at e.<anonymous> (file:///C:/Users/Alexey/AppData/Local/avocode/app-3.5.6/resources/app.asar/dist/avocode.min.js:1:3072738)
    at tryCatch (C:\Users\Alexey\AppData\Local\avocode\app-3.5.6\resources\app.asar\node_modules\regenerator-runtime\runtime.js:64:40)
    at Generator.invoke [as _invoke] (C:\Users\Alexey\AppData\Local\avocode\app-3.5.6\resources\app.asar\node_modules\regenerator-runtime\runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\Alexey\AppData\Local\avocode\app-3.5.6\resources\app.asar\node_modules\regenerator-runtime\runtime.js:116:21)
    at n (file:///C:/Users/Alexey/AppData/Local/avocode/app-3.5.6/resources/app.asar/dist/avocode.min.js:1:3070194)
    at file:///C:/Users/Alexey/AppData/Local/avocode/app-3.5.6/resources/app.asar/dist/avocode.min.js:1:3070333
    at new Promis
```

**Comment by AlexKiZer** [comment]
after previous update,i cant use avacode. reinstall dont help me.

**Comment by jankuca** [comment]
Hello, thanks for reaching out!

This is strange. Does it happen with all your designs or just a particular one?

**Comment by AlexKiZer** [comment]
with all. when i try delete psd from project and reopen app ,its still here. its all about only app , with web version no problems with same psd.

**Comment by jankuca** [comment]
Can you try logging out and back in?

**Comment by jankuca** [comment]
Are you using a firewall which might block the Avocode app from connecting to our server API?

**Comment by AlexKiZer** [comment]
just try.disable all and its not firewall or antivirus.
