### ISSUE TITLE
Click on a image with ruler | An inexpected error has occurred

### ISSUE THREAD

**Issue by t1gu1** [avocode/avocode#2221]
- It's the first time on this build (it looks like it's not frequent.. pretty sure if I restart, all will be ok)
- I just click on a image.
- The present tools is the ruler

![image](https://user-images.githubusercontent.com/12479055/47373680-500b9e80-d6ba-11e8-87b6-0399d425dc3b.png)

---
* **Version**: 3.6.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 136162
---
```
TypeError: Cannot read property 'set' of undefined
    at file:///C:/Users/guill/AppData/Local/avocode/app-3.6.0/resources/app.asar/dist/avocode.min.js:1:4052319
    at updateInDeepMap (C:\Users\guill\AppData\Local\avocode\app-3.6.0\resources\app.asar\node_modules\immutable\dist\immutable.js:1973:22)
    at updateInDeepMap (C:\Users\guill\AppData\Local\avocode\app-3.6.0\resources\app.asar\node_modules\immutable\dist\immutable.js:1982:23)
    at updateInDeepMap (C:\Users\guill\AppData\Local\avocode\app-3.6.0\resources\app.asar\node_modules\immutable\dist\immutable.js:1982:23)
    at Map.updateIn (C:\Users\guill\AppData\Local\avocode\app-3.6.0\resources\app.asar\node_modules\immutable\dist\immutable.js:1280:26)
    at file:///C:/Users/guill/AppData/Local/avocode/app-3.6.0/resources/app.asar/dist/avocode.min.js:1:4052283
    at C:\Users\guill\AppData\Local\avocode\app-3.6.0\resources\app.asar\node_modules\immutable\dist\immutable.js:3907:58
    at C:\Users\guill\AppData\Local\avocode\app-
```

**Comment by vojtatranta** [comment]
Hi @t1gu1 ,
this issue is already fixed in `3.6.2`. Just update you application and you should be go to go.

Sorry for this error.
