### ISSUE TITLE
Can't load file

### ISSUE THREAD

**Issue by AndreyBragin** [avocode/avocode#2223]
I'm using mac mini 2014

---
* **Version**: 3.6.2
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 117474
---
```
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:175056
    at List.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at List.forEach (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4383:19)
    at f (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:174946)
    at d (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:175964)
    at Function.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:177271)
    at t._getUpdatedInspectorDocumentComposition (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:4397627)
    at t._createInspectorDocumentComposition (file:///App
```

**Comment by crashmajstr** [comment]
Hi @AndreyBragin , thanks for reporting this problem. Can you please send us the link the project or design where this is happening? We'll investigate the problem.

In the meantime, you can try reloading or re-uploading the design to see if the problem still occurs.

**Comment by AndreyBragin** [comment]
> Hi @AndreyBragin , thanks for reporting this problem. Can you please send us the link the project or design where this is happening? We'll investigate the problem.
> 
> In the meantime, you can try reloading or re-uploading the design to see if the problem still occurs.

https://app.avocode.com/projects/715806/

**Comment by crashmajstr** [comment]
Hi, I've just tried to upload your file on my end and it's working just fine. Please, can you try to reupload it or reupload via web app if the problem is the same? Thank you

**Comment by crashmajstr** [comment]
Hi, I've just tried to upload your file on my end and it's working just fine. Please, can you try to reupload it or reupload via web app if the problem is the same? Thank you
