### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by obalaushko** [avocode/avocode#2226]
---
* **Version**: 3.6.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 320600
---
```
TypeError: Cannot read property 'set' of undefined
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:4052319
    at updateInDeepMap (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:1973:22)
    at updateInDeepMap (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:1982:23)
    at updateInDeepMap (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:1982:23)
    at Map.updateIn (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:1280:26)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:4052283
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3907:58
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2701:43
    at List.__iterate (/
```

**Comment by vojtatranta** [comment]
Hi @ZolotoeKoputo ,
this issue is fiex in 3.6.2. Please, update your application.

Sorry for this troubles.
