### ISSUE TITLE
not download .psd

### ISSUE THREAD

**Issue by Valentina-Aktanko** [avocode/avocode#2232]
---
* **Version**: 3.6.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 444355
---
```
Error: Octopus not available
    at e.<anonymous> (file:///C:/Users/v.aktanko/AppData/Local/avocode/app-3.6.2/resources/app.asar/dist/avocode.min.js:1:10414099)
    at tryCatch (C:\Users\v.aktanko\AppData\Local\avocode\app-3.6.2\resources\app.asar\node_modules\regenerator-runtime\runtime.js:64:40)
    at Generator.invoke [as _invoke] (C:\Users\v.aktanko\AppData\Local\avocode\app-3.6.2\resources\app.asar\node_modules\regenerator-runtime\runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\v.aktanko\AppData\Local\avocode\app-3.6.2\resources\app.asar\node_modules\regenerator-runtime\runtime.js:116:21)
    at tryCatch (C:\Users\v.aktanko\AppData\Local\avocode\app-3.6.2\resources\app.asar\node_modules\regenerator-runtime\runtime.js:64:40)
    at Generator.invoke [as _invoke] (C:\Users\v.aktanko\AppData\Local\avocode\app-3.6.2\resources\app.asar\node_modules\regenerator-runtime\runtime.js:297:24)
    at Generator.prototype.(anonymous function) [as next] (C:\
```

**Comment by crashmajstr** [comment]
Hello @Valentina-Aktanko  ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

**Comment by Valentina-Aktanko** [comment]
Good day! 
The project was already open, but for some reason it began to load again. An error appeared in the middle of the download, restarting the desctop application did not help. After some time I tried again, successfully. Now the error no longer manifests itself.

**Comment by crashmajstr** [comment]
Ok, thank you for the provided info. I'll close this issue for now, but please let me know if it happens again in the future.
Best,
Josef
