### ISSUE TITLE
error

### ISSUE THREAD

**Issue by EduardZiganshin** [avocode/avocode#2233]
---
* **Version**: 3.6.2-web.2
* **Web/Desktop**: Web
* **Platform**: windows 10.0
* **Browser**: chrome 70.0.3538.77
* **Avocode UID**: 111132
---
```
Error: The preview could not be loaded.
    at e.<anonymous> (https://cdn.app.avocode.com/dist/v-1cea384/js/avocode-web.min.js:156:1896797)
    at S (https://cdn.app.avocode.com/dist/v-1cea384/js/avocode-web.min.js:58:350771)
    at Generator._invoke (https://cdn.app.avocode.com/dist/v-1cea384/js/avocode-web.min.js:58:350536)
    at Generator.e.(anonymous function) [as next] (https://cdn.app.avocode.com/dist/v-1cea384/js/avocode-web.min.js:58:350950)
    at r (https://cdn.app.avocode.com/dist/v-1cea384/js/avocode-web.min.js:156:1884818)
    at https://cdn.app.avocode.com/dist/v-1cea384/js/avocode-web.min.js:156:1884957
    at new Promise (<anonymous>)
    at e.<anonymous> (https://cdn.app.avocode.com/dist/v-1cea384/js/avocode-web.min.js:156:1884755)
    at e.<anonymous> (https://cdn.app.avocode.com/dist/v-1cea384/js/avocode-web.min.js:156:1897317)
    at e.<anonymous> (https://cdn.app.avocode.com/dist/v-1cea384/js/avocode-web.min.js:156:1893931)
    at S (https://cdn.app.avocode.com/di
```

**Comment by crashmajstr** [comment]
Hello @EduardZiganshin  ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

**Comment by crashmajstr** [comment]
Hello @EduardZiganshin ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?
