### ISSUE TITLE
ds

### ISSUE THREAD

**Issue by Walentun** [avocode/avocode#2251]
---
* **Version**: 3.6.3
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 447477
---
```
Error: Octopus not available
    at e.<anonymous> (file:///C:/Users/W/AppData/Local/avocode/app-3.6.3/resources/app.asar/dist/avocode.min.js:1:10426273)
    at tryCatch (C:\Users\W\AppData\Local\avocode\app-3.6.3\resources\app.asar\node_modules\regenerator-runtime\runtime.js:64:40)
    at Generator.invoke [as _invoke] (C:\Users\W\AppData\Local\avocode\app-3.6.3\resources\app.asar\node_modules\regenerator-runtime\runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\W\AppData\Local\avocode\app-3.6.3\resources\app.asar\node_modules\regenerator-runtime\runtime.js:116:21)
    at tryCatch (C:\Users\W\AppData\Local\avocode\app-3.6.3\resources\app.asar\node_modules\regenerator-runtime\runtime.js:64:40)
    at Generator.invoke [as _invoke] (C:\Users\W\AppData\Local\avocode\app-3.6.3\resources\app.asar\node_modules\regenerator-runtime\runtime.js:297:24)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\W\AppData\Local\avocode\app-3.6.3\resource
```

**Comment by crashmajstr** [comment]
Hello @Walentun ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

**Comment by crashmajstr** [comment]
Hello @Walentun ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?
