### ISSUE TITLE
document failed to load

### ISSUE THREAD

**Issue by ruslandjent** [avocode/avocode#2252]
---
* **Version**: 3.6.3
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 457046
---
```
Error: Octopus not available
    at e.<anonymous> (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:10426273)
    at tryCatch (/opt/Avocode/resources/app.asar/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/opt/Avocode/resources/app.asar/node_modules/regenerator-runtime/runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (/opt/Avocode/resources/app.asar/node_modules/regenerator-runtime/runtime.js:116:21)
    at tryCatch (/opt/Avocode/resources/app.asar/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/opt/Avocode/resources/app.asar/node_modules/regenerator-runtime/runtime.js:297:24)
    at Generator.prototype.(anonymous function) [as next] (/opt/Avocode/resources/app.asar/node_modules/regenerator-runtime/runtime.js:116:21)
    at r (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:10420242)
    at file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1
```

**Comment by ruslandjent** [comment]
firstly some of the layers did not loaded, then this error appeared

**Comment by crashmajstr** [comment]
Hello @ruslandjent  ,
Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design? Does it also happen in the web app?
Let me know and we'll try to fix everything asap.

**Comment by ruslandjent** [comment]
All the layers loaded just fine, it is my fault i did not see it. 
But error appeared when i tried to use the design menu 
![screenshot from 2018-11-08 16-59-42](https://user-images.githubusercontent.com/41237074/48197674-4059ae80-e378-11e8-9d38-c3afb6ade52e.png)

Also everything is working fine now. Ty for response

**Comment by crashmajstr** [comment]
Ok, let me know if you have any other problem, comments or concerns in the future :)
Best, 
Josef
