### ISSUE TITLE
It alert an error on just load a document. In that time i open this psd in browser on avocode site with out problems.

### ISSUE THREAD

**Issue by trendspb-developer** [avocode/avocode#2256]
---
* **Version**: 3.6.3
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 223433
---
```
Error: Octopus not available
    at e.<anonymous> (file:///C:/Users/Webmaster/AppData/Local/avocode/app-3.6.3/resources/app.asar/dist/avocode.min.js:1:10426273)
    at tryCatch (C:\Users\Webmaster\AppData\Local\avocode\app-3.6.3\resources\app.asar\node_modules\regenerator-runtime\runtime.js:64:40)
    at Generator.invoke [as _invoke] (C:\Users\Webmaster\AppData\Local\avocode\app-3.6.3\resources\app.asar\node_modules\regenerator-runtime\runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\Webmaster\AppData\Local\avocode\app-3.6.3\resources\app.asar\node_modules\regenerator-runtime\runtime.js:116:21)
    at tryCatch (C:\Users\Webmaster\AppData\Local\avocode\app-3.6.3\resources\app.asar\node_modules\regenerator-runtime\runtime.js:64:40)
    at Generator.invoke [as _invoke] (C:\Users\Webmaster\AppData\Local\avocode\app-3.6.3\resources\app.asar\node_modules\regenerator-runtime\runtime.js:297:24)
    at Generator.prototype.(anonymous function) [as next] (C:\
```

**Comment by crashmajstr** [comment]
Hello @trendspb-developer 
thank you for reporting this. I am sorry for the inconvenience. We are aware of this issue, hopefully, we'll be able to release the fix this week. I'll let you know once it's out, for know please, use the web version.

**Comment by crashmajstr** [comment]
Hello @trendspb-developer 
thank you for reporting this. I am sorry for the inconvenience. We are aware of this issue, hopefully, we'll be able to release the fix this week. I'll let you know once it's out, for know please, use the web version.
