### ISSUE TITLE
SVG Export problem

### ISSUE THREAD

**Issue by derzach** [avocode/avocode#226]
I'm having a problem to quick export some svg's

-----

```
TypeError: Cannot read property 'length' of undefined
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/octopus-svg/lib/octopus-reader.js:1:1076
  at convertPaths (/Applications/Avocode.app/Contents/Resources/app/node_modules/octopus-svg/lib/octopus-reader.js:1:1130)
  at t.convertShape (/Applications/Avocode.app/Contents/Resources/app/node_modules/octopus-svg/lib/main.js:1:5238)
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/octopus-svg/lib/main.js:1:2955
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:610:21
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:249:17
  at iterate (/Applications/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:149:13)
  at async.eachSeries (/Applications/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:165:9)
  at _asyncMap (/Applications/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:248:13)
  at Object.mapSeries (/Applications/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:231:23)
  at Object.async.series (/Applications/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:608:19)
  at t.convert (/Applications/Avocode.app/Contents/Resources/app/node_modules/octopus-svg/lib/main.js:1:2851)
  at s (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/export.js:10:13)
  at module.exports.exportRule (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/export.js:10:383)
  at b._instantExport (/Applications/Avocode.app/Contents/Resources/app/node_modules/export-panel/lib/stores/export.js:19:217)
  at b._register (/Applications/Avocode.app/Contents/Resources/app/node_modules/export-panel/lib/stores/export.js:21:190)
  at Object.ID_14 (/Applications/Avocode.app/Contents/Resources/app/node_modules/export-panel/lib/stores/export.js:1:174)
  at a.Dispatcher.$Dispatcher_invokeCallback (/Applications/Avocode.app/Contents/Resources/app/node_modules/flux/lib/Dispatcher.js:220:35)
  at a.Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app/node_modules/flux/lib/Dispatcher.js:195:14)
  at a.handleViewAction (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/dispatcher.js:1:405)
  at b.module.exports.instantExport [as exportCallback] (/Applications/Avocode.app/Contents/Resources/app/node_modules/export-panel/lib/actions/export.js:3:324)
  at b.module.exports.b.onConfirm (/Applications/Avocode.app/Contents/Resources/app/node_modules/export-panel/lib/instant-export-dialog.js:7:113)
  at b.module.exports.b.onSave (/Applications/Avocode.app/Contents/Resources/app/node_modules/export-panel/lib/instant-export-dialog.js:6:209)
  at b.onSave (/Applications/Avocode.app/Contents/Resources/app/node_modules/export-panel/lib/instant-export-dialog.js:1:142)
  at HTMLButtonElement.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:182:36)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLButtonElement.elemData.handle (/Applications/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4360:46)

```

**Comment by petrbrzek** [comment]
Thanks for reporting the issue. We'll look into it.

**Comment by PavelGavlik** [comment]
This should be added in 2.2.0. Feel free to reopen this if you run into any problems.
