### ISSUE TITLE
Design "tuso_main_new_top.psd" user t@d3signer.ru

### ISSUE THREAD

**Issue by d3signer** [avocode/avocode#2262]
---
* **Version**: 3.6.2
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 46617
---
```
RangeError [ERR_OUT_OF_RANGE]: The value of "mode" is out of range. Received 33206
    at Object.fs.fchmod (fs.js:1070:11)
    at Object.fchmod (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/graceful-fs/polyfills.js:237:17)
    at mode (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/vinyl-fs/lib/fileOperations.js:132:10)
    at onStat (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/vinyl-fs/lib/fileOperations.js:125:14)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:183:5)
```

**Comment by d3signer** [comment]
design tuso_new_main_top.psd
user t@d3signer.ru

**Comment by crashmajstr** [comment]
Hi @d3signer ,
I am sorry for the inconvenience, but I can see that you have an outdated app, please, can you update your app and let me know if the problem still persists? 
Thank you

**Comment by crashmajstr** [comment]
Hi @d3signer ,
I am sorry for the inconvenience, but I can see that you have an outdated app, please, can you update your app and let me know if the problem still persists?
Thank you
