### ISSUE TITLE
crash subfolder

### ISSUE THREAD

**Issue by camburley** [avocode/avocode#2265]
Crashed when trying to drag files into subfolder

---
* **Version**: 3.6.3-web-rollback.1
* **Web/Desktop**: Web
* **Platform**: macosx 10.14.2
* **Browser**: chrome 70.0.3538.102
* **Avocode UID**: 447812
---
```
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at e.exports (https://cdn.app.avocode.com/dist/v-f738d24/js/avocode-web.min.js:27:98411)
    at e.dispatch (https://cdn.app.avocode.com/dist/v-f738d24/js/avocode-web.min.js:127:204906)
    at e.value (https://cdn.app.avocode.com/dist/v-f738d24/js/avocode-web.min.js:105:35596)
    at t.value (https://cdn.app.avocode.com/dist/v-f738d24/js/avocode-web.min.js:105:34016)
    at t.value (https://cdn.app.avocode.com/dist/v-f738d24/js/avocode-web.min.js:58:1047271)
    at t.value (https://cdn.app.avocode.com/dist/v-f738d24/js/avocode-web.min.js:58:78672)
    at updateComponent (https://cdn.app.avocode.com/dist/v-f738d24/js/avocode-web.min.js:75:513348)
    at u.receiveComponent (https://cdn.app.avocode.com/dist/v-f738d24/js/avocode-web.min.js:75:512750)
    at Object.receiveComponent (https://cdn.app.avocode.com/dist/v-f738d24/js/avocode-web.min.js:32:368074)
```

**Comment by crashmajstr** [comment]
Hello @camburley ,
thank you for reporting this. I am sorry for the inconvenience. Does this error happen every time you try to move designs to subfolders or it was just a one time error? 
Please, let me know, thank you

**Comment by camburley** [comment]
Not sure — haven’t reproduced it a bunch of times

CB

**Comment by crashmajstr** [comment]
Ok, please let me know once this error will appear again. Thank you and sorry for the inconvenience. I'll close this issue for now.
