### ISSUE TITLE
Document failed to load

### ISSUE THREAD

**Issue by ievgenii-syrotenko** [avocode/avocode#2267]
---
* **Version**: 3.6.3
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 65196
---
```
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at file:///C:/Users/Evgenii/AppData/Local/avocode/app-3.6.3/resources/app.asar/dist/avocode.min.js:1:178919
    at List.__iterate (C:\Users\Evgenii\AppData\Local\avocode\app-3.6.3\resources\app.asar\node_modules\immutable\dist\immutable.js:2208:13)
    at List.forEach (C:\Users\Evgenii\AppData\Local\avocode\app-3.6.3\resources\app.asar\node_modules\immutable\dist\immutable.js:4383:19)
    at f (file:///C:/Users/Evgenii/AppData/Local/avocode/app-3.6.3/resources/app.asar/dist/avocode.min.js:1:178809)
    at d (file:///C:/Users/Evgenii/AppData/Local/avocode/app-3.6.3/resources/app.asar/dist/avocode.min.js:1:179827)
    at Function.value (file:///C:/Users/Evgenii/AppData/Local/avocode/app-3.6.3/resources/app.asar/dist/avocode.min.js:1:181134)
    at t._getUpdatedInspectorDocumentComposition (file:///C:/Users/Evgenii/AppData/Local/avocode/app-3.6.3/reso
```

**Comment by crashmajstr** [comment]
Hello @justevgenii . 
Could you describe exactly how this error happened? Were you trying to open a specific design? If so, does this error occur every time you try to open that design? Please, let me know and we'll try to fix the issue as soon as possible.

**Comment by ievgenii-syrotenko** [comment]
@crashmajstr Yes, I tried to open PSD design file. And yes, this error appers everytime when I try to open deisgn.

**Comment by crashmajstr** [comment]
@justevgenii please, can you send me a link to a design you have problems with? Thank you

**Comment by ievgenii-syrotenko** [comment]
@crashmajstr https://app.avocode.com/view/8f781fbb921a4832adbb7c4a0574c853/_/comments

**Comment by crashmajstr** [comment]
Thank you for sending this over, I've just tried to reproduce it on my end and everything is working just ok. 
Do you have the same problem in the web app when you try to open this design? Can you try to re-upload it, please?
I am sorry for the inconvenience, let me know

**Comment by crashmajstr** [comment]
Thank you for sending this over, I've just tried to reproduce it on my end and everything is working just ok.
Do you have the same problem in the web app when you try to open this design? Can you try to re-upload it, please?
I am sorry for the inconvenience, let me know
