### ISSUE TITLE
Take it problem

### ISSUE THREAD

**Issue by EmilEvil1** [avocode/avocode#2268]
---
* **Version**: 3.6.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 465911
---
```
TypeError: Cannot read property 'set' of undefined
    at file:///C:/Users/emil/AppData/Local/avocode/app-3.6.0/resources/app.asar/dist/avocode.min.js:1:4052319
    at updateInDeepMap (C:\Users\emil\AppData\Local\avocode\app-3.6.0\resources\app.asar\node_modules\immutable\dist\immutable.js:1973:22)
    at updateInDeepMap (C:\Users\emil\AppData\Local\avocode\app-3.6.0\resources\app.asar\node_modules\immutable\dist\immutable.js:1982:23)
    at updateInDeepMap (C:\Users\emil\AppData\Local\avocode\app-3.6.0\resources\app.asar\node_modules\immutable\dist\immutable.js:1982:23)
    at Map.updateIn (C:\Users\emil\AppData\Local\avocode\app-3.6.0\resources\app.asar\node_modules\immutable\dist\immutable.js:1280:26)
    at file:///C:/Users/emil/AppData/Local/avocode/app-3.6.0/resources/app.asar/dist/avocode.min.js:1:4052283
    at C:\Users\emil\AppData\Local\avocode\app-3.6.0\resources\app.asar\node_modules\immutable\dist\immutable.js:3907:58
    at C:\Users\emil\AppData\Local\avocode\app-3.6.0\re

**Comment by crashmajstr** [comment]
Hello. 
Could you describe exactly how this error happened? Were you trying to open a specific design? If so, does this error occur every time you try to open that design? 
Please, let me know and we'll try to fix the issue as soon as possible.

**Comment by crashmajstr** [comment]
Hello @EmilEvil1 it looks like you have an outdated version of Avocode, please update it and let me know if the error still persists.
Best,
Josef
