### ISSUE TITLE
ыв

### ISSUE THREAD

**Issue by AtomicHeart** [avocode/avocode#2269]
---
* **Version**: 3.5.3
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 231455
---
```
Error: Remote octopus link missing
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3074070)
    at e.<anonymous> (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3073077)
    at tryCatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:116:21)
    at n (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3070533)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3070672
    at new Promise (<anonymous>)
    at e.<anonymous> (file:///Applications/Avocode.app/Contents/Resources/app.a
```

**Comment by crashmajstr** [comment]
Hello @RhytmGuitar 

Could you describe exactly how this error happened? Were you trying to open a specific design? If so, does this error occur every time you try to open that design? 

Please, let me know and we'll try to fix the issue as soon as possible.
