### ISSUE TITLE
ыы

### ISSUE THREAD

**Issue by artem67801** [avocode/avocode#2275]
---
* **Version**: 3.0.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 482948
---
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new ArrayBuffer (C:\Users\arti2\AppData\Local\avocode\app-3.0.0\resources\app.asar\node_modules\core-js\modules\_typed-buffer.js:247:14)
    at Rendering (C:\Users\arti2\AppData\Local\avocode\app-3.0.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:1:23650)
    at C:\Users\arti2\AppData\Local\avocode\app-3.0.0\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:1122
    at Promise (<anonymous>)
    at C:\Users\arti2\AppData\Local\avocode\app-3.0.0\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:637
    at <anonymous>
```

**Comment by crashmajstr** [comment]
Hello @artem67801 thank you for reporting this, but I can see that you have an outdated app, please update your app to the latest version https://avocode.com/download and let me know if the problem still persists.
