### ISSUE TITLE
failed to load

### ISSUE THREAD

**Issue by aneena-thomas** [avocode/avocode#2279]
---
* **Version**: 3.5.3
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 174597
---
```
Error: Remote octopus link missing
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3074070)
    at e.<anonymous> (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3073077)
    at tryCatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:116:21)
    at n (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3070533)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3070672
    at new Promise (<anonymous>)
    at e.<anonymous> (file:///Applications/Avocode.app/Contents/Resources/app.a
```

**Comment by crashmajstr** [comment]
Hello,
​
could you describe exactly how this error happened? Were you trying to open a specific design? If so, does this error occur every time you try to open that design? 

Please, let me know and we'll try to fix the issue as soon as possible.

**Comment by crashmajstr** [comment]
Hello,
​
could you describe exactly how this error happened? Were you trying to open a specific design? If so, does this error occur every time you try to open that design?

Please, let me know and we'll try to fix the issue as soon as possible.

**Comment by aneena-thomas** [comment]
Hi,

It happened when I trying to open a design no the specific one.Sometimes it
occurs now its happening every time.Please have look at the screen shot i
have attached with this.But its working fine in website.App side only its
not working
[image: Screen Shot 2018-12-31 at 2.57.05 PM.png]


Thanks and Regards,
Aneena Susan Thomas | Software Engineer | Experion Technologies | [
www.experionglobal.com ]( http://www.experionglobal.com/ )

**Comment by crashmajstr** [comment]
Ok, thank you for sharing this with me. We'll take a look at that. Please, for now, use the web version of our app. Thank you and sorry for the inconvenience.
