### ISSUE TITLE
Upload issue

### ISSUE THREAD

**Issue by garbinluca** [avocode/avocode#228]
Describe your problem here…

-----

```
TypeError: Cannot read property 'id' of undefined
  at b._loadRevisionToView (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/avocode.js:24:441)
  at b.openRevision (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/avocode.js:36:436)
  at b.openDocument (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/avocode.js:36:305)
  at b._handleAction (/Applications/Avocode.app/Contents/Resources/app/node_modules/project-manager/lib/stores/project.js:25:100)
  at Object.ID_11 (/Applications/Avocode.app/Contents/Resources/app/node_modules/project-manager/lib/stores/project.js:1:144)
  at a.Dispatcher.$Dispatcher_invokeCallback (/Applications/Avocode.app/Contents/Resources/app/node_modules/flux/lib/Dispatcher.js:220:35)
  at a.Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app/node_modules/flux/lib/Dispatcher.js:195:14)
  at a.handleViewAction (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/dispatcher.js:1:405)
  at Object.module.exports.openDocument (/Applications/Avocode.app/Contents/Resources/app/node_modules/project-manager/lib/actions/project.js:2:139)
  at [object Object].module.exports.React.createClass._onDoubleClick (/Applications/Avocode.app/Contents/Resources/app/node_modules/project-manager/lib/components/document-item.js:2:168)
  at Object.executeDispatch (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/EventPluginUtils.js:110:21)
  at SimpleEventPlugin.executeDispatch (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/SimpleEventPlugin.js:305:40)
  at forEachEventDispatch (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/EventPluginUtils.js:98:5)
  at Object.executeDispatchesInOrder (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/EventPluginUtils.js:119:3)
  at executeDispatchesAndRelease (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/EventPluginHub.js:46:22)
  at forEachAccumulated (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/forEachAccumulated.js:25:8)
  at Object.EventPluginHub.processEventQueue (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/EventPluginHub.js:251:5)
  at runEventQueueInBatch (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
  at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/ReactEventEmitterMixin.js:44:5)
  at handleTopLevelImpl (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/ReactEventListener.js:80:24)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/Transaction.js:134:20)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
  at Object.batchedUpdates (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/ReactUpdates.js:109:20)
  at ReactEventListener.dispatchEvent (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/ReactEventListener.js:175:20)

```

**Comment by rychlis** [comment]
This should be fixed in Avocode 2.2.0, feel free to re-open the issue if you encounter this again in the latest version.
