### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KozakevichVitaliy** [avocode/avocode#2301]
---
* **Version**: 2.26.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 554628
---
```
TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.
    at _glShaderSource (C:\Users\Віталій\AppData\Local\avocode\app-2.26.2\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:1:676469)
    at aP (C:\Users\Віталій\AppData\Local\avocode\app-2.26.2\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:5:141067)
    at Ju (C:\Users\Віталій\AppData\Local\avocode\app-2.26.2\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:8:173649)
    at Array.RP (C:\Users\Віталій\AppData\Local\avocode\app-2.26.2\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:5:176024)
    at Wt (C:\Users\Віталій\AppData\Local\avocode\app-2.26.2\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:8:102495)
    at Zta (C:\Users\Віталій\AppData\Local\avocode\app-2.26.2\resources\app.asar\node_modules\@avocode\rendering-emsc
```

**Comment by crashmajstr** [comment]
Hello @KozakevichVitaliy it looks like that you have an outdated version of our app. Please, download the latest one at avocode.com/download and let me know if the error still happens.
Best,
Josef

**Comment by KozakevichVitaliy** [comment]
Hello Joseph
I've installed an updated version of app
And the error no longer exists
Tnx for help))

пн, 11 бер. 2019, 10:42 користувач Josef Kettner <notifications@github.com>
пише:

**Comment by crashmajstr** [comment]
Glad to hear that @KozakevichVitaliy

Let me know if you have any other questions, comments or concerns in the future.
Best,
Josef
