### ISSUE TITLE
Error while opening .psd

### ISSUE THREAD

**Issue by Protonn** [avocode/avocode#231]
Error while opening .psd

-----

```
TypeError: Cannot read property 'originalBounds' of undefined
  at new b (/home/codesushi/Downloads/Avocode/resources/app/node_modules/avocode/lib/document.js:4:159)
  at /home/codesushi/Downloads/Avocode/resources/app/node_modules/avocode/lib/user.js:29:398
  at fs.js:295:14
  at Object.oncomplete (fs.js:93:15)

```

**Comment by PavelGavlik** [comment]
This should be fixed in 2.2.0. Feel free to reopen this if you run into any problems.
