### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PetrKulko** [avocode/avocode#2319]
---
* **Version**: 2.26.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 1150806
---
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new ArrayBuffer (C:\Users\Peter\AppData\Local\avocode\app-2.26.2\resources\app.asar\node_modules\core-js\modules\_typed-buffer.js:247:14)
    at Rendering (C:\Users\Peter\AppData\Local\avocode\app-2.26.2\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:1:23650)
    at C:\Users\Peter\AppData\Local\avocode\app-2.26.2\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:1122
    at Promise (<anonymous>)
    at C:\Users\Peter\AppData\Local\avocode\app-2.26.2\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:637
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @KulkoP, thanks for the report, but do you realize you're using an extremely old version of Avocode? Please, download the latest from https://avocode.com/download and let us know how that goes 😉
