### ISSUE TITLE
Error when exporting slice

### ISSUE THREAD

**Issue by marlonmarcello** [avocode/avocode#234]
I'm running into this error when exporting a slice to jpg.
Linux Ubuntu 14.10

-----

```
TypeError: Cannot read property 'bounds' of undefined
  at Object.module.exports.getBoundsForLayers (/home/marlon/Downloads/Avocode/resources/app/node_modules/avocode/lib/document.js:13:159)
  at module.exports.exportRule (/home/marlon/Downloads/Avocode/resources/app/node_modules/avocode/lib/export.js:10:395)
  at b._instantExport (/home/marlon/Downloads/Avocode/resources/app/node_modules/export-panel/lib/stores/export.js:19:217)
  at b._register (/home/marlon/Downloads/Avocode/resources/app/node_modules/export-panel/lib/stores/export.js:21:190)
  at Object.ID_14 (/home/marlon/Downloads/Avocode/resources/app/node_modules/export-panel/lib/stores/export.js:1:174)
  at a.Dispatcher.$Dispatcher_invokeCallback (/home/marlon/Downloads/Avocode/resources/app/node_modules/flux/lib/Dispatcher.js:220:35)
  at a.Dispatcher.dispatch (/home/marlon/Downloads/Avocode/resources/app/node_modules/flux/lib/Dispatcher.js:195:14)
  at a.handleViewAction (/home/marlon/Downloads/Avocode/resources/app/node_modules/avocode/lib/dispatcher.js:1:405)
  at b.module.exports.instantExport [as exportCallback] (/home/marlon/Downloads/Avocode/resources/app/node_modules/export-panel/lib/actions/export.js:3:324)
  at b.module.exports.b.onConfirm (/home/marlon/Downloads/Avocode/resources/app/node_modules/export-panel/lib/instant-export-dialog.js:7:113)
  at b.module.exports.b.onSave (/home/marlon/Downloads/Avocode/resources/app/node_modules/export-panel/lib/instant-export-dialog.js:6:209)
  at b.onSave (/home/marlon/Downloads/Avocode/resources/app/node_modules/export-panel/lib/instant-export-dialog.js:1:142)
  at HTMLButtonElement.<anonymous> (/home/marlon/Downloads/Avocode/resources/app/node_modules/space-pen/lib/space-pen.js:182:36)
  at HTMLButtonElement.jQuery.event.dispatch (/home/marlon/Downloads/Avocode/resources/app/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLButtonElement.elemData.handle (/home/marlon/Downloads/Avocode/resources/app/node_modules/space-pen/vendor/jquery.js:4360:46)

```

**Comment by PavelGavlik** [comment]
This should be added in 2.2.0. Feel free to reopen this if you run to any problems.
