### ISSUE TITLE
I'm getting a popup saying my Avocode has gone bad when slicing a PSD and clicking Export, but everything appears to be working fine. Mac OS X Yosemite. 

### ISSUE THREAD

**Issue by tomcwatts** [avocode/avocode#235]
Describe your problem here…

-----

```
TypeError: Cannot read property 'x' of null
  at r (/Applications/Avocode.app/Contents/Resources/app/node_modules/slice-tool/lib/slice-tool.js:1:565)
  at b.module.exports.b._mousemoveDrag (/Applications/Avocode.app/Contents/Resources/app/node_modules/slice-tool/lib/slice-tool.js:10:127)
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/slice-tool/lib/slice-tool.js:1:148
  at c.module.exports.Emitter.emit (/Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at c.mousewheel (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/stage.js:23:423)
  at HTMLCanvasElement.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/stage.js:1:324)

```

**Comment by PavelGavlik** [comment]
This should be added in 2.2.0. Feel free to reopen this if you run into any problems.
