### ISSUE TITLE
Crash on first laucnh

### ISSUE THREAD

**Issue by remirobert** [avocode/avocode#239]
Describe your problem here…

-----

```
Error: Cannot find module 'remote'
  at Function.Module._resolveFilename (module.js:344:15)
  at Function.Module._load (module.js:286:25)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///Users/remirobert/Downloads/Avocode.app/Contents/Resources/app/static/index.js:25:25)
  at http://cdn.mxpnl.com/libs/mixpanel-2.2.min.js:23:231

```

**Comment by rychlis** [comment]
This should be fixed in Avocode 2.2.0, feel free to re-open the issue if you encounter this again in the latest version.
