### ISSUE TITLE
Random

### ISSUE THREAD

**Issue by Chrisriis** [avocode/avocode#241]
Describe your problem here…

-----

```
Error: InvalidStateError: not a child of this node
  at Error (native)
  at a._removeDomChild (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/overlay.js:3:464)
  at a.removeDomChild (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/overlay.js:4:103)
  at a.removeChild (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/overlay.js:3:343)
  at f.clearGroup (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode-selection-stageview/lib/main.js:11:248)
  at f.clear (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode-selection-stageview/lib/main.js:11:376)
  at b.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode-selection-stageview/lib/main.js:3:187)
  at b.EventEmitter.emit (/Applications/Avocode.app/Contents/Resources/app/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
  at b.emitSelected (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/selection.js:6:502)
  at b.setActiveView (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/avocode.js:40:16)
  at HTMLDivElement.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/avocode.js:10:337)
  at HTMLDivElement.jQuery.event.dispatch (/Applications/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLDivElement.elemData.handle (/Applications/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4360:46)
  at Object.jQuery.event.trigger (/Applications/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4594:12)
  at HTMLDivElement.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5119:17)
  at Function.jQuery.extend.each (/Applications/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:590:23)
  at PaneContainerView.jQuery.fn.jQuery.each (/Applications/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:237:17)
  at PaneContainerView.jQuery.fn.extend.trigger (/Applications/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5118:15)
  at PaneContainerView.module.exports.PaneContainerView.onActivePaneItemChanged (/Applications/Avocode.app/Contents/Resources/app/src/pane-container-view.js:87:19)
  at /Applications/Avocode.app/Contents/Resources/app/src/pane-container-view.js:3:61
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at Signal.module.exports.Emitter.emitSlow (/Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:154:47)
  at Signal.module.exports.Emitter.emit (/Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:107:30)
  at Signal.module.exports.Signal.emitValue (/Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/signal.js:82:19)
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/behavior.js:81:29
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at Behavior.module.exports.Emitter.emitSlow (/Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:154:47)
  at Behavior.module.exports.Emitter.emit (/Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:107:30)
  at Behavior.module.exports.Behavior.emit (/Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/behavior.js:44:38)
  at Behavior.module.exports.Signal.emitValue (/Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/signal.js:82:19)
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/signal.js:252:38
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at Behavior.module.exports.Emitter.emitSlow (/Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:154:47)
  at Behavior.module.exports.Emitter.emit (/Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:107:30)
  at Behavior.module.exports.Behavior.emit (/Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/behavior.js:44:38)
  at Behavior.module.exports.Signal.emitValue (/Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/signal.js:82:19)
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/signal.js:173:28
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at Behavior.module.exports.Emitter.emitSlow (/Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:154:47)
  at Behavior.module.exports.Emitter.emit (/Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:107:30)
  at Behavior.module.exports.Behavior.emit (/Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/behavior.js:44:38)
  at Behavior.module.exports.Signal.emitValue (/Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/signal.js:82:19)
  at Pane.module.exports.Model.set (/Applications/Avocode.app/Contents/Resources/app/node_modules/theorist/lib/model.js:166:21)
  at Pane.accessor.set (/Applications/Avocode.app/Contents/Resources/app/node_modules/theorist/lib/model.js:57:23)
  at Pane.module.exports.Pane.activateItem (/Applications/Avocode.app/Contents/Resources/app/src/pane.js:176:25)
  at PaneView._results.push._this.(anonymous function) [as activateItem] (/Applications/Avocode.app/Contents/Resources/app/node_modules/delegato/lib/delegator.js:67:61)
  at tabs-tab.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:214:24)
  at HTMLUListElement.jQuery.event.dispatch (/Applications/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLUListElement.elemData.handle (/Applications/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4360:46)

```

**Comment by rychlis** [comment]
This should be fixed in Avocode 2.2.0, feel free to re-open the issue if you encounter this again in the latest version.
