### ISSUE TITLE
Dont open PSD for mac 10.10.4

### ISSUE THREAD

**Issue by maxicms** [avocode/avocode#242]
Describe your problem here…

-----

```
TypeError: Cannot read property 'title' of undefined
  at Object.module.exports.setLanguage (/Applications/Avocode.app/Contents/Resources/app/node_modules/code-panel/lib/main.js:8:476)
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/code-panel/lib/main.js:5:56
  at Emitter.module.exports.Emitter.emit (/Applications/Avocode.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:71:11)
  at b.module.exports.b.openDocument (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/active-document.js:3:261)
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/user.js:30:84
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/assets-loader.js:2:390
  at process._tickCallback (node.js:378:11)

```

**Comment by maxicms** [comment]
Already I solved the problem
