### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by indrajeet-ambadekar** [avocode/avocode#243]
Describe your problem here…

-----

```
Error: Cannot find module 'bootstrap/js/tooltip'
  at Function.Module._resolveFilename (module.js:344:15)
  at Function.Module._load (module.js:286:25)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Atom.module.exports.Atom.requireWithGlobals (/Users/indrajeet/Downloads/Avocode.app/Contents/Resources/app/src/atom.js:624:7)
  at /Users/indrajeet/Downloads/Avocode.app/Contents/Resources/app/src/space-pen-extensions.js:62:17
  at /Users/indrajeet/Downloads/Avocode.app/Contents/Resources/app/node_modules/underscore/underscore.js:890:21
  at [object Object].jQuery.fn.destroyTooltip (/Users/indrajeet/Downloads/Avocode.app/Contents/Resources/app/src/space-pen-extensions.js:119:5)
  at tabs-tab.module.exports.TabView.destroyTooltip (/Users/indrajeet/Downloads/Avocode.app/Contents/Resources/app/node_modules/tabs/lib/tab-view.js:150:22)
  at tabs-tab.module.exports.TabView.updateTooltip (/Users/indrajeet/Downloads/Avocode.app/Contents/Resources/app/node_modules/tabs/lib/tab-view.js:132:12)
  at tabs-tab.<anonymous> (/Users/indrajeet/Downloads/Avocode.app/Contents/Resources/app/node_modules/tabs/lib/tab-view.js:110:17)

```

**Comment by PavelGavlik** [comment]
This should be fixed in 2.2.0. Feel free to reopen this if you run into any problems.
