### ISSUE TITLE
member joining error

### ISSUE THREAD

**Issue by pshoria** [avocode/avocode#247]
Describe your problem here…

-----

```
TypeError: Cannot read property 'id' of null
  at Function.b.fromDesign (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/upload-target.js:1:463)
  at [object Object].module.exports.React.createClass._createUploadTarget (/Applications/Avocode.app/Contents/Resources/app/node_modules/project-manager/lib/components/project-manager.js:2:364)
  at [object Object].module.exports.React.createClass.getInitialState (/Applications/Avocode.app/Contents/Resources/app/node_modules/project-manager/lib/components/project-manager.js:2:226)
  at [object Object].mountComponent (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/ReactCompositeComponent.js:781:48)
  at [object Object].ReactComponent.Mixin._mountComponentIntoNode (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/ReactComponent.js:405:25)
  at ReactReconcileTransaction.Mixin.perform (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/Transaction.js:134:20)
  at [object Object].ReactComponent.Mixin.mountComponentIntoNode (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/ReactComponent.js:381:19)
  at Object._renderNewRootComponent (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/ReactMount.js:312:25)
  at Object.ReactMount.render (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/ReactMount.js:381:32)
  at a.module.exports.a.setReactComponent (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/avocode-view.js:3:395)
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/avocode.js:21:125
  at Object.ReactContext.withContext (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/ReactContext.js:51:16)
  at b.withContext (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/avocode.js:15:497)
  at b._addProjectManagerView (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/avocode.js:21:88)
  at b._openAvocodeResource (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/avocode.js:20:196)
  at b.opener (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/avocode.js:17:501)
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/avocode.js:1:252
  at Workspace.module.exports.Workspace.openUriInPane (/Applications/Avocode.app/Contents/Resources/app/src/workspace.js:205:22)
  at Workspace.module.exports.Workspace.open (/Applications/Avocode.app/Contents/Resources/app/src/workspace.js:142:19)
  at b.openManager (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/avocode.js:16:482)
  at b._onUserData (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/avocode.js:30:193)
  at b._onUserData (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/avocode.js:1:252)
  at a.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/avocode.js:31:50)
  at a.emit (events.js:104:17)
  at a.module.exports.a.emitChange (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/stores/base.js:1:499)
  at a._dispatcherCallback (/Applications/Avocode.app/Contents/Resources/app/node_modules/auth/lib/stores/user.js:2:474)
  at Object.ID_5 (/Applications/Avocode.app/Contents/Resources/app/node_modules/auth/lib/stores/user.js:1:130)
  at a.Dispatcher.$Dispatcher_invokeCallback (/Applications/Avocode.app/Contents/Resources/app/node_modules/flux/lib/Dispatcher.js:220:35)
  at a.Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app/node_modules/flux/lib/Dispatcher.js:195:14)
  at a.handleViewAction (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/dispatcher.js:1:405)
  at Object.module.exports.receiveUser (/Applications/Avocode.app/Contents/Resources/app/node_modules/auth/lib/actions/user.js:1:211)
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/auth/lib/utils/api.js:2:93
  at Request.callback (/Applications/Avocode.app/Contents/Resources/app/node_modules/superagent/lib/node/index.js:746:30)
  at Request.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/node_modules/superagent/lib/node/index.js:135:10)
  at Request.emit (events.js:107:17)
  at IncomingMessage.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/node_modules/superagent/lib/node/index.js:938:12)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:907:16
  at process._tickCallback (node.js:378:11)

```

**Comment by rychlis** [comment]
This should be fixed in Avocode 2.2.0, feel free to re-open the issue if you encounter this again in the latest version.
