### ISSUE TITLE
mac Avocode app crash

### ISSUE THREAD

**Issue by liakwee** [avocode/avocode#248]
Describe your problem here…
Downloading the psd halfway and it just crash
-----

```
Error: Emitter has been disposed
  at Emitter.module.exports.Emitter.on (/Applications/Avocode.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:31:15)
  at a.module.exports.a.onDidClose (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/avocode-view.js:2:215)
  at b._loadRevisionToView (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/avocode.js:25:56)
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/avocode.js:24:6
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/user.js:23:33
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/user.js:26:165
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/progress.js:5:104
  at done (/Applications/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:135:19)
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:32:16
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/progress.js:5:11
  at b._handleRevisionResult (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/revision-download-queue.js:5:344)
  at next (/Applications/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:801:43)
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:32:16
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/revision-download-queue.js:4:172
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/user.js:19:74
  at a.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/downloader.js:2:71)
  at a.g (events.js:199:16)
  at a.emit (events.js:129:20)
  at a.resolve (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/downloader.js:2:201)
  at b._handleRequestComplete (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/downloader.js:9:136)
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/downloader.js:1:316
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at Task.module.exports.Emitter.emitSlow (/Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:154:47)
  at Task.module.exports.Emitter.emit (/Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:107:30)
  at ChildProcess.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/src/task.js:70:29)
  at ChildProcess.emit (events.js:110:17)
  at handleMessage (child_process.js:323:10)
  at Pipe.channel.onread (child_process.js:351:11)

```

**Comment by rychlis** [comment]
This should be fixed in Avocode 2.2.0, feel free to re-open the issue if you encounter this again in the latest version.
