### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by egor-a-trubnikov-panov** [avocode/avocode#252]
Describe your problem here…

-----

```
TypeError: Cannot read property 'addDocument' of undefined
  at e._addDesignToProject (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/user.js:23:320)
  at e._handleDesignAssignment (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/user.js:6:404)
  at c.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/user.js:1:164)
  at c.emit (events.js:129:20)
  at Request._callback (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/api.js:6:244)
  at Request.self.callback (/Applications/Avocode.app/Contents/Resources/app/node_modules/request/request.js:368:22)
  at Request.emit (events.js:110:17)
  at Request.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/node_modules/request/request.js:1219:14)
  at Request.emit (events.js:129:20)
  at IncomingMessage.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/node_modules/request/request.js:1167:12)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:907:16
  at process._tickCallback (node.js:378:11)

```

**Comment by rychlis** [comment]
This should be fixed in Avocode 2.2.0, feel free to re-open the issue if you encounter this again in the latest version.
