### ISSUE TITLE
Something went wrong message on uploading a design

### ISSUE THREAD

**Issue by SkoebaSteve** [avocode/avocode#254]
Describe your problem here…

-----

```
Error: Invalid state: assign of upload without an upload slot
  at Error (native)
  at c._assignUploadedFileAsDesignRevision (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/uploader.js:7:436)
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/uploader.js:6:413
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/uploader.js:8:507
  at Request._callback (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/api.js:6:276)
  at Request.self.callback (/Applications/Avocode.app/Contents/Resources/app/node_modules/request/request.js:368:22)
  at Request.emit (events.js:110:17)
  at Request.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/node_modules/request/request.js:1219:14)
  at Request.emit (events.js:129:20)
  at IncomingMessage.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/node_modules/request/request.js:1167:12)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:907:16
  at process._tickCallback (node.js:378:11)

```

**Comment by SkoebaSteve** [comment]
![screen shot 2015-05-18 at 5 31 19 pm](https://cloud.githubusercontent.com/assets/3404599/7676101/ba60eb14-fd83-11e4-9796-a49190bfd3df.png)

**Comment by jankuca** [comment]
Thanks for the report.

Do you by any chance remember what kind of upload this was? Was it a new design upload to an existing project, to a new project (created via the upload assign sidebar form) or just a design revision upload?

**Comment by SkoebaSteve** [comment]
It's a new design for an existing project.

**Comment by SkoebaSteve** [comment]
I just tried uploading it through the website and it says the filesize exceeds the 200MB limit. This only applies for the web version right? The file is about 280MB big

**Comment by jankuca** [comment]
Unfortunately, this applies for the app as well. It will be failing silently in the app until the next release in which the same message is showing.

**Comment by rychlis** [comment]
The handling of PSDs sized over the limit is fixed in the latest Avocode. If you have Photoshop, you can upload such PSDs with the [Photoshop Extension](manager.avocode.com/downloads/) for now
