### ISSUE TITLE
Looks like it can't sync with web version.

### ISSUE THREAD

**Issue by riversy** [avocode/avocode#255]
Describe your problem here…

-----

```
TypeError: Cannot set property 'layers' of undefined
  at b.accessor.set (/home/riversy/bin/avacode/resources/app/node_modules/avocode/lib/selection.js:3:364)
  at b.setSelection (/home/riversy/bin/avacode/resources/app/node_modules/avocode/lib/selection.js:8:170)
  at c.deselectGuides_ (/home/riversy/bin/avacode/resources/app/node_modules/avocode-guides/lib/ruler-manager.js:15:154)
  at c.toggleRulers (/home/riversy/bin/avacode/resources/app/node_modules/avocode-guides/lib/ruler-manager.js:5:6)
  at Immediate._onImmediate (/home/riversy/bin/avacode/resources/app/node_modules/avocode-guides/lib/main.js:1:371)
  at processImmediate [as _immediateCallback] (timers.js:374:17)

```

**Comment by rychlis** [comment]
This should be fixed in Avocode 2.2.0, feel free to re-open the issue if you encounter this again in the latest version.
