### ISSUE TITLE
Error when opening PSD

### ISSUE THREAD

**Issue by joska** [avocode/avocode#256]
Describe your problem here…

-----

```
TypeError: Cannot read property 'originalBounds' of undefined
  at new b (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/document.js:4:159)
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/user.js:29:398
  at fs.js:295:14
  at Object.oncomplete (fs.js:93:15)

```

**Comment by petrbrzek** [comment]
Duplicate of #231. This is going to be fixed in upcoming release.
