### ISSUE TITLE
Crash after new design processing

### ISSUE THREAD

**Issue by uchamb** [avocode/avocode#260]
Describe your problem here…

-----

```
TypeError: Cannot read property 'id' of undefined
  at b.<anonymous> (/home/ucha/Avocode/Avocode/resources/app/node_modules/avocode/lib/avocode.js:40:448)
  at b.EventEmitter.emit (/home/ucha/Avocode/Avocode/resources/app/node_modules/eventemitter2/lib/eventemitter2.js:312:17)
  at /home/ucha/Avocode/Avocode/resources/app/node_modules/avocode/lib/user.js:12:366
  at /home/ucha/Avocode/Avocode/resources/app/node_modules/avocode/lib/progress.js:5:104
  at Object.async.each (/home/ucha/Avocode/Avocode/resources/app/node_modules/async/lib/async.js:121:20)
  at Function.e.forEach (/home/ucha/Avocode/Avocode/resources/app/node_modules/avocode/lib/progress.js:4:458)
  at e._downloadRevisions (/home/ucha/Avocode/Avocode/resources/app/node_modules/avocode/lib/user.js:13:217)
  at e._syncProjects (/home/ucha/Avocode/Avocode/resources/app/node_modules/avocode/lib/user.js:12:283)
  at e._onUserData (/home/ucha/Avocode/Avocode/resources/app/node_modules/avocode/lib/user.js:11:387)
  at /home/ucha/Avocode/Avocode/resources/app/node_modules/avocode/lib/user.js:1:164
  at Request._callback (/home/ucha/Avocode/Avocode/resources/app/node_modules/avocode/lib/api.js:3:294)
  at Request.self.callback (/home/ucha/Avocode/Avocode/resources/app/node_modules/request/request.js:360:22)
  at Request.emit (events.js:110:17)
  at Request.<anonymous> (/home/ucha/Avocode/Avocode/resources/app/node_modules/request/request.js:1202:14)
  at Request.emit (events.js:129:20)
  at IncomingMessage.<anonymous> (/home/ucha/Avocode/Avocode/resources/app/node_modules/request/request.js:1150:12)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:907:16
  at process._tickCallback (node.js:378:11)

```

**Comment by rychlis** [comment]
This should be fixed in Avocode 2.2.0, feel free to re-open the issue if you encounter this again in the latest version.
