### ISSUE TITLE
9

### ISSUE THREAD

**Issue by paulbigdrop** [avocode/avocode#261]
Describe your problem here…

-----

```
TypeError: Cannot read property 'length' of undefined
  at m (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/text-commands.js:1:286)
  at HTMLDivElement.c (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/text-commands.js:1:521)
  at HTMLDivElement.wrapper (/Applications/Avocode.app/Contents/Resources/app/node_modules/lodash/index.js:3639:19)
  at HTMLDivElement.jQuery.event.dispatch (/Applications/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLDivElement.elemData.handle (/Applications/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4360:46)
  at Object.jQuery.event.trigger (/Applications/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4594:12)
  at HTMLButtonElement.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5119:17)
  at Function.jQuery.extend.each (/Applications/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:590:23)
  at [object Object].jQuery.fn.jQuery.each (/Applications/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:237:17)
  at [object Object].jQuery.fn.extend.trigger (/Applications/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5118:15)
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Avocode.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:170:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Avocode.app/Contents/Resources/app/src/select-list-view.js:274:21)
  at HTMLLIElement.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/src/select-list-view.js:125:19)
  at HTMLOListElement.jQuery.event.dispatch (/Applications/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLOListElement.elemData.handle (/Applications/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4360:46)

```

**Comment by rychlis** [comment]
This should be fixed in Avocode 2.2.0, feel free to re-open the issue if you encounter this again in the latest version.
