### ISSUE TITLE
Unexpected error while Avocode was running in the background

### ISSUE THREAD

**Issue by VadimWelldone** [avocode/avocode#263]
Describe your problem here…

-----

```
TypeError: Cannot read property 'organization' of undefined
  at e._onUserData (/home/starglider/Downloads/Avocode/resources/app/node_modules/avocode/lib/user.js:11:226)
  at /home/starglider/Downloads/Avocode/resources/app/node_modules/avocode/lib/user.js:1:164
  at Request._callback (/home/starglider/Downloads/Avocode/resources/app/node_modules/avocode/lib/api.js:3:294)
  at Request.self.callback (/home/starglider/Downloads/Avocode/resources/app/node_modules/request/request.js:360:22)
  at Request.emit (events.js:110:17)
  at Request.<anonymous> (/home/starglider/Downloads/Avocode/resources/app/node_modules/request/request.js:1202:14)
  at Request.emit (events.js:129:20)
  at IncomingMessage.<anonymous> (/home/starglider/Downloads/Avocode/resources/app/node_modules/request/request.js:1150:12)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:907:16
  at process._tickCallback (node.js:378:11)

```

**Comment by rychlis** [comment]
This should be fixed in Avocode 2.2.0, feel free to re-open the issue if you encounter this again in the latest version.
