### ISSUE TITLE
avocode error

### ISSUE THREAD

**Issue by susiko** [avocode/avocode#265]
Describe your problem here…

-----

```
TypeError: Cannot read property 'addRevision' of null
  at /home/susa/Avocode/resources/app/node_modules/avocode/lib/user.js:22:501
  at /home/susa/Avocode/resources/app/node_modules/avocode/lib/user.js:25:342
  at Request._callback (/home/susa/Avocode/resources/app/node_modules/avocode/lib/api.js:4:28)
  at self.callback (/home/susa/Avocode/resources/app/node_modules/request/request.js:360:22)
  at Request.emit (events.js:107:17)
  at /home/susa/Avocode/resources/app/node_modules/request/request.js:958:12

```

**Comment by rychlis** [comment]
This should be fixed in Avocode 2.2.0, feel free to re-open the issue if you encounter this again in the latest version.
