### ISSUE TITLE
File won't upload or preview

### ISSUE THREAD

**Issue by johnchourajr** [avocode/avocode#266]
Won't upload or preview to avocode.

-----

```
TypeError: Cannot read property 'id' of null
  at [object Object].module.exports.React.createClass._onAbortClick (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/assign-design-panel.js:6:374)
  at Object.executeDispatch (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/EventPluginUtils.js:110:21)
  at SimpleEventPlugin.executeDispatch (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/SimpleEventPlugin.js:305:40)
  at forEachEventDispatch (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/EventPluginUtils.js:98:5)
  at Object.executeDispatchesInOrder (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/EventPluginUtils.js:119:3)
  at executeDispatchesAndRelease (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/EventPluginHub.js:46:22)
  at forEachAccumulated (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/forEachAccumulated.js:25:8)
  at Object.EventPluginHub.processEventQueue (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/EventPluginHub.js:251:5)
  at runEventQueueInBatch (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
  at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/ReactEventEmitterMixin.js:44:5)
  at handleTopLevelImpl (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/ReactEventListener.js:80:24)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/Transaction.js:134:20)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
  at Object.batchedUpdates (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/ReactUpdates.js:109:20)
  at ReactEventListener.dispatchEvent (/Applications/Avocode.app/Contents/Resources/app/node_modules/react/lib/ReactEventListener.js:175:20)

```

**Comment by rychlis** [comment]
This should be fixed in Avocode 2.2.0, feel free to re-open the issue if you encounter this again in the latest version.
