### ISSUE TITLE
Emitter has been disposed

### ISSUE THREAD

**Issue by paulbigdrop** [avocode/avocode#269]
Describe your problem here…

-----

```
Error: Emitter has been disposed
  at Emitter.module.exports.Emitter.on (/Applications/Avocode.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:31:15)
  at a.module.exports.a.onDidClose (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/avocode-view.js:2:215)
  at c.createManager_ (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode-guides/lib/ruler-manager.js:12:63)
  at c.getManagerForView (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode-guides/lib/ruler-manager.js:11:114)
  at c.handleActiveView_ (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode-guides/lib/ruler-manager.js:10:172)
  at b.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode-guides/lib/ruler-manager.js:1:138)
  at b.EventEmitter.emit (/Applications/Avocode.app/Contents/Resources/app/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
  at b.setActiveView (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/avocode.js:39:290)
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/avocode.js:26:223

```

**Comment by rychlis** [comment]
Do you still experience this issue on Avocode 2.2.0? Or was it an one-time event? Whend did this happen?

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
