### ISSUE TITLE
Nedari sa prihlasit

### ISSUE THREAD

**Issue by janaobzerova** [avocode/avocode#270]
Describe your problem here…

-----

```
TypeError: Cannot read property 'ok' of undefined
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/auth/lib/utils/api.js:2:52
  at Request.callback (/Applications/Avocode.app/Contents/Resources/app/node_modules/superagent/lib/node/index.js:746:30)
  at ClientRequest.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/node_modules/superagent/lib/node/index.js:711:10)
  at ClientRequest.emit (events.js:107:17)
  at TLSSocket.socketErrorListener (_http_client.js:271:9)
  at TLSSocket.emit (events.js:129:20)
  at net.js:915:16
  at process._tickCallback (node.js:378:11)

```

**Comment by petrbrzek** [comment]
Avocode is experiencing network issues. Our network provider is working on that, we should be stable again in about 30 minutes. Check our [twitter](https://twitter.com/avocode/) for more information.
