### ISSUE TITLE
TypeError: Cannot read property 'addDocument' of undefined

### ISSUE THREAD

**Issue by Lykhoyda** [avocode/avocode#275]
Describe your problem here…

-----

```
TypeError: Cannot read property 'addDocument' of undefined
  at e._addDesignToProject (/home/antony/Desktop/Avocode/resources/app/node_modules/avocode/lib/user.js:23:320)
  at e._handleDesignAssignment (/home/antony/Desktop/Avocode/resources/app/node_modules/avocode/lib/user.js:6:404)
  at c.<anonymous> (/home/antony/Desktop/Avocode/resources/app/node_modules/avocode/lib/user.js:1:164)
  at c.emit (events.js:129:20)
  at Request._callback (/home/antony/Desktop/Avocode/resources/app/node_modules/avocode/lib/api.js:6:244)
  at Request.self.callback (/home/antony/Desktop/Avocode/resources/app/node_modules/request/request.js:360:22)
  at Request.emit (events.js:110:17)
  at Request.<anonymous> (/home/antony/Desktop/Avocode/resources/app/node_modules/request/request.js:1202:14)
  at Request.emit (events.js:129:20)
  at IncomingMessage.<anonymous> (/home/antony/Desktop/Avocode/resources/app/node_modules/request/request.js:1150:12)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:907:16
  at process._tickCallback (node.js:378:11)

```

**Comment by rychlis** [comment]
This should be fixed in Avocode 2.2.0, feel free to re-open the issue if you encounter this again in the latest version.
