### ISSUE TITLE
oh my god

### ISSUE THREAD

**Issue by egor-a-trubnikov-panov** [avocode/avocode#279]
Describe your problem here…

-----

```
Error: Invalid state: assign of upload without an upload slot
  at Error (native)
  at c._assignUploadedFileAsDesignRevision (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/uploader.js:7:436)
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/uploader.js:6:413
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/uploader.js:8:507
  at Request._callback (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/api.js:6:276)
  at Request.self.callback (/Applications/Avocode.app/Contents/Resources/app/node_modules/request/request.js:368:22)
  at Request.emit (events.js:110:17)
  at Request.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/node_modules/request/request.js:1219:14)
  at Request.emit (events.js:129:20)
  at IncomingMessage.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/node_modules/request/request.js:1167:12)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:907:16
  at process._tickCallback (node.js:378:11)

```

**Comment by rychlis** [comment]
This should be fixed in Avocode 2.2.0, feel free to re-open the issue if you encounter this again in the latest version.
