### ISSUE TITLE
Error on failed login

### ISSUE THREAD

**Issue by offline** [avocode/avocode#280]
Used wrong credentials and after couple of minutes avocode crashed with next error:
-----

```
TypeError: Cannot read property 'ok' of undefined
  at /home/andrey/Avocode/resources/app/node_modules/auth/lib/utils/api.js:2:52
  at Request.callback (/home/andrey/Avocode/resources/app/node_modules/superagent/lib/node/index.js:746:30)
  at ClientRequest.<anonymous> (/home/andrey/Avocode/resources/app/node_modules/superagent/lib/node/index.js:711:10)
  at ClientRequest.emit (events.js:107:17)
  at TLSSocket.socketOnEnd (_http_client.js:292:9)
  at TLSSocket.emit (events.js:129:20)
  at _stream_readable.js:907:16
  at process._tickCallback (node.js:378:11)

```

**Comment by rychlis** [comment]
This should be fixed in Avocode 2.2.0, feel free to re-open the issue if you encounter this again in the latest version.

If you want to use a Proxy server, see our [new article](https://avocode.zendesk.com/hc/en-us/articles/203402352)
