### ISSUE TITLE
error open file

### ISSUE THREAD

**Issue by lnked** [avocode/avocode#281]
Describe your problem here…

-----

```
TypeError: undefined is not a function
  at [object Object].jQuery.fn.destroyTooltip (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/src/space-pen-extensions.js:120:17)
  at tabs-tab.module.exports.TabView.destroyTooltip (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/node_modules/tabs/lib/tab-view.js:150:22)
  at tabs-tab.module.exports.TabView.updateTooltip (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/node_modules/tabs/lib/tab-view.js:132:12)
  at HTMLDivElement.<anonymous> (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/node_modules/tabs/lib/tab-view.js:41:24)
  at HTMLDivElement.jQuery.event.dispatch (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLDivElement.elemData.handle (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4360:46)
  at Object.jQuery.event.trigger (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4594:12)
  at HTMLDivElement.<anonymous> (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5119:17)
  at Function.jQuery.extend.each (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:590:23)
  at a.jQuery.fn.jQuery.each (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:237:17)
  at a.jQuery.fn.extend.trigger (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5118:15)
  at a.module.exports.a.setTitle (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/avocode-view.js:3:118)
  at b._updateView (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/upload-view-manager.js:6:202)
  at b._handleUploadStoreChange (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/upload-view-manager.js:4:297)
  at b.<anonymous> (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/upload-view-manager.js:1:128)
  at b.emit (events.js:129:20)
  at b.module.exports.a.emitChange (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/stores/base.js:1:499)
  at b._handleAction (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/stores/upload-store.js:6:311)
  at Object.ID_10 (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/stores/upload-store.js:1:126)
  at a.Dispatcher.$Dispatcher_invokeCallback (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/node_modules/flux/lib/Dispatcher.js:220:35)
  at a.Dispatcher.dispatch (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/node_modules/flux/lib/Dispatcher.js:195:14)
  at a.handleServerAction (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/dispatcher.js:1:503)
  at c._emitItemUploadProgress (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/uploader.js:16:39)
  at FormData.<anonymous> (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/uploader.js:13:131)
  at FormData.emit (events.js:107:17)
  at ReadStream.<anonymous> (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/uploader.js:14:98)
  at ReadStream.emit (events.js:129:20)
  at ReadStream.source.emit (/Users/edik/Downloads/Avocode.app/Contents/Resources/app/node_modules/delayed-stream/lib/delayed_stream.js:30:21)
  at ReadStream.Readable.read (_stream_readable.js:372:10)
  at flow (_stream_readable.js:749:26)
  at resume_ (_stream_readable.js:729:3)
  at _stream_readable.js:716:7
  at process._tickCallback (node.js:378:11)

```

**Comment by rychlis** [comment]
This should be fixed in Avocode 2.2.0, feel free to re-open the issue if you encounter this again in the latest version.
