### ISSUE TITLE
Error crash after 5-10 min work

### ISSUE THREAD

**Issue by Menma27** [avocode/avocode#292]
Describe your problem here…

-----

```
TypeError: Cannot read property 'bounds' of undefined
  at Object.module.exports.getBoundsForLayers (/home/menma/IDE/Avocode/resources/app/node_modules/avocode/lib/document.js:13:159)
  at module.exports.exportRule (/home/menma/IDE/Avocode/resources/app/node_modules/avocode/lib/export.js:10:395)
  at b._instantExport (/home/menma/IDE/Avocode/resources/app/node_modules/export-panel/lib/stores/export.js:19:217)
  at b._register (/home/menma/IDE/Avocode/resources/app/node_modules/export-panel/lib/stores/export.js:21:190)
  at Object.ID_14 (/home/menma/IDE/Avocode/resources/app/node_modules/export-panel/lib/stores/export.js:1:174)
  at a.Dispatcher.$Dispatcher_invokeCallback (/home/menma/IDE/Avocode/resources/app/node_modules/flux/lib/Dispatcher.js:220:35)
  at a.Dispatcher.dispatch (/home/menma/IDE/Avocode/resources/app/node_modules/flux/lib/Dispatcher.js:195:14)
  at a.handleViewAction (/home/menma/IDE/Avocode/resources/app/node_modules/avocode/lib/dispatcher.js:1:405)
  at b.module.exports.instantExport [as exportCallback] (/home/menma/IDE/Avocode/resources/app/node_modules/export-panel/lib/actions/export.js:3:324)
  at b.module.exports.b.onConfirm (/home/menma/IDE/Avocode/resources/app/node_modules/export-panel/lib/instant-export-dialog.js:7:113)
  at b.module.exports.b.onSave (/home/menma/IDE/Avocode/resources/app/node_modules/export-panel/lib/instant-export-dialog.js:6:209)
  at b.onSave (/home/menma/IDE/Avocode/resources/app/node_modules/export-panel/lib/instant-export-dialog.js:1:142)
  at HTMLButtonElement.<anonymous> (/home/menma/IDE/Avocode/resources/app/node_modules/space-pen/lib/space-pen.js:182:36)
  at HTMLButtonElement.jQuery.event.dispatch (/home/menma/IDE/Avocode/resources/app/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLButtonElement.elemData.handle (/home/menma/IDE/Avocode/resources/app/node_modules/space-pen/vendor/jquery.js:4360:46)

```

**Comment by rychlis** [comment]
Are you on Avocode 2.2.0?

**Comment by Menma27** [comment]
Install couple hours ago. Crashes Stopped and no updates warning. At last! Theme can be closed
