### ISSUE TITLE
Sorry. But this is one more.

### ISSUE THREAD

**Issue by MihaylovAlexey** [avocode/avocode#299]
Describe your problem here…

-----

```
TypeError: Cannot read property 'x' of null
    at e.calculateBounds (/home/alexey/Рабочий стол/Avocode/resources/app.asar/node_modules/@avocode/select-tool/lib/select-tool.js:1:8100)
    at e.mousemoveDrag (/home/alexey/Рабочий стол/Avocode/resources/app.asar/node_modules/@avocode/select-tool/lib/select-tool.js:1:4976)
    at /home/alexey/Рабочий стол/Avocode/resources/app.asar/node_modules/@avocode/select-tool/lib/select-tool.js:1:240
    at t.module.exports.Emitter.emit (/home/alexey/Рабочий стол/Avocode/resources/app.asar/node_modules/emissary/lib/emitter.js:118:15)
    at t.mousewheel (/home/alexey/Рабочий стол/Avocode/resources/app.asar/node_modules/@avocode/core/lib/stage.js:1:12624)
    at HTMLCanvasElement.<anonymous> (/home/alexey/Рабочий стол/Avocode/resources/app.asar/node_modules/@avocode/core/lib/stage.js:1:422)
    at EventEmitter.ipc.sendSync (/home/alexey/Рабочий стол/Avocode/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as getSize] (/home/alexey/Рабочий стол/Avocode/resources/atom.asar/renderer/api/lib/remote.js:110:29)
    at Atom.module.exports.Atom.getWindowDimensions (/home/alexey/Рабочий стол/Avocode/resources/app.asar/src/atom.js:534:29)
    at Atom.module.exports.Atom.storeDefaultWindowDimensions (/home/alexey/Рабочий стол/Avocode/resources/app.asar/src/atom.js:566:25)
    at /home/alexey/Рабочий стол/Avocode/resources/app.asar/src/window-event-handler.js:103:21
    at handler (/home/alexey/Рабочий стол/Avocode/resources/app.asar/src/space-pen-extensions.js:115:32)
    at jQuery.event.dispatch (/home/alexey/Рабочий стол/Avocode/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
    at elemData.handle (/home/alexey/Рабочий стол/Avocode/resources/app.asar/node_modules/space-pen/vendor
```

**Comment by PavelGavlik** [comment]
Hi, could you please tell me, how did this error happen? Is it different from #298?

**Comment by MihaylovAlexey** [comment]
Hello, Pavel.

Unfortunately, I don`t remember, how did it happen. I got these two messages after a single crush. 
Also, if you have some time, I would like you to check this issue: 
https://github.com/avocode/avocode/issues/294 . 

Thanks

**Comment by petrbrzek** [comment]
I cannot reproduce this issue but I fix some code that probably caused it. The "fix" will part of the next release. I leave the issue open until proven to be fixed.

**Comment by petrbrzek** [comment]
@MihaylovAlexey We released 2.2.1 version yesterday. It should fix this issue. Can you let us know if that works?
