### ISSUE TITLE
Got avocode error..

### ISSUE THREAD

**Issue by ogoog** [avocode/avocode#302]
Describe your problem here…

-----

```
TypeError: Cannot read property 'id' of null
  at Function.b.fromDesign (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/upload-target.js:1:463)
  at [object Object].module.exports.React.createClass._createUploadTarget (/Applications/Avocode.app/Contents/Resources/app/node_modules/project-manager/lib/components/project-manager.js:2:364)
  at [object Object].module.exports.React.createClass._onChange (/Applications/Avocode.app/Contents/Resources/app/node_modules/project-manager/lib/components/project-manager.js:3:401)
  at b.emit (events.js:104:17)
  at b.module.exports.a.emitChange (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/stores/base.js:1:499)
  at b._onProjectsLoaded (/Applications/Avocode.app/Contents/Resources/app/node_modules/project-manager/lib/stores/project.js:6:127)
  at b.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/node_modules/project-manager/lib/stores/project.js:1:144)
  at b.EventEmitter.emit (/Applications/Avocode.app/Contents/Resources/app/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
  at e._syncProjects (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/user.js:12:148)
  at e._onUserData (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/user.js:11:387)
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/user.js:1:164
  at Request._callback (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/api.js:3:294)
  at Request.self.callback (/Applications/Avocode.app/Contents/Resources/app/node_modules/request/request.js:368:22)
  at Request.emit (events.js:110:17)
  at Request.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/node_modules/request/request.js:1219:14)
  at Request.emit (events.js:129:20)
  at IncomingMessage.<anonymous> (/Applications/Avocode.app/Contents/Resources/app/node_modules/request/request.js:1167:12)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:907:16
  at process._tickCallback (node.js:378:11)

```

**Comment by jankuca** [comment]
Hi, thanks for reporting.

Where in the application were you when this occurred? Were you by any change browsing a sketch folder?

**Comment by ogoog** [comment]
I was not actively using avocode it was just open in the background. But I think
my designer may have just made an update to his files. In any case, it's working
fine now. Thanks.

Sent from a phone
On Tue, Jun 16, 2015 at 12:28 PM, avocode/avocode
<reply@reply.github.com>
wrote:
Hi, thanks for reporting.

Where in the application were you when this occurred? Were you by any change
browsing a sketch folder?

—
Reply to this email directly or view it on GitHub
[https://github.com/avocode/avocode/issues/302#issuecomment-112488767] .[https://github.com/notifications/beacon/AAAiaI2tulM30Y534rAEFAK3mDVq7jS4ks5oUEYwgaJpZM4FDm1b.gif]

**Comment by rychlis** [comment]
What version of Avocode are you using? From the error it looks like it might be a very old version. Maybe the auto-update didn't work for you

**Comment by ogoog** [comment]
it looks like i am currently using 2.2.0-4d82283

On Thu, Jun 18, 2015 at 10:12 AM, Tomáš Rychlik <notifications@github.com>
wrote:

> What version of Avocode are you using? From the error it looks like it
> might be a very old version. Maybe the auto-update didn't work for you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/avocode/avocode/issues/302#issuecomment-113169153>.
>



-- 
Marc Gugliuzza
914.473.2446
marc.gugliuzza@gmail.com

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
