### ISSUE TITLE
Slice tool error..

### ISSUE THREAD

**Issue by aliduman** [avocode/avocode#309]
Describe your problem here…

-----

```
TypeError: Cannot read property 'x' of null
  at _calculateBounds (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/slice-tool/lib/slice-tool.js:1:1000)
  at e.module.exports.e._mousemoveDrag (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/slice-tool/lib/slice-tool.js:1:5410)
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/slice-tool/lib/slice-tool.js:1:330
  at t.module.exports.Emitter.emit (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:118:15)
  at t.mousewheel (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/stage.js:1:12624)
  at HTMLCanvasElement.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/stage.js:1:422)

```

**Comment by petrbrzek** [comment]
What version of Avocode do you have?

**Comment by aliduman** [comment]
Screenshot..
![ekran resmi 2015-06-19 16 14 57](https://cloud.githubusercontent.com/assets/6185469/8254115/63bd9a6c-169e-11e5-95b3-108be664a11d.png)

**Comment by petrbrzek** [comment]
Please update to Avocode 2.2.1. It should fix this issue. Let me know if it works.
