### ISSUE TITLE
error

### ISSUE THREAD

**Issue by erhanaydin** [avocode/avocode#311]
Describe your problem here…

-----

```
TypeError: Converting circular structure to JSON
  at Object.stringify (native)
  at StorageFolder.module.exports.StorageFolder.store (/Users/grmyazilim/Desktop/4saat/Avocode.app/Contents/Resources/app.asar/src/storage-folder.js:14:59)
  at Atom.module.exports.Atom.saveSync (/Users/grmyazilim/Desktop/4saat/Avocode.app/Contents/Resources/app.asar/src/atom.js:887:50)
  at t.saveAppState (/Users/grmyazilim/Desktop/4saat/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:10606)
  at e._finishSync (/Users/grmyazilim/Desktop/4saat/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:6471)
  at /Users/grmyazilim/Desktop/4saat/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:9333
  at /Users/grmyazilim/Desktop/4saat/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/progress.js:1:4040
  at Object.async.each (/Users/grmyazilim/Desktop/4saat/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:118:20)
  at Function.Progress.forEach (/Users/grmyazilim/Desktop/4saat/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/progress.js:1:3989)
  at e._downloadRevisions (/Users/grmyazilim/Desktop/4saat/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:9706)
  at e._syncProjects (/Users/grmyazilim/Desktop/4saat/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:8886)
  at e._onUserData (/Users/grmyazilim/Desktop/4saat/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:8278)
  at /Users/grmyazilim/Desktop/4saat/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:342
  at Request._callback (/Users/grmyazilim/Desktop/4saat/Avoc
```

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
