### ISSUE TITLE
PSD

### ISSUE THREAD

**Issue by apipemc** [avocode/avocode#313]
Describe your problem here…

-----

```
RangeError: Maximum call stack size exceeded
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/space-pen/lib/space-pen.js:259:9
  at Builder.openTag (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/space-pen/lib/space-pen.js:265:9)
  at Builder.tag (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/space-pen/lib/space-pen.js:239:12)
  at Function.View.(anonymous function) (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/space-pen/lib/space-pen.js:56:49)
  at Function.module.exports.e.content (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode-view.js:1:781)
  at Function.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/space-pen/lib/space-pen.js:122:31)
  at Function.View.buildHtml (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/space-pen/lib/space-pen.js:96:10)
  at e.View (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/space-pen/lib/space-pen.js:121:33)
  at new e (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode-view.js:1:632)
  at t._addRevisionView (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:13966)
  at t._openAvocodeResource (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:13327)
  at t.opener (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:11769)
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:950
  at wrappedOpener (/Applications/Avocode.app/Contents/Resources/app.asar/src/workspace.js:525:18)
  at Workspace.module.exports.Wo
```

**Comment by rychlis** [comment]
I think this was fixed in Avocode 2.3. Let me know if you can still reproduce this issue and I will reopen
