### ISSUE TITLE
Avocode will not start

### ISSUE THREAD

**Issue by tomleo** [avocode/avocode#328]
```
> cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.04
DISTRIB_CODENAME=vivid
DISTRIB_DESCRIPTION="Ubuntu 15.04"
NAME="Ubuntu"
VERSION="15.04 (Vivid Vervet)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 15.04"
VERSION_ID="15.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

-----

```
TypeError: object is not a function
    at t.<anonymous> (/home/tom/Downloads/Avocode/resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:26467)
    at t.EventEmitter.emit (/home/tom/Downloads/Avocode/resources/app.asar/node_modules/@avocode/core/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
    at e._onUserData (/home/tom/Downloads/Avocode/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:8253)
    at /home/tom/Downloads/Avocode/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:342
    at Request._callback (/home/tom/Downloads/Avocode/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:2348)
    at Request.self.callback (/home/tom/Downloads/Avocode/resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:197:22)
    at emitTwo (events.js:92:20)
    at Request.emit (events.js:169:7)
    at Request.<anonymous> (/home/tom/Downloads/Avocode/resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:1050:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:166:7)
    at IncomingMessage.<anonymous> (/home/tom/Downloads/Avocode/resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:996:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:163:7)
    at _stream_readable.js:891:16
    at process._tickCallback (node.js:357:13)
```

**Comment by rychlis** [comment]
This should be fixed in Avocode 2.3.0.
