### ISSUE TITLE
issue unknown

### ISSUE THREAD

**Issue by nkko** [avocode/avocode#332]
Describe your problem here…

-----

```
TypeError: object is not a function
    at t.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:26359)
    at t.EventEmitter.emit (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
    at e._onUserData (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:8242)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:342
    at Request._callback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:2125)
    at Request.self.callback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:354:22)
    at emitTwo (events.js:92:20)
    at Request.emit (events.js:169:7)
    at Request.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:1207:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:166:7)
    at IncomingMessage.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:1153:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:163:7)
    at _stream_readable.js:891:16
    at process._tickCallback (node.js:357:13)
```

**Comment by rychlis** [comment]
Please update to Avocode 2.3.0, this error should be fixed in this release.

If it still happens we will re-open the issue
