### ISSUE TITLE
Error on trying to export non-visible icons

### ISSUE THREAD

**Issue by ihorml** [avocode/avocode#335]
Describe your problem here…

-----

```
TypeError: Cannot read property 'resolution' of undefined
  at t.addRule (/Users/ihorbrazhnichenko/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/separately-rules.js:1:1026)
  at t._addSeparatelyRule (/Users/ihorbrazhnichenko/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:8088)
  at t._register (/Users/ihorbrazhnichenko/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:11725)
  at Object.ID_14 (/Users/ihorbrazhnichenko/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:459)
  at r.Dispatcher.$Dispatcher_invokeCallback (/Users/ihorbrazhnichenko/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:220:35)
  at r.Dispatcher.dispatch (/Users/ihorbrazhnichenko/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:195:14)
  at r.handleViewAction (/Users/ihorbrazhnichenko/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/dispatcher.js:1:495)
  at Object.module.exports.addSeparatelyRule (/Users/ihorbrazhnichenko/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/actions/export.js:1:933)
  at [object Object].module.exports.React.createClass._onCreateSeparatelyRuleClick (/Users/ihorbrazhnichenko/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/components/add-rule-button.js:1:581)
  at Object.executeDispatch (/Users/ihorbrazhnichenko/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:110:21)
  at SimpleEventPlugin.executeDispatch (/Users/ihorbrazhnichenko
```

**Comment by rychlis** [comment]
Does this still happen on Avocode 2.3.0? Is it happening on a Sketch or Photoshop design?

**Comment by rychlis** [comment]
Hi, please let us know if it still happens in 2.3.2 and how can we reproduce it, otherwise we will close this issue
