### ISSUE TITLE
arbitrary crash

### ISSUE THREAD

**Issue by heppstux** [avocode/avocode#336]
Describe your problem here…

-----

```
TypeError: object is not a function
    at t.<anonymous> (/[...]/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:26467)
    at t.EventEmitter.emit (/[...]/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
    at e._onUserData (/[...]/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:8253)
    at /[...]/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:342
    at Request._callback (/[...]/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:2348)
    at Request.self.callback (/[...]/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:197:22)
    at emitTwo (events.js:92:20)
    at Request.emit (events.js:169:7)
    at Request.<anonymous> (/[...]/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:1050:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:166:7)
    at IncomingMessage.<anonymous> (/[...]/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:996:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:163:7)
    at _stream_readable.js:891:16
    at process._tickCallback (node.js:357:13)
```

**Comment by rychlis** [comment]
Thanks for the report, this error should be fixed in Avocode 2.3.0
