### ISSUE TITLE
Buggy Modal Dialog - "Export"

### ISSUE THREAD

**Issue by robertfairley** [avocode/avocode#337]
Describe your problem here…
Clicked "export" button while I was exploring the program and didn't want to save the result. There being no cancel option, I repeated the "save" option trying to cancel from the dialog. The result was I returned to the modal offering me to export once again. I closed the project and the modal remained. I tried the button in the modal again and it delivered this error.

Not a problem for me as I was just exploring, but it's likely repeatable so I thought I'd send you what I ran into. Great job, by the way. Keep it up. There seems to be a few excellent tools popping up -- Avacode being one of them.
-----

```
TypeError: Cannot read property 'project' of null
  at t._results.push.Object.defineProperty.get (/Users/rfairley/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/delegato/lib/delegator.js:30:42)
  at _makeDocumentScreenshot (/Users/rfairley/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:2191)
  at t._register (/Users/rfairley/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:11929)
  at Object.ID_14 (/Users/rfairley/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:459)
  at o.Dispatcher.$Dispatcher_invokeCallback (/Users/rfairley/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:220:35)
  at o.Dispatcher.dispatch (/Users/rfairley/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:195:14)
  at o.handleViewAction (/Users/rfairley/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/dispatcher.js:1:707)
  at e.module.exports.makeDocumentScreenshot [as exportCallback] (/Users/rfairley/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/actions/export.js:1:1307)
  at e.module.exports.e.onConfirm (/Users/rfairley/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/instant-export-dialog.js:1:3917)
  at e.module.exports.e.onSave (/Users/rfairley/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/instant-export-dialog.js:1:3421)
  at e.onSave (/Users/rfairley/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/instant-export-dialog.js:1:233)
  at
```

**Comment by rychlis** [comment]
We've just released 2.3.0 which fixes this behavior. Export dialog can now be cancelled by pressing Escape or clicking outside of the dialog and it closes automatically if you exit the document
