### ISSUE TITLE
Error Avocode

### ISSUE THREAD

**Issue by Simonzzzz** [avocode/avocode#341]
App v.2.3.0-ddf81ed
Source UID: 106182
Please try to describe how did it happen.

-----
```
TypeError: Cannot read property 'settings' of undefined
    at a.module.exports.a.getVariables (/home/semenz/Загрузки/Avocode/resources/app.asar/node_modules/@avocode/core/lib/language-manager.js:1:1866)
    at a.module.exports.a.processLayers (/home/semenz/Загрузки/Avocode/resources/app.asar/node_modules/@avocode/core/lib/language-manager.js:1:2239)
    at Object.module.exports._processLayers (/home/semenz/Загрузки/Avocode/resources/app.asar/node_modules/@avocode/code-panel/lib/main.js:1:3738)
    at Object.module.exports._onVariablesChange (/home/semenz/Загрузки/Avocode/resources/app.asar/node_modules/@avocode/code-panel/lib/main.js:1:3380)
    at emitNone (events.js:72:20)
    at emit (events.js:163:7)
    at e.module.exports.e.emitChange (/home/semenz/Загрузки/Avocode/resources/app.asar/node_modules/@avocode/core/lib/stores/base.js:1:558)
    at e.setItems (/home/semenz/Загрузки/Avocode/resources/app.asar/node_modules/@avocode/core/lib/stores/variables.js:1:1518)
    at t.<anonymous> (/home/semenz/Загрузки/Avocode/resources/app.asar/node_modules/@avocode/core/lib/stores/variables.js:1:1305)
    at t.EventEmitter.emit (/home/semenz/Загрузки/Avocode/resources/app.asar/node_modules/@avocode/core/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
    at t.setActiveView (/home/semenz/Загрузки/Avocode/resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:25169)
    at /home/semenz/Загрузки/Avocode/resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:16754
```

**Comment by rychlis** [comment]
Could you please try:
1. Go to app menu Avocode (or File on Windows&Linux) -> Preferences
2. Select Code in the GLOBAL section to the left
3. Do you have any language selected? Try selecting any language or different one

**Comment by Simonzzzz** [comment]
Thanks =)))
