### ISSUE TITLE
Error when trying to select a layer

### ISSUE THREAD

**Issue by epschmidt** [avocode/avocode#342]
App v.2.3.0-ddf81ed
Source UID: 2254
Please try to describe how did it happen.

I get an error every time I try to select a layer in a PSD. Trying to click or double click an image or text block or just selecting the layer from the layers panel.

-----
```
TypeError: Cannot read property '734' of null
    at t._onLayersSelected (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:6481)
    at t.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:459)
    at t.EventEmitter.emit (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
    at t.processSelection (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/selection.js:1:5038)
    at t.select (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/selection.js:1:4834)
    at e.selectLayerFromEvent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/select-tool/lib/select-tool.js:1:7416)
    at e.mouseup (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/select-tool/lib/select-tool.js:1:6037)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/select-tool/lib/select-tool.js:1:240
```

**Comment by rychlis** [comment]
Is it happening in every document? Does it also happen in Avocode 2.3.1?

**Comment by epschmidt** [comment]
Not sure about 2.3.1, but I just updated to 2.3.2 and that seems to have fixed it. Haven't run into any issues so far.
