### ISSUE TITLE
Open file after upgrade to version 2.3.1 - ERROR

### ISSUE THREAD

**Issue by janaobzerova** [avocode/avocode#347]
Open file after upgrade to version 2.3.1

IMPORTANT: Please try to describe how did it happen.

-----
App v.2.3.1-5d82b90
Source UID: 96644
```
TypeError: Cannot read property 'settings' of undefined
    at a.module.exports.a.getVariables (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/language-manager.js:1:2607)
    at a.module.exports.a.processLayers (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/language-manager.js:1:2980)
    at Object.module.exports._processLayers (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/code-panel/lib/main.js:1:3738)
    at Object.module.exports._onVariablesChange (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/code-panel/lib/main.js:1:3380)
    at emitNone (events.js:72:20)
    at emit (events.js:163:7)
    at e.module.exports.e.emitChange (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/stores/base.js:1:558)
    at e.setItems (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/stores/variables.js:1:1518)
    at t.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/stores/variables.js:1:1305)
    at t.EventEmitter.emit (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
    at t.setActiveView (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:25184)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:16754
```

**Comment by rychlis** [comment]
Could you please try:
1. Go to app menu Avocode (or File on Windows&Linux) -> Preferences
2. Select Code in the GLOBAL section to the left
3. Do you have any language selected? Try selecting any language or a different one

**Comment by janaobzerova** [comment]
Choosing different one helped, thanks.

**Comment by rychlis** [comment]
That's weird. What language was selected there and which language were you using?

**Comment by janaobzerova** [comment]
It was css and now it is less. Before update I had less language.

**Comment by rychlis** [comment]
Thanks for the info! I think we can see the issue. Sorry about that. We will release another bugfix release shortly to fix this for other users automatically
