### ISSUE TITLE
Problem usualy occures when try to upload design via app in Linux Ubuntu. 

### ISSUE THREAD

**Issue by riversy** [avocode/avocode#355]
Describe your problem here…

-----

```
TypeError: Cannot read property 'addRevision' of null
  at /home/riversy/bin/avacode/resources/app/node_modules/avocode/lib/user.js:22:501
  at /home/riversy/bin/avacode/resources/app/node_modules/avocode/lib/user.js:25:342
  at Request._callback (/home/riversy/bin/avacode/resources/app/node_modules/avocode/lib/api.js:4:28)
  at self.callback (/home/riversy/bin/avacode/resources/app/node_modules/request/request.js:360:22)
  at Request.emit (events.js:107:17)
  at /home/riversy/bin/avacode/resources/app/node_modules/request/request.js:958:12

```

**Comment by petrbrzek** [comment]
It looks like you use outdated version of Avocode. Could you please try to install Avocode 2.3.0 and let us know if it's still happening?
