### ISSUE TITLE
Crash when clear My Guides

### ISSUE THREAD

**Issue by xenongattz** [avocode/avocode#356]
IMPORTANT: Please try to describe how did it happen.

When I trying to clear my own guides in Avo, it crashes. Green lines stay but lines hide&

![screen](https://cloud.githubusercontent.com/assets/6165014/8744605/27952c28-2c81-11e5-96db-bced7dd41206.png)

-----
App v.2.3.2-ea60620
Source UID: 106814
```
TypeError: Cannot read property 'guide' of undefined
  at t.handleRulerMouseDown_ (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/guides/lib/rulers.js:1:7175)
  at HTMLDivElement.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/guides/lib/rulers.js:1:252)

```

**Comment by rychlis** [comment]
This should be fixed in latest version, let me know if you can still reproduce the issue
