### ISSUE TITLE
Error when openning a acreen of a project

### ISSUE THREAD

**Issue by luismesas** [avocode/avocode#358]
Just trying to open a screen in a project

-----
App v.2.3.2-ea60620
Source UID: 91674
```
TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'
  at TypeError (native)
  at t.module.exports.t._loadMaskedBy (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:3710)
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:1011
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:3245
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:200:33
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:3183
  at replenish (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:191:21)
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:203:33
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:3183
  at replenish (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:191:21)
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:203:33
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:3183
  at replenish (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:191:21)
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:203:33
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:3183
  at replenish (/Applications/Avocode.
```

**Comment by rychlis** [comment]
Hi, does it happen every time for each screen or just for a particular one? Sorry for not responding earlier.

**Comment by petrbrzek** [comment]
Closing because of no activity.
