### ISSUE TITLE
Deleted an old project that was not synced locally

### ISSUE THREAD

**Issue by johnnybridges** [avocode/avocode#364]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.3.2-ea60620
Source UID: 7093
```
Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.
  at invariant (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/invariant.js:42:15)
  at o.Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:185:5)
  at o.handleServerAction (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/dispatcher.js:1:980)
  at e._emitItemUploadProgress (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uploader.js:1:10344)
  at ReadStream.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uploader.js:1:8619)
  at emitOne (events.js:77:13)
  at ReadStream.emit (events.js:166:7)
  at ReadStream.source.emit (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/request/node_modules/combined-stream/node_modules/delayed-stream/lib/delayed_stream.js:30:21)
  at ReadStream.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uploader.js:1:9056)
  at emitOne (events.js:82:20)
  at ReadStream.emit (events.js:166:7)
  at ReadStream.source.emit (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/request/node_modules/combined-stream/node_modules/delayed-stream/lib/delayed_stream.js:30:21)
  at ReadStream.Readable.read (_stream_readable.js:356:10)
  at flow (_stream_readable.js:734:26)
  at resume_ (_stream_readable.js:714:3)
  at _stream_readable.js:701:7
  at process._tickCallback (node.js:357:13)
  at EventEmitter.ipc.sendSync (/Applications/Avocode.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at Object.RemoteMem
```

**Comment by petrbrzek** [comment]
This should be fixed in Avocode 2.4.3. Let me know if the problem persists.
