### ISSUE TITLE
Avocode

### ISSUE THREAD

**Issue by tomkrej** [avocode/avocode#366]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.3.2-ea60620
Source UID: 94469
```
TypeError: boolean is not a function
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:11102
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/export.js:1:4967
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/fstream/node_modules/graceful-fs/graceful-fs.js:104:5
  at FSReqWrap.oncomplete (fs.js:77:15)

```

**Comment by rychlis** [comment]
Hi, could you please give us at least some information? When did the issue happen?

**Comment by rychlis** [comment]
Did it happen when exporting SVG icon, like #351 ?

**Comment by rychlis** [comment]
As you didn't respond I'm assuming it's the same issue as #351, closing this one as a duplicate
