### ISSUE TITLE
Having trouble to access my designs after upgrade from v2.0

### ISSUE THREAD

**Issue by nbiton** [avocode/avocode#368]
IMPORTANT: Please try to describe how did it happen.

I can access the projects and see the list of designs associated with them, but they're stuck on "downloading", and I can't access any.
During this time, the message to report this error appears.

-----
App v.2.3.2-e7da973
Source UID: 48243
```
Error: channel closed
    at ChildProcess.target.send (child_process.js:396:26)
    at Task.module.exports.Task.send (/usr/share/Avocode/resources/app.asar/src/task.js:125:27)
    at e._send (/usr/share/Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:5895)
    at e._addRequest (/usr/share/Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:3910)
    at e.downloadFiles (/usr/share/Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:1981)
    at e.downloadFiles (/usr/share/Avocode/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:6381)
    at t.module.exports.t._createImageRequest (/usr/share/Avocode/resources/app.asar/node_modules/@avocode/core/lib/assets-downloader.js:1:1938)
    at t.module.exports.t.downloadImages (/usr/share/Avocode/resources/app.asar/node_modules/@avocode/core/lib/assets-downloader.js:1:1150)
    at e._downloadRevisionImages (/usr/share/Avocode/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:13852)
    at /usr/share/Avocode/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:12667
    at /usr/share/Avocode/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:801
    at /usr/share/Avocode/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:5681
    at /usr/share/Avocode/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:6126
    at /usr/share/Avocode/resources/app.asar/node_modules/fstream/node_modules/graceful-fs/graceful-fs.js:104:5
    at FSReqWrap.oncomplete (fs.js:77:15)
```

**Comment by rychlis** [comment]
It might help to remove .avcd from your home folder - `rm -r ~/.avcd` to reset your local storage. You can also move the folder so you can return it back if it won't help.

If it doesn't help please share your account email with us at team@avocode.com so we can investigate if there is something wrong with your designs

**Comment by nbiton** [comment]
Thanks @rychlis . What you suggested fixed it.
