### ISSUE TITLE
One Sketch artboard gives an error when selected.

### ISSUE THREAD

**Issue by mochabcha** [avocode/avocode#369]
I've uninstalled and reinstalled the plugin itself....Only this one page doesn't load in the Avocode app when I double click it.  I have no idea why.  It doesn't load for my developer either.  He's on Windows.

IMPORTANT: Please try to describe how did it happen.

-----
App v.2.3.2-ea60620
Source UID: 103645
```
TypeError: Cannot read property 'imageName' of undefined
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:2540
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:2460
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:2460
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:2460
    at t.module.exports.t._getImagesToLoad (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:2673)
    at new t (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:515)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:21597
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)
```

**Comment by rychlis** [comment]
Hey thanks for the report, we should be able to fix this this week. I'm closing this issue as it's a duplicate  of #365 which will stay open until we fix this
