### ISSUE TITLE
Can't get online

### ISSUE THREAD

**Issue by itsjustmath** [avocode/avocode#375]
Network is online, but Avocode stays on 'Offline Mode'

-----

```
TypeError: Cannot read property 'id' of null
    at new e (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/model/project.js:1:359)
    at e._projectCreated (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/project-manager/lib/stores/project.js:1:14421)
    at e._handleAction (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/project-manager/lib/stores/project.js:1:16441)
    at Object.ID_11 (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/project-manager/lib/stores/project.js:1:307)
    at r.Dispatcher.$Dispatcher_invokeCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:220:35)
    at r.Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:195:14)
    at r.handleServerAction (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/dispatcher.js:1:593)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/project-manager/lib/actions/project.js:1:2247
    at Request._callback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:2758)
    at self.callback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:354:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:166:7)
    at Request.onRequestError (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:1011:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:166:7)
    at TLSSocket.socketErrorListener (_http_client.js:254:9)
    at emitOne (events.js:
```

**Comment by rychlis** [comment]
I think the issue was caused by a short downtime of our server 9 hours ago. Such downtimes are pretty rare and we are investigating what happened, it looks like some kind of DNS issue so far.

Also you are not using the latest version of Avocode, please download the latest version here: https://manager.avocode.com/downloads/
