### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by lucien144** [avocode/avocode#378]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.3.2-ea60620
Source UID: undefined
```
TypeError: Cannot read property 'token' of null
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/auth.js:1:1953
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:180:53
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)
```

**Comment by rychlis** [comment]
Please try to describe how did it happen. Also please try to update to the latest version (2.4.1) if you can reproduce the issue there

**Comment by petrbrzek** [comment]
Closing because of no activity.
