### ISSUE TITLE
Sketch plugin not syncing - unexpected error

### ISSUE THREAD

**Issue by designbyremedy** [avocode/avocode#384]
IMPORTANT: Please try to describe how did it happen.

UPDATE: MORE DETAILS
Using OS X Yosemite 10.10.4
Issue happens using both WiFi and ethernet

When choosing Sync to Avocode in Sketch, I'm getting an unexpected error saying no such file or directory exists. See screenshot.
![screen shot 2015-08-10 at 11 23 25 am](https://cloud.githubusercontent.com/assets/6165717/9179584/76a2b662-3f52-11e5-8932-4a47c56bb7a8.png)

-----
Sketch Exporter 2.1.1 running in Sketch 3.3.3
```
Error: ENOENT, no such file or directory '/Users/andrew.coss/…/avocode.token'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at main (/Users/andrew.coss/…/avocode-exporter/lib/main.js:1:3056)
    at Object.<anonymous> (/Users/andrew.coss/…/avocode-exporter/lib/main.js:1:3473)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

**Comment by designbyremedy** [comment]
This works when testing on a different network. This must be a firewall/security issue. Let's mark this is resolved and I'll reach out to our IT team here.

Thanks!

**Comment by c42705** [comment]
this was solved by the IT department? im having the same issue here... but i dont have a different network to test it.  im running all  (osx, sketch and avocode from a virtual machine, on windows 8.1)

**Comment by designbyremedy** [comment]
Yes, IT was able to resolve this issue for me. Maybe you can test using your 4G network from your phone? That's what I did to prove that it was a network issue.
