### ISSUE TITLE
error

### ISSUE THREAD

**Issue by malitov** [avocode/avocode#391]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.1-9839e14
Source UID: 113520
```
Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.
  at invariant (/home/malitov/Загрузки/Avocode/resources/app.asar/node_modules/flux/lib/invariant.js:42:15)
  at o.Dispatcher.dispatch (/home/malitov/Загрузки/Avocode/resources/app.asar/node_modules/flux/lib/Dispatcher.js:185:5)
  at o.handleViewAction (/home/malitov/Загрузки/Avocode/resources/app.asar/node_modules/@avocode/core/lib/dispatcher.js:1:707)
  at t.module.exports.t.setDocument (/home/malitov/Загрузки/Avocode/resources/app.asar/node_modules/@avocode/core/lib/active-document.js:1:1668)
  at t._fireNoActiveViewEvents (/home/malitov/Загрузки/Avocode/resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:24433)
  at t._fireNoActiveViewEvents (/home/malitov/Загрузки/Avocode/resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:999)
  at atom-workspace.<anonymous> (/home/malitov/Загрузки/Avocode/resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:8427)
  at atom-workspace.handler (/home/malitov/Загрузки/Avocode/resources/app.asar/src/space-pen-extensions.js:110:34)
  at atom-workspace.jQuery.event.dispatch (/home/malitov/Загрузки/Avocode/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/home/malitov/Загрузки/Avocode/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/home/malitov/Загрузки/Avocode/resources/app.asar/src/command-registry.js:251:29)
  at CommandRegistry.handleCommandEvent (/home/malitov/Загрузки/Avocode/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/home/malitov/Загрузки/Avocode/resources/app.asar/src/command-registry.js:16
```

**Comment by rychlis** [comment]
What were you doing when the error happened? We've fixed most cases of this error in 2.4.3, let me know if you can reproduce this problem in the latest version and I will reopen this issue
