### ISSUE TITLE
Error: Emitter has been disposed, an error while adding files to project 

### ISSUE THREAD

**Issue by hadabo** [avocode/avocode#398]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.3.2-ea60620
Source UID: 109347
```
Error: Emitter has been disposed
  at Emitter.module.exports.Emitter.on (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:34:15)
  at e.module.exports.e.onDidClose (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode-view.js:1:880)
  at e.createManager_ (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/guides/lib/ruler-manager.js:1:6084)
  at e.getManagerForView (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/guides/lib/ruler-manager.js:1:5617)
  at e.handleActiveView_ (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/guides/lib/ruler-manager.js:1:5136)
  at t.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/guides/lib/ruler-manager.js:1:214)
  at t.EventEmitter.emit (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
  at t.setActiveView (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:25184)
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:16754

```

**Comment by rychlis** [comment]
Hi you are not using the latest version (2.4.2), please let me know if you can reproduce this in the [latest version](avocode.com/download/)

**Comment by rychlis** [comment]
Ok I am closing this issue and let just #399 open
