### ISSUE TITLE
I was trying to reproduce an Error: Emitter has been disposed

### ISSUE THREAD

**Issue by hadabo** [avocode/avocode#399]
@rychlis I was trying to reproduce the following error on the latest version so I had this new one:
- [ ] #398

-----
App v.2.4.2-d618096
Source UID: 109347
```
Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.
  at invariant (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/invariant.js:42:15)
  at o.Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:185:5)
  at o.handleViewAction (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/dispatcher.js:1:707)
  at t.module.exports.t.setDocument (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/active-document.js:1:1668)
  at t._fireNoActiveViewEvents (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:24433)
  at t._fireNoActiveViewEvents (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:999)
  at atom-workspace.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:8427)
  at atom-workspace.handler (/Applications/Avocode.app/Contents/Resources/app.asar/src/space-pen-extensions.js:110:34)
  at atom-workspace.jQuery.event.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Avocode.app/Contents/Resources/app.asar/src/command-registry.js:251:29)
  at CommandRegistry.handleCommandEvent (/Applications/Avocode.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Avocode.app/Co
```

**Comment by rychlis** [comment]
I think we fixed this in 2.4.3, in case you can still reproduce it I will re-open this issue
