### ISSUE TITLE
Trying to upload a revision

### ISSUE THREAD

**Issue by chrisbcn** [avocode/avocode#401]
Describe your problem here…

-----

```
TypeError: Cannot read property 'design' of null
    at e._getTreeUploads (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/project-manager/lib/stores/project.js:1:17811)
    at e._applyUploads (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/project-manager/lib/stores/project.js:1:17114)
    at e._handleUploadStoreChange (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/project-manager/lib/stores/project.js:1:17005)
    at t.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/project-manager/lib/stores/project.js:1:307)
    at emitNone (events.js:72:20)
    at t.emit (events.js:163:7)
    at t.module.exports.e.emitChange (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/stores/base.js:1:558)
    at t._handleAction (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/stores/upload-store.js:1:3518)
    at Object.ID_10 (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/stores/upload-store.js:1:142)
    at r.Dispatcher.$Dispatcher_invokeCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:220:35)
    at r.Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:195:14)
    at r.handleServerAction (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/dispatcher.js:1:593)
    at e._emitItemUploadProgress (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uploader.js:1:10320)
    at FormData.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uplo
```

**Comment by rychlis** [comment]
Hey I think issue was is fixed for some time now, let me know if you can reproduce it in 2.4.3 or later
