### ISSUE TITLE
Random error while app is open

### ISSUE THREAD

**Issue by pushred** [avocode/avocode#409]
This is happening sort of randomly while the app is open, presumably when a sync is occurring. I was/am a beta user, the last version I had installed was 0.5.0, that could perhaps be related.

-----
App v.2.4.2-d618096
Source UID: 21509
```
TypeError: Converting circular structure to JSON
  at Object.stringify (native)
  at StorageFolder.module.exports.StorageFolder.store (/Applications/Avocode.app/Contents/Resources/app.asar/src/storage-folder.js:14:59)
  at Atom.module.exports.Atom.saveSync (/Applications/Avocode.app/Contents/Resources/app.asar/src/atom.js:887:50)
  at t.saveAppState (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:11576)
  at e._finishSync (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:6611)
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:10055
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/progress.js:1:4040
  at Object.async.each (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:118:20)
  at Function.Progress.forEach (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/progress.js:1:3989)
  at e._downloadRevisions (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:10428)
  at e._syncProjects (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:9608)
  at e._onUserData (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:8900)
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:369
  at Request._callback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:3588)
  at Request.self.callback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/jsdom/node_modules/request/request.js:198:22)
  at emit
```

**Comment by rychlis** [comment]
How often does it happen?

I think it might help to move `~/.avcd/` folder elsewhere which will completely reset your local config and data (including variables unfortunately). It would be helpful if you could send the whole `.avcd` folder to us at team@avocode.com

Let me know if (re)moving .avcd help.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
