### ISSUE TITLE
Issue trying to run Avocode plugin with any design in Sketch

### ISSUE THREAD

**Issue by ewydler** [avocode/avocode#413]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.1 running in Sketch 3.3.2
```
Error: ENOENT, no such file or directory '/Users/ewydler/…/avocode.token'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at main (/Users/ewydler/…/avocode-exporter/lib/main.js:1:3056)
    at Object.<anonymous> (/Users/ewydler/…/avocode-exporter/lib/main.js:1:3473)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

**Comment by chazchumley** [comment]
Does support want to fix this issue.  I am having same issue

**Comment by marekhrabe** [comment]
We are working on a new major release of Sketch extension for some time. It fixes a lot of bugs and crashes. We will let you know when the new version is released.
