### ISSUE TITLE
Bug with Sketch plugin

### ISSUE THREAD

**Issue by nomijoy** [avocode/avocode#416]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.1 running in Sketch 3.3.3
```
Error: ENOENT, no such file or directory '/Users/NomiJoyShikma/…/avocode.token'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at main (/Users/NomiJoyShikma/…/avocode-exporter/lib/main.js:1:3056)
    at Object.<anonymous> (/Users/NomiJoyShikma/…/avocode-exporter/lib/main.js:1:3473)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

**Comment by chazchumley** [comment]
+1 WTF-  why pay for a tool that doesnt work.  Anyone want to fix this IMMEDIATELY

**Comment by marekhrabe** [comment]
We are working on a new major release of Sketch extension for some time. It fixes a lot of bugs including this one. We will let you know when the new version is released.
