### ISSUE TITLE
Can't open

### ISSUE THREAD

**Issue by yustnip** [avocode/avocode#425]
IMPORTANT: Please try to describe how did it happen.
Tried to open one of PSDs and got the error. After that I reloaded the PSD and get some more errors. But from nth-attempt the PSD opened.
-----
App v.2.4.2-d618096
Source UID: 113072
```
RangeError: Maximum call stack size exceeded
  at e.update (/home/yustnip/apps/Avocode/resources/app.asar/node_modules/@avocode/core/lib/overlay.js:null:null)
  at e.update (/home/yustnip/apps/Avocode/resources/app.asar/node_modules/@avocode/core/lib/overlay.js:1:2702)
  at e.update (/home/yustnip/apps/Avocode/resources/app.asar/node_modules/@avocode/core/lib/overlay.js:1:2702)
  at e.update (/home/yustnip/apps/Avocode/resources/app.asar/node_modules/@avocode/core/lib/overlay.js:1:2702)
  at e._renderCanvas (/home/yustnip/apps/Avocode/resources/app.asar/node_modules/@avocode/core/lib/overlay.js:1:2183)
  at e.b.CanvasRenderer.renderDisplayObject (/home/yustnip/apps/Avocode/resources/app.asar/node_modules/@avocode/core/node_modules/pixi.js/bin/pixi.js:15:6584)
  at e.b.CanvasRenderer.render (/home/yustnip/apps/Avocode/resources/app.asar/node_modules/@avocode/core/node_modules/pixi.js/bin/pixi.js:15:5785)
  at e.render (/home/yustnip/apps/Avocode/resources/app.asar/node_modules/@avocode/core/lib/overlay.js:1:5397)
  at t.renderOverlay (/home/yustnip/apps/Avocode/resources/app.asar/node_modules/@avocode/core/lib/stage.js:1:14477)
  at t.render (/home/yustnip/apps/Avocode/resources/app.asar/node_modules/@avocode/guides/lib/guide-stageview.js:1:3646)
  at t.update (/home/yustnip/apps/Avocode/resources/app.asar/node_modules/@avocode/core/lib/reactive-view.js:1:771)
  at t.setState (/home/yustnip/apps/Avocode/resources/app.asar/node_modules/@avocode/core/lib/reactive-view.js:1:523)
  at t._handleGuideStoreChange (/home/yustnip/apps/Avocode/resources/app.asar/node_modules/@avocode/guides/lib/guide-stageview.js:1:1804)
  at t.<anonymous> (/home/yustnip/apps/Avocode/resources/app.asar/node_modules/@avocode/guides/lib/guide-stageview.js:1:170)
  at emitNone (events.js:72:20)
  at 
```

**Comment by rychlis** [comment]
It seems that this error doesn't happen in Avocode 2.4.3.

Let me know if you still experience this issue in 2.4.3 and I will re-open
