### ISSUE TITLE
theres a file I cant import -- uploading repeatedly stucks at 50%. application crashed upon pressing 'try again'.

### ISSUE THREAD

**Issue by Masquer** [avocode/avocode#426]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.2-d618096
Source UID: 116023
```
Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.
    at invariant (/home/masquer/apps/avocode/resources/app.asar/node_modules/flux/lib/invariant.js:42:15)
    at o.Dispatcher.dispatch (/home/masquer/apps/avocode/resources/app.asar/node_modules/flux/lib/Dispatcher.js:185:5)
    at o.handleViewAction (/home/masquer/apps/avocode/resources/app.asar/node_modules/@avocode/core/lib/dispatcher.js:1:707)
    at t.module.exports.t.setDocument (/home/masquer/apps/avocode/resources/app.asar/node_modules/@avocode/core/lib/active-document.js:1:1668)
    at t.setActiveView (/home/masquer/apps/avocode/resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:26694)
    at atom-workspace.<anonymous> (/home/masquer/apps/avocode/resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:8223)
    at atom-workspace.handler (/home/masquer/apps/avocode/resources/app.asar/src/space-pen-extensions.js:110:34)
    at atom-workspace.jQuery.event.dispatch (/home/masquer/apps/avocode/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
    at atom-workspace.elemData.handle (/home/masquer/apps/avocode/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/home/masquer/apps/avocode/resources/app.asar/src/command-registry.js:251:29)
    at CommandRegistry.handleCommandEvent (/home/masquer/apps/avocode/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/home/masquer/apps/avocode/resources/app.asar/src/command-registry.js:166:19)
    at PaneContainerView.jQuery.fn.trigger (/home/masquer/apps/avocode/resources/app.asar/src/space-pen-extensions.js:64:23)
    at PaneContainerView.module.ex
```

**Comment by petrbrzek** [comment]
Hello, we’ve just released Avocode 2.4.3 that should fix the issue. Let us know if the problem persists.
