### ISSUE TITLE
SVG export

### ISSUE THREAD

**Issue by blcarson** [avocode/avocode#435]
Selected a vector smart object, went to menu and hit 'export as' and then chose svg. On El Capitan GM, iMac 5k.

-----
App v.2.4.2-d618096
Source UID: 4007
```
TypeError: boolean is not a function
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:11459
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/export.js:1:4967
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/fstream/node_modules/graceful-fs/graceful-fs.js:104:5
    at FSReqWrap.oncomplete (fs.js:77:15)
```

**Comment by petrbrzek** [comment]
Hello, we’ve just released Avocode 2.4.3 that should fix the issue. Let us know if the problem persists.
