### ISSUE TITLE
Uploading designs from network drive crash on Windows 

### ISSUE THREAD

**Issue by solariz** [avocode/avocode#441]
Drag & Drop of a PSD (180MB) in Win 7 (x64) to Avocode. 
Problem causing: PSD is not locally it's saved on a mounted smb network drive.

-----
App v.2.4.2-d618096
Source UID: 118812
```
Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (C:\Users\solariz\AppData\Local\avocode\app-2.4.2\resources\app.asar\src\project.js:442:17)
  at Project.module.exports.Project.bufferForPath (C:\Users\solariz\AppData\Local\avocode\app-2.4.2\resources\app.asar\src\project.js:420:63)
  at Project.module.exports.Project.open (C:\Users\solariz\AppData\Local\avocode\app-2.4.2\resources\app.asar\src\project.js:383:19)
  at Workspace.module.exports.Workspace.openURIInPane (C:\Users\solariz\AppData\Local\avocode\app-2.4.2\resources\app.asar\src\workspace.js:447:29)
  at Workspace.module.exports.Workspace.open (C:\Users\solariz\AppData\Local\avocode\app-2.4.2\resources\app.asar\src\workspace.js:371:19)
  at t._handleDrop (C:\Users\solariz\AppData\Local\avocode\app-2.4.2\resources\app.asar\node_modules\@avocode\core\lib\avocode.js:1:11284)
  at HTMLDocument.<anonymous> (C:\Users\solariz\AppData\Local\avocode\app-2.4.2\resources\app.asar\node_modules\@avocode\core\lib\avocode.js:1:999)

```

**Comment by petrbrzek** [comment]
Thanks to your mention of network drive, I was able to reproduce the issue. :+1: 
The fix will be part of upcoming release.

**Comment by petrbrzek** [comment]
We've launched Avocode 2.4.4 beta which should fix this issue, you can download the build from here:

​Mac - https://manager.avocode.com/download/app-beta/mac/

Linux ia32 - https://manager.avocode.com/download/app-beta/linux-ia32/
​Linux x64 - https://manager.avocode.com/download/app-beta/linux/
​Windows - https://manager.avocode.com/download/app-beta/windows/

This will remain in beta for now, if everything goes fine we will enable auto-update to 2.4.4 globally

**Comment by rychlis** [comment]
Avocode 2.4.5 is now live with the fix. Let us know if you still experience the same issue and we will re-open the issue
