### ISSUE TITLE
I click delete element 

### ISSUE THREAD

**Issue by hameltomor** [avocode/avocode#444]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.2-d618096
Source UID: 118661
```
TypeError: Cannot read property 'x' of null
  at _calculateBounds (/home/ace7557/Programms/Avocode/resources/app.asar/node_modules/@avocode/slice-tool/lib/slice-tool.js:1:1000)
  at e.module.exports.e._mousemoveDrag (/home/ace7557/Programms/Avocode/resources/app.asar/node_modules/@avocode/slice-tool/lib/slice-tool.js:1:5862)
  at /home/ace7557/Programms/Avocode/resources/app.asar/node_modules/@avocode/slice-tool/lib/slice-tool.js:1:330
  at t.module.exports.Emitter.emit (/home/ace7557/Programms/Avocode/resources/app.asar/node_modules/emissary/lib/emitter.js:118:15)
  at t.mousewheel (/home/ace7557/Programms/Avocode/resources/app.asar/node_modules/@avocode/core/lib/stage.js:1:13091)
  at HTMLCanvasElement.<anonymous> (/home/ace7557/Programms/Avocode/resources/app.asar/node_modules/@avocode/core/lib/stage.js:1:438)

```

**Comment by petrbrzek** [comment]
Hello, we’ve just released Avocode 2.4.3 that should fix the issue. Let us know if the problem persists.
