### ISSUE TITLE
trying to export imported graphic as svg.

### ISSUE THREAD

**Issue by rokelvisar** [avocode/avocode#450]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.2-d618096
Source UID: 98978
```
TypeError: boolean is not a function
  at C:\Users\rokel_000\AppData\Local\avocode\app-2.4.2\resources\app.asar\node_modules\@avocode\export-panel\lib\stores\export.js:1:11459
  at C:\Users\rokel_000\AppData\Local\avocode\app-2.4.2\resources\app.asar\node_modules\@avocode\core\lib\export.js:1:4967
  at C:\Users\rokel_000\AppData\Local\avocode\app-2.4.2\resources\app.asar\node_modules\fstream\node_modules\graceful-fs\graceful-fs.js:104:5
  at FSReqWrap.oncomplete (fs.js:77:15)

```

**Comment by petrbrzek** [comment]
Hello, we’ve just released Avocode 2.4.3 that should fix the issue. Let us know if the problem persists.
