### ISSUE TITLE
Avocode goes bad when trying to process file

### ISSUE THREAD

**Issue by milasevicius** [avocode/avocode#452]
Describe your problem here…

-----

```
Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.
    at invariant (/Users/Rokas/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/invariant.js:42:15)
    at o.Dispatcher.dispatch (/Users/Rokas/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:185:5)
    at o.handleServerAction (/Users/Rokas/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/dispatcher.js:1:980)
    at e._emitRemoteQueueError (/Users/Rokas/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uploader.js:1:12110)
    at /Users/Rokas/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uploader.js:1:1412
    at e._passDisabledError (/Users/Rokas/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:2107)
    at e.getPendingUploadSlots (/Users/Rokas/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:7478)
    at e.loadRemoteQueue (/Users/Rokas/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uploader.js:1:1326)
    at t._onUserData (/Users/Rokas/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:19224)
    at t._onUserData (/Users/Rokas/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:950)
    at t.<anonymous> (/Users/Rokas/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:19744)
    at emitNone (events.js:67:13)
    at t.emit (events.js:163:7)
    at t.module.exports.e.emitChange (/Users/Rokas/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/stores/bas
```

**Comment by petrbrzek** [comment]
Hello, we’ve just released Avocode 2.4.3 that should fix the issue. Let us know if the problem persists.
