### ISSUE TITLE
Processing failed when trying to upload a PSD

### ISSUE THREAD

**Issue by SkoebaSteve** [avocode/avocode#454]
I've had issues with the processing of PSD's before, see bug #431 
After updating Avocode to it's latest version, it still happens with the same designs. I tried an older design which I uploaded in a different project before and this one does process correctly.

I thought it might've been an issue with PSD's from an updated version of Photoshop, so I tried another one made in a recent version of Photoshop but that one works.

-----
App v.2.4.3-3630f5a
Source UID: 57141
```
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at invariant (/Users/steefjanssen/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/flux/node_modules/fbjs/lib/invariant.js:35:15)
    at o.dispatch (/Users/steefjanssen/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:167:160)
    at o.handleServerAction (/Users/steefjanssen/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/dispatcher.js:1:980)
    at e._emitItemProcessingProgress (/Users/steefjanssen/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uploader.js:1:10574)
    at /Users/steefjanssen/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uploader.js:1:7483
    at Request._callback (/Users/steefjanssen/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:8607)
    at Request.self.callback (/Users/steefjanssen/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:198:22)
    at emitTwo (events.js:92:20)
    at Request.emit (events.js:169:7)
    at Request.<anonymous> (/Users/steefjanssen/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:1063:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:166:7)
    at IncomingMessage.<anonymous> (/Users/steefjanssen/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:1009:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:163:7)
    at _stream_readable.js:891:16
    at process._tickCallback (node.js:357:
```

**Comment by gibson** [comment]
+1 i have a same problem

**Comment by SkoebaSteve** [comment]
From the research I've done it seems that it actually is working with the Photoshop 2014 version but all designs from the 2015 version seem to be unable to process. Would be great if you guys could respond and give me an update about this.

**Comment by petrbrzek** [comment]
Thanks for your report and investigation. Could you share us the problematic design at team[at]avocode.com? It'd help us a lot.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
