### ISSUE TITLE
Error when syncing

### ISSUE THREAD

**Issue by 2gen** [avocode/avocode#457]
Error when syncing updates with sketch plugin 2.1.1.

---

App v.2.4.3-3630f5a
Source UID: 109207

```
TypeError: Cannot read property 'id' of undefined
    at t.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:28038)
    at t.EventEmitter.emit (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:9823
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/progress.js:1:4040
    at done (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:132:19)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:32:16
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/progress.js:1:3925
    at s._handleRevisionResult (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/revision-download-queue.js:1:3485)
    at next (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:798:43)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:32:16
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/revision-download-queue.js:1:2300
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:11387
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:13904
    at t.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:933)
    at t.g (events.js:257:16)
    at emitNone (events.js:72:20)
    at t.emit (events.js:163:7)
```

**Comment by marekhrabe** [comment]
We are working on a new major release of Sketch extension for some time. It fixes a lot of bugs including this one. We will let you know you when the new version is released.

**Comment by bolekkerous** [comment]
This shouldn't happen anymore with the latest Sketch plugin.

You can always download the latest version here:

https://manager.avocode.com/downloads/

If you still experience this problem or any other, please create a new issue with it.
