### ISSUE TITLE
Open the delete menu before finishing processing

### ISSUE THREAD

**Issue by davidemazzanti** [avocode/avocode#461]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.3-3630f5a
Source UID: 121610
```
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at invariant (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/node_modules/fbjs/lib/invariant.js:35:15)
    at o.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:167:160)
    at o.handleServerAction (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/dispatcher.js:1:980)
    at e._emitItemProcessingProgress (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uploader.js:1:10574)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uploader.js:1:7483
    at Request._callback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:8607)
    at Request.self.callback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:198:22)
    at emitTwo (events.js:92:20)
    at Request.emit (events.js:169:7)
    at Request.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:1063:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:166:7)
    at IncomingMessage.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:1009:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:163:7)
    at _stream_readable.js:891:16
    at process._tickCallback (node.js:357:13)
    at EventEmitter.ipc.sendSync (/Applications/Avocode.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at Object.Remote
```

**Comment by petrbrzek** [comment]
Thanks for the report. I can reproduce the issue reliably. It should be fixed in upcoming release. I'll let you know.

**Comment by jakubzitny** [comment]
I've ref'd two recent issues related to this, they were reported from Avocode 2.4.5.
