### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by gayankt** [avocode/avocode#463]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.3-3630f5a
Source UID: 115184
```
Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (C:\Users\gthrimanne\AppData\Local\avocode\app-2.4.3\resources\app.asar\src\project.js:442:17)
  at Project.module.exports.Project.bufferForPath (C:\Users\gthrimanne\AppData\Local\avocode\app-2.4.3\resources\app.asar\src\project.js:420:63)
  at Project.module.exports.Project.open (C:\Users\gthrimanne\AppData\Local\avocode\app-2.4.3\resources\app.asar\src\project.js:383:19)
  at Workspace.module.exports.Workspace.openURIInPane (C:\Users\gthrimanne\AppData\Local\avocode\app-2.4.3\resources\app.asar\src\workspace.js:447:29)
  at Workspace.module.exports.Workspace.open (C:\Users\gthrimanne\AppData\Local\avocode\app-2.4.3\resources\app.asar\src\workspace.js:371:19)
  at t._handleDrop (C:\Users\gthrimanne\AppData\Local\avocode\app-2.4.3\resources\app.asar\node_modules\@avocode\core\lib\avocode.js:1:11347)
  at HTMLDocument.<anonymous> (C:\Users\gthrimanne\AppData\Local\avocode\app-2.4.3\resources\app.asar\node_modules\@avocode\core\lib\avocode.js:1:999)

```

**Comment by rychlis** [comment]
Looks like drag and drop of a file failed, where did you drag the file to?

**Comment by rychlis** [comment]
Closing due to no activity, we will reopen the issue if you provide some information, thanks
