### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by maroon775** [avocode/avocode#469]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.3-3630f5a
Source UID: 122247
```
TypeError: Cannot read property 'right' of undefined
  at e.calculateDistance (C:\Users\AmalAltibaev\AppData\Local\avocode\app-2.4.3\resources\app.asar\node_modules\@avocode\measure-stageview\lib\measure.js:1:3066)
  at e.measure (C:\Users\AmalAltibaev\AppData\Local\avocode\app-2.4.3\resources\app.asar\node_modules\@avocode\measure-stageview\lib\measure.js:1:2537)
  at t.<anonymous> (C:\Users\AmalAltibaev\AppData\Local\avocode\app-2.4.3\resources\app.asar\node_modules\@avocode\measure-stageview\lib\main.js:1:521)
  at t.EventEmitter.emit (C:\Users\AmalAltibaev\AppData\Local\avocode\app-2.4.3\resources\app.asar\node_modules\@avocode\core\node_modules\eventemitter2\lib\eventemitter2.js:339:22)
  at C:\Users\AmalAltibaev\AppData\Local\avocode\app-2.4.3\resources\app.asar\node_modules\@avocode\measure-tool\lib\measure-tool.js:1:2025
  at process._tickCallback (node.js:357:13)

```

**Comment by rychlis** [comment]
Please try to describe how did it happen. Does it happen every time or just randomly in some cases?

**Comment by rychlis** [comment]
Closing due to no activity, let us know if you can still reproduce the issue and we will re-open
