### ISSUE TITLE
This is the error I got just after my payment.

### ISSUE THREAD

**Issue by ciriarte** [avocode/avocode#471]
IMPORTANT: Please try to describe how did it happen.

I assume it has something to do with the initial sync after payment.

-----
App v.2.4.3-3630f5a
Source UID: 117233
```
TypeError: Cannot read property 'imageName' of undefined
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:2540
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:2460
    at t.module.exports.t._getImagesToLoad (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:2673)
    at new t (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:515)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:21523
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)
```

**Comment by rychlis** [comment]
Hi, it seems like a problem with the design. It might have been a temporary issue as you said, did it happen again later?

**Comment by rychlis** [comment]
Closing due to no activity, let us know if you can still reproduce the issue and we will re-open
