### ISSUE TITLE
Crash on Sketch 3.4

### ISSUE THREAD

**Issue by shiienurm** [avocode/avocode#474]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.1 running in Sketch 3.4
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/User/Library/Containers/com.bohemiancoding.sketch3.beta/Data/…/Avocode/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

**Comment by shiienurm** [comment]
Happens while uploading files. Huge blocker. Is there any beta version of the Avocode Sketch Sync which works on the Sketch beta?

**Comment by shiienurm** [comment]
Seems that there is already issue opened for it.
