### ISSUE TITLE
Cancelling upload

### ISSUE THREAD

**Issue by D-Sheep** [avocode/avocode#475]
IMPORTANT: Please try to describe how did it happen.

Cancelling an upload of a new design produces this error message.

-----
App v.2.4.2-d618096
Source UID: 115349
```
Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.
    at invariant (/usr/share/Avocode/resources/app.asar/node_modules/flux/lib/invariant.js:42:15)
    at o.Dispatcher.dispatch (/usr/share/Avocode/resources/app.asar/node_modules/flux/lib/Dispatcher.js:185:5)
    at o.handleViewAction (/usr/share/Avocode/resources/app.asar/node_modules/@avocode/core/lib/dispatcher.js:1:707)
    at t.module.exports.t.setDocument (/usr/share/Avocode/resources/app.asar/node_modules/@avocode/core/lib/active-document.js:1:1668)
    at t._fireNoActiveViewEvents (/usr/share/Avocode/resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:24433)
    at t._fireNoActiveViewEvents (/usr/share/Avocode/resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:999)
    at atom-workspace.<anonymous> (/usr/share/Avocode/resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:8427)
    at atom-workspace.handler (/usr/share/Avocode/resources/app.asar/src/space-pen-extensions.js:110:34)
    at atom-workspace.jQuery.event.dispatch (/usr/share/Avocode/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
    at atom-workspace.elemData.handle (/usr/share/Avocode/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/Avocode/resources/app.asar/src/command-registry.js:251:29)
    at CommandRegistry.handleCommandEvent (/usr/share/Avocode/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/Avocode/resources/app.asar/src/command-registry.js:166:19)
    at PaneContainerView.jQuery.fn.trigger (/usr/share/Avocode/resources/app.asar/src/space-pen-extensions.js:64:23)
    at 
```

**Comment by petrbrzek** [comment]
This bug is supposed to be fixed in 2.4.3 version. Could you update the app and let us know if it's fine?
