### ISSUE TITLE
Syncing error from Sketch Beta Version 3.4 (15009)

### ISSUE THREAD

**Issue by sawao** [avocode/avocode#480]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.1 running in Sketch 3.4
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/uxpersona/Library/Containers/com.bohemiancoding.sketch3.beta/Data/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

**Comment by rychlis** [comment]
Hi thanks for the report, this is a duplicate of #437

We're currently working on a solution
