### ISSUE TITLE
Select error

### ISSUE THREAD

**Issue by retyui** [avocode/avocode#484]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.3-3630f5a
Source UID: 122041
```
TypeError: Cannot read property 'x' of null
  at e.calculateBounds (C:\Users\asd\AppData\Local\avocode\app-2.4.3\resources\app.asar\node_modules\@avocode\select-tool\lib\select-tool.js:1:8064)
  at e.mousemoveDrag (C:\Users\asd\AppData\Local\avocode\app-2.4.3\resources\app.asar\node_modules\@avocode\select-tool\lib\select-tool.js:1:4959)
  at e.mousemoveDrag (C:\Users\asd\AppData\Local\avocode\app-2.4.3\resources\app.asar\node_modules\@avocode\select-tool\lib\select-tool.js:1:240)
  at C:\Users\asd\AppData\Local\avocode\app-2.4.3\resources\app.asar\node_modules\@avocode\select-tool\lib\select-tool.js:1:6212

```

**Comment by rychlis** [comment]
hey does it happen in every design or just in some? Could you please share the design with us at team@avocode.com? Thanks

**Comment by rychlis** [comment]
Closing due to no activity, we will reopen the issue if you provide new information, thanks
