### ISSUE TITLE
Export process fails to spawn

### ISSUE THREAD

**Issue by Pratnomenis** [avocode/avocode#495]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.3-3630f5a
Source UID: 124138
```
Error: spawn ENOMEM
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at exports.spawn (child_process.js:977:9)
  at exports.fork (child_process.js:574:10)
  at new Task (/home/anonimus/Avocode/resources/app.asar/src/task.js:44:27)
  at Function.module.exports.Task.once (/home/anonimus/Avocode/resources/app.asar/src/task.js:19:14)
  at GitRepository.module.exports.GitRepository.refreshStatus (/home/anonimus/Avocode/resources/app.asar/src/git-repository.js:398:37)
  at /home/anonimus/Avocode/resources/app.asar/src/git-repository.js:77:26

```

**Comment by vojtatranta** [comment]
Thank you for your report.
Seems you were trying to export some assets from your PSD, could you be more specific about what happen? Could you send this problematic PSD to [team@avocode.com](mailto:team@avocode.com)?

**Comment by rychlis** [comment]
Closing due to no activity, we will reopen the issue if you provide new information, thanks
