### ISSUE TITLE
Sync Error

### ISSUE THREAD

**Issue by ddotx** [avocode/avocode#501]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.1 running in Sketch 3.4
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/richstudio04/Library/Containers/com.bohemiancoding.sketch3/Data/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

**Comment by rychlis** [comment]
Please update to the latest Sketch extension 2.1.3 https://manager.avocode.com/downloads/#plugins
