### ISSUE TITLE
Cannot read property 'progress' after API call

### ISSUE THREAD

**Issue by retyui** [avocode/avocode#507]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.3-3630f5a
Source UID: 122041
```
TypeError: Cannot read property 'progress' of undefined
    at C:\Users\asd\AppData\Local\avocode\app-2.4.3\resources\app.asar\node_modules\@avocode\core\lib\user.js:1:12448
    at C:\Users\asd\AppData\Local\avocode\app-2.4.3\resources\app.asar\node_modules\@avocode\core\lib\api.js:1:766
    at C:\Users\asd\AppData\Local\avocode\app-2.4.3\resources\app.asar\node_modules\@avocode\core\lib\api.js:1:6899
    at C:\Users\asd\AppData\Local\avocode\app-2.4.3\resources\app.asar\node_modules\@avocode\core\lib\api.js:1:7489
    at C:\Users\asd\AppData\Local\avocode\app-2.4.3\resources\app.asar\node_modules\fstream\node_modules\graceful-fs\graceful-fs.js:104:5
    at FSReqWrap.oncomplete (fs.js:77:15)
```

**Comment by jankuca** [comment]
Can you elaborate a bit on what were the steps that lead to this situation? Please try to be as specific as possible as this seems to be an edge case.

**Comment by rychlis** [comment]
I am closing this because of no activity, we will of course re-open the issue if you provide more info, thanks

**Comment by karokar** [comment]
Same here:
`TypeError: Cannot read property 'progress' of undefined
  at C:\Users\Maria\AppData\Local\avocode\app-2.5.2\resources\app.asar\node_modules\@avocode\core\lib\user.js:1:13019
  at C:\Users\Maria\AppData\Local\avocode\app-2.5.2\resources\app.asar\node_modules\@avocode\core\lib\api.js:1:766
  at C:\Users\Maria\AppData\Local\avocode\app-2.5.2\resources\app.asar\node_modules\@avocode\core\lib\api.js:1:7834
  at C:\Users\Maria\AppData\Local\avocode\app-2.5.2\resources\app.asar\node_modules\@avocode\core\lib\api.js:1:8424
  at C:\Users\Maria\AppData\Local\avocode\app-2.5.2\resources\app.asar\node_modules\fstream\node_modules\graceful-fs\graceful-fs.js:104:5
  at FSReqWrap.oncomplete (fs.js:77:15)`
happens, when trying to proccess new design, after throwing 'Didn't get expected byte count' error.

**Comment by vojtatranta** [comment]
@karokar thank you for this information.
Does it repeat all the time again with one single design?

**Comment by karokar** [comment]
Nope, on 2.5.3 all works fine.
