### ISSUE TITLE
empty of undefined

### ISSUE THREAD

**Issue by marekhrabe** [avocode/avocode#523]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.5
Source UID: 4
```
TypeError: Cannot read property 'empty' of undefined
    at module.exports.React.createClass.render (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/project-manager/lib/components/page-item.js:1:976)
    at null._renderValidatedComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:1260:34)
    at null.mountComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:802:14)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:195:42)
    at ReactDOMComponent.Mixin._createContentMarkup (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:260:32)
    at ReactDOMComponent.mountComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:182:14)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:195:42)
    at ReactDOMComponent.Mixin._createContentMarkup (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:260:32)
    at ReactDOMComponent.mountComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:182:14)
    at null.mountComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:808:44)
    at ReactDOMComponent.ReactMultiChild.Mixin._mountChildByNameAtIndex (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:395:30)
    at ReactDOMComp
```

**Comment by jakubzitny** [comment]
Same/similar issues in #535 and #539. Closing this one.
