### ISSUE TITLE
Opened a page from project in the avocode app

### ISSUE THREAD

**Issue by Niladev** [avocode/avocode#534]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.5
Source UID: 38637
```
Error: ENOENT: no such file or directory, lstat '/Users/Ququ/Downloads/Avocode.app'
  at Error (native)
  at fs.lstatSync (fs.js:838:18)
  at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:170:16)
  at realpathSync (fs.js:1447:21)
  at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:253:24)
  at tryFile (module.js:118:15)
  at tryExtensions (module.js:126:20)
  at Function.Module._findPath (module.js:166:20)
  at Module._resolveFilename (module.js:322:25)
  at Function.Module._resolveFilename (/Users/Ququ/Downloads/Avocode.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:266:25)
  at Module.require (module.js:353:17)
  at require (module.js:372:17)
  at a.module.exports.a.getVariables (/Users/Ququ/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/language-manager.js:1:2943)
  at a.module.exports.a.processLayers (/Users/Ququ/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/language-manager.js:1:3428)
  at Object.module.exports._processLayers (/Users/Ququ/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/code-panel/lib/main.js:1:3738)
  at Object.module.exports._onVariablesChange (/Users/Ququ/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/code-panel/lib/main.js:1:3380)
  at emitNone (events.js:72:20)
  at emit (events.js:163:7)
  at e.module.exports.e.emitChange (/Users/Ququ/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/stores/base.js:1:558)
  at e.setItems (/Users/Ququ/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/stores/variables.js:1:1518)
  at t.<anonymous> (/Users/Ququ/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/store
```

**Comment by vojtatranta** [comment]
Thank you for you report.
Seems you have deleted Avocode.app from your downloads folder.
Reinstalling the app should work fine.
After unziping downloaded .zip package from http://avocode.com/download/ you should move Avocode into you Applications folder. Afterwards you should not get this error again.

**Comment by Niladev** [comment]
Correct, no longer getting this error.

**Comment by vojtatranta** [comment]
Great, thank you for using Avocode!
