### ISSUE TITLE
Manual syncing to revised design

### ISSUE THREAD

**Issue by Niladev** [avocode/avocode#535]
IMPORTANT: Please try to describe how did it happen.

---

App v.2.4.5
Source UID: 133107

```
TypeError: Cannot read property 'empty' of undefined
  at [object Object].module.exports.React.createClass.render (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/project-manager/lib/components/page-item.js:1:976)
  at [object Object]._renderValidatedComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:1260:34)
  at [object Object].updateComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:1187:30)
  at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:1131:10)
  at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:1074:12)
  at [object Object].ReactComponent.Mixin.receiveComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactComponent.js:307:12)
  at [object Object].ReactCompositeComponentMixin.receiveComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:1157:43)
  at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:287:21)
  at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:247:14)
  at ReactDOMComponent.Mixin._updateDOMChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:457:12)
  at ReactDOMComponent.updateComponent 
```

**Comment by vojtatranta** [comment]
Thank you for your report!
Can you describe how did this happen?

**Comment by Niladev** [comment]
Synced a new revision through Sketch using the 2.1.5 version of the plugin after which I went to Avocode to manually sync the new revision which gave this error.
Had to restart the app in order for the sync to complete.

**Comment by vojtatranta** [comment]
A see and restarting fixed this error?

**Comment by Niladev** [comment]
Restarting seemed to also restart the syncing which then worked and went through.

**Comment by vojtatranta** [comment]
This might be connected to the Sketch extension itself.
If you experience same issue again, you may try to use newer version of Avocode Sketch extension: https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md
Please let us know, when you get same error again.

**Comment by bolekkerous** [comment]
This shouldn't happen anymore with the latest Sketch plugin.

You can always download the latest version here:

https://manager.avocode.com/downloads/

If you still experience this problem or any other, please create a new issue with it.
