### ISSUE TITLE
Error on OS X El Capitan

### ISSUE THREAD

**Issue by josemanuelguzman** [avocode/avocode#539]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.5
Source UID: 126161
```
TypeError: Cannot read property 'empty' of undefined
    at module.exports.React.createClass.render (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/project-manager/lib/components/page-item.js:1:976)
    at null._renderValidatedComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:1260:34)
    at null.mountComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:802:14)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:195:42)
    at ReactDOMComponent.Mixin._createContentMarkup (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:260:32)
    at ReactDOMComponent.mountComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:182:14)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:195:42)
    at ReactDOMComponent.Mixin._createContentMarkup (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:260:32)
    at ReactDOMComponent.mountComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:182:14)
    at null.mountComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:808:44)
    at ReactDOMComponent.ReactMultiChild.Mixin._mountChildByNameAtIndex (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:395:30)
    at ReactDOMComp
```

**Comment by jakubzitny** [comment]
Hi, thanks for the report. We already have the same issue in #535 and #523 and we think it might be a problem with Sketch extension. Can you please confirm it happened after sync from Sketch extension?

Restarting the app or updating the Sketch extension to our [latest beta](https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md) might help.

I am closing this issue, let's continue the discussion in #535.
