### ISSUE TITLE
Faced issue while I was trying to sync designs using the plugin. 

### ISSUE THREAD

**Issue by noopurvarma** [avocode/avocode#554]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.4.3
```
Error: ENOENT, no such file or directory '/Users/Noopur/…/avocode.token'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at main (/Users/Noopur/…/avocode-exporter/lib/main.js:1:3056)
    at Object.<anonymous> (/Users/Noopur/…/avocode-exporter/lib/main.js:1:3473)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

**Comment by vojtatranta** [comment]
Thank you for your report, this looks like same issue as this one https://github.com/avocode/avocode/issues/517

You can try to use newer version of sketch plugin. Installation guide is here: https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md
