### ISSUE TITLE
Error while slicing 

### ISSUE THREAD

**Issue by kletchatii** [avocode/avocode#564]
IMPORTANT: Please try to describe how did it happen.
My tring to slice a layer
-----
App v.2.4.5
Source UID: 137251
```
TypeError: Cannot read property 'bounds' of undefined
  at Object.getBoundsForLayers (/home/kletchatii/Program/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/document.js:1:724)
  at exportRule (/home/kletchatii/Program/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/export.js:1:5697)
  at t._instantExport (/home/kletchatii/Program/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:11420)
  at t._register (/home/kletchatii/Program/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:12487)
  at Object.ID_15 (/home/kletchatii/Program/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:459)
  at o._invokeCallback (/home/kletchatii/Program/Avocode-linux-x64/resources/app.asar/node_modules/flux/lib/Dispatcher.js:198:24)
  at o.dispatch (/home/kletchatii/Program/Avocode-linux-x64/resources/app.asar/node_modules/flux/lib/Dispatcher.js:174:14)
  at o.handleViewAction (/home/kletchatii/Program/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/dispatcher.js:1:707)
  at o.module.exports.instantExport [as onExport] (/home/kletchatii/Program/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/export-panel/lib/actions/export.js:1:1651)
  at o.module.exports.o.onConfirm (/home/kletchatii/Program/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/export-panel/lib/instant-export-dialog.js:1:4563)
  at o.module.exports.o.onSave (/home/kletchatii/Program/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/export-panel/lib/instant-export-dialog.js:1:4067)
  at space-pen-div.<anonymous> (/home/kletchatii/Program/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/export-panel/l
```

**Comment by jankuca** [comment]
Thank you for the report! We added this to our internal ticketing system and will look at it shortly. We'll keep you posted.

How severe is the issue? Does it happen regularly and prevents the slice tool from being used or was this an isolated occurrence?

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
