### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by anshulg12** [avocode/avocode#569]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.5
Source UID: 130129
```
Error: ENOSPC: no space left on device, write
    at Error (native)
    at Object.fs.writeSync (fs.js:659:20)
    at Object.fs.writeFileSync (fs.js:1168:24)
    at Object.fsPlus.writeFileSync (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at StorageFolder.module.exports.StorageFolder.store (/Applications/Avocode.app/Contents/Resources/app.asar/src/storage-folder.js:14:17)
    at Atom.module.exports.Atom.saveSync (/Applications/Avocode.app/Contents/Resources/app.asar/src/atom.js:887:50)
    at t.saveAppState (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:11639)
    at e._finishSync (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:6611)
    at e._handleUserDataError (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:7909)
    at e._onUserData (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:8126)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:369
    at Request._callback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:3657)
    at self.callback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:198:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:166:7)
    at Request.onRequestError (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:867:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:166:7)
    at TLSSocket.socketErrorListener (_http_client.js:254:9)
    at emitO
```

**Comment by anshulg12** [comment]
Sorry, was not an issue, forget about it

**Comment by vojtatranta** [comment]
No problem.
