### ISSUE TITLE
Sync problem

### ISSUE THREAD

**Issue by musterid** [avocode/avocode#572]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.5
Source UID: 135272
```
TypeError: this._task.removeListener is not a function
    at t._unregisterTaskListeners (/Users/jonste/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:3779)
    at t._restart (/Users/jonste/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:2738)
    at t._send (/Users/jonste/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:6454)
    at t._addRequest (/Users/jonste/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:4400)
    at t.downloadFiles (/Users/jonste/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:2016)
    at e.downloadFiles (/Users/jonste/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:7802)
    at t.module.exports.t._createImageRequest (/Users/jonste/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-downloader.js:1:1938)
    at t.module.exports.t.downloadImages (/Users/jonste/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-downloader.js:1:1150)
    at e._downloadRevisionImages (/Users/jonste/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:13922)
    at /Users/jonste/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:12737
    at /Users/jonste/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:766
    at /Users/jonste/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:6957
    at /Users/jonste/Downloads/Avocode.app/Contents/Resources/app.asar/node_mo
```

**Comment by vojtatranta** [comment]
Thank you for your report.
Can you please describe what were you trying to do and whether the problem keeps poping up when you try again?
Thanks

**Comment by jakubzitny** [comment]
This issue is similar to #605, let's continue the discussion over there.
