### ISSUE TITLE
Avocode export failed.

### ISSUE THREAD

**Issue by dangn** [avocode/avocode#573]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.4.4
```
Error: ENOENT, no such file or directory '/Users/dnguyen/…/avocode-exporter/temp/CFC4C0F5-10D1-4CEF-9EE2-36E2BDD203F0.json'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at e.process (/Users/dnguyen/…/avocode-exporter/lib/exporter.js:1:2006)
    at e.r (/Users/dnguyen/…/avocode-exporter/lib/exporter.js:1:1376)
    at new e (/Users/dnguyen/…/avocode-exporter/lib/exporter.js:1:1800)
    at r.<anonymous> (/Users/dnguyen/…/avocode-exporter/lib/exporter.js:1:2815)
    at new r (/Users/dnguyen/…/avocode-exporter/lib/exporter.js:1:2921)
    at /Users/dnguyen/…/avocode-exporter/lib/main.js:1:3274
    at Object.findObject.onEndCallback (/Users/dnguyen/…/avocode-exporter/lib/main.js:1:1940)
    at findElement (/Users/dnguyen/…/avocode-exporter/lib/main.js:1:1143)
```

**Comment by vojtatranta** [comment]
This seems like failure of Avocode ZIP extraction.
There's probably same issue here with solution https://github.com/avocode/avocode/issues/517
Closing as duplicated.
