### ISSUE TITLE
error

### ISSUE THREAD

**Issue by DariaKachailo** [avocode/avocode#579]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.5
Source UID: 88379
```
TypeError: Cannot read property 'empty' of undefined
    at module.exports.React.createClass.render (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/project-manager/lib/components/page-item.js:1:976)
    at null._renderValidatedComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:1260:34)
    at null.updateComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:1187:30)
    at ReactCompositeComponentMixin._performComponentUpdate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:1131:10)
    at ReactCompositeComponentMixin.performUpdateIfNecessary (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:1074:12)
    at ReactComponent.Mixin.receiveComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactComponent.js:307:12)
    at ReactCompositeComponentMixin.receiveComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:1157:43)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:287:21)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:247:14)
    at ReactDOMComponent.Mixin._updateDOMChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:457:12)
    at ReactDOMComponent.updateComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/Re
```

**Comment by vojtatranta** [comment]
Thank you for your report.
This is known and closed issue, you can find the solution here: https://github.com/avocode/avocode/issues/539
