### ISSUE TITLE
Bug after canceling upload file

### ISSUE THREAD

**Issue by jansedivy** [avocode/avocode#594]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.5.0
Source UID: 142956
```
Error: No revision passed to Avocode#_loadRevisionToView()
  at t._loadRevisionToView (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:19456)
  at t._handleUploadResult (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:19255)
  at t._handleAction (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:9057)
  at Object.ID_8 (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:1157)
  at o._invokeCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:198:24)
  at o.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:174:14)
  at o.handleServerAction (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/dispatcher.js:1:980)
  at t._emitItemRemove (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uploader.js:1:13064)
  at t._removeUpload (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uploader.js:1:10398)
  at t.abortUpload (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uploader.js:1:3063)
  at [object Object].module.exports.React.createClass._abortUpload (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/components/upload-queue-item.js:1:650)
  at Object.executeDispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:110:21)
  at SimpleEventPlugin.executeDispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/SimpleEventPlugin.js:305:40)
  
```

**Comment by vojtatranta** [comment]
Thank you for your report.
We haven't encountered such bug yet.
Can you tell use what were you trying to do? Have you been uploading multiple files? Does canceling fails again and again?

**Comment by rychlis** [comment]
I am closing this issue due to no activity. We will of course reopen the issue if you provide more information, thanks
