### ISSUE TITLE
??

### ISSUE THREAD

**Issue by shlee83** [avocode/avocode#596]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.5
Source UID: 121037
```
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at invariant (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/invariant.js:35:15)
    at Object.getID (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMount.js:85:13)
    at Object.ReactMount.isRenderedByReact (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMount.js:567:25)
    at Object.ReactMount.getFirstReactDOM (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMount.js:582:22)
    at handleTopLevelImpl (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventListener.js:63:35)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:134:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
    at Object.batchedUpdates (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdates.js:109:20)
    at ReactEventListener.dispatchEvent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventListener.js:175:20)
```

**Comment by jankuca** [comment]
Hi, thank you. Can you describe where in the app you were and roughly what were you doing when this happened?
