### ISSUE TITLE
Sync problem on Avocode App (synced via Sketch 3.4.4)

### ISSUE THREAD

**Issue by Naemy** [avocode/avocode#601]
IMPORTANT: Please try to describe how did it happen.
I tried to sync a document to avocode via Sketch; works great on browsers, however the app can't access the file
-----
App v.2.4.5
Source UID: 9715
```
TypeError: Cannot read property 'empty' of undefined
    at module.exports.React.createClass.render (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/project-manager/lib/components/page-item.js:1:976)
    at null._renderValidatedComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:1260:34)
    at null.mountComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:802:14)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:195:42)
    at ReactDOMComponent.Mixin._createContentMarkup (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:260:32)
    at ReactDOMComponent.mountComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:182:14)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:195:42)
    at ReactDOMComponent.Mixin._createContentMarkup (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:260:32)
    at ReactDOMComponent.mountComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:182:14)
    at null.mountComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:808:44)
    at ReactDOMComponent.ReactMultiChild.Mixin._mountChildByNameAtIndex (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:395:30)
    at ReactDOMComp
```

**Comment by vojtatranta** [comment]
Thank you for your report.
This is know issue, it is due to old version of Sketch Extension for Avocode.
Take a look here, where you can find more info: https://github.com/avocode/avocode/issues/535
Basically we recommend you to try newer version of Avocode Extension for Sketch, install instructions are to be fund in the link as well.
Closing as duplicated.
