### ISSUE TITLE
Was uploading 3 PSD files at once then avocode started crashing.

### ISSUE THREAD

**Issue by simaks** [avocode/avocode#605]
IMPORTANT: Please try to describe how did it happen.
I think it crashed at the time of upload completed for each file, but there were more than 3 errors

---

App v.2.5.0
Source UID: 128983

```
TypeError: this._task.removeListener is not a function
  at t._unregisterTaskListeners (/opt/Avocode-2.5.0-beta/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:3779)
  at t._restart (/opt/Avocode-2.5.0-beta/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:2738)
  at t._send (/opt/Avocode-2.5.0-beta/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:6454)
  at t._addRequest (/opt/Avocode-2.5.0-beta/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:4400)
  at t.downloadFiles (/opt/Avocode-2.5.0-beta/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:2016)
  at e.downloadFiles (/opt/Avocode-2.5.0-beta/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:7870)
  at t.module.exports.t.downloadThumbnails (/opt/Avocode-2.5.0-beta/resources/app.asar/node_modules/@avocode/core/lib/assets-downloader.js:1:1124)
  at e._downloadThumbnails (/opt/Avocode-2.5.0-beta/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:15805)
  at e._updateDesignThumbnail (/opt/Avocode-2.5.0-beta/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:20984)
  at /opt/Avocode-2.5.0-beta/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:20213
  at /opt/Avocode-2.5.0-beta/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:766
  at Request._callback (/opt/Avocode-2.5.0-beta/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:4329)
  at Request.self.callback (/opt/Avocode-2.5.0-beta/resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:198:22)
  at emitTwo (events.js:92:20)
  at Request.emit (events.js:169:7)
  at Request.<anonymous> (/opt/Avocode-2.5.0-beta/resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:1035:10)
  at emitOne (even
```

**Comment by jankuca** [comment]
Hi, thanks for the report.

What is the result? Can you access the files? Were you able to access them right away or were these errors preventing you to open them?

**Comment by simaks** [comment]
I just opened the stable avocode version and I saw my files uploaded and used them successfull. I think I saw only one file thumbnail out of three in beta version before closing it.

**Comment by vojtatranta** [comment]
So the problem does not persist anymore?

**Comment by simaks** [comment]
Ok, now I opened avocode 2.5.0 beta again and tried doing the same thing again.
Now I can tell that I got exactly 2 errors for each PSD right after it finished processing each PSD.
result is only one thumbnail appeard out of three and that one is greyed out with text "Processing 100%": http://storage5.static.itmages.com/i/16/0126/h_1453799511_2409137_b546e90733.png

After a while I got another error and then all three thumbnails appeared, but without image preview:
http://storage3.static.itmages.com/i/16/0126/h_1453799718_6205279_b42352b5ac.png

after opening new tab: http://i.imgur.com/7KaShDu.png


Errors:
1 file:
* http://pastebin.com/ykDg5BVr
* http://pastebin.com/cW7Lim0B

2 file:
* http://pastebin.com/00fHY7ja
* http://pastebin.com/jAC9814i

3 file:
* http://pastebin.com/nnYEV0Ek
* http://pastebin.com/LMuM5BKV

the next one:
http://pastebin.com/03JMVHnA

**Comment by simaks** [comment]
Tried dropping single one of those PSD again and this is what I see: http://i.imgur.com/2m56GYF.png

**Comment by vojtatranta** [comment]
Thank you for this detailed information.
Can you either share with us at team@avocode.com all the problematic PSDs?

**Comment by simaks** [comment]
sent to team@avocode.com

**Comment by vojtatranta** [comment]
Thanks a lot.

**Comment by vojtatranta** [comment]
We tried to upload the PSDs you have sent us and it went without any troubles.
Maybe that is because we use current version of app 2.5.0 not Beta.
In order to update your app, just click at check for updates in Avocode menu, update overlay should pop up in few seconds.

Or is there any reason why you use Beta version of app?

**Comment by simaks** [comment]
Just tried on 2.5.2 and got similar crash errors, but in the end seemed to be working fine after dismissing them all.
version 2.4.5 was working without these crash errors.

**Comment by simaks** [comment]
Sorry actually 2.5.2 did not worked. It just stopped at 95% Proccessing.
And after opening 2.4.5 this is what I saw:
http://storage4.static.itmages.com/i/16/0126/h_1453814388_3422844_1af5e7cf2e.png
Then after like 15 seconds:
http://i.imgur.com/NaWCXcw.png

And after all this I could inspect new designs on both versions normally

**Comment by vojtatranta** [comment]
I see.
So now everything works?

**Comment by tarasholub** [comment]
Hi. I have same problem with upload files on 2.5.2. It just stopped at 95% proccessing. How to backup previous version of avocode?

**Comment by vojtatranta** [comment]
@tarasholub it should stop, because processing cannot be estimated. Have you tried waiting a bit longer? If you have large PSD it might take a while.

**Comment by simaks** [comment]
Still happens on avocode v2.6.0
when uploading new PSD it throws error and then thumbnail text stops at "Processing 95%"

After closing and reopening avocode, uploaded design is missing, but then appears with no-pic thumbnail after few seconds.

When trying to open thet PSD some another error was thrown.

After reopening avocode few times again and opening the new PSD it opened successfully, and PSD thumbnail is now also visible in the PSD list

**Comment by bolekkerous** [comment]
This should not happen anymore with the latest version of the app.

You can always download the latest version here:

https://manager.avocode.com/downloads/

If you still experience this problem or any other problem, please create a new issue or comment here.
