### ISSUE TITLE
error

### ISSUE THREAD

**Issue by TeamWeb4u** [avocode/avocode#613]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.5.2
Source UID: 120501
```
TypeError: Cannot read property 'progress' of undefined
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:13019
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:766
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:7834
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:8424
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/fstream/node_modules/graceful-fs/graceful-fs.js:104:5
  at FSReqWrap.oncomplete (fs.js:77:15)

```

**Comment by vojtatranta** [comment]
This is duplicated issue. More info is here: #507
