### ISSUE TITLE
error on doubleclick on object

### ISSUE THREAD

**Issue by therealpecus** [avocode/avocode#627]
IMPORTANT: Please try to describe how did it happen.

Doubleclicking on object in PSD file uploaded to 2.5.2.

-----
App v.2.5.2
Source UID: 136472
```
TypeError: Cannot read property 'then' of undefined
  at e.requestRevisionDownload (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:24994)
  at e.loadRevision (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:25219)
  at t._loadRevisionToView (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:20238)
  at t._addRevisionView (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:17623)
  at t._openAvocodeResource (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:16852)
  at t.opener (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:15249)
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:1157
  at wrappedOpener (/Applications/Avocode.app/Contents/Resources/app.asar/src/workspace.js:525:18)
  at Workspace.module.exports.Workspace.openURIInPane (/Applications/Avocode.app/Contents/Resources/app.asar/src/workspace.js:441:22)
  at Workspace.module.exports.Workspace.open (/Applications/Avocode.app/Contents/Resources/app.asar/src/workspace.js:371:19)
  at t.openSubdocument (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:28407)
  at e._onDblClick (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/select-tool/lib/select-tool.js:1:2671)
  at t.module.exports.Emitter.emit (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:118:15)
  at HTMLCanvasElement.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avoco
```

**Comment by vojtatranta** [comment]
Hi, thank you for your report.
Can you please tell us how did it happen? So that we could reproduce such error.
Thanks.

**Comment by rychlis** [comment]
I am closing the issue due to no activity. We'll definetely re-open the issue if you can still reproduce it with latest Avocode
