### ISSUE TITLE
Error selecting text in asset title input box (export pane)

### ISSUE THREAD

**Issue by Helstein** [avocode/avocode#670]
1. Selected an icon to be exported
2. Clicked "Define Export Rules" in "Export" pane
3. Entered title for the icon
4. Pressed CTRL + A

-----
App v.2.5.2
Source UID: 65458
```
TypeError: menu.sendActionToFirstResponder is not a function
  at HTMLDocument.<anonymous> (C:\Users\vytautas\AppData\Local\avocode\app-2.5.2\resources\app.asar\src\window-event-handler.js:170:20)
  at HTMLDocument.handler (C:\Users\vytautas\AppData\Local\avocode\app-2.5.2\resources\app.asar\src\space-pen-extensions.js:115:32)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\vytautas\AppData\Local\avocode\app-2.5.2\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\vytautas\AppData\Local\avocode\app-2.5.2\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\vytautas\AppData\Local\avocode\app-2.5.2\resources\app.asar\src\command-registry.js:251:29)
  at C:\Users\vytautas\AppData\Local\avocode\app-2.5.2\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\vytautas\AppData\Local\avocode\app-2.5.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\vytautas\AppData\Local\avocode\app-2.5.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\vytautas\AppData\Local\avocode\app-2.5.2\resources\app.asar\src\window-event-handler.js:185:27)

```

**Comment by vojtatranta** [comment]
This is duplicated issue.
More info is to be found here: #597
