### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by dclarktandem** [avocode/avocode#671]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.1 running in Sketch 3.4.4
```
Error: ENOENT, no such file or directory '/Users/tandemseven/…/avocode.token'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at main (/Users/tandemseven/…/avocode-exporter/lib/main.js:1:3056)
    at Object.<anonymous> (/Users/tandemseven/…/avocode-exporter/lib/main.js:1:3473)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

**Comment by bolekkerous** [comment]
Hello!
It looks like you are using old version of Sketch extension. We've released new version yesterday.

Could you please try it with that one? You can download it here:
https://manager.avocode.com/downloads/#plugins

Let me know whether it helps!

**Comment by dclarktandem** [comment]
Yes, that worked!


On Jan 30, 2016, at 4:08 AM, Bolek <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello!
It looks like you are using old version of Sketch extension. We've released new version yesterday.

Could you please try it with that one? You can download it here:
https://manager.avocode.com/downloads/#plugins

Let me know whether it helps!

-

**Comment by rychlis** [comment]
Great to hear that!
