### ISSUE TITLE
 Cannot read property 'progress'

### ISSUE THREAD

**Issue by vitnait** [avocode/avocode#676]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.5.2
Source UID: 132525
```
TypeError: Cannot read property 'progress' of undefined
    at Immediate._onImmediate (C:\Users\Виталий\AppData\Local\avocode\app-2.5.2\resources\app.asar\node_modules\@avocode\core\lib\user.js:1:15027)
    at processImmediate [as _immediateCallback] (timers.js:361:17)
```

**Comment by vojtatranta** [comment]
This is duplicated issue. More info is here: #507
