### ISSUE TITLE
I'm only open design in app and away to my IDE.

### ISSUE THREAD

**Issue by vasiliy0s** [avocode/avocode#691]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.5.2
Source UID: 3858
```
TypeError: Cannot read property 'statusCode' of undefined
  at Request._callback (/opt/avocode/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:3394)
  at self.callback (/opt/avocode/resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:198:22)
  at emitOne (events.js:77:13)
  at Request.emit (events.js:166:7)
  at Request.onRequestError (/opt/avocode/resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:820:8)
  at emitOne (events.js:77:13)
  at ClientRequest.emit (events.js:166:7)
  at TLSSocket.socketErrorListener (_http_client.js:254:9)
  at emitOne (events.js:77:13)
  at TLSSocket.emit (events.js:166:7)
  at TLSSocket.onHangUp (_tls_wrap.js:953:14)
  at TLSSocket.g (events.js:257:16)
  at emitNone (events.js:72:20)
  at TLSSocket.emit (events.js:163:7)
  at _stream_readable.js:891:16
  at process._tickCallback (node.js:347:13)

```

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
