### ISSUE TITLE
I got a notification toast in OS X about a new design being available. I clicked on the toast and this happened.

### ISSUE THREAD

**Issue by stevebrown** [avocode/avocode#697]
IMPORTANT: Please try to describe how did it happen.

Was notified of a new design update by Avocode with an OS X notification toast. I clicked the toast as instructed and this error was trapped. I had Avocode 2.5.2 open at the time. Using OS X 10.11.3.
-----
App v.2.5.2
Source UID: 4218
```
Error: Emitter has been disposed
  at Emitter.module.exports.Emitter.on (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:77:15)
  at e.module.exports.e.onDidClose (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode-view.js:1:880)
  at t._loadRevisionToView (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:19819)
  at t.openRevision (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:28091)
  at o (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:30832)
  at Notification.o.onclick (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:31319)

```

**Comment by petrbrzek** [comment]
This error should be now fixed with the latest Avocode 2.5.3. Please try it and let us know.
