### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by dkacha** [avocode/avocode#703]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.5.2
Source UID: 88763
```
TypeError: Cannot read property 'progress' of undefined
    at C:\Users\uzivatel\AppData\Local\avocode\app-2.5.2\resources\app.asar\node_modules\@avocode\core\lib\user.js:1:13019
    at C:\Users\uzivatel\AppData\Local\avocode\app-2.5.2\resources\app.asar\node_modules\@avocode\core\lib\api.js:1:766
    at C:\Users\uzivatel\AppData\Local\avocode\app-2.5.2\resources\app.asar\node_modules\@avocode\core\lib\api.js:1:7834
    at C:\Users\uzivatel\AppData\Local\avocode\app-2.5.2\resources\app.asar\node_modules\@avocode\core\lib\api.js:1:8424
    at C:\Users\uzivatel\AppData\Local\avocode\app-2.5.2\resources\app.asar\node_modules\fstream\node_modules\graceful-fs\graceful-fs.js:104:5
    at FSReqWrap.oncomplete (fs.js:77:15)
```

**Comment by vojtatranta** [comment]
Thank you for your report.
This is known issue, for further info please follow thread here: #507
