### ISSUE TITLE
Problem With Sketch 3.5.1

### ISSUE THREAD

**Issue by Paul2025** [avocode/avocode#709]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.5.1
```
Error: Error: Command failed: 2016-02-06 11:58:53.791 sketchtool[624:11378] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer)
2016-02-06 11:58:53.792 sketchtool[624:11378] Error: caught exception whilst decoding (version 76):*** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer)
Failed to open document file:///Proyectos%20Kation/En%20Progreso/Constructora%20AG/UIConstructoraAG.sketch
((null) MSDocumentDomain:11)


    at /Users/pauljimenezrojas/…/avocode-exporter/lib/image-exporter.js:1:873
    at ChildProcess.exithandler (child_process.js:651:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Socket.<anonymous> (child_process.js:966:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

**Comment by vojtatranta** [comment]
You are using new Sketch with old Avocode Sketch Extension. Please upgrade to newer version.
Instructions and other info is to be found here: #707
