### ISSUE TITLE
Next problem

### ISSUE THREAD

**Issue by ioszhuk** [avocode/avocode#711]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.5.3
Source UID: 113287
```
TypeError: Cannot read property 'progress' of undefined
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:13256
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:766
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:7834
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:8424
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/@avocode/decompress/node_modules/vinyl-fs/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:77:15)
```

**Comment by vojtatranta** [comment]
Thank you for your report.
This is known issue and we are working on fix.
Please follow this thread for more info: #507
