### ISSUE TITLE
Error uploading (pt 2)

### ISSUE THREAD

**Issue by ehigz** [avocode/avocode#715]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.5.3
Source UID: 19006
```
TypeError: Cannot read property 'progress' of undefined
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:13256
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:766
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:7834
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:8424
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/@avocode/decompress/node_modules/vinyl-fs/node_modules/graceful-fs/graceful-fs.js:43:10
  at FSReqWrap.oncomplete (fs.js:77:15)

```

**Comment by vojtatranta** [comment]
This is duplicated issue.
Please follow thread here: #507
