### ISSUE TITLE
Error uploading (pt 3)

### ISSUE THREAD

**Issue by ehigz** [avocode/avocode#716]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.5.3
Source UID: 19006
```
TypeError: Cannot read property 'progress' of undefined
  at Immediate._onImmediate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:15335)
  at processImmediate [as _immediateCallback] (timers.js:361:17)

```

**Comment by vojtatranta** [comment]
Thank you for your report.
Can you please tell us what were you trying to do?
Thanks

**Comment by rychlis** [comment]
I am closing the issue due to no activity. We'll definetely re-open the issue if you provide m
