### ISSUE TITLE
Syncing didn't work

### ISSUE THREAD

**Issue by oemisch** [avocode/avocode#717]
IMPORTANT: Please try to describe how did it happen.
I just clicked "Sync to Avocode"
-----
Sketch Exporter 2.1.5 running in Sketch 3.5.1
```
Error: ENOENT, no such file or directory '/Users/oemisch/…/avocode.token'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at main (/Users/oemisch/…/avocode-exporter/lib/main.js:1:3056)
    at Object.<anonymous> (/Users/oemisch/…/avocode-exporter/lib/main.js:1:3473)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

**Comment by vojtatranta** [comment]
Thank you for your report.
You are using old version of Avocode Sketch extension. Could you please upgrade to newer version? 
Instructions are here: https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md
Let us know whether it worked, thanks.

**Comment by oemisch** [comment]
Hey, I'm gonna try that later today. However, I downloaded the plugin from your website yesterday, maybe you should provide the most recent extension there :) no one likes to install something just to update it.
Best,
Alex
