### ISSUE TITLE
This happened when canceling the upload from the Avocode app

### ISSUE THREAD

**Issue by lucien144** [avocode/avocode#732]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.3.2-ea60620
Source UID: 47943
```
TypeError: Cannot read property 'id' of null
  at [object Object].module.exports.React.createClass._onAbortClick (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assign-design-panel.js:1:3437)
  at Object.executeDispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:110:21)
  at SimpleEventPlugin.executeDispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/SimpleEventPlugin.js:305:40)
  at forEachEventDispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:98:5)
  at Object.executeDispatchesInOrder (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:119:3)
  at executeDispatchesAndRelease (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:46:22)
  at forEachAccumulated (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/forEachAccumulated.js:25:8)
  at Object.EventPluginHub.processEventQueue (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:251:5)
  at runEventQueueInBatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
  at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventEmitterMixin.js:44:5)
  at handleTopLevelImpl (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventListener.js:80:24)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:134
```

**Comment by petrbrzek** [comment]
Please update to the latest Avocode version (2.5.4). If you still have this problem in the new app, feel free to report it as a new issue.
