### ISSUE TITLE
Didn't open sketch file (Avocode Sync 3.1). Help please.

### ISSUE THREAD

**Issue by zevsik** [avocode/avocode#733]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.5.1
```
Error: Error: Command failed: 2016-02-10 15:54:41.886 sketchtool[4530:61714] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer)
2016-02-10 15:54:41.886 sketchtool[4530:61714] Error: caught exception whilst decoding (version 76):*** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer)
Failed to open document file:///Users/adminUser/Downloads/budzgo_website_10.sketch
((null) MSDocumentDomain:11)


    at /Users/adminUser/…/avocode-exporter/lib/image-exporter.js:1:873
    at ChildProcess.exithandler (child_process.js:651:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Socket.<anonymous> (child_process.js:966:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

**Comment by rychlis** [comment]
Hello,

this error is not from Avocode Sync 3.1, are you sure you are launching the new extension? See the installation [guide](https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update)

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
