### ISSUE TITLE
IMPORTANT: Please try to describe how did it happen

### ISSUE THREAD

**Issue by neborskiyA** [avocode/avocode#737]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.5.3
Source UID: 48685
```
TypeError: Cannot read property 'progress' of undefined
  at C:\Users\unit1\AppData\Local\avocode\app-2.5.3\resources\app.asar\node_modules\@avocode\core\lib\user.js:1:13256
  at C:\Users\unit1\AppData\Local\avocode\app-2.5.3\resources\app.asar\node_modules\@avocode\core\lib\api.js:1:766
  at C:\Users\unit1\AppData\Local\avocode\app-2.5.3\resources\app.asar\node_modules\@avocode\core\lib\api.js:1:7834
  at C:\Users\unit1\AppData\Local\avocode\app-2.5.3\resources\app.asar\node_modules\@avocode\core\lib\api.js:1:8424
  at C:\Users\unit1\AppData\Local\avocode\app-2.5.3\resources\app.asar\node_modules\@avocode\core\node_modules\@avocode\decompress\node_modules\vinyl-fs\node_modules\graceful-fs\graceful-fs.js:43:10
  at FSReqWrap.oncomplete (fs.js:77:15)

```

**Comment by jankuca** [comment]
Hi, please upgrade to 2.5.4 which includes a fix for this case.
