### ISSUE TITLE
I just opened a PSD and the app crashed

### ISSUE THREAD

**Issue by GuilhermeMedeiros** [avocode/avocode#738]
I just opened a PSD

-----
App v.2.5.4
Source UID: 4029
```
TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'
  at TypeError (native)
  at t.module.exports.t._loadMaskedBy (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:3710)
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:1011
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:3245
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:200:33
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:3183
  at replenish (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:191:21)
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:203:33
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:3183
  at replenish (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:191:21)
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:203:33
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:3183
  at replenish (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:191:21)
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:203:33
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:3183
  at replenish (/Applications/Avocode.
```

**Comment by vojtatranta** [comment]
Thank you for this report.
You are not able to open this particular PSD? Or is it happening again and again with different designs?

**Comment by GuilhermeMedeiros** [comment]
It happened just once, I couldn't open any PSD. 
I'm able to open it now.
