### ISSUE TITLE
Received this error after syncing a sketch to avocode.

### ISSUE THREAD

**Issue by hraynaud** [avocode/avocode#740]
I have both this version of the plugin and the beta version installed.

The beta got hung up on the loading pop up page with the "rolling out red carpet text".  I downloaded and installed this version (without uninstalling the beta) tried again. everything worked until the end when I received this error below.

IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.5.2
```
Error: Error: Command failed: 2016-02-11 14:50:48.412 sketchtool[26045:1391861] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer)
2016-02-11 14:50:48.412 sketchtool[26045:1391861] Error: caught exception whilst decoding (version 76):*** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer)
Failed to open document file:///Users/herbyraynaud/Downloads/airbo-homepage%20(1).sketch
((null) MSDocumentDomain:11)


    at /Users/herbyraynaud/…/avocode-exporter/lib/image-exporter.js:1:873
    at ChildProcess.exithandler (child_process.js:651:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Socket.<anonymous> (child_process.js:966:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

**Comment by marekhrabe** [comment]
Hi, we have released Sketch Extension 3.2 with Sketch 3.5 support. Please download the latest version from https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update
