### ISSUE TITLE
When i tried to export avocode alerted error

### ISSUE THREAD

**Issue by ak1987** [avocode/avocode#742]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.5.4
Source UID: 137485
```
TypeError: Cannot read property 'bounds' of undefined
    at Object.getBoundsForLayers (/home/ak/programs/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/document.js:1:724)
    at exportRule (/home/ak/programs/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/export.js:1:5697)
    at t._instantExport (/home/ak/programs/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:11420)
    at t._register (/home/ak/programs/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:12487)
    at Object.ID_16 (/home/ak/programs/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:459)
    at o._invokeCallback (/home/ak/programs/Avocode-linux-x64/resources/app.asar/node_modules/flux/lib/Dispatcher.js:198:24)
    at o.dispatch (/home/ak/programs/Avocode-linux-x64/resources/app.asar/node_modules/flux/lib/Dispatcher.js:174:14)
    at o.handleViewAction (/home/ak/programs/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/dispatcher.js:1:707)
    at o.module.exports.instantExport [as onExport] (/home/ak/programs/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/export-panel/lib/actions/export.js:1:1651)
    at o.module.exports.o.onConfirm (/home/ak/programs/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/export-panel/lib/instant-export-dialog.js:1:4563)
    at o.module.exports.o.onSave (/home/ak/programs/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/export-panel/lib/instant-export-dialog.js:1:4067)
    at o.onSave (/home/ak/programs/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/export-panel/lib/instant-export-dialog.js:1:239)
    at HTMLButtonElement.<anonymous> (/hom
```

**Comment by vojtatranta** [comment]
Has it worked when you tried it again? Does this occur just with one design?
If so, would you send us this PSD at team@avocode.com?

**Comment by ak1987** [comment]
Sorry, i don't exactly remebmer.
Next time i'll post PSD to cloud storage immediately

I can give you another PSD that is unable to properly open in avocode

**Comment by vojtatranta** [comment]
And now it works? So it happened just once, right?

**Comment by ak1987** [comment]
no, it's not working, it uploads and fails

**Comment by vojtatranta** [comment]
It uploads? Can you please describe the whole process when it fails?

**Comment by ak1987** [comment]
I do receive this email:


 
Hello,
We noticed that our servers weren’t able to process your design ”karaooke_27_12.psd”. It’s probably because the design file is too large or too complex. Unfortunately, that’s an issue we’re currently working on.
In the meantime, you can use the Photoshop Plugin to sync this design. Get the plugin here:  https://manager.avocode.com/downloads/
If you don't have Photoshop, you can ask someone in your team or we might be able to upload that PSD for you manually. Let us know if you need that.
Thank you,
– The Avocode Team

**Comment by vojtatranta** [comment]
So do you want us to upload this PSD?

**Comment by ak1987** [comment]
yes, try to upload it, i failed.

**Comment by vojtatranta** [comment]
OK. Can you send that PSD at team@avocode.com? We will upload it.

**Comment by jakubzitny** [comment]
This is actually known issue with our slice tool and instant export, same as #564. 
I am going to close this thread, let's continue the discussion over there.
