### ISSUE TITLE
Sketch export error

### ISSUE THREAD

**Issue by dinodeveloper1** [avocode/avocode#745]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.5.2
```
Error: Error: Command failed: 2016-02-15 00:39:49.051 sketchtool[3900:1079928] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer)
2016-02-15 00:39:49.052 sketchtool[3900:1079928] Error: caught exception whilst decoding (version 76):*** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer)
Failed to open document file:///Users/westchapel/Desktop/Poet's%20Walk/Sketch/Poet's%20Walk.sketch
((null) MSDocumentDomain:11)


    at /Users/westchapel/…/avocode-exporter/lib/image-exporter.js:1:873
    at ChildProcess.exithandler (child_process.js:651:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Socket.<anonymous> (child_process.js:966:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

**Comment by jankuca** [comment]
Hello, thanks for the report.

The error talks about a file at `file:///Users/westchapel/Desktop/Poet's%20Walk/Sketch/Poet's%20Walk.sketch`. Does it exist? Removing links to this location might solve your problem.

We will look into this and try to handle it gracefully in a future versino of course, thanks again.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
