### ISSUE TITLE
Error on add new tab when psd is loading

### ISSUE THREAD

**Issue by funrichy** [avocode/avocode#746]
IMPORTANT: I load psd files to avocode and when loading files - click on + to add new tab on top.

-----
App v.2.5.4
Source UID: 51235
```
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
  at invariant (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/node_modules/fbjs/lib/invariant.js:35:15)
  at o.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:167:160)
  at o.handleServerAction (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/dispatcher.js:1:980)
  at e._emitItemUploadProgress (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uploader.js:1:11593)
  at Immediate._onImmediate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uploader.js:1:9299)
  at processImmediate [as _immediateCallback] (timers.js:361:17)
  at EventEmitter.ipc.sendSync (/Applications/Avocode.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as getPosition] (/Applications/Avocode.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at Atom.module.exports.Atom.getWindowDimensions (/Applications/Avocode.app/Contents/Resources/app.asar/src/atom.js:540:29)
  at Atom.module.exports.Atom.storeDefaultWindowDimensions (/Applications/Avocode.app/Contents/Resources/app.asar/src/atom.js:573:25)
  at /Applications/Avocode.app/Contents/Resources/app.asar/src/window-event-handler.js:107:21
  at handler (/Applications/Avocode.app/Contents/Resources/app.asar/src/space-pen-extensions.js:115:32)
  at jQuery.event.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at elemData.handle (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/space-pen
```

**Comment by jankuca** [comment]
Hi, thank you for the report. Does this happen regularly or was this a one time occurrence?

**Comment by funrichy** [comment]
one time

**Comment by vojtatranta** [comment]
Thank you for details.
We know about this issue and we are working on a fix.
Thanks

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
