### ISSUE TITLE
Error uploading on a slow internet connection

### ISSUE THREAD

**Issue by evilsprut** [avocode/avocode#753]
Error uploading on a slow internet connection

![avocode-error](http://i.imgur.com/rKXaxgF.jpg?1)

-----
App v.2.5.3
Source UID: 136855
```
TypeError: Cannot read property 'progress' of undefined
  at /opt/homebrew-cask/Caskroom/avocode/2.5.3/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:13256
  at /opt/homebrew-cask/Caskroom/avocode/2.5.3/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:766
  at /opt/homebrew-cask/Caskroom/avocode/2.5.3/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:7834
  at /opt/homebrew-cask/Caskroom/avocode/2.5.3/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:8424
  at /opt/homebrew-cask/Caskroom/avocode/2.5.3/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/@avocode/decompress/node_modules/vinyl-fs/node_modules/graceful-fs/graceful-fs.js:43:10
  at FSReqWrap.oncomplete (fs.js:77:15)

```

**Comment by petrbrzek** [comment]
Please update to the latest Avocode version (2.5.4). If you still have this problem in the new app, feel free to report it as a new issue.
