### ISSUE TITLE
Logged in sucessfully using browser and then app crashed

### ISSUE THREAD

**Issue by afeinber** [avocode/avocode#755]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.5.2
Source UID: undefined
```
TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/Users/alexf/Downloads/Avocode 2.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:3394)
    at self.callback (/Users/alexf/Downloads/Avocode 2.app/Contents/Resources/app.asar/node_modules/request/request.js:368:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:166:7)
    at Request.onRequestError (/Users/alexf/Downloads/Avocode 2.app/Contents/Resources/app.asar/node_modules/request/request.js:1025:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:166:7)
    at TLSSocket.socketErrorListener (_http_client.js:254:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:166:7)
    at net.js:438:14
    at process._tickCallback (node.js:347:13)
```

**Comment by vojtatranta** [comment]
That's odd.
There is another user that has same version of app and same issue. Can you try to update to Avocod 2.5?

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
