### ISSUE TITLE
While rendering image data

### ISSUE THREAD

**Issue by ksuwala** [avocode/avocode#757]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.6.0
Source UID: 150151
```
TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'
  at TypeError (native)
  at t.module.exports.t._loadMaskedBy (/Users/kamilsuwala/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:3602)
  at /Users/kamilsuwala/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:1011
  at /Users/kamilsuwala/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:3245
  at /Users/kamilsuwala/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:200:33
  at /Users/kamilsuwala/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:3183
  at replenish (/Users/kamilsuwala/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:191:21)
  at /Users/kamilsuwala/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:203:33
  at /Users/kamilsuwala/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:3183
  at replenish (/Users/kamilsuwala/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:191:21)
  at /Users/kamilsuwala/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:203:33
  at /Users/kamilsuwala/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:3183
  at replenish (/Users/kamilsuwala/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:191:21)
  at /Users/kamilsuwala/Downloads/Avocode.app/Contents/Resources/app.a
```

**Comment by vojtatranta** [comment]
Seems you don't have design downloaded properly.
You can upload it again and it should fix this.

**Comment by ksuwala** [comment]
Ok, now it works. Thx

**Comment by jakubzitny** [comment]
Thank you. Let us know if you have any more problems or questions.
