### ISSUE TITLE
sketch sync to avocode

### ISSUE THREAD

**Issue by luya8** [avocode/avocode#775]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.6
```
Error: Error: Command failed: 2016-03-02 14:58:59.952 sketchtool[2268:1187028] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer)
2016-03-02 14:58:59.952 sketchtool[2268:1187028] Error: caught exception whilst decoding (version 76):*** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer)
Failed to open document file:///Users/jiake002/Desktop/inFan.sketch
((null) MSDocumentDomain:11)


    at /Users/jiake002/…/avocode-exporter/lib/image-exporter.js:1:873
    at ChildProcess.exithandler (child_process.js:651:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Socket.<anonymous> (child_process.js:966:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

**Comment by jakubzitny** [comment]
Hi, this is same thing as #774. You're using and old version of our Sketch plugin. We have a new version now, please install it from [manager.avocode.com/downloads](http://manager.avocode.com/downloads/). The new Sketch plugin 3 is compatible with Sketch 3.6 you are using.

Let us know if you have any problems. Thank you :)
