### ISSUE TITLE
Ctrl+a when renaming asset for export

### ISSUE THREAD

**Issue by Holicz** [avocode/avocode#781]
In export panel on the right, when I'm renaming asset for export and click ctrl+a to select whole name I got unexcpepted error.

-----
App v.2.6.0
Source UID: 153934
```
TypeError: menu.sendActionToFirstResponder is not a function
  at HTMLDocument.<anonymous> (C:\Users\Lukas\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\window-event-handler.js:170:20)
  at HTMLDocument.handler (C:\Users\Lukas\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\space-pen-extensions.js:115:32)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\Lukas\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\Lukas\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Lukas\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\command-registry.js:251:29)
  at C:\Users\Lukas\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Lukas\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Lukas\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Lukas\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\window-event-handler.js:185:27)

```

**Comment by jakubzitny** [comment]
Hi, we know about this bug and we already have the fix prepared for next release. It's already mentioned in #566 so I will close this issue and we can continue the discussion over there. Please use mouse to select the text for now and we will let you know when the new release is ready.

Thank you ;)
