### ISSUE TITLE
Cannot read property 'right' of undefined (MeasureTool)

### ISSUE THREAD

**Issue by lnked** [avocode/avocode#787]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.6.0
Source UID: 152439
```
TypeError: Cannot read property 'right' of undefined
  at e.calculateDistance (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/measure-stageview/lib/measure.js:1:3066)
  at e.measure (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/measure-stageview/lib/measure.js:1:2537)
  at t.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/measure-stageview/lib/main.js:1:521)
  at t.EventEmitter.emit (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
  at e.mousemove (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/measure-tool/lib/measure-tool.js:1:911)
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/measure-tool/lib/measure-tool.js:1:146
  at t.module.exports.Emitter.emit (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:118:15)
  at HTMLCanvasElement.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/stage.js:1:4480)

```

**Comment by jakubzitny** [comment]
Hi, thank you for reporting this issue.

Can you please describe how did this happen and whether it happend just this one time or multiple times? It seems to be happening with measure tool occasionaly. Similar thing happened also in #469.

I submitted this into our internal bug tracking system. We will look into it and update you soon.

**Comment by Cactucs** [comment]
In my case it happend multiple times.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
