### ISSUE TITLE
Double clicked the background image in a PSD.

### ISSUE THREAD

**Issue by shock** [avocode/avocode#788]
I double clicked the background image layer in a PSD and got this exception.  It wasn't anything extraordinary.  Thanks!

-----
App v.2.6.0
Source UID: 153619
```
TypeError: Cannot read property 'then' of undefined
  at e.requestRevisionDownload (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:25741)
  at e.loadRevision (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:26028)
  at t._loadRevisionToView (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:20334)
  at t._addRevisionView (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:17701)
  at t._openAvocodeResource (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:16930)
  at t.opener (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:15327)
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:1178
  at wrappedOpener (/Applications/Avocode.app/Contents/Resources/app.asar/src/workspace.js:525:18)
  at Workspace.module.exports.Workspace.openURIInPane (/Applications/Avocode.app/Contents/Resources/app.asar/src/workspace.js:441:22)
  at Workspace.module.exports.Workspace.open (/Applications/Avocode.app/Contents/Resources/app.asar/src/workspace.js:371:19)
  at t.openSubdocument (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:28715)
  at e._onDblClick (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/select-tool/lib/select-tool.js:1:2671)
  at t.module.exports.Emitter.emit (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:118:15)
  at HTMLCanvasElement.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avoco
```

**Comment by jakubzitny** [comment]
Hi, thanks for the report. This is already mentioned in #627, but we forgot to look into it.

Can you reproduce it every time when double-clicking on the same object? Or did it happen just one time? If you can reproduce it, please send us the design to team@avocode.com. If not, we'll have to find out ourselves when exactly is it happening.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
