### ISSUE TITLE
Measue tool: TypeError: Cannot read property 'right' of undefined

### ISSUE THREAD

**Issue by Cactucs** [avocode/avocode#789]
Opened design with measure tool. (Error alert window opening multiple times)

-----
App v.2.6.0
Source UID: 62957
```
TypeError: Cannot read property 'right' of undefined
  at e.calculateDistance (/home/vojta/bin/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/measure-stageview/lib/measure.js:1:3066)
  at e.measure (/home/vojta/bin/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/measure-stageview/lib/measure.js:1:2537)
  at t.<anonymous> (/home/vojta/bin/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/measure-stageview/lib/main.js:1:521)
  at t.EventEmitter.emit (/home/vojta/bin/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
  at e.mousemove (/home/vojta/bin/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/measure-tool/lib/measure-tool.js:1:911)
  at /home/vojta/bin/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/measure-tool/lib/measure-tool.js:1:146
  at t.module.exports.Emitter.emit (/home/vojta/bin/Avocode-linux-x64/resources/app.asar/node_modules/emissary/lib/emitter.js:118:15)
  at HTMLCanvasElement.<anonymous> (/home/vojta/bin/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/stage.js:1:4480)

```

**Comment by jakubzitny** [comment]
Hi, thanks for letting us know. We're already investigating this. Let's continue the discussion at #787.
