### ISSUE TITLE
Error while exporting base64

### ISSUE THREAD

**Issue by JohnnyBushy** [avocode/avocode#794]
I used slice tool, selected an area 2x252 and exported selection to base64.

-----
App v.2.6.0
Source UID: 153033
```
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
  at invariant (/home/jk/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/flux/node_modules/fbjs/lib/invariant.js:35:15)
  at o.dispatch (/home/jk/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/flux/lib/Dispatcher.js:167:160)
  at o.handleViewAction (/home/jk/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/dispatcher.js:1:707)
  at Object.module.exports.setActiveView (/home/jk/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/slice-tool/lib/actions/slice.js:1:485)
  at e.module.exports.e._mousemoveDrag (/home/jk/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/slice-tool/lib/slice-tool.js:1:6102)
  at /home/jk/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/slice-tool/lib/slice-tool.js:1:330
  at EventEmitter.ipc.sendSync (/home/jk/Downloads/Avocode-linux-x64/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at Object.RemoteMemberFunction [as writeText] (/home/jk/Downloads/Avocode-linux-x64/resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at Clipboard.module.exports.Clipboard.write (/home/jk/Downloads/Avocode-linux-x64/resources/app.asar/src/clipboard.js:22:24)
  at t._base64 (/home/jk/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:10489)
  at t._register (/home/jk/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:12243)
  at Object.ID_16 (/home/jk/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:459)
  at o._invokeCallback (/home/jk/Downloads/Avocode
```

**Comment by jankuca** [comment]
Hi! Thanks for the report.

Were you able to get the info on a second try?

**Comment by JohnnyBushy** [comment]
Hello!
Nope, I still get the same crash..

--

Гордеев Евгений,
Веб-разработчик,
компания «Фабрика Лояльности»

+7 921 406-84-21

**Comment by jakubzitny** [comment]
Can you please send us the design you're having the problem with to team@avocode.com? We'll try to look into it. Thanks.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
