### ISSUE TITLE
Can't export as PNG

### ISSUE THREAD

**Issue by irodrigo17** [avocode/avocode#796]
IMPORTANT: Please try to describe how did it happen.

Just tried to import a layer as PNG, the only interesting detail is that both Avocode and my Mac have been idle for a couple of hours, mentioning just in case it could be a caching issue.

-----
App v.2.6.0
Source UID: 154750
```
TypeError: Cannot read property 'bounds' of undefined
  at Object.getBoundsForLayers (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/document.js:1:724)
  at exportRule (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/export.js:1:5697)
  at t._instantExport (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:11420)
  at t._register (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:12487)
  at Object.ID_16 (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:459)
  at o._invokeCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:198:24)
  at o.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:174:14)
  at o.handleViewAction (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/dispatcher.js:1:707)
  at o.module.exports.instantExport [as onExport] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/actions/export.js:1:1812)
  at o.module.exports.o.onConfirm (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/instant-export-dialog.js:1:4563)
  at o.module.exports.o.onSave (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/instant-export-dialog.js:1:4067)
  at o.onSave (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/instant-export-dialog.js:1:239)
  at HTMLButtonElement.<anonymous> (/Applications/Avocode.app/Contents/Resourc
```

**Comment by irodrigo17** [comment]
Just restarted Avocode and I can export the same layer as PNG just fine.

**Comment by jakubzitny** [comment]
#564
