### ISSUE TITLE
error sync update

### ISSUE THREAD

**Issue by aguer83** [avocode/avocode#799]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.4 running in Sketch 3.6
```
Error: Error: Command failed: 2016-03-16 10:57:14.904 sketchtool[849:61589] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer)
2016-03-16 10:57:14.905 sketchtool[849:61589] Error: caught exception whilst decoding (version 78):*** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer)
Failed to open document file:///Users/andresaguer/Desktop/ux-mockups/Landings/Pascua/landing-pascua.sketch
((null) MSDocumentDomain:11)


    at /Users/andresaguer/…/avocode-exporter/lib/image-exporter.js:1:873
    at ChildProcess.exithandler (child_process.js:651:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Socket.<anonymous> (child_process.js:966:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

**Comment by jakubzitny** [comment]
Hi, you're using an old version of our Sketch plugin. We have a new version now, please install it from [manager.avocode.com/downloads](http://manager.avocode.com/downloads/). The new Sketch plugin 3 is compatible with Sketch 3.6 you are using.

Let us know if you have any other problems. Thank you :)
