### ISSUE TITLE
Pressed some btn and crashed

### ISSUE THREAD

**Issue by kbytin** [avocode/avocode#802]
IMPORTANT: Please try to describe how did it happen.

Just  occasional btn press
-----
App v.2.6.0
Source UID: 157877
```
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
  at invariant (/home/kbytin/Загрузки/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/invariant.js:35:15)
  at Object.getID (/home/kbytin/Загрузки/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactMount.js:104:13)
  at Object.ReactMount.isRenderedByReact (/home/kbytin/Загрузки/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactMount.js:691:25)
  at Object.ReactMount.getFirstReactDOM (/home/kbytin/Загрузки/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactMount.js:706:22)
  at handleTopLevelImpl (/home/kbytin/Загрузки/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactEventListener.js:63:35)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/home/kbytin/Загрузки/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/Transaction.js:134:20)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/home/kbytin/Загрузки/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
  at Object.batchedUpdates (/home/kbytin/Загрузки/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactUpdates.js:110:20)
  at ReactEventListener.dispatchEvent (/home/kbytin/Загрузки/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/ReactEventListener.js:174:20)

```

**Comment by connor-bean** [comment]
Hi, thanks for the report. Are you able to reproduce this error please? When did you press the button? And what button did you press?

Looks similar to #800 #596 and #468.

**Comment by kbytin** [comment]
Sorry, I can't reproduce, the only thing I can say that it happened on Ubuntu, and at the same time, I was running WebStorm and Gulp.

**Comment by jakubzitny** [comment]
Thanks anyway. We will try to fix this in next release and we will update you.

I will close this issue as it is similar to #800.
We can continue the discussion overe there if anything comes up.
