### ISSUE TITLE
not open layer

### ISSUE THREAD

**Issue by mateusmoura** [avocode/avocode#804]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.6.0
Source UID: 71748
```
TypeError: Cannot read property 'then' of undefined
  at e.requestRevisionDownload (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:25741)
  at e.loadRevision (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:26028)
  at t._loadRevisionToView (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:20334)
  at t._addRevisionView (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:17701)
  at t._openAvocodeResource (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:16930)
  at t.opener (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:15327)
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:1178
  at wrappedOpener (/Applications/Avocode.app/Contents/Resources/app.asar/src/workspace.js:525:18)
  at Workspace.module.exports.Workspace.openURIInPane (/Applications/Avocode.app/Contents/Resources/app.asar/src/workspace.js:441:22)
  at Workspace.module.exports.Workspace.open (/Applications/Avocode.app/Contents/Resources/app.asar/src/workspace.js:371:19)
  at t.openSubdocument (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:28715)
  at HTMLLIElement.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/layers-view/lib/layers-view.js:1:3461)
  at HTMLLIElement.handler (/Applications/Avocode.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDivElement.jQuery.event.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/spac
```

**Comment by jakubzitny** [comment]
Hi, thanks for the report, we know about this already. We will release a fix soon.

I'll close this issue, we can continue discussion in #788.
