### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by gvozdilla** [avocode/avocode#805]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.6.0
Source UID: 146153
```
TypeError: Cannot read property 'right' of undefined
  at e.calculateDistance (C:\Users\jenov_000\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\@avocode\measure-stageview\lib\measure.js:1:3066)
  at e.measure (C:\Users\jenov_000\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\@avocode\measure-stageview\lib\measure.js:1:2537)
  at t.<anonymous> (C:\Users\jenov_000\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\@avocode\measure-stageview\lib\main.js:1:521)
  at t.EventEmitter.emit (C:\Users\jenov_000\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\@avocode\core\node_modules\eventemitter2\lib\eventemitter2.js:339:22)
  at e.mousemove (C:\Users\jenov_000\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\@avocode\measure-tool\lib\measure-tool.js:1:911)
  at C:\Users\jenov_000\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\@avocode\measure-tool\lib\measure-tool.js:1:146
  at t.module.exports.Emitter.emit (C:\Users\jenov_000\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\emissary\lib\emitter.js:118:15)
  at HTMLCanvasElement.<anonymous> (C:\Users\jenov_000\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\@avocode\core\lib\stage.js:1:4480)

```

**Comment by jakubzitny** [comment]
Hi, thanks for the report. We already know about this and we will be fixing it soon.

I'll close this issue, please see #787 for updates.
