### ISSUE TITLE
Not syncing

### ISSUE THREAD

**Issue by BrendanMiller** [avocode/avocode#812]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.6.0
Source UID: 158336
```
Error: No revision passed to Avocode#openRevision()
    at t.openRevision (/Users/brendan-cloudcity/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:28119)
    at o (/Users/brendan-cloudcity/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:31089)
    at Notification.o.onclick (/Users/brendan-cloudcity/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:31626)
```

**Comment by connor-bean** [comment]
Thanks for the report. Can you provide us with context as to what you were doing when this happened?

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
