### ISSUE TITLE
Scrolling the document spawned multiple alerts

### ISSUE THREAD

**Issue by greystate** [avocode/avocode#813]
The app had been open in the background for a couple of hours, and now I just scrolled the document and I got like 5 or 6 dialogs like this:

<img width="532" alt="avocode-beta-scrolling" src="https://cloud.githubusercontent.com/assets/5463/14301521/d2345b18-fb98-11e5-9386-adf73f01119e.png">

and the document scrolls a little bit everytime I dismiss the dialog.

Restarting the app solved the problem.

-----
App v.2.8.0-beta.1
Source UID: 460
```
TypeError: Cannot read property 'x' of null
    at e.calculateBounds (file:///Users/chriz/Applications/Avocode.app/Contents/Resources/app/dist/avocode.min.js:23:21512)
    at e.mousemoveDrag (file:///Users/chriz/Applications/Avocode.app/Contents/Resources/app/dist/avocode.min.js:23:17979)
    at file:///Users/chriz/Applications/Avocode.app/Contents/Resources/app/dist/avocode.min.js:23:11732
    at t.module.exports.Emitter.emit (/Users/chriz/Applications/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:118:15)
    at t.mousewheel (file:///Users/chriz/Applications/Avocode.app/Contents/Resources/app/dist/avocode.min.js:20:11205)
    at HTMLCanvasElement.<anonymous> (file:///Users/chriz/Applications/Avocode.app/Contents/Resources/app/dist/avocode.min.js:19:30144)
    at HTMLCanvasElement.c (file:///Users/chriz/Applications/Avocode.app/Contents/Resources/app/static/raven.min.js:2:3899)
```

**Comment by jakubzitny** [comment]
Hi, thanks for the report. We have this in our internal tracking system already, we'll fix it in next beta release.

This was happening in old releases too (#702, #484, #451, #444, #402, #390, etc.)

**Comment by vojtatranta** [comment]
gitlab MR: !336

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
