### ISSUE TITLE
Scrolling page after exporting shape as png

### ISSUE THREAD

**Issue by vsiestov** [avocode/avocode#814]
IMPORTANT: Please try to describe how did it happen.
It happens after exporting shape as png and if i try to scroll page with mouse wheel I've got this error
-----
App v.2.8.0-beta.1
Source UID: 7389
```
TypeError: Cannot read property 'x' of null
    at e.calculateBounds (file:///Volumes/Data/Avocode.app/Contents/Resources/app/dist/avocode.min.js:23:21512)
    at e.mousemoveDrag (file:///Volumes/Data/Avocode.app/Contents/Resources/app/dist/avocode.min.js:23:17979)
    at file:///Volumes/Data/Avocode.app/Contents/Resources/app/dist/avocode.min.js:23:11732
    at t.module.exports.Emitter.emit (/Volumes/Data/Avocode.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:118:15)
    at t.mousewheel (file:///Volumes/Data/Avocode.app/Contents/Resources/app/dist/avocode.min.js:20:11205)
    at HTMLCanvasElement.<anonymous> (file:///Volumes/Data/Avocode.app/Contents/Resources/app/dist/avocode.min.js:19:30144)
    at HTMLCanvasElement.c (file:///Volumes/Data/Avocode.app/Contents/Resources/app/static/raven.min.js:2:3899)
```

**Comment by jakubzitny** [comment]
Hi, thanks for the report. We'll fix this in next beta release.

This looks similar to #813, so I'll close this issue.
