### ISSUE TITLE
Double-clicking image causes exception

### ISSUE THREAD

**Issue by shock** [avocode/avocode#815]
Double clicking an image in PSD to open in full-size view caused this exception.

-----
App v.2.6.0
Source UID: 54141
```
TypeError: Cannot read property 'then' of undefined
  at e.requestRevisionDownload (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:25741)
  at e.loadRevision (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:26028)
  at t._loadRevisionToView (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:20334)
  at t._addRevisionView (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:17701)
  at t._openAvocodeResource (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:16930)
  at t.opener (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:15327)
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:1178
  at wrappedOpener (/Applications/Avocode.app/Contents/Resources/app.asar/src/workspace.js:525:18)
  at Workspace.module.exports.Workspace.openURIInPane (/Applications/Avocode.app/Contents/Resources/app.asar/src/workspace.js:441:22)
  at Workspace.module.exports.Workspace.open (/Applications/Avocode.app/Contents/Resources/app.asar/src/workspace.js:371:19)
  at t.openSubdocument (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:28715)
  at e._onDblClick (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/select-tool/lib/select-tool.js:1:2671)
  at t.module.exports.Emitter.emit (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:118:15)
  at HTMLCanvasElement.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avoco
```

**Comment by connor-bean** [comment]
Hey, thanks for the report. This looks exactly like #788 so I'm going to close this and we will continue to track it in that other ticket.
