### ISSUE TITLE
Failed to log in via browser

### ISSUE THREAD

**Issue by mrk13spx** [avocode/avocode#819]
Tried the 'log in via browser' function. Browser opened, I logged in via browser, authorized app and swath  error when returning to the Avocode app (also happened in v.2.6).

-----
App v.2.8.0-beta.1
Source UID: null
```
TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (file:///Users/Mark/Downloads/Avocode.app/Contents/Resources/app/dist/avocode.min.js:18:20974)
    at self.callback (/Users/Mark/Downloads/Avocode.app/Contents/Resources/app/node_modules/request/request.js:199:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/Users/Mark/Downloads/Avocode.app/Contents/Resources/app/node_modules/request/request.js:821:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:265:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```

**Comment by vojtatranta** [comment]
Thank you for this report.
There's a bug when handling browser login failure.
It will be fixed. GL MR: 343

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
