### ISSUE TITLE
After selecting layers

### ISSUE THREAD

**Issue by janaobzerova** [avocode/avocode#823]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.0-beta.1
Source UID: 16989
```
TypeError: Cannot read property 'length' of undefined
    at Object.prepareTextStyles (/Users/jan.michalik/Downloads/Avocode 2.app/Contents/Resources/app/node_modules/csshat-language-css/node_modules/octopus-helpers/lib/font.js:115:19)
    at CSS.render (/Users/jan.michalik/Downloads/Avocode 2.app/Contents/Resources/app/node_modules/csshat-language-css/main.js:153:20)
    at e.build (file:///Users/jan.michalik/Downloads/Avocode%202.app/Contents/Resources/app/dist/avocode.min.js:2:23231)
    at e._classRenderer (file:///Users/jan.michalik/Downloads/Avocode%202.app/Contents/Resources/app/dist/avocode.min.js:2:22061)
    at e.<anonymous> (file:///Users/jan.michalik/Downloads/Avocode%202.app/Contents/Resources/app/dist/avocode.min.js:2:20538)
    at e.render (file:///Users/jan.michalik/Downloads/Avocode%202.app/Contents/Resources/app/dist/avocode.min.js:2:22256)
    at l.map.t.map.t (file:///Users/jan.michalik/Downloads/Avocode%202.app/Contents/Resources/app/dist/avocode.min.js:2:20235)
    at /Users/jan.michalik/Downloads/Avocode 2.app/Contents/Resources/app/node_modules/async/lib/async.js:246:17
    at /Users/jan.michalik/Downloads/Avocode 2.app/Contents/Resources/app/node_modules/async/lib/async.js:122:13
    at _each (/Users/jan.michalik/Downloads/Avocode 2.app/Contents/Resources/app/node_modules/async/lib/async.js:46:13)
    at async.each (/Users/jan.michalik/Downloads/Avocode 2.app/Contents/Resources/app/node_modules/async/lib/async.js:121:9)
    at _asyncMap (/Users/jan.michalik/Downloads/Avocode 2.app/Contents/Resources/app/node_modules/async/lib/async.js:245:13)
    at Object.map (/Users/jan.michalik/Downloads/Avocode 2.app/Contents/Resources/app/node_modules/async/lib/async.js:216:23)
    at file:///Users/jan.michalik/Downloads/Avocode%202.app/Contents/Resources/a
```

**Comment by jakubzitny** [comment]
Hi, thanks for the report. Can you please describe how did this happen in more detail? And possibly share with us the design where this happened on team@avocode.com?

**Comment by janaobzerova** [comment]
Yes, I send video and psd to your email.

**Comment by connor-bean** [comment]
Hello!

Can you try sending the email again to team@avocode.com? We have not received it yet.

Thanks!
Connor, Avocode Team

**Comment by vojtatranta** [comment]
There was a bug in csshat language - selected layer has no text styles and no size. Kinda edge case.
Will be fixed in release. Thanks

**Comment by bolekkerous** [comment]
I've tested it in the current beta version (will be released soon) and it looks like it's fixed there.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
