### ISSUE TITLE
IMPORTANT: Please try to describe how did it happen.

### ISSUE THREAD

**Issue by retyui** [avocode/avocode#828]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.6.0
Source UID: 163587
```
TypeError: menu.sendActionToFirstResponder is not a function
  at HTMLDocument.<anonymous> (C:\Users\asd\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\window-event-handler.js:170:20)
  at HTMLDocument.handler (C:\Users\asd\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\space-pen-extensions.js:115:32)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\asd\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\asd\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\asd\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\command-registry.js:251:29)
  at C:\Users\asd\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\asd\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\asd\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\asd\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\window-event-handler.js:185:27)

```

**Comment by bolekkerous** [comment]
Hello!
Thanks for the report. Can you please describe how did this happen in more detail? And possibly share with us the design where this happened on team@avocode.com?

Thanks!

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey @retyui 

Thanks for the report. Can you please describe how did this happen in more detail? And possibly share with us the design where this happened on team@avocode.com?

Thanks,
Connor, Avocode Support
