### ISSUE TITLE
Freeze on copy text from context-menu

### ISSUE THREAD

**Issue by trurl-master** [avocode/avocode#837]
Was copying text from one of the layers from context menu. Freezes completely. Every time.

-----
App v.2.8.0-beta.2
Source UID: 15216
```
TypeError: Cannot read property 'name' of undefined
    at valueToMeta (/home/evan/bin/Avocode-linux-x64/resources/atom.asar/renderer/api/remote.js:48:50)
    at valueToMeta (/home/evan/bin/Avocode-linux-x64/resources/atom.asar/renderer/api/remote.js:68:18)
    at valueToMeta (/home/evan/bin/Avocode-linux-x64/resources/atom.asar/renderer/api/remote.js:68:18)
    at valueToMeta (/home/evan/bin/Avocode-linux-x64/resources/atom.asar/renderer/api/remote.js:68:18)
    at valueToMeta (/home/evan/bin/Avocode-linux-x64/resources/atom.asar/renderer/api/remote.js:68:18)
    at valueToMeta (/home/evan/bin/Avocode-linux-x64/resources/atom.asar/renderer/api/remote.js:68:18)
    at valueToMeta (/home/evan/bin/Avocode-linux-x64/resources/atom.asar/renderer/api/remote.js:68:18)
    at valueToMeta (/home/evan/bin/Avocode-linux-x64/resources/atom.asar/renderer/api/remote.js:68:18)
    at valueToMeta (/home/evan/bin/Avocode-linux-x64/resources/atom.asar/renderer/api/remote.js:68:18)
    at valueToMeta (/home/evan/bin/Avocode-linux-x64/resources/atom.asar/renderer/api/remote.js:68:18)
    at valueToMeta (/home/evan/bin/Avocode-linux-x64/resources/atom.asar/renderer/api/remote.js:68:18)
    at valueToMeta (/home/evan/bin/Avocode-linux-x64/resources/atom.asar/renderer/api/remote.js:68:18)
    at valueToMeta (/home/evan/bin/Avocode-linux-x64/resources/atom.asar/renderer/api/remote.js:68:18)
    at valueToMeta (/home/evan/bin/Avocode-linux-x64/resources/atom.asar/renderer/api/remote.js:68:18)
    at valueToMeta (/home/evan/bin/Avocode-linux-x64/resources/atom.asar/renderer/api/remote.js:68:18)
    at valueToMeta (/home/evan/bin/Avocode-linux-x64/resources/atom.asar/renderer/api/remote.js:68:18)
    at valueToMeta (/home/evan/bin/Avocode-linux-x64/resources/atom.asar/renderer/api/remote.js:68:1
```

**Comment by vojtatranta** [comment]
Hi, thank you for this report.
There is a bug in our CopyManager. Will be fixed in next beta (this week), thank you.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
