### ISSUE TITLE
Unable to login to the system

### ISSUE THREAD

**Issue by maritelle** [avocode/avocode#839]
I have tried to login using browser and after I have been waiting for about 2 minutes I have clicked on "Cancel Login" button. Then I've got the error.

-----
App v.2.6.0
Source UID: undefined
```
TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/home/telle/Avocode/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:3394)
    at self.callback (/home/telle/Avocode/resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:199:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:166:7)
    at Request.onRequestError (/home/telle/Avocode/resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:821:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:166:7)
    at TLSSocket.socketErrorListener (_http_client.js:254:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket.onHangUp (_tls_wrap.js:953:14)
    at TLSSocket.g (events.js:257:16)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:163:7)
    at _stream_readable.js:891:16
    at process._tickCallback (node.js:347:13)
```

**Comment by connor-bean** [comment]
Hello. Thanks for the report. This looks like #819 so I'm going to close this out and we will track it in the other case.

Thanks,
Connor, Avocode Team
