### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Alexander-smirnov** [avocode/avocode#841]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.6.0
Source UID: 73960
```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source height is 0.
  at Error (native)
  at Object.module.exports.addBackground (/home/sandrik/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/bitmap.js:1:1923)
  at saveComposition (/home/sandrik/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/export.js:1:4671)
  at _exportRule (/home/sandrik/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/export.js:1:4485)
  at exportRule (/home/sandrik/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/export.js:1:5749)
  at t._instantExport (/home/sandrik/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:11420)
  at /home/sandrik/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:11353
  at /home/sandrik/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:2159
  at CallbacksRegistry.module.exports.CallbacksRegistry.apply (/home/sandrik/Downloads/Avocode-linux-x64/resources/atom.asar/common/api/lib/callbacks-registry.js:35:42)
  at EventEmitter.<anonymous> (/home/sandrik/Downloads/Avocode-linux-x64/resources/atom.asar/renderer/api/lib/remote.js:146:30)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)

```

**Comment by connor-bean** [comment]
Hello, 

Could you try to describe what was happening when you received this error?

Thanks,
Connor, Avocode Support

**Comment by Alexander-smirnov** [comment]
I am upload new design to project. File <100 Mb PSD format

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
