### ISSUE TITLE
After trying to copy text like a text :)

### ISSUE THREAD

**Issue by janaobzerova** [avocode/avocode#847]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.0-beta.2
Source UID: 16989
```
TypeError: Error processing argument at index 0, conversion failure from 
    at TypeError (native)
    at e.copyText (file:///Users/jan.michalik/Downloads/Avocode%202.app/Contents/Resources/app/dist/avocode.min.js:9:7243)
    at t._handleCopyText (file:///Users/jan.michalik/Downloads/Avocode%202.app/Contents/Resources/app/dist/avocode.min.js:3:25035)
    at file:///Users/jan.michalik/Downloads/Avocode%202.app/Contents/Resources/app/dist/avocode.min.js:3:23297
    at CallbacksRegistry.apply (/Users/jan.michalik/Downloads/Avocode 2.app/Contents/Resources/atom.asar/common/api/callbacks-registry.js:58:39)
    at EventEmitter.<anonymous> (/Users/jan.michalik/Downloads/Avocode 2.app/Contents/Resources/atom.asar/renderer/api/remote.js:238:28)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at EventEmitter.ipcRenderer.emit (/Users/jan.michalik/Downloads/Avocode 2.app/Contents/Resources/atom.asar/renderer/api/ipc.js:17:38)
```

**Comment by vojtatranta** [comment]
We know about this bug. It should be OK in Beta.3. have you tried to upgrade your Avocode Beta?

**Comment by janaobzerova** [comment]
I downloaded it yesterday, It is working great in new beta 3.

**Comment by vojtatranta** [comment]
Great to hear it! Thanks for testing.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
