### ISSUE TITLE
Uploading 9 designs. But all uploaded succesfully, crash report came afterwards.

### ISSUE THREAD

**Issue by Kout** [avocode/avocode#850]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.6.0
Source UID: 154142
```
TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/home/kout/Avocode/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:3394)
    at self.callback (/home/kout/Avocode/resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:199:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:166:7)
    at Request.onRequestError (/home/kout/Avocode/resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:821:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:166:7)
    at TLSSocket.socketErrorListener (_http_client.js:254:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket.onHangUp (_tls_wrap.js:953:14)
    at TLSSocket.g (events.js:257:16)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:163:7)
    at _stream_readable.js:891:16
    at process._tickCallback (node.js:347:13)
```

**Comment by connor-bean** [comment]
Hello. Thanks for the report. This looks like #819 so I'm going to close this out and we will track it in the other case.

Thanks,
Connor, Avocode Team
