### ISSUE TITLE
Beta error report

### ISSUE THREAD

**Issue by joelgoodman** [avocode/avocode#855]
IMPORTANT: Please try to describe how did it happen.

Was syncing a Photoshop uploaded design down to the app.

-----
App v.2.8.0-beta.3
Source UID: 1370
```
TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'
    at TypeError (native)
    at file:///Applications/Avocode.app/Contents/Resources/app/dist/avocode.min.js:9:19039
    at Array.forEach (native)
    at e.exports.e._loadMaskedBy (file:///Applications/Avocode.app/Contents/Resources/app/dist/avocode.min.js:9:18551)
    at file:///Applications/Avocode.app/Contents/Resources/app/dist/avocode.min.js:9:16395
    at file:///Applications/Avocode.app/Contents/Resources/app/dist/avocode.min.js:9:18492
    at /Applications/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:200:33
    at r (file:///Applications/Avocode.app/Contents/Resources/app/dist/avocode.min.js:9:18405)
    at replenish (/Applications/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:191:21)
    at /Applications/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:203:33
    at r (file:///Applications/Avocode.app/Contents/Resources/app/dist/avocode.min.js:9:18405)
    at replenish (/Applications/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:191:21)
    at /Applications/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:203:33
    at r (file:///Applications/Avocode.app/Contents/Resources/app/dist/avocode.min.js:9:18405)
    at replenish (/Applications/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:191:21)
    at /Applications/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:203:33
    at r (file:///Applications/Avocode.app/Contents/Resources/app/dist/avocode.min.js:9:18405)
    at replenish (/Applications/Avocode.app/Contents/Resources/app/node_modules/async/li
```

**Comment by connor-bean** [comment]
Hey, Joel -

Thanks for the report. We've seen similar errors in the past as this and it seemed to work if you try to re-upload the design.

Could you try that and then let me know if you still have the same problem?

Thanks!
Connor, Avocode Team

**Comment by joelgoodman** [comment]
Same problem. I've re-uploaded, rasterized smart objects and re-uploaded. Same error pops up when trying to sync down to the app.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
