### ISSUE TITLE
Can't open design

### ISSUE THREAD

**Issue by kupcza** [avocode/avocode#857]
On v2.6.0 it's ok

IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.0-beta.3
Source UID: 675
```
TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'
    at TypeError (native)
    at file:///Users/xxx/Downloads/Avocode.app/Contents/Resources/app/dist/avocode.min.js:9:19039
    at Array.forEach (native)
    at e.exports.e._loadMaskedBy (file:///Users/xxx/Downloads/Avocode.app/Contents/Resources/app/dist/avocode.min.js:9:18551)
    at file:///Users/xxx/Downloads/Avocode.app/Contents/Resources/app/dist/avocode.min.js:9:16395
    at file:///Users/xxx/Downloads/Avocode.app/Contents/Resources/app/dist/avocode.min.js:9:18492
    at /Users/xxx/Downloads/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:200:33
    at r (file:///Users/xxx/Downloads/Avocode.app/Contents/Resources/app/dist/avocode.min.js:9:18405)
    at replenish (/Users/xxx/Downloads/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:191:21)
    at /Users/xxx/Downloads/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:203:33
    at r (file:///Users/xxx/Downloads/Avocode.app/Contents/Resources/app/dist/avocode.min.js:9:18405)
    at replenish (/Users/xxx/Downloads/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:191:21)
    at /Users/xxx/Downloads/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:203:33
    at r (file:///Users/xxx/Downloads/Avocode.app/Contents/Resources/app/dist/avocode.min.js:9:18405)
    at replenish (/Users/xxx/Downloads/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:191:21)
    at /Users/xxx/Downloads/Avocode.app/Contents/Resources/app/node_modules/async/lib/async.js:203:33
    at r (file:///Users/xxx/Downloads/Avocode.app/Contents/Resources/a
```

**Comment by connor-bean** [comment]
Thanks for sending the report. This looks like a similar issue in #855 so I'm going to close this ticket and we will track it there instead. Please let us know in #855 of any other questions related to this. Or feel free to email us at team@avocode.com
