### ISSUE TITLE
Unexpected error while trying to render image data

### ISSUE THREAD

**Issue by anirudhab2** [avocode/avocode#860]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.6.0
Source UID: 117756
```
TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'
    at TypeError (native)
    at t.module.exports.t._loadMaskedBy (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:3602)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:1011
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:3245
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:200:33
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:3183
    at replenish (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:191:21)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:203:33
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:3183
    at replenish (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:191:21)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:203:33
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:3183
    at replenish (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:191:21)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:203:33
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:3183
    at r
```

**Comment by connor-bean** [comment]
This looks very similar to ticket #757. 

Seems you don't have design downloaded properly.
You can upload it again and it should fix this.

Let me know if this doesn't work!

Thanks,
Connor, Avocode Team

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
