### ISSUE TITLE
Error while uploading PSDS

### ISSUE THREAD

**Issue by mvpspl619** [avocode/avocode#861]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.6.0
Source UID: 145701
```
TypeError: this._task.removeListener is not a function
    at t._unregisterTaskListeners (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:4038)
    at t._restart (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:2997)
    at t._send (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:6713)
    at t._addRequest (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:4659)
    at t.downloadFiles (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:2275)
    at e.downloadFiles (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:8679)
    at e.module.exports.e.downloadPreviews (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-downloader.js:1:1606)
    at e._downloadPreviews (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:17215)
    at e._updateRevisionPreview (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:24481)
    at e.addRevision (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:18520)
    at e._finishUpload (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uploader.js:1:10138)
    at e._handleUploadResult (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uploader.js:1:6397)
    at e._handleUploadResult (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uploader.js:1:197)
    at /Applications/Avo
```

**Comment by connor-bean** [comment]
Hi, we have experienced this issue several times and we're working on a fix. We will soon finish a new version of the app with major changes. This problem should be fixed there. The public beta version will be available in the upcoming coming weeks.

I will close this issue now and continue discussion in ticket #605
