### ISSUE TITLE
Problem with updating designs

### ISSUE THREAD

**Issue by masalygin** [avocode/avocode#866]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.6.0
Source UID: 106367
```
TypeError: this._task.removeListener is not a function
    at t._unregisterTaskListeners (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:4038)
    at t._restart (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:2997)
    at t._send (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:6713)
    at t._addRequest (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:4659)
    at t.downloadFiles (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:2275)
    at e.downloadFiles (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:8679)
    at e.module.exports.e.downloadThumbnails (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/assets-downloader.js:1:1302)
    at e._downloadThumbnails (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:16420)
    at /opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:15916
    at e (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/progress.js:1:3952)
    at replenish (/opt/Avocode/resources/app.asar/node_modules/async/lib/async.js:191:21)
    at /opt/Avocode/resources/app.asar/node_modules/async/lib/async.js:208:15
    at Object.async.eachLimit (/opt/Avocode/resources/app.asar/node_modules/async/lib/async.js:168:12)
    at Function.Progress.forEachLimit (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/progress.js:1:4152)
    at e._downloadThumbnailsInGroups (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:15960)
    at e._syncProjects (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:9698)
    at e._onUserData (/opt/Avocode/resources/app.asar/node_mo
```

**Comment by connor-bean** [comment]
Hi, we have experienced this issue several times and we're working on a fix. We will soon finish a new version of the app with major changes. This problem should be fixed there. The public beta version will be available in the upcoming coming weeks.

I will close this issue now and continue discussion in ticket #605
