### ISSUE TITLE
Error when trying to open newly uploaded PSD

### ISSUE THREAD

**Issue by simaks** [avocode/avocode#867]
1. uploaded new psd using website https://manager.avocode.com/
2. tried to open it in avocode

Erros are also occuring if uploaded using avocode application

OS: Ubuntu 16.04
Avocode version: 2.6.0

-----
App v.2.6.0
Source UID: 128983
```
TypeError: this._task.removeListener is not a function
    at t._unregisterTaskListeners (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:4038)
    at t._restart (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:2997)
    at t._send (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:6713)
    at t._addRequest (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:4659)
    at t.downloadFiles (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:2275)
    at e.downloadFiles (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:8679)
    at e.module.exports.e._requestArchive (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/assets-downloader.js:1:3474)
    at e.module.exports.e._downloadArchive (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/assets-downloader.js:1:2443)
    at e.module.exports.e.downloadArchive (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/assets-downloader.js:1:2064)
    at e._downloadRevisionArchive (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:15226)
    at /opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:13212
    at /opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:766
    at /opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:7834
    at /opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:8424
    at /opt/Avocode/resources/app.asar/node_modules/@avocode/core/node_modules/@avocode/decompress/node_modules/vinyl-fs/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:77:15)
```

**Comment by connor-bean** [comment]
Hi, we have experienced this issue several times and we're working on a fix. We will soon finish a new version of the app with major changes. This problem should be fixed there. The public beta version will be available in the upcoming coming weeks.

I will close this issue now and continue discussion in ticket #605
