### ISSUE TITLE
Avocode crash #2 when opening new design

### ISSUE THREAD

**Issue by simaks** [avocode/avocode#868]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.6.0
Source UID: 128983
```
TypeError: this._task.removeListener is not a function
    at t._unregisterTaskListeners (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:4038)
    at t._restart (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:2997)
    at t._send (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:6713)
    at t._addRequest (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:4659)
    at t.downloadFiles (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:2275)
    at e.downloadFiles (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:8679)
    at e.module.exports.e._requestArchive (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/assets-downloader.js:1:3474)
    at e.module.exports.e._downloadArchive (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/assets-downloader.js:1:2443)
    at e.module.exports.e.downloadArchive (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/assets-downloader.js:1:2064)
    at e._downloadRevisionArchive (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:15226)
    at /opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:13212
    at /opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:766
    at /opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:7834
    at /opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:8424
    at /opt/Avocode/resources/app.asar/node_modules/@avocode/core/node_modules/@avocode/decompress/node_modules/vinyl-fs/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:77:15)
```

**Comment by connor-bean** [comment]
Thanks for the report.

I'm going to close this out. Please refer to ticket #870 and #605 for further details.
