### ISSUE TITLE
Another random crash, probably also related to newly uploaded PSD

### ISSUE THREAD

**Issue by simaks** [avocode/avocode#870]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.6.0
Source UID: 128983
```
TypeError: this._task.removeListener is not a function
    at t._unregisterTaskListeners (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:4038)
    at t._restart (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:2997)
    at t._send (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:6713)
    at t._addRequest (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:4659)
    at t.downloadFiles (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:2275)
    at e.downloadFiles (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:8679)
    at e.module.exports.e.downloadThumbnails (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/assets-downloader.js:1:1302)
    at e._downloadThumbnails (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:16420)
    at /opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:15916
    at e (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/progress.js:1:3952)
    at replenish (/opt/Avocode/resources/app.asar/node_modules/async/lib/async.js:191:21)
    at /opt/Avocode/resources/app.asar/node_modules/async/lib/async.js:208:15
    at Object.async.eachLimit (/opt/Avocode/resources/app.asar/node_modules/async/lib/async.js:168:12)
    at Function.Progress.forEachLimit (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/progress.js:1:4152)
    at e._downloadThumbnailsInGroups (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:15960)
    at e._syncProjects (/opt/Avocode/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:9698)
    at e._onUserData (/opt/Avocode/resources/app.asar/node_mo
```

**Comment by connor-bean** [comment]
Hey, Simas - 

Could you try downloading our most recent Beta and see if it works there instead?

Here are the links to the Beta, depending on your operating system:

Mac:
https://manager.avocode.com/download/app-beta/mac/

Windows:
https://manager.avocode.com/download/app-beta/windows/

Linux 32-bit:
https://manager.avocode.com/download/app-beta/linux-ia32

Linux 64-bit:
https://manager.avocode.com/download/app-beta/linux/

Let me know if you still encounter these problems once you've downloaded the beta.

Thanks!
Connor, Avocode Support

**Comment by simaks** [comment]
Got some errors on beta version right after launching it.

-----
App v.2.8.0-beta.4
Source UID: 10912
```
Error: EACCES: permission denied, open '/home/sskilinskas/.avocode/state.json'
    at Error (native)
```

-----
App v.2.8.0-beta.4
Source UID: 10912
```
Error: EACCES: permission denied, open '/home/sskilinskas/.avocode/state.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:158:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at e.saveStateSync (file:///home/sskilinskas/.local/share/Avocode%202.8.0/resources/app.asar/dist/avocode.min.js:20:3911)
    at t.saveAppStateSync (file:///home/sskilinskas/.local/share/Avocode%202.8.0/resources/app.asar/dist/avocode.min.js:2:6328)
    at e.deactivate (file:///home/sskilinskas/.local/share/Avocode%202.8.0/resources/app.asar/dist/avocode.min.js:1:21588)
    at file:///home/sskilinskas/.local/share/Avocode%202.8.0/resources/app.asar/dist/avocode.min.js:1:1178
    at c (file:///home/sskilinskas/.local/share/Avocode%202.8.0/resources/app.asar/static/raven.min.js:2:3899)
```

**Comment by simaks** [comment]
Removed ~/.avocode and ~/.avcd folders and crashes on opening dissapeared

**Comment by simaks** [comment]
Uploading new PSD worked without crashes, although this beta version of avocode feels very slow and unresponsive, and using my processor (AMD A8-3870 APU with Radeon(tm) HD Graphics × 4) at 100% almost all the time

**Comment by simaks** [comment]
Im stuck on this for 10 minutes now >:( was just navigating thru some designs
![selection_100](https://cloud.githubusercontent.com/assets/5489941/15349543/4b139abc-1cdc-11e6-9d3e-a9a376e533c1.png)

**Comment by simaks** [comment]
and it showed me the design instantly after clicking "cancel", seriously?

**Comment by vojtatranta** [comment]
@simaks what about Beta 6 (auto update should have showed you update screen)
Has it resolved your issues?

**Comment by simaks** [comment]
Do you even have anyone testing the linux avocode version? Or you think its the job of the end users?

**Comment by vojtatranta** [comment]
@simaks Beta 6 is of course not available globally to all users. That is why you can't download it at the moment. When we release `2.8.0` it will be downloadable. Links for beta are above will always download latest Beta release.
Of course we test Linux. The bug you reported seems as a problem at your side - `state.json` was created with `sudo` permission - the app itself is not capable of such thing. Seems that old Beta was started for first time with other user or as superuser.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
