### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by AliveDD** [avocode/avocode#871]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.6.0
Source UID: 175367
```
TypeError: Cannot read property 'latestRevisionId' of undefined
  at t.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:31160)
  at t.EventEmitter.emit (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
  at e.requestRevisionDownload (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:25364)
  at e.loadRevision (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:26028)
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:26566
  at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:302:5)

```

**Comment by connor-bean** [comment]
Hello -

Can you try to explain to us what you were doing when you received this report? We need more information to try and recreate and diagnose the problem.

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
