### ISSUE TITLE
created two projects one by one. after starting uploading design to second project error occurred

### ISSUE THREAD

**Issue by max-bulygin** [avocode/avocode#872]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.6.0
Source UID: 67522
```
Error: EINVAL: invalid argument, open '/Users/iMax/.avcd/storage/state.json'
  at Error (native)
  at Object.fs.openSync (fs.js:546:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.writeFileSync (fs.js:1159:15)
  at Object.fsPlus.writeFileSync (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
  at StorageFolder.module.exports.StorageFolder.store (/Applications/Avocode.app/Contents/Resources/app.asar/src/storage-folder.js:14:17)
  at Atom.module.exports.Atom.saveSync (/Applications/Avocode.app/Contents/Resources/app.asar/src/atom.js:887:50)
  at t.saveAppState (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:13805)
  at e._finishSync (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:6815)
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:10486
  at n (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/progress.js:1:4105)
  at Object.async.each (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:118:20)
  at Function.Progress.forEachLimit (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/progress.js:1:4180)
  at Function.Progress.forEach (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/progress.js:1:3785)
  at e._addRevisionsToQueue (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:11062)
  at e._syncProjects (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:10037)
  at e._onUserData (/Applications/A
```

**Comment by connor-bean** [comment]
Hello -

Can you send us the problematic designs to team@avocode.com?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at manager.avocode.com. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
