### ISSUE TITLE
I've tried to upload revision

### ISSUE THREAD

**Issue by alexeybondarenko** [avocode/avocode#877]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.6.0
Source UID: 115826
```
TypeError: this._task.removeListener is not a function
    at t._unregisterTaskListeners (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:4038)
    at t._restart (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:2997)
    at t._send (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:6713)
    at t._addRequest (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:4659)
    at t.downloadFiles (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:2275)
    at e.downloadFiles (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:8679)
    at e.module.exports.e.downloadThumbnails (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-downloader.js:1:1302)
    at e._downloadThumbnails (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:16420)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:15916
    at e (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/progress.js:1:3952)
    at replenish (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:191:21)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:208:15
    at Object.async.eachLimit (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:168:12)
    at Function.Progress.forEachLimit (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/cor
```

**Comment by connor-bean** [comment]
Thanks for the report.

I'm going to close this out as it looks like a bug we've seen before and are tracking elsewhere. Please refer to ticket #870 and #605 for further details.
