### ISSUE TITLE
"An unexpected error has occurred" pop-up after start

### ISSUE THREAD

**Issue by ajtakrajta** [avocode/avocode#880]
-----
App v.2.8.0-beta.4
Source UID: 22175
```
Error: No such revision (ID = 88808a1504a34c758eb2b4f7c4004e86)
    at e.downloadNewRevisionById (file:///home/user/.local/opt/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:12:20871)
    at e.addRevision (file:///home/user/.local/opt/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:13:14055)
    at e._finishUpload (file:///home/user/.local/opt/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:13:8763)
    at e._handleUploadResult (file:///home/user/.local/opt/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:13:4553)
    at e._handleUploadResult (file:///home/user/.local/opt/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:12:28981)
    at Immediate._onImmediate (file:///home/user/.local/opt/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:8:25209)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at [manager.avocode.com](https://avocode.com/download/). I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
