### ISSUE TITLE
Authorization error

### ISSUE THREAD

**Issue by luthian** [avocode/avocode#883]
I tried to login in to the beta using the website and got the following:

-----
App v.2.8.0-beta.5
Source UID: 312
```
TypeError: Cannot read property '*' of undefined
    at e._getProjectsFromLegacyConfig (file:///Users/dda/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:12:29479)
    at e._getProjectFromStateAndConfig (file:///Users/dda/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:12:29351)
    at e._migrateLegacyAppData (file:///Users/dda/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:12:28985)
    at e.migrateLegacyAppState (file:///Users/dda/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:12:28669)
    at t.setAuthInfo (file:///Users/dda/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:2:3473)
    at t._onAuthTokenData (file:///Users/dda/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:2:2533)
    at t._onAuthTokenData (file:///Users/dda/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:11988)
    at Immediate._onImmediate (file:///Users/dda/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:24802)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by connor-bean** [comment]
Please download 2.8.6 here and let us know if this you still experience this issue:

https://manager.avocode.com/download/app-beta/mac/

https://manager.avocode.com/download/app-beta/windows/ 

https://manager.avocode.com/download/app-beta/linux-ia32/

https://manager.avocode.com/download/app-beta/linux/

**Comment by luthian** [comment]
Hi,

Worked like a champ; no problems authorizing using the browser.

Thanks,
DDA

> On Jun 1, 2016, at 4:56 AM, Connor <notifications@github.com> wrote:
> 
> Please download 2.8.6 here and let us know if this you still experience this issue:
> 
> https://manager.avocode.com/download/app-beta/mac/ <https://manager.avocode.com/download/app-beta/mac/>
> https://manager.avocode.com/download/app-beta/windows/ <https://manager.avocode.com/download/app-beta/windows/>
> https://manager.avocode.com/download/app-beta/linux-ia32/ <https://manager.avocode.com/download/app-beta/linux-ia32/>
> https://manager.avocode.com/download/app-beta/linux/ <https://manager.avocode.com/download/app-beta/linux/>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/avocode/avocode/issues/883#issuecomment-222933222>, or mute the thread <https://github.com/notifications/unsubscribe/AFgGWaNk6nkWXVbFtQY0V7-aOeDtTWB8ks5qHUlIgaJpZM4InooV>.
> 

--
DDA
 Events Area Head, Arisia ’16. http://www.arisia.org
  All the world's a stage and all the men and women merely players...

**Comment by connor-bean** [comment]
Thanks for the feedback! We definitely apologize for any frustration you experienced. Please don't hesitate to reach out in the future with any questions or comments!

Connor, Avocode Support
