### ISSUE TITLE
Starting up application

### ISSUE THREAD

**Issue by VaclovasV** [avocode/avocode#886]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.0-beta.5
Source UID: 21742
```
TypeError: Cannot read property '*' of undefined
    at e._getProjectsFromLegacyConfig (file:///C:/Users/Admin/AppData/Local/avocodebeta/app-2.8.0-beta5/resources/app.asar/dist/avocode.min.js:12:29479)
    at e._getProjectFromStateAndConfig (file:///C:/Users/Admin/AppData/Local/avocodebeta/app-2.8.0-beta5/resources/app.asar/dist/avocode.min.js:12:29351)
    at e._migrateLegacyAppData (file:///C:/Users/Admin/AppData/Local/avocodebeta/app-2.8.0-beta5/resources/app.asar/dist/avocode.min.js:12:28985)
    at e.migrateLegacyAppState (file:///C:/Users/Admin/AppData/Local/avocodebeta/app-2.8.0-beta5/resources/app.asar/dist/avocode.min.js:12:28669)
    at t.setAuthInfo (file:///C:/Users/Admin/AppData/Local/avocodebeta/app-2.8.0-beta5/resources/app.asar/dist/avocode.min.js:2:3473)
    at t._onAuthTokenData (file:///C:/Users/Admin/AppData/Local/avocodebeta/app-2.8.0-beta5/resources/app.asar/dist/avocode.min.js:2:2533)
    at t._onAuthTokenData (file:///C:/Users/Admin/AppData/Local/avocodebeta/app-2.8.0-beta5/resources/app.asar/dist/avocode.min.js:1:11988)
    at Immediate._onImmediate (file:///C:/Users/Admin/AppData/Local/avocodebeta/app-2.8.0-beta5/resources/app.asar/dist/avocode.min.js:1:24802)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by connor-bean** [comment]
Hello - thanks for the report. 

This looks very similar to #883 so we will close this out and track it in the other case.

**Comment by connor-bean** [comment]
Please download Beta 2.8.6 here and let us know if this you still experience this issue:

https://manager.avocode.com/download/app-beta/mac/

https://manager.avocode.com/download/app-beta/windows/

https://manager.avocode.com/download/app-beta/linux-ia32/

https://manager.avocode.com/download/app-beta/linux/
