### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by zeevblu** [avocode/avocode#891]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.0-beta.6
Source UID: 44085
```
Error: ENOENT: no such file or directory, lstat '/Users/zeev/Downloads/Avocode-darwin-x64/Avocode.app'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:228:16)
    at realpathSync (fs.js:1528:21)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:313:24)
    at toRealPath (module.js:126:13)
    at tryFile (module.js:122:22)
    at tryExtensions (module.js:132:20)
    at Function.Module._findPath (module.js:172:20)
    at Function.Module._resolveFilename (module.js:337:25)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at BufferList.Readable (/Users/zeev/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/decompress-targz/node_modules/tar-stream/node_modules/bl/node_modules/readable-stream/lib/_stream_readable.js:128:22)
    at BufferList.Duplex (/Users/zeev/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/decompress-targz/node_modules/tar-stream/node_modules/bl/node_modules/readable-stream/lib/_stream_duplex.js:43:12)
    at new BufferList (/Users/zeev/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/decompress-targz/node_modules/tar-stream/node_modules/bl/bl.js:32:16)
    at BufferList (/Users/zeev/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/decompress-targz/node_modules/tar-stream/node_modules/bl/bl.js:7:12)
    at new Extract (/Users/zeev/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/decompress-targz/node_modules/tar-stream/extract.js:46:18)
    at Object.Extract (/Users/zeev/Downloads/Avocode-darwin-x64/Avocode.app/Cont
```

**Comment by vojtatranta** [comment]
Oh that is a common issue. It seems you moved Avocode.app from Downloads folder somewhere else and shortcut you made cannot find it anymore.
You can download beta again a move it into you Applications folder and you are good to go.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at [manager.avocode.com](https://avocode.com/download/). I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
