### ISSUE TITLE
App v.2.8.0-beta.6 fails to start

### ISSUE THREAD

**Issue by RobertLang** [avocode/avocode#892]
IMPORTANT: Please try to describe how did it happen.
When trying to start the application under MacOSX
-----
App v.2.8.0-beta.6
Source UID: 13396
```
TypeError: e.map is not a function
    at e._createRuleGroups (file:///Users/rlang/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:13:2835)
    at e._createExportRules (file:///Users/rlang/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:13:2760)
    at file:///Users/rlang/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:13:2217
    at e.update (file:///Users/rlang/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:9:9440)
    at e._migrateDesign (file:///Users/rlang/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:13:2144)
    at file:///Users/rlang/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:13:1044
    at Array.forEach (native)
    at file:///Users/rlang/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:13:1015
    at Array.forEach (native)
    at e._migrateProjects (file:///Users/rlang/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:13:918)
    at e._migrateLegacyAppData (file:///Users/rlang/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:13:215)
    at e.migrateLegacyAppState (file:///Users/rlang/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:12:31891)
    at t.setAuthInfo (file:///Users/rlang/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:2:3719)
    at t._onAuthTokenData (file:///Users/rlang/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:2:2729)
    at t._onAuthTokenData (file:///U
```

**Comment by vojtatranta** [comment]
Hi,
thank you for this report.
Would you mind to send me your app state? It is located in you home directory in `~/.avcd/storage/stage.json` at `vojtatranta@avocode.com`?
Because it seems that your export rules are saved in unexpected shape.

**Comment by vojtatranta** [comment]
It seems you have pretty old version of App installed that has different shape of state.
We will fix it so the app won't crash.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at [manager.avocode.com](https://avocode.com/download/). I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
