### ISSUE TITLE
avocode beta-testing testing open design after upload new revision

### ISSUE THREAD

**Issue by vAhyThe** [avocode/avocode#893]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.0-beta.6
Source UID: 70641
```
TypeError: Cannot read property 'scale' of null
    at React.createClass._getStageState (file:///Users/vAhy_The/Downloads/avocode/Avocode-darwin-x64%202/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:30:15649)
    at React.createClass._getState (file:///Users/vAhy_The/Downloads/avocode/Avocode-darwin-x64%202/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:30:15143)
    at React.createClass.componentWillReceiveProps (file:///Users/vAhy_The/Downloads/avocode/Avocode-darwin-x64%202/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:30:13900)
    at ReactCompositeComponentMixin.updateComponent (/Users/vAhy_The/Downloads/avocode/Avocode-darwin-x64 2/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:458:14)
    at ReactCompositeComponentMixin.receiveComponent (/Users/vAhy_The/Downloads/avocode/Avocode-darwin-x64 2/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:405:10)
    at Object.ReactReconciler.receiveComponent (/Users/vAhy_The/Downloads/avocode/Avocode-darwin-x64 2/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:87:22)
    at ReactCompositeComponentMixin._updateRenderedComponent (/Users/vAhy_The/Downloads/avocode/Avocode-darwin-x64 2/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:562:23)
    at ReactCompositeComponentMixin._performComponentUpdate (/Users/vAhy_The/Downloads/avocode/Avocode-darwin-x64 2/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:544:10)
    at ReactCompositeComponentMixin.updateComponent (/Users/vAhy_The/Downloads/avocode/Avocode-darwin-x64 2/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCo
```

**Comment by vojtatranta** [comment]
Thank you for your time!
I tried to reproduce it with no luck. But I have a tip where a problem might be.
You probably cannot send us that particular PSD, right?

**Comment by vAhyThe** [comment]
Hi no because NDA :/

**Comment by vojtatranta** [comment]
That's a shame. 
Can you please tell what way of uploading a revision did you choose?
Did you use `File -> upload design` or did you tile on the Project Manager and upload it right on a design?

**Comment by vAhyThe** [comment]
I know.
i use menubar and clic on `upload revision`

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at [manager.avocode.com](https://avocode.com/download/). I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
