### ISSUE TITLE
avocode beta-testing yust open from menubar 

### ISSUE THREAD

**Issue by vAhyThe** [avocode/avocode#897]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.0-beta.6
Source UID: 52477
```
Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/Users/vAhy_The/Downloads/avocode/Avocode-darwin-x64/Avocode.app/Contents/Resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/Users/vAhy_The/Downloads/avocode/Avocode-darwin-x64/Avocode.app/Contents/Resources/electron.asar/browser/rpc-server.js:317:31)
    at emitMany (events.js:121:13)
    at EventEmitter.emit (events.js:195:7)
    at EventEmitter.<anonymous> (/Users/vAhy_The/Downloads/avocode/Avocode-darwin-x64/Avocode.app/Contents/Resources/electron.asar/browser/api/web-contents.js:139:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at metaToValue (/Users/vAhy_The/Downloads/avocode/Avocode-darwin-x64/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:176:13)
    at remoteMemberFunction (/Users/vAhy_The/Downloads/avocode/Avocode-darwin-x64/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:110:18)
    at t._sendSetTargetWindowId (file:///Users/vAhy_The/Downloads/avocode/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:23:4592)
    at t.setTargetWindowId (file:///Users/vAhy_The/Downloads/avocode/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:23:3520)
    at t.<anonymous> (file:///Users/vAhy_The/Downloads/avocode/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:23:2571)
    at t.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at t.emit (events.js:179:7)
    at t._handleDownloaderLoad (file:///Users/vAhy_The/Downloads/avocode/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:23:5407)
    at file:///Use
```

**Comment by vojtatranta** [comment]
Thank you.
We know abou this, it is a bug in downloader process.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it here at [manager.avocode.com](https://avocode.com/download/). I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
