### ISSUE TITLE
Error in 2.8.0-beta.6

### ISSUE THREAD

**Issue by svistunov** [avocode/avocode#898]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.0-beta.6
Source UID: 56708
```
TypeError: Cannot read property 'get' of null
    at file:///home/svistunov/opt/avacode/resources/app.asar/dist/avocode.min.js:10:2109
    at Array.forEach (native)
    at e.exports.e._loadMaskedBy (file:///home/svistunov/opt/avacode/resources/app.asar/dist/avocode.min.js:10:1557)
    at file:///home/svistunov/opt/avacode/resources/app.asar/dist/avocode.min.js:9:31377
    at file:///home/svistunov/opt/avacode/resources/app.asar/dist/avocode.min.js:10:1498
    at /home/svistunov/opt/avacode/resources/app.asar/node_modules/async/lib/async.js:200:33
    at r (file:///home/svistunov/opt/avacode/resources/app.asar/dist/avocode.min.js:10:1411)
    at replenish (/home/svistunov/opt/avacode/resources/app.asar/node_modules/async/lib/async.js:191:21)
    at /home/svistunov/opt/avacode/resources/app.asar/node_modules/async/lib/async.js:203:33
    at r (file:///home/svistunov/opt/avacode/resources/app.asar/dist/avocode.min.js:10:1411)
    at replenish (/home/svistunov/opt/avacode/resources/app.asar/node_modules/async/lib/async.js:191:21)
    at /home/svistunov/opt/avacode/resources/app.asar/node_modules/async/lib/async.js:203:33
    at r (file:///home/svistunov/opt/avacode/resources/app.asar/dist/avocode.min.js:10:1411)
    at replenish (/home/svistunov/opt/avacode/resources/app.asar/node_modules/async/lib/async.js:191:21)
    at /home/svistunov/opt/avacode/resources/app.asar/node_modules/async/lib/async.js:203:33
    at r (file:///home/svistunov/opt/avacode/resources/app.asar/dist/avocode.min.js:10:1411)
    at replenish (/home/svistunov/opt/avacode/resources/app.asar/node_modules/async/lib/async.js:191:21)
    at /home/svistunov/opt/avacode/resources/app.asar/node_modules/async/lib/async.js:203:33
    at r (file:///home/svistunov/opt/avacode/resources/app.asar/dist/avocode.min.js
```

**Comment by connor-bean** [comment]
Hello - thanks for the report. Can you explain to us what you were doing when you received this error? Any screenshots or videos would be greatly appreciated to help us try to recreate the problem.

Thanks,
Connor, Avocode Support

**Comment by jankuca** [comment]
Hi, I am guessing a design of yours could not be opened. Correct me if I'm wrong.

Would you be willing to send us the problematic PSD/Sketch file in question to team@avocode.com? It would help us greatly in resolving this issue.

**Comment by jankuca** [comment]
Actually, nevermind, I was able to reproduce this and fix it. It's going to be OK in the next release.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at [manager.avocode.com.](https://avocode.com/download/) I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
