### ISSUE TITLE
Try to use Slice tool 

### ISSUE THREAD

**Issue by koty33** [avocode/avocode#900]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.0-sentrytest7
Source UID: 70634
```
TypeError: Cannot read property 'scale' of null
    at React.createClass._getStageState (file:///Users/Koty/Downloads/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:30:16247)
    at React.createClass._getState (file:///Users/Koty/Downloads/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:30:15708)
    at React.createClass.getInitialState (file:///Users/Koty/Downloads/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:30:14378)
    at new Constructor (/Users/Koty/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactClass.js:708:54)
    at ReactCompositeComponentMixin.mountComponent (/Users/Koty/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:153:16)
    at Object.ReactReconciler.mountComponent (/Users/Koty/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:37:35)
    at ReactCompositeComponentMixin.mountComponent (/Users/Koty/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:225:34)
    at Object.ReactReconciler.mountComponent (/Users/Koty/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:37:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/Koty/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:241:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/Users/Koty/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:591:32)
    at ReactDOMComponent.Mixin.mountComponent (/Users/Koty/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:479:29)
    at Object.ReactReconciler.mountComponent 
```

**Comment by jakubzitny** [comment]
#893
