### ISSUE TITLE
App v.2.8.0-beta.6 -  closing tabs with cmd+w then cmd+e

### ISSUE THREAD

**Issue by xar** [avocode/avocode#902]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.0-beta.6
Source UID: 1670
```
Error: Could not call remote function 'quit'. Check that the function signature is correct. Underlying error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: avocode.min.js:23:3830.
Error: Could not call remote function 'quit'. Check that the function signature is correct. Underlying error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: avocode.min.js:23:3830.
    at callFunction (/Applications/Avocode.app/Contents/Resources/electron.asar/browser/rpc-server.js:237:11)
    at EventEmitter.<anonymous> (/Applications/Avocode.app/Contents/Resources/electron.asar/browser/rpc-server.js:318:12)
    at emitMany (events.js:121:13)
    at EventEmitter.emit (events.js:195:7)
    at EventEmitter.<anonymous> (/Applications/Avocode.app/Contents/Resources/electron.asar/browser/api/web-contents.js:139:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at metaToValue (/Applications/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:176:13)
    at remoteMemberFunction (/Applications/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:110:18)
    at t.quit (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:2:6011)
    at React.createClass._handleShortcut (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:7:11660)
    at module.exports.React.createClass._handleShortcuts (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/component/shortcuts.js:138:25)
    at _fireCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/node_modules/mousetrap/mousetrap.js:610:17)
    at Mouset
```

**Comment by vojtatranta** [comment]
Hello!
Thank you fort this report.
This happens when you reload the Electron window with eg. `cmd+r` but that should not be possible in the build.
Did you try to do something like this? Probably not, right?

**Comment by xar** [comment]
Maybe by misstype but i'm not sure. Probably no

**Comment by vojtatranta** [comment]
I thought is would be a problem with deregistering main process listeners but it seems as a bug in Electron.
I asked kind guys that develop Electron, hopefully they will help us.
Thank you for your time!

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at manager.avocode.com. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
