### ISSUE TITLE
Exprot path input ! not work Ctrl+A 

### ISSUE THREAD

**Issue by retyui** [avocode/avocode#904]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.6.0
Source UID: 71307
```
TypeError: menu.sendActionToFirstResponder is not a function
  at HTMLDocument.<anonymous> (C:\Users\asd\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\window-event-handler.js:170:20)
  at HTMLDocument.handler (C:\Users\asd\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\space-pen-extensions.js:115:32)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\asd\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\asd\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\asd\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\command-registry.js:251:29)
  at C:\Users\asd\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\asd\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\asd\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\asd\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\window-event-handler.js:185:27)

```

**Comment by connor-bean** [comment]
Thanks for the report.

Can you upgrade to our 2.8 Beta and retry?

Mac OS X<https://manager.avocode.com/download/app-beta/mac/> 
Windows<https://manager.avocode.com/download/app-beta/windows/> 
Linux ia32<https://manager.avocode.com/download/app-beta/linux-ia32/> 
Linux x64<https://manager.avocode.com/download/app-beta/linux/>

If you still have issues, can you send us screenshots of what you're looking at when you received the error as well as a detailed use case?

**Comment by jakubzitny** [comment]
In upcoming release there is completely new Export interface with support for keyboard shortcuts. Please install the beta version (links above) or wait few days for the official release ;)
