### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by artureldib** [avocode/avocode#907]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.6.0
Source UID: 180324
```
TypeError: Cannot read property 'right' of undefined
  at e.calculateDistance (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/measure-stageview/lib/measure.js:1:3066)
  at e.measure (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/measure-stageview/lib/measure.js:1:2537)
  at t.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/measure-stageview/lib/main.js:1:521)
  at t.EventEmitter.emit (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
  at e.mousemove (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/measure-tool/lib/measure-tool.js:1:911)
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/measure-tool/lib/measure-tool.js:1:146
  at t.module.exports.Emitter.emit (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:118:15)
  at HTMLCanvasElement.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/stage.js:1:4480)

```

**Comment by connor-bean** [comment]
Hi, thanks for the report. We already know about this and we will be fixing it soon.

I'll close this issue, please see #787 for updates.
