### ISSUE TITLE
Avocode crashes on startup

### ISSUE THREAD

**Issue by sbaechler** [avocode/avocode#909]
IMPORTANT: Please try to describe how did it happen.

Avocode completes startup but is very slow.

---

App v.2.8.0-beta.6
Source UID: 48989

```
Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (C:\Users\bao\AppData\Local\avocodebeta\app-2.8.0-beta6\resources\electron.asar\browser\objects-registry.js:44:28)
    at EventEmitter.<anonymous> (C:\Users\bao\AppData\Local\avocodebeta\app-2.8.0-beta6\resources\electron.asar\browser\rpc-server.js:317:31)
    at emitMany (events.js:121:13)
    at EventEmitter.emit (events.js:195:7)
    at EventEmitter.<anonymous> (C:\Users\bao\AppData\Local\avocodebeta\app-2.8.0-beta6\resources\electron.asar\browser\api\web-contents.js:139:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at metaToValue (C:\Users\bao\AppData\Local\avocodebeta\app-2.8.0-beta6\resources\electron.asar\renderer\api\remote.js:176:13)
    at remoteMemberFunction (C:\Users\bao\AppData\Local\avocodebeta\app-2.8.0-beta6\resources\electron.asar\renderer\api\remote.js:110:18)
    at t._sendSetTargetWindowId (file://
```

**Comment by vojtatranta** [comment]
This is Electron problem, which should be fixed in newer versions. Please update and comment if it still persists.
