### ISSUE TITLE
I just clicked on the screen and then it crashed.

### ISSUE THREAD

**Issue by LetaiefAymen** [avocode/avocode#910]
I just clicked on one of the screens and then it crashed.

-----
App v.2.8.0-beta.6
Source UID: 55029
```
TypeError: Cannot read property 'get' of null
    at file:///home/aymen/Downloads/avocode-new/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:10:2109
    at Array.forEach (native)
    at e.exports.e._loadMaskedBy (file:///home/aymen/Downloads/avocode-new/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:10:1557)
    at file:///home/aymen/Downloads/avocode-new/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:9:31377
    at file:///home/aymen/Downloads/avocode-new/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:10:1498
    at /home/aymen/Downloads/avocode-new/Avocode-linux-x64/resources/app.asar/node_modules/async/lib/async.js:200:33
    at r (file:///home/aymen/Downloads/avocode-new/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:10:1411)
    at replenish (/home/aymen/Downloads/avocode-new/Avocode-linux-x64/resources/app.asar/node_modules/async/lib/async.js:191:21)
    at /home/aymen/Downloads/avocode-new/Avocode-linux-x64/resources/app.asar/node_modules/async/lib/async.js:203:33
    at r (file:///home/aymen/Downloads/avocode-new/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:10:1411)
    at replenish (/home/aymen/Downloads/avocode-new/Avocode-linux-x64/resources/app.asar/node_modules/async/lib/async.js:191:21)
    at /home/aymen/Downloads/avocode-new/Avocode-linux-x64/resources/app.asar/node_modules/async/lib/async.js:203:33
    at r (file:///home/aymen/Downloads/avocode-new/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:10:1411)
    at replenish (/home/aymen/Downloads/avocode-new/Avocode-linux-x64/resources/app.asar/node_modules/async/lib/async.js:191:21)
    at /home/aymen/Downloads/avocode-new/Avocode-linux-x64/resources/app.asar/node_modules/async/lib/async.js:203:33
    at r (file:///home/aymen/Downloads
```

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it [at manager.avocode.com](https://avocode.com/download/). I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
