### ISSUE TITLE
after the upgrade to 2.8, does not work when you open a psd

### ISSUE THREAD

**Issue by AlexLvov** [avocode/avocode#916]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.0
Source UID: 71382
```
RangeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation
    at RangeError (native)
    at e.exports.e.drawImage (file:///C:/Users/master/AppData/Local/avocode/app-2.8.0/resources/app.asar/dist/avocode.min.js:24:5280)
    at file:///C:/Users/master/AppData/Local/avocode/app-2.8.0/resources/app.asar/dist/avocode.min.js:24:3236
    at List.__iterate (C:\Users\master\AppData\Local\avocode\app-2.8.0\resources\app.asar\node_modules\immutable\dist\immutable.js:2208:13)
    at List.forEach (C:\Users\master\AppData\Local\avocode\app-2.8.0\resources\app.asar\node_modules\immutable\dist\immutable.js:4383:19)
    at e.exports.e.createSprites (file:///C:/Users/master/AppData/Local/avocode/app-2.8.0/resources/app.asar/dist/avocode.min.js:24:2834)
    at e.exports.e.loadDocument (file:///C:/Users/master/AppData/Local/avocode/app-2.8.0/resources/app.asar/dist/avocode.min.js:24:2578)
    at t.loadDocument (file:///C:/Users/master/AppData/Local/avo
```

**Comment by connor-bean** [comment]
Hey @AlexLvov -

Thanks for the report. Would you be able to send us any screenshots and the PSD you were trying to open to team@avocode.com?

**Comment by AlexLvov** [comment]
PSD to update opened. Now most of the PSD issued a screen - http://prntscr.com/bg76b1. Example file that is not open - https://yadi.sk/i/Er2Hoz1IsUMCc

**Comment by vojtatranta** [comment]
Hi @AlexLvov 
this is clearly a problem of 32bits version of Avocode.

We backed x64 build of Avocode for you. You can try it out: http://media.avocode.com/download/avocode-app/2.8.0/avocode-app-windows-x64-2.8.0.exe

Opening a design should be OK, because Avocode would be able to allocate more memory.
Note that you will not lose any of your data, but you may experience bad performance first few minutes after login - app needs to download assets and other stuff.
Thank you!

**Comment by AlexLvov** [comment]
Thank you!
Everything is working!

**Comment by vojtatranta** [comment]
@AlexLvov wooow! I love to hear this!! We will be releasing 2.8.1 you should be notified at least via github. I hope you won't have any troubles with this minor update, if so, please let us know. Thank you!

**Comment by vojtatranta** [comment]
Hi @AlexLvov here's link for stable 64bit Windows Avocode build https://manager.avocode.com/download/avocode-app/windows-x64/ please use this one, thanks.
