### ISSUE TITLE
On right click on transparent section with nothing. when design is open. (on Linux)

### ISSUE THREAD

**Issue by t1gu1** [avocode/avocode#917]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.0
Source UID: 71755
```
TypeError: Cannot read property 'get' of null
    at e._onContextMenu (file:///home/guillaume/Documents/Apps/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:29:3953)
    at file:///home/guillaume/Documents/Apps/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:28:31911
    at t.module.exports.Emitter.emit (/home/guillaume/Documents/Apps/Avocode-linux-x64/resources/app.asar/node_modules/emissary/lib/emitter.js:118:15)
    at t._handleContextMenu (file:///home/guillaume/Documents/Apps/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:23:22233)
    at HTMLDivElement.<anonymous> (file:///home/guillaume/Documents/Apps/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:23:16068)
    at HTMLDivElement.d (file:///home/guillaume/Documents/Apps/Avocode-linux-x64/resources/app.asar/static/raven.min.js:2:3637)
```

**Comment by jakubzitny** [comment]
Hi @t1gu1, thanks a lot for the report. We already know about this from #912 so I will close this issue.

The problem will be fixed for `2.8.1`.
