### ISSUE TITLE
tried to open psd when clicking "open in avocode app" button

### ISSUE THREAD

**Issue by ny1am** [avocode/avocode#924]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.0
Source UID: 57527
```
TypeError: Parameter "url" must be a string, not object
    at Url.parse (url.js:79:11)
    at Object.urlParse [as parse] (url.js:73:5)
    at t._normalizeUri (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:21:378)
    at t._addItemWithUri (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:20:29852)
    at t._handleAction (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:20:27282)
    at Object.ID_2 (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:20:25041)
    at Dispatcher._invokeCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:198:24)
    at Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:174:14)
    at e.dispatch (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:21:8327)
    at t.e.dispatch (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:2:20643)
    at t.addItemWithUri (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:15:23134)
    at e.openUri (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:14:17277)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:27666
    at Array.forEach (native)
    at t._openInitialUris (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:27600)
    at Immediate._onImmediate (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:24755)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by jakubzitny** [comment]
Hi @ny1am, thanks for reporting this. I am putting it into our TODO list and we will fix it as soon as possible.

**Comment by jakubzitny** [comment]
Hey, we've just released [Avocode 2.8.1](http://avocode.com/download/) which solves this issue. Please, check it out and let us know if you have any more problems with it.

Thanks ;)

**Comment by ny1am** [comment]
thanks! it works:)

2016-06-16 22:16 GMT+03:00 Jakub Žitný <notifications@github.com>:

**Comment by vojtatranta** [comment]
@ny1am yeah, we are sorry that we broke it :(
