### ISSUE TITLE
Drag & drop .psd create 2 upload on MAC desktop 

### ISSUE THREAD

**Issue by morcegon** [avocode/avocode#928]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.0
Source UID: 17209
```
TypeError: Cannot read property 'completed_at' of undefined
    at t._handleAction (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:19:8624)
    at Object.ID_13 (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:19:3049)
    at Dispatcher._invokeCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:198:24)
    at Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:174:14)
    at e.dispatch (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:21:8327)
    at t.e.dispatch (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:2:20643)
    at t.assignItem (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:15:12660)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:14:4129
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:14:6793
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:21:19255
    at callback (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:21:31292)
    at t._handleResponse (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:22:2649)
    at Request._callback (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:21:31160)
    at Request.self.callback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/request/request.js:200:22)
    at emitTwo (events.js:111:20)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/req
```

**Comment by jakubzitny** [comment]
Thank @morcegon for this report. We already know about it (from issue #926) and we will fix it for next release `2.8.1`.

I will close this issue. Let's continue in #926 if anything comes up.
