### ISSUE TITLE
Error in the background

### ISSUE THREAD

**Issue by OlafurTorfi** [avocode/avocode#939]
I had avocode running in the background for a while without actually looking at it. Then this error started popping up repeatedly

-----
App v.2.6.0
Source UID: 176746
```
Error: EROFS: read-only file system, open '/home/olafury/.avcd/storage/state.json'
    at Error (native)
    at Object.fs.openSync (fs.js:546:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.writeFileSync (fs.js:1159:15)
    at Object.fsPlus.writeFileSync (/home/olafury/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at StorageFolder.module.exports.StorageFolder.store (/home/olafury/Downloads/Avocode-linux-x64/resources/app.asar/src/storage-folder.js:14:17)
    at Atom.module.exports.Atom.saveSync (/home/olafury/Downloads/Avocode-linux-x64/resources/app.asar/src/atom.js:887:50)
    at t.saveAppState (/home/olafury/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:13805)
    at e._finishSync (/home/olafury/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:6815)
    at /home/olafury/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:10486
    at n (/home/olafury/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/progress.js:1:4105)
    at Object.async.each (/home/olafury/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/async/lib/async.js:118:20)
    at Function.Progress.forEachLimit (/home/olafury/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/progress.js:1:4180)
    at Function.Progress.forEach (/home/olafury/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/progress.js:1:3785)
    at e._addRevisionsToQueue (/home/olafury/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:11062)
    at e._syncProjects (/home/olafury/Download
```

**Comment by connor-bean** [comment]
Hey @OlafurTorfi -

Can you try using Avocode 2.8.1 instead to see if this fixes the problem?

Download links are below:

[Mac](https://avocode-media.s3.amazonaws.com/download/avocode-app/2.8.1/avocode-app-mac-2.8.1.zip)

[Windows](https://avocode-media.s3.amazonaws.com/download/avocode-app/2.8.1/avocode-app-windows-2.8.1.exe)

[Linux 64bit](https://avocode-media.s3.amazonaws.com/download/avocode-app/2.8.1/avocode-app-linux-2.8.1.zip)

[Linux 32bit](https://avocode-media.s3.amazonaws.com/download/avocode-app/2.8.1/avocode-app-linux-ia32-2.8.1.zip)

Please let us know the result to this problem once you've downloaded 2.8.1.

Thanks!
Connor, Avocode Support

**Comment by jakubzitny** [comment]
Hey @OlafurTorfi, your issue seems to be related to the permissions on your filesystem. If you still have problems with current version of Avocode, feel free to reopen this issue.
