### ISSUE TITLE
On opening the program

### ISSUE THREAD

**Issue by flyke** [avocode/avocode#940]
IMPORTANT: Please try to describe how did it happen.

---

App v.2.8.1
Source UID: 62475

```
Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (C:\Users\joery.lemmens\AppData\Local\avocode\app-2.8.1\resources\electron.asar\browser\objects-registry.js:44:28)
    at EventEmitter.<anonymous> (C:\Users\joery.lemmens\AppData\Local\avocode\app-2.8.1\resources\electron.asar\browser\rpc-server.js:302:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at EventEmitter.<anonymous> (C:\Users\joery.lemmens\AppData\Local\avocode\app-2.8.1\resources\electron.asar\browser\api\web-contents.js:165:13)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at metaToValue (C:\Users\joery.lemmens\AppData\Local\avocode\app-2.8.1\resources\electron.asar\renderer\api\remote.js:178:13)
    at remoteMemberFunction (C:\Users\joery.lemmens\AppData\Local\avocode\app-2.8.1\resources\electron.asar\renderer\api\remote.js:112:18)
    at t._sendSetTargetWindowId (file://
```

**Comment by connor-bean** [comment]
Hey @flyke 

Thanks for the report. Can you try to give us more information of what happened so we can better diagnose any problems.

Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey, @flyke 

I just wanted to check in to see if you could give us more information on what happened? 

Thanks!
Connor, Avocode Support

**Comment by vojtatranta** [comment]
this is a random Electron issue, which should be okay in newer versions, closing.
