### ISSUE TITLE
Crash while Avocode in background.

### ISSUE THREAD

**Issue by zanerock** [avocode/avocode#942]
I was working in another email when Avocode popped up with this.

-----
App v.2.6.0
Source UID: undefined
```
TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:3394)
    at self.callback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:199:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:166:7)
    at e._handleOfflineState (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:12813)
    at e._handleOfflineState (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:192)
    at e.setOfflineState (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:1876)
    at t.suspend (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:27063)
    at HTMLBodyElement.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:1178)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Avocode.app/Contents/Resources/app.asar/src/command-registry.js:251:29)
    at CommandRegistry.handleCommandEvent (/Applications/Avocode.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/src/command-registry.js:166:19)
    at EventEmitter.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/src/window-event-handler.js:75:30)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)
```

**Comment by jakubzitny** [comment]
Hey @zanerock, thanks for the report. You are using an old version of Avocode. We have already released `2.8.1`, have you considered upgrading? You can upgrade directly in the app or download current version from [avocode.com/download](http://avocode.com/download/).

I'll close this issue. Feel free to reopen, if it happens the current version as well.
