### ISSUE TITLE
hex to rgb preferences

### ISSUE THREAD

**Issue by WarEnek** [avocode/avocode#961]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.3
Source UID: 75670
```
TypeError: this.context.codeLanguageManager.off is not a function
    at Constructor.componentWillUnmount (file:///C:/Users/WarEnek-dt/AppData/Local/avocode/app-2.8.3/resources/app.asar/dist/avocode.min.js:6:5102)
    at ReactCompositeComponentWrapper.unmountComponent (C:\Users\WarEnek-dt\AppData\Local\avocode\app-2.8.3\resources\app.asar\node_modules\react\lib\ReactCompositeComponent.js:243:12)
    at Object.unmountComponent (C:\Users\WarEnek-dt\AppData\Local\avocode\app-2.8.3\resources\app.asar\node_modules\react\lib\ReactReconciler.js:52:22)
    at Object.unmountChildren (C:\Users\WarEnek-dt\AppData\Local\avocode\app-2.8.3\resources\app.asar\node_modules\react\lib\ReactChildReconciler.js:115:25)
    at ReactDOMComponent.unmountChildren (C:\Users\WarEnek-dt\AppData\Local\avocode\app-2.8.3\resources\app.asar\node_modules\react\lib\ReactMultiChild.js:398:28)
    at ReactDOMComponent.unmountComponent (C:\Users\WarEnek-dt\AppData\Local\avocode\app-2.8.3\resources\app.asar\node_modules\re
```

**Comment by bolekkerous** [comment]
Hello!
Thanks for the report. We're already working on fix-build, it should be ready soon.

**Comment by vojtatranta** [comment]
@WarEnek Hi!
I was completely my mistake I apologize.
`2.8.4` is released - after booting update should start downloading and that a prompt to installing should pop up.
If not click on check for update in help menu.
Thank you soo much and let us know whether it is fixed.
Thanks

**Comment by WarEnek** [comment]
@vojtatranta 
Thank you for the quick response.
2.8.4 Perfectly convert rgb to hex and inversely.

**Comment by vojtatranta** [comment]
@WarEnek  I love to hear it! Thank you for your patience.
I would be glad if you reported any other issue in the future (hopefully, there will not by any:).

**Comment by darksis** [comment]
Hello i want ask if this possible run that on ubuntu 32 bit?
