### ISSUE TITLE
tabs wasn't switch

### ISSUE THREAD

**Issue by salexpro** [avocode/avocode#963]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.3
Source UID: 30893
```
TypeError: this.context.codeLanguageManager.off is not a function
    at Constructor.componentWillUnmount (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:6:5102)
    at ReactCompositeComponentWrapper.unmountComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:243:12)
    at Object.unmountComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:52:22)
    at Object.unmountChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler.js:115:25)
    at ReactDOMComponent.unmountChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:398:28)
    at ReactDOMComponent.unmountComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:911:10)
    at Object.unmountComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:52:22)
    at Object.unmountChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler.js:115:25)
    at ReactDOMComponent.unmountChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:398:28)
    at ReactDOMComponent.unmountComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:911:10)
    at Object.unmountComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:52:22)
    at ReactCompositeComponentWrapper.unmountComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:2
```

**Comment by petrbrzek** [comment]
Fixed in 2.8.4. Please update the app to the newest version.
