### ISSUE TITLE
just shut down

### ISSUE THREAD

**Issue by AlexeyPogorelov** [avocode/avocode#968]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.1
Source UID: 43187
```
RangeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation
    at RangeError (native)
    at e.exports.e.drawImage (file:///D:/Soft/Avocode-win32-ia32/resources/app.asar/dist/avocode.min.js:24:8825)
    at file:///D:/Soft/Avocode-win32-ia32/resources/app.asar/dist/avocode.min.js:24:6788
    at List.__iterate (D:\Soft\Avocode-win32-ia32\resources\app.asar\node_modules\immutable\dist\immutable.js:2208:13)
    at List.forEach (D:\Soft\Avocode-win32-ia32\resources\app.asar\node_modules\immutable\dist\immutable.js:4383:19)
    at e.exports.e.createSprites (file:///D:/Soft/Avocode-win32-ia32/resources/app.asar/dist/avocode.min.js:24:6386)
    at e.exports.e.loadDocument (file:///D:/Soft/Avocode-win32-ia32/resources/app.asar/dist/avocode.min.js:24:6130)
    at t.loadDocument (file:///D:/Soft/Avocode-win32-ia32/resources/app.asar/dist/avocode.min.js:24:182)
    at e.createStageForDocument (file:///D:/Soft/Avocode-win32-ia32/resources/app.asa
```

**Comment by petrbrzek** [comment]
If you can please update to x64 Windows version of Avocode and let me know if the problem persists. You can download it here https://manager.avocode.com/download/avocode-app/windows-x64/.

**Comment by connor-bean** [comment]
Hey, @AlexeyPogorelov -

Were you able to update to the x64 Windows version to see if this fixed the problem you were seeing?

Thanks!
Connor, Avocode Support

**Comment by connor-bean** [comment]
Closing due to inactivity. Please reopen if you see this problem again
