### ISSUE TITLE
Error closing tab

### ISSUE THREAD

**Issue by thomasaw** [avocode/avocode#979]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.0-beta.6
Source UID: 41855
```
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at invariant (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/node_modules/fbjs/lib/invariant.js:35:15)
    at Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:167:160)
    at e.dispatch (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:21:6702)
    at t.e.dispatch (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:2:20253)
    at t.addUiItem (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:15:12783)
    at e.exports.React.createClass.componentDidMount (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:33:11943)
    at CallbackQueue.assign.notifyAll (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/CallbackQueue.js:65:22)
    at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconcileTransaction.js:81:26)
    at ReactReconcileTransaction.Mixin.closeAll (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:202:25)
    at ReactReconcileTransaction.Mixin.perform (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:149:16)
    at ReactUpdatesFlushTransaction.Mixin.perform (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:136:20)
    at ReactUpdatesFlushTransaction.assign.perform (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdates.js:86:38)
    at flushBatch
```

**Comment by connor-bean** [comment]
Hey, @thomasaw -

Thanks for the report. Can you try downloading our newest version of Avocode to see if this helps the problem? You can download it for Mac [here](https://avocode-media.s3.amazonaws.com/download/avocode-app/2.8.4/avocode-app-mac-2.8.4.zip).

Please let us know if this helps or not once you've updated to the newest version.

Thanks,
Connor, Avocode Support

**Comment by thomasaw** [comment]
I upgraded to that version, thanks. I think the crash ran into is pretty random, so even if it is still around it would be difficult to reproduce. It seems that the update mechanism wasn't working so I was still running the beta build.

**Comment by connor-bean** [comment]
Hey @thomasaw -

Thanks for letting us know. Please reopen this ticket if you experience the crash again.

Thanks,
Connor, Avocode Support
