### ISSUE TITLE
Avocode crash log

### ISSUE THREAD

**Issue by tyronem** [avocode/avocode#983]
IMPORTANT: Please try to describe how did it happen.

I launched Avocode - no special circumstances occurred, really.
-----
App v.2.8.4
Source UID: 68354
```
Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/Applications/Avocode.app/Contents/Resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/Applications/Avocode.app/Contents/Resources/electron.asar/browser/rpc-server.js:302:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at EventEmitter.<anonymous> (/Applications/Avocode.app/Contents/Resources/electron.asar/browser/api/web-contents.js:165:13)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at metaToValue (/Applications/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:178:13)
    at remoteMemberFunction (/Applications/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:112:18)
    at t._sendSetTargetWindowId (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:23:14324)
    at t.setTargetWindowId (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:23:13237)
    at t.<anonymous> (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:23:12318)
    at t.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at t.emit (events.js:185:7)
    at t._handleDownloaderLoad (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:23:15169)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:23:12577
    at CallbacksRegistry.apply (/Applications/Avocode.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:54:39)
    at EventEmitter.<anonymous> (/Applications/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:243:21)
    at emitThr
```

**Comment by connor-bean** [comment]
Hey @tyronem 

Thanks for the report. We are currently tracking this bug in #940. This is an Electron bug and you can see more about it [here](https://github.com/electron/electron/issues/4733).

I am going to close out this ticket and we will continue to monitor this in #940.

Thanks,
Connor, Avocode Support
