### ISSUE TITLE
Crash after trying to open a large psd with multiple artboards that has problems uploading from the app, and showing background layers after uploading from the PS plugin

### ISSUE THREAD

**Issue by erikvandewiel** [avocode/avocode#985]
I've added a psd (189,6mb / 31 artboards) to avocode by using the latest PS (2015.5) plugin (2.2.3) on OSX. The avocode app crashed after trying to open the file. 

Co workers complained that they couldn't see 28 of the 31 background layers in the avocode app so I wanted to check it for myself. 

Some extra info:
Yesterday just before using the PS plugin to upload the file, I tried uploading the same file via the avocode app. After completing uploading and sending mail notifications the processing got stuck around 95%. I removed the PSD from avocode and used the plugin instead.

Erik

---

App v.2.8.4
Source UID: 21082

```
Error: Cannot open a document with no revision or no current revision
    at t.openDesign (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:2:8298)
    at t.openDesignById (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:2:7986)
    at Constructor._handleEntityOpen (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:35:17353)
    at Constructor._handleEntityDoubleClick (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:35:26324)
    at Object.invokeGuardedCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactErrorUtils.js:27:12)
    at executeDispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:79:21)
    at Object.executeDispatchesInOrder (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:102:5)
    at executeDispatchesAndRelease (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:43:22)
    at executeDispatchesAndReleaseTopLevel (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:54:10)
    at Array.forEach (native)
    at forEachAccumulated (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/forEachAccumulated.js:23:9)
    at Object.processEventQueue (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:259:7)
    at runEventQueueInBatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
    at Object.handleTopLevel [as _handleTopLevel] (/Applications/Avocode.app/Contents/Resources/app.asar/node
```

**Comment by bolekkerous** [comment]
Hello!
First of all, Avocode does not support Photoshop Artboards yet, so in case your PSD is not displayed correctly, it may be caused by using artboards in the file.

If you want to be able to use artboards with Avocode, please uvpote it on our Uservoice forum, so we know what to prioritize:

https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/9428469-support-photoshop-artboards

About the error and crashing itself - could you please send us the problematic design to team@avocode.com, so we can properly test it?

Thanks!
Bolek, Avocode Team

**Comment by erikvandewiel** [comment]
Hi Bolek,

Thanks for getting back to me so quickly!
I used wetransfer to send you guys the file. 

Erik

**Comment by connor-bean** [comment]
Hey @erikvandewiel -

Can you try resending the design to team@avocode.com? I don't see it in our inbox. 

Thanks,
Connor, Avocode Support

**Comment by erikvandewiel** [comment]
Hi Connor, I used wetransfer at 22 July 2016 at 11:28am (Amsterdam time). Link should still work. 
Erik

**Comment by connor-bean** [comment]
Hey @erikvandewiel - 

Thanks. I have passed it along to the dev team. They will comment here once they have more information.

Connor, Avocode Support

**Comment by erikvandewiel** [comment]
Hi @connor-bean 
FYI: just got a notification that the file hasnt been downloaded from wetransfer yet and that the wetransfer link will be available only for 2 more days

Erik

**Comment by bolekkerous** [comment]
This shouldn't happen anymore in the latest version of the Avocode app.

You can always download the latest version here:
https://manager.avocode.com/downloads/

Photoshop artboards are still not supported though. If you want us to support Photoshop artboards, please upvote it on our UserVoice:

https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/9428469-support-photoshop-artboards

If you still experience this problem or any other problem, please create a new issue or comment here.
