### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by IvanKhartov** [avocode/avocode#995]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.4
Source UID: null
```
Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (C:\Users\ivank\AppData\Local\avocode\app-2.8.4\resources\electron.asar\browser\objects-registry.js:44:28)
    at EventEmitter.<anonymous> (C:\Users\ivank\AppData\Local\avocode\app-2.8.4\resources\electron.asar\browser\rpc-server.js:302:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at EventEmitter.<anonymous> (C:\Users\ivank\AppData\Local\avocode\app-2.8.4\resources\electron.asar\browser\api\web-contents.js:165:13)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at metaToValue (C:\Users\ivank\AppData\Local\avocode\app-2.8.4\resources\electron.asar\renderer\api\remote.js:178:13)
    at remoteMemberFunction (C:\Users\ivank\AppData\Local\avocode\app-2.8.4\resources\electron.asar\renderer\api\remote.js:112:18)
    at t._sendSetTargetWindowId (file:///C:/Users/ivank/AppData/Local/avocode/ap
```

**Comment by connor-bean** [comment]
Hey @IvanKhartov -

Thanks for the report. We are currently tracking this bug in #940. This is an Electron bug and you can see more about it [here](https://github.com/electron/electron/issues/4733).

I am going to close out this ticket and we will continue to monitor this in #940.

Thanks,
Connor, Avocode Support
