### ISSUE TITLE
TypeError: Cannot read property 'imageName' of undefined

### ISSUE THREAD

**Issue by wmadden** [avocode/avocode#996]
> IMPORTANT: Please try to describe how did it happen.

I just tried to open a project :/ 

No unusual steps I can describe to reproduce, but every time I try to open that project this error is reported.

-----
App v.2.3.2-ea60620
Source UID: 75201
```
TypeError: Cannot read property 'imageName' of undefined
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:2540
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:2460
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:2460
    at t.module.exports.t._getImagesToLoad (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:2673)
    at new t (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:515)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:21597
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)
```

**Comment by connor-bean** [comment]
Hey @wmadden -

It looks like you're using an outdated version of the app. Could you try updating to the newest version and see if this error still keeps happening?

You can download it [here](https://manager.avocode.com/downloads/).

Thanks,
Connor, Avocode Support

**Comment by wmadden** [comment]
That fixed it, sorry for the false alarm!
