### ISSUE TITLE
Can not open mockup uploaded few minutes ago

### ISSUE THREAD

**Issue by kuziv-andriy** [avocode/avocode#999]
IMPORTANT: Please try to describe how did it happen.

---

App v.2.8.4
Source UID: 27409

```
TypeError: Cannot read property 'get' of undefined
    at e._loadRevisionData (file:///C:/Users/Andriy/AppData/Local/avocode/app-2.8.4/resources/app.asar/dist/avocode.min.js:9:31241)
    at file:///C:/Users/Andriy/AppData/Local/avocode/app-2.8.4/resources/app.asar/dist/avocode.min.js:9:30329
    at Immediate._onImmediate (file:///C:/Users/Andriy/AppData/Local/avocode/app-2.8.4/resources/app.asar/dist/avocode.min.js:13:17516)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by kuziv-andriy** [comment]
Windows 10

**Comment by vojtatranta** [comment]
this hsould be already fixed, please update :)
